### DISCUSSION TITLE
Enabling MIMO with srsRAN Project

### DISCUSSION THREAD

**Discussion by andrepuschmann** [srsran/srsRAN_Project#102] [Announcements]
Hey guys,

clearly the biggest new feature in our most recent code drop was the addition of MIMO. In this initial version we've focused on the downlink that now allows us to use two transmit antennas and use two-layers or "streams" to send data to a single user. In good conditions this effectively doubles the data rate for a UE compared to SISO operation. In the case of MIMO a "good channel" actually means that there is little to no correlation between the two streams. If there is a high correlation, basically meaning that the two received streams are very similar to each other, the MIMO channel is considered to be bad, and hence giving little to no performance gain.

Before showing how to configure multi-antenna operation in the gNB application I'd like to give a big shout-out to the entire team who has completed the entire feature in just about two weeks of time. This is an amazing achievement and just another example of how well the new software architecture plays out and how the entire development team behind srsRAN works together.
### Setting the baseline

As a baseline config let's pick the 20 MHz TDD config in band n78. You'll find that [here](https://github.com/srsran/srsRAN_Project/blob/main/configs/gnb_rf_b200_tdd_n78_20mhz.yml).

Spinning up the gNB with that and running a downlink iperf test gives around 42 Mbit/s as we can see in the trace below. One of the new things to note is the the `ri` column in the console trace. This column displays the so called rank indicator (RI). The value basically says how well the multiple antennas work, i.e. how correlated the received streams are. With a two-layer system the best we can get is an RI of 2 - meaning that the channel isn't correlated. In this example, however, since we're still using SISO, the RI is 1.

```
Cell pci=1, bw=20 MHz, dl_arfcn=632628 (n78), dl_freq=3489.42 MHz, dl_ssb_arfcn=632544, ul_freq=3489.42 MHz

==== gNodeB started ===
Type <t> to view trace
t
           -----------------DL----------------|------------------UL--------------------
 pci rnti  cqi  ri  mcs  brate   ok  nok  (%) | pusch  mcs  brate   ok  nok  (%)    bsr
   1 4601   15   1   28    42M 1199    1   0% |  13.5   25   9.2k    3    7  70%    0.0
   1 4601   15   1   28    42M 1199    3   0% |  28.2   24   109k  160    0   0%    0.0
   1 4601   15   1   28    42M 1201    0   0% |  18.2   22    99k   29    2   6%    0.0
   1 4601   15   1   28    42M 1195    6   0% |  28.8   24    97k  153    0   0%    0.0
   1 4601   15   1   28    42M 1200    0   0% |  27.1   28   606k  145    6   3%    0.0
   1 4601   15   1   28    42M 1198    2   0% |  29.5   24   204k  323    0   0%    0.0
   1 4601   15   1   28    42M 1201    0   0% |  23.9   27    80k   25    1   3%    0.0
   1 4601   15   1   28    42M 1200    0   0% |  27.5   24   104k  158    0   0%    0.0
```

If you followed the recent discussion post about QAM256 [here](https://github.com/srsran/srsRAN_Project/discussions/89) you might ask: Only 42Mbit/s? You're absolutely right, let's enable QAM256 and try again. But let's not patch the current config file but let's instead use a pretty cool feature to concatenate config files. That's right, by specifying configs multiple times you can actually overlay one config over the other. With `gnb -c gnb_rf_b200_tdd_n78_20mhz.yml -c qam256.yml` we can load both files. With this we reach almost 60Mbit/s in the DL.
```
           -----------------DL----------------|------------------UL--------------------
 pci rnti  cqi  ri  mcs  brate   ok  nok  (%) | pusch  mcs  brate   ok  nok  (%)    bsr
   1 4602   15   1   27    45M  922    1   0% |   7.4   13    63k   10    5  33%    0.0
   1 4602   15   1   27    57M 1177   19   1% |  29.0   24   158k  206   12   5%    0.0
   1 4602   15   1   27    59M 1200    0   0% |  29.7   26   104k   75    0   0%    0.0
   1 4602   15   1   27    59M 1204    0   0% |  29.8   24    83k  118    0   0%    0.0
   1 4602   15   1   27    58M 1185   12   1% |  28.1   25    18k   11    0   0%    0.0
   1 4602   15   1   27    59M 1204    0   0% |  30.2   24   120k  192    7   3%    0.0
```

### Enabling 2x2 MIMO for the downlink

Let's now finally enable MIMO. For this you can either patch the existing config file and specify the `nof_antennas_dl` and `nof_antennas_ul` in the `cell_cfg` section or, and that's what we do here, use the `mimo_usrp.yml` config extension. Et voilà. With this we get almost double the rate: 120Mbit/s.

```
$ ./apps/gnb/gnb -c ../configs/gnb_rf_b200_tdd_n78_20mhz.yml -c ../configs/mimo_usrp.yml 
...
           -----------------DL----------------|------------------UL--------------------
 pci rnti  cqi  ri  mcs  brate   ok  nok  (%) | pusch  mcs  brate   ok  nok  (%)    bsr
   1 4601   15   2   27   117M 1200    1   0% |   9.7   23   8.6k    2    7  77%    0.0
   1 4601   15   2   27   117M 1200    0   0% |  10.2   16    63k   54    2   3%    0.0
   1 4601   15   2   26   110M 1172   30   2% |   8.9   18    18k    5    5  50%    0.0
   1 4601   15   2   27   112M 1147   54   4% |  14.4   25   5.1k    2    6  75%    0.0
   1 4601   15   2   27   109M 1122   79   6% |  -1.8   12    41k   10    6  37%    0.0
   1 4601   15   2   27   111M 1138   62   5% |  23.2   24    37k   55    9  14%    0.0
   1 4601   15   2   27   113M 1162   42   3% |   9.4   17    15k    5    3  37%    0.0
```
Here is a screenshot of NSG showing the MIMO Rank is two. Note that it also shows 4x4 MIMO which is not correct in this case.

<img src="https://github.com/srsran/srsRAN_Project/assets/525775/bab4d60a-190a-49bd-80d9-9d706a896cb9" width="250">

### UL MIMO

You might have noticed that we also enable two receive antennas in the above mentioned config but never talk about uplink rates. This is because we currently only enable receive diversity in the UL. So we use two antennas but only one transmission layer.

### What's next?

We are currently working on adding support for four layer MIMO in the downlink and with that we will again double the rate. We expect this to come very very soon. The only caveat is that this will no longer work with the relatively affordable USRP B210 as it supports only two transmit/receive channels. For split-8 we would need to use the USRP N3xx or X4xx series instead. For split-7.2 we believe most commercial O-RUs will support up to 4 layers. 

Please let us know if that was helpful and if you have any comments regarding this or anything else related to srsRAN Project.

**Comment by fllay** [comment]
There is no `mimo_usrp.yml` in the source tree. Please share the file.  I set `nof_antennas_dl=2` and `nof_antennas_ul=2` in the `cell_cfg` section but I got very slow speed comparing to SISO.

**Reply by andrepuschmann** [reply]
We'll push it shortly - sorry, I assumed it was already there. But it's just this:
```
cell_cfg:
  nof_antennas_dl: 2
  nof_antennas_ul: 2
```
What sort of issues do you get? For a B210 - make sure to rotate the 2 Tx antenna (the ports showing tx/rx) by 90 degree.

**Reply by frankist** [reply]
You also need to set the number of ports for PDSCH to 2. Basically this parameter:
```
$ ./gnb cell_cfg pdsch --help
...
  --nof_ports TEXT:{1,2,4}    Number of ports for PDSCH. By default it is set to be equal to number of DL antennas
```

**Reply by frankist** [reply]
Nevermind my previous comment. If not specified, the number of pdsch ports is automatically equal to the number of dl antennas.

**Reply by fahad-ece** [reply]
Dear @andrepuschmann 

Thanks a lot for your continuous effort to helping us with the latest insight. I am trying to implement 2x2 MIMO configuration using the USRP N310 in Band 78. It works perfectly for SISO. But I am unable to run the MIMO configuration. I am hereby attaching the configuration file along with the screenshot. Looking forward for your valuable feedback. Thank you.

![MIMO Error-1](https://github.com/srsran/srsRAN_Project/assets/158372277/b865997c-15c4-496a-9854-45257ee6102a)
=======================================================================================
amf:
  addr: 127.0.1.100                   
  bind_addr: 127.0.0.45                

ru_sdr:
  device_driver: uhd                  
  device_args: type=n3xx, addr= 192.168.20.2, send_frame_size=8000,recv_frame_size=8000               
  clock: internal                     
  sync:                               
  srate: 122.88                        
  tx_gain: 55                         
  rx_gain: 40                         

cell_cfg:
  dl_arfcn: 627340                    
  band: 78                             
  channel_bandwidth_MHz: 100           
  common_scs: 30                      
  plmn: "00101"                       
  tac: 7                              
  pci: 1                              
  nof_antennas_dl: 2
  nof_antennas_ul: 2
  pdsch:
   mcs_table: qam256  
  ssb:
   ssb_period: 20     

log:
  filename: /tmp/gnb.log              
  all_level: info                     

pcap:
  mac_enable: true                   
  mac_filename: /tmp/gnb_mac.pcap     
  ngap_enable: true                  
  ngap_filename: /tmp/gnb_ngap.pcap

**Reply by andrepuschmann** [reply]
Please make sure the config is a correctly formatted YAML file.

**Reply by fahad-ece** [reply]
Dear @andrepuschmann 

Like I have mentioned the SISO configuration is working without any problem. I am having issues with MIMO configuration. I am attaching the file as well for your configuration. Thank you.

[n310_n78_mimo.zip](https://github.com/srsran/srsRAN_Project/files/14910661/n310_n78_mimo.zip)

**Comment by fllay** [comment]
I am not sure what the issues are. I got a very stable connection with SISO. It stays connected for few hours. For MIMO, I am using b210 and the speed drops a lot compare to SISO. Rotating TX antennas 90 degree help to improve a lot in the up link but in the downlink still slow but both up and down link are still slower than SISO. However, I need to verify my UE (ZTE MU 5002) that it supports MIMO or not.  Unfortunately, I broke the antenna cable in the UE that support MIMO  so I cannot test it. I am still waiting for replacement cable. 

I don't know what happen when gNB is configured as 2x2 MIMO but the UE does not support MIMO?

**Reply by ismagom** [reply]
Can you attach a picture of the antennas?

Also, can you share logs in info level? Thanks

**Comment by fllay** [comment]
This is my set up. 

![IMG_5153](https://github.com/srsran/srsRAN_Project/assets/3962267/de0d5c4d-7148-4799-8063-568d06930d2d)

And the log file. 

[gnb-1.log](https://github.com/srsran/srsRAN_Project/files/11846098/gnb-1.log)

It seems that there is a lot of these messages when I am doing speed test.

```
2023-06-23T07:48:07.020115 [Low-PHY ] [W] Real-time failure in low-phy: Downlink data late for sector 0 and slot 926.12.
2023-06-23T07:48:07.020525 [Low-PHY ] [W] Real-time failure in low-phy: Downlink data late for sector 0 and slot 926.13.
2023-06-23T07:48:07.029485 [Low-PHY ] [W] Real-time failure in low-phy: Downlink data late for sector 0 and slot 927.12.
2023-06-23T07:48:07.030068 [Low-PHY ] [W] Real-time failure in low-phy: Downlink data late for sector 0 and slot 927.13.
2023-06-23T07:48:07.103118 [Low-PHY ] [W] Real-time failure in low-phy: Downlink data late for sector 0 and slot 935.2.
2023-06-23T07:48:12.501614 [Low-PHY ] [W] Real-time failure in low-phy: Downlink data late for sector 0 and slot 450.4.
2023-06-23T07:48:12.502084 [Low-PHY ] [W] Real-time failure in low-phy: Downlink data late for sector 0 and slot 450.5.
```

Does it mean that my computer is not fast enough? I ordered  the  new one but have to wait for weeks.

**Reply by ismagom** [reply]
You have some RT faults yes. You need to run the srsran_performance script under scripts/ folder. 

The antennas are wrong. The TX/RX antenna in RF2 must be perpendicular to TX/RX in RF1.

If the problem persists, send logs but enable all_level = info in the config file

**Comment by fllay** [comment]
How about something like this?

![IMG_5154](https://github.com/srsran/srsRAN_Project/assets/3962267/68ba9ac3-2b27-40a1-914b-4d135cc027f2)

but the log file is too big to upload now. But I think the problem is my computer is too old. I will try a better computer tonight. and I can confirm that the antenna arrangement did improve the performance.

**Reply by ismagom** [reply]
In this picture the TX/RX ports are still parallel. They need to be orthogonal for best performance. RFA: TX/RX and RFB: TX/RX ports one up, one right.

**Comment by fllay** [comment]
This is my config file content.

```
amf:
  addr: 127.0.0.2                                               # The address or hostname of the AMF.
  bind_addr: 127.0.0.1                                            # A local IP that the gNB binds to for traffic from the AMF.

ru_sdr:
  device_driver: uhd                                            # The RF driver name.
  device_args: type=b200,num_recv_frames=64,num_send_frames=64  # Optionally pass arguments to the selected RF driver.
  clock: internal                                                       # Specify the clock source used by the RF.
  sync: internal                                                        # Specify the sync source used by the RF.
  srate: 23.04                                                  # RF sample rate might need to be adjusted according to selected bandwidth.
  otw_format: sc12
  tx_gain: 79                                                  # Transmit gain of the RF might need to adjusted to the given situation.
  rx_gain: 60                                                   # Receive gain of the RF might need to adjusted to the given situation.

cell_cfg:
  dl_arfcn: 632628                                                # ARFCN of the downlink carrier (center frequency).
  band: 78                                                        # The NR band.
  channel_bandwidth_MHz: 20                                       # Bandwith in MHz. Number of PRBs will be automatically derived.
  common_scs: 30                                                  # Subcarrier spacing in kHz used for data.
  plmn: "99970"                                                   # PLMN broadcasted by the gNB.
  tac: 7                                                          # Tracking area code (needs to match the core configuration).
  pci: 1                                                          # Physical cell ID.
  nof_antennas_dl: 2
  nof_antennas_ul: 2
  ssb:
    ssb_period: 10
  pdsch:
    mcs_table: qam256
log:
  filename: /tmp/gnb.log                                          # Path of the log file.
  all_level:  info                                               # Logging level applied to all layers.
  phy_rx_symbols_filename: /tmp/iq.log

pcap:
  mac_enable: false                                               # Set to true to enable MAC-layer PCAPs.
  mac_filename: /tmp/gnb_mac.pcap                                 # Path where the MAC PCAP is stored.
  ngap_enable: false                                              # Set to true to enable NGAP PCAPs.
  ngap_filename: /tmp/gnb_ngap.pcap                               # Path where the NGAP PCAP is stored.

```

Do I need to set something else besides   nof_antennas_dl: 2
  nof_antennas_ul: 2

**Reply by ismagom** [reply]
comment this line: `phy_rx_symbols_filename: /tmp/iq.log` this file will record all IQ samples and consumes a lot of CPU.

**Comment by fllay** [comment]
Thank you I will fix them

**Reply by fllay** [reply]
I use more powerful computer.  It seems to be normal now.  Thank you very much.

**Reply by gustavobsch** [reply]
What kind of speed did you achieve with more powerful computer? I've seen a slight increase of speed using MIMO, nowhere near 100M, max I reached was 60M.

I don't think it's a matter of antenna position, I tried different combinations.

**Reply by fllay** [reply]
I got about the same as you 60M. I just used speed test to the internet not iperf. I have used iperf before and I observe that the speed will be about twice the internet speed test.  Also, I think that 20 MHz bandwidth of the maximum when using 2x2 MIMO with b210. Antenna position need to be in uncorrelated position so that MIMO can be exploited otherwise its performance will be the same as SISO. Normally, we will put antennas very far away from each other. at least a quarter wave. But, in this set up with b210, we cannot do that so we try to de-correlate them using orthogonal position.

**Reply by ismagom** [reply]
You should achieve more than that. Can you share console trace? Do you get ri 2?

**Comment by fllay** [comment]
My set up is a bit mess.   Something like

gNB -> UE -> computer via wifi

My UE is ZTE MU5002 which is a pocket WiFi. I am not sure that there is a button neck in WiFi link between UE and the computer.  I have another UE that connect directly to raspberry pi but I am waiting for RF replacement cable since I broke it.  

This is my console.  

```
          -----------------DL----------------|------------------UL--------------------
 pci rnti  cqi  ri  mcs  brate   ok  nok  (%) | pusch  mcs  brate   ok  nok  (%)    bsr
   1 4602   15   2   26   4.2M  157   15   8% |  23.3   28   1.2M   75    2   2%    0.0
   1 4602   15   2   26    64k   16    2  11% |  25.0   27   140k   24    0   0%    0.0
   1 4602   15   2   27    31M  427   11   2% |  24.2   28   1.2M   81    4   4%    0.0
   1 4602   15   2   27    43M  637   17   2% |  23.1   28   1.7M   90   10  10%    0.0
   1 4602   12   2   27    45M  618   19   2% |  22.7   28   1.5M   79    8   9%    0.0
   1 4602   13   2   26    51M  660   11   1% |  23.6   28   1.4M   84    6   6%  20.5k
   1 4602   15   2   27    45M  579   16   2% |  23.0   28   1.7M   78   11  12%    0.0
   1 4602   15   2   26    24M  385   19   4% |  23.3   28   1.2M   78   11  12%    0.0
   1 4602   15   2   27    56M  716   21   2% |  23.2   28   2.0M  110   12   9%    0.0
   1 4602   15   2   27    68M  828   10   1% |  23.5   28   2.2M  119    8   6%    0.0
   1 4602   15   2   26    40M  513   12   2% |  23.8   28   1.2M   83    4   4%    0.0

           -----------------DL----------------|------------------UL--------------------
 pci rnti  cqi  ri  mcs  brate   ok  nok  (%) | pusch  mcs  brate   ok  nok  (%)    bsr
   1 4602   15   2   26    60M  722    7   0% |  23.0   28   1.4M   86   15  14%    0.0
   1 4602   15   2   27    56M  677   17   2% |  23.4   28   1.4M   87   10  10%    0.0
   1 4602   15   2   26    47M  598   11   1% |  23.4   28   1.3M   84    7   7%    0.0
   1 4602   15   2   27    59M  729    9   1% |  23.3   28   1.5M   91    7   7%    0.0
   1 4602   15   2   26    35M  493   22   4% |  23.9   28   968k   63    5   7%    0.0
   1 4602   15   2   26    42M  545   12   2% |  23.7   28   1.2M   71    5   6%    0.0
   1 4602   15   2   27    11M  185    6   3% |  23.5   28   788k   57    4   6%    0.0
   1 4602   15   2   26    37k   12    4  25% |  23.7   28   275k   25    0   0%    0.0
   1 4602   15   2   26   3.6M  790   91  10% |  22.3   28    16M  499   19   3%   300k
   1 4602   15   2   26   4.4M  872  126  12% |  22.2   28    18M  562   25   4%   300k
   1 4602   15   2   26   2.7M  874  119  11% |  22.4   28    19M  567   21   3%   300k

           -----------------DL----------------|------------------UL--------------------
 pci rnti  cqi  ri  mcs  brate   ok  nok  (%) | pusch  mcs  brate   ok  nok  (%)    bsr
   1 4602   15   2   26   2.1M  803  103  11% |  22.3   28    18M  555   32   5%   300k
   1 4602   15   2   26   2.3M  816  109  11% |  22.8   28    18M  566   20   3%   300k
Late: 0; Underflow: 4; Overflow: 0;
   1 4602   15   2   26   2.7M  765  128  14% |  22.2   28    16M  497   25   4%   300k
   1 4602   15   2   26   2.8M  740  120  13% |  22.6   28    16M  498   24   4%   300k
   1 4602   15   2   26   2.2M  446   59  11% |  22.6   28    11M  338   13   3%    0.0
```

**Reply by ismagom** [reply]
It seems the bottleneck is somewhere else, maybe in the application. The DL signal looks very good (CQI 15) and rank is 2, so it's using full MIMO multiplexing. BLER is also very good

**Comment by gustavobsch** [comment]
I also have CQI 15 and ran 2. The application I use is just regular speedtest from market place.

What 5G core / UPF are you using? I use open5gs and testing with a software UE with iperf3 I see the single core UPF bottlenecks at around 260M both uplink and downlink

```
$ iperf3 -c 172.16.10.3
Connecting to host 172.16.10.3, port 5201
[  5] local 172.16.6.72 port 47312 connected to 172.16.10.3 port 5201
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec  32.4 MBytes   272 Mbits/sec   57    523 KBytes       
[  5]   1.00-2.00   sec  31.0 MBytes   260 Mbits/sec   14    423 KBytes       
[  5]   2.00-3.00   sec  31.6 MBytes   265 Mbits/sec    0    469 KBytes       
[  5]   3.00-4.00   sec  30.8 MBytes   259 Mbits/sec    0    511 KBytes       
[  5]   4.00-5.00   sec  30.8 MBytes   258 Mbits/sec    0    553 KBytes       
[  5]   5.00-6.00   sec  30.8 MBytes   258 Mbits/sec    0    592 KBytes       
[  5]   6.00-7.00   sec  31.5 MBytes   264 Mbits/sec    0    629 KBytes       
[  5]   7.00-8.00   sec  31.1 MBytes   260 Mbits/sec    3    365 KBytes       
[  5]   8.00-9.00   sec  31.7 MBytes   266 Mbits/sec   25    317 KBytes       
[  5]   9.00-10.00  sec  30.9 MBytes   259 Mbits/sec    0    382 KBytes  
```

**Reply by ameseguerITI** [reply]
Hello gustav, I am trying to deploy a  5G 20MHz bandwidth SA 2x2 MIMO TDD network using USRP B210 and OAI Core Network and I am suffering this error: 
[PHY]   rx_rf: Asked for 15360 samples, got 0 from USRP 
[PHY]   problem receiving samples
LLLLLLLLLLLLLLLLLLULULLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLOL[HW]   [recv] received 7184 samples out of 15360
LL[HW]   Time: 44.1533 s
ERROR_CODE_OVERFLOW (Overflow)

Have you faced the same problem? I have ensured that USB 3.0 is correctly connected and the host computer is on performance mode. May you give me any tip? I think that you have deployed 2x2 with B210, please correct me if I am mistaken.  Thank you for your time.  Please, @andrepuschmann or anyone, any help is more that welcome.

**Reply by ismagom** [reply]
Are you sure you are using srsGNB? This output doesn't seem it is.

**Reply by ameseguerITI** [reply]
Hello Isma, I am not using it, but as I understand it is a commun UHD problem. Hence just checking if any of you have faced a similar issue. Thank you for your time.

**Reply by ameseguerITI** [reply]
Hello, I think that I have found the problem. For some reason, although I use 20 MHz, the OAI gNB is requesting 30MHz and the host computer is not capable of achieving the samples at time with that bandwidth. I would like to reproduce your results if possible, so in case that there is not any problem, I would thank you if you indicate any steps to follow. Thank you very much

**Reply by Zplusless** [reply]
> I also have CQI 15 and ran 2. The application I use is just regular speedtest from market place.
> 
> What 5G core / UPF are you using? I use open5gs and testing with a software UE with iperf3 I see the single core UPF bottlenecks at around 260M both uplink and downlink
> 
> ```
> $ iperf3 -c 172.16.10.3
> Connecting to host 172.16.10.3, port 5201
> [  5] local 172.16.6.72 port 47312 connected to 172.16.10.3 port 5201
> [ ID] Interval           Transfer     Bitrate         Retr  Cwnd
> [  5]   0.00-1.00   sec  32.4 MBytes   272 Mbits/sec   57    523 KBytes       
> [  5]   1.00-2.00   sec  31.0 MBytes   260 Mbits/sec   14    423 KBytes       
> [  5]   2.00-3.00   sec  31.6 MBytes   265 Mbits/sec    0    469 KBytes       
> [  5]   3.00-4.00   sec  30.8 MBytes   259 Mbits/sec    0    511 KBytes       
> [  5]   4.00-5.00   sec  30.8 MBytes   258 Mbits/sec    0    553 KBytes       
> [  5]   5.00-6.00   sec  30.8 MBytes   258 Mbits/sec    0    592 KBytes       
> [  5]   6.00-7.00   sec  31.5 MBytes   264 Mbits/sec    0    629 KBytes       
> [  5]   7.00-8.00   sec  31.1 MBytes   260 Mbits/sec    3    365 KBytes       
> [  5]   8.00-9.00   sec  31.7 MBytes   266 Mbits/sec   25    317 KBytes       
> [  5]   9.00-10.00  sec  30.9 MBytes   259 Mbits/sec    0    382 KBytes  
> ```

Hi @gustavobsch , Just wondering what software UE did you use. Was it packetrusher or just a software UE working with srsRAN gnb? Thanks in advance if you could reply!

**Comment by fllay** [comment]
I want to update my progress and observation. 

1. From NSG screenshot above, It seems that the bandwidth is 30MHz. I am using 20MHz bandwidth since my UE support 20 40 50 MHz. I think that why I will never reach 100M. If I set 30MHz BW, my UE will not find the network. 
2. I am not sure why the screenshot say MIMO 4x4 but rank 2? It mean that UE has 4 tx 4 rx antennas?

@gustavobsch Could you check your setting for BW and BW for UE.

I will try Quectel RM510Q-GL when I got my cable. It seems that Quectel RM510Q-GL support all requirements.

**Comment by ismagom** [comment]
> I want to update my progress and observation.
> 
> 1. From NSG screenshot above, It seems that the bandwidth is 30MHz. I am using 20MHz bandwidth since my UE support 20 40 50 MHz. I think that why I will never reach 100M. If I set 30MHz BW, my UE will not find the network.

The screenshot above shows `N78 / 20 MHz`, maybe you confuse with SCS 30 KHz? Typical UEs won't support 30 MHz BW I think

> 2. I am not sure why the screenshot say MIMO 4x4 but rank 2? It mean that UE has 4 tx 4 rx antennas?

This is a bug in NSG. It's really 2x2 MIMO. 
> 
> @gustavobsch Could you check your setting for BW and BW for UE.
> 
> I will try Quectel RM510Q-GL when I got my cable. It seems that Quectel RM510Q-GL support all requirements.

**Reply by gustavobsch** [reply]
My UE is OnePlus Nord N10 5G which has a Qualcomm® Snapdragon™ X51 5G Modem-RF System. I haven't been able to find what BW it supports but I had the same experience when setting it to 30MHZ the UE will not see the network.

**Reply by andrepuschmann** [reply]
You can find this info in the UE capability information that is exchanged between gNB and UE during attach. Enable MAC PCAPs with `pcap --mac_enable=true` and attach the UE. Then close the gNB and check the file `/tmp/gnb_mac.pcap` with Wireshark.

**Comment by fllay** [comment]
@ismagom Sorry I confuse it with the one posed in twitter. 
![FzOzhOAaUAANE6r](https://github.com/srsran/srsRAN_Project/assets/3962267/d10fb945-e0c3-48d6-b379-ae238bc7444e)

I still try to figure out what went wrong.

**Comment by aldalahmeh** [comment]
What is the transmission mode used here? I suspect it is transmit diversity, especially if the UE does not support MU-MIMO. 

On the same matter, can you control which transmission mode is used?

**Comment by OsmanMertYilmaz** [comment]
Hello,

I am trying to run srsRAN gNodeB as MIMO with USRP N320.

I am running it with the following command:

`sudo ./gnb -c ../../../configs/gnb_n320.yml`

And I am getting an error like this:

```
[ERROR] [RPC] Invalid master clock rate: 122.88 MHz
[INFO] [MPM.Rhodium-0] init() called with args `fpga=XG,master_clock_rate=122.88e6,mgmt_addr=192.168.20.2,name=ni-n3xx-3349E58,product=n320,recv_frame_size=64,send_frame_size=64,clock_source=internal,time_source=internal'
[INFO] [MPM.Rhodium-1] init() called with args `fpga=XG,master_clock_rate=122.88e6,mgmt_addr=192.168.20.2,name=ni-n3xx-3349E58,product=n320,recv_frame_size=64,send_frame_size=64,clock_source=internal,time_source=internal'
[ERROR] [MPM.RPCServer] init() failed with error: Invalid master clock rate: 122.88 MHz
Failed to open device with address 'type=n3xx, addr= 192.168.20.2, send_frame_size=64,recv_frame_size=64': RuntimeError: Error during RPC call to `init'. Error message: Invalid master clock rate: 122.88 MHz
srsRAN ERROR: Unable to create radio session.
```

When I try the same "srate" value (122.88) for USRP X410, I do not get such an error and it works.

The gnb_n320.yml file is as follows:

```
cu_cp:
  amf:
    addr: 127.0.1.100                                           
    bind_addr: 127.0.0.1                                        
    supported_tracking_areas:                                   
      - tac: 7                        
        plmn_list:
          - plmn: "00101"
            tai_slice_support_list:
              - sst: 1

ru_sdr:
  device_driver: uhd
  device_args: type=n3xx, addr= 192.168.20.2, send_frame_size=64,recv_frame_size=64
  clock: internal
  srate: 122.88
  tx_gain: 55
  rx_gain: 40


cell_cfg:
  dl_arfcn: 627340
  band: 78
  channel_bandwidth_MHz: 100
  common_scs: 30
  plmn: "00101"
  tac: 7
  pci: 1
  nof_antennas_dl: 2
  nof_antennas_ul: 2

pcap:
  mac_enable: false
  mac_filename: /tmp/gnb_mac.pcap
  ngap_enable: false
  ngap_filename: /tmp/gnb_ngap.pcap
```

Thank you for your help.
