### DISCUSSION TITLE
High Network Traffic Between USRP and gNB Even Without User Data

### DISCUSSION THREAD

**Discussion by Moussa-Guemdani** [srsran/srsRAN_Project#1036] [General Help] [answered]
## Description
I'm experiencing high network traffic between my USRP and the gNB, even when no user data is being transmitted. When monitoring the interface with `ifstat`, I notice continuous data flow.

![image](https://github.com/user-attachments/assets/54fb4047-9c35-4b31-b9a3-f950eb2c12d9)

## Setup Details
- **srsRAN Version:** [24.10]
- **USRP Model:** [USRPx310]
- **Configuration:** Running in [TDD] mode  [N77]

## Observations
- Even when no UE or Core is attached, the network interface between the USRP and gNB shows significant data transfer.
- The data flow persists even when there are no active user data transmissions.

## Questions
- Is this expected behavior for an idle srsRAN gNB setup?
- Are there any configuration parameters to reduce unnecessary traffic when no UE is attached?
- Any suggestions on how to analyze and optimize the traffic flow further?

Any insights or guidance would be greatly appreciated. Thanks in advance!

**Comment by pgawlowicz** [comment, marked as answer]
Hi @Moussa-Guemdani,
This is normal behaviour with the default `tx_mode: continuous`.

Could you try with:
```
ru_sdr:
  expert_cfg:
    tx_mode: discontinuous
```
a little docs:
```
             "Selects a radio transmission mode. Discontinuous modes are not supported by all radios.\n"
             "  continuous:    the TX chain is always active.\n"
             "  discontinuous: the transmitter stops when there is no data to transmit.\n"
             "  same-port:     the radio transmits and receives from the same antenna port.\n")
```

**Comment by Moussa-Guemdani** [comment]
Hi @pgawlowicz,

Thanks for your insights!

Yes, I’ve tested this option. The value remains around 500Mbps until data generation starts, at which point it increases to 3.87 Gbps.

Let me know if you need any further details!
![image](https://github.com/user-attachments/assets/714f6e58-f0b2-4910-bc07-1d1ec4730cfb)

**Reply by pgawlowicz** [reply]
Which BW do you use? Could you share your gnb  config?

**Reply by Moussa-Guemdani** [reply]
I use 60 Mhz BW
```
cell_cfg:
  dl_arfcn: 663334 
  band: 77
  channel_bandwidth_MHz: 60
  common_scs: 30
  plmn: "00101"
  tac: 1
  pci: 1

  tdd_ul_dl_cfg: #format 32: DDDDDDDDDDFFUU 
    dl_ul_tx_period: 10                     
    nof_dl_slots: 6                     
    nof_dl_symbols: 10                      
    nof_ul_slots: 3                         
    nof_ul_symbols: 2                       
    #pattern2:
      #dl_ul_tx_period: 5                       
      #nof_dl_slots: 7                           
      #nof_dl_symbols: 6                        
      #nof_ul_slots: 2                           
      #nof_ul_symbols: 4               


ru_sdr:
  device_driver: uhd
  device_args: type=x300, addr=192.168.30.2 , num_send_frames=64, num_recv_frames=64, send_frame_size=8000 
  srate: 92.16 
  otw_format: default #sc16 ##default
  clock: default
  sync: default
  tx_gain: 31.5
  rx_gain: 31.5
  time_alignment_calibration: -170
  freq_offset: 0                        
  clock_ppm: 0                         
  lo_offset: 0                          

  ru_sdr:
  expert_cfg:
    low_phy_dl_throttling: 0
    tx_mode: discontinuous #same-port #continuous
    #power_ramping_time_us: 2
    dl_buffer_size_policy: auto #[auto,single-packet,half-slot,slot,optimal-slot]
```

==> I am using mimo usrp x310 and qam256 on different files

I have two additional options 
1)  does srsRAN report backhaul and fronthaul metrics as latency, bitrate, packet loss?

2) the console reports the rsrp, is there a way to report the snr?
