### DISCUSSION TITLE
50MHz QAM256 4x4 MIMO - Uplink

### DISCUSSION THREAD

**Discussion by RafalArciszewski** [srsran/srsRAN_Project#1039] [General Help] [answered]
Hello,
I am trying to run MIMO on UL direction, but regardless of the mode 4x1 4x2 4x4 I always get the same result 50Mbps.  Does srsRAN currently supports only rx_diversity? 

The second question is for Downlink. Maksimum MCS received by the UE is 26.   Is it possilbe to use MSC 27?

The setup
![obraz](https://github.com/user-attachments/assets/2020009e-61f3-4715-bb9b-831798406287)

Uplink Traffic:
![obraz](https://github.com/user-attachments/assets/4078f392-f92b-46c1-9f5c-0ed16da3b486)

Downlink Traffic:
![obraz](https://github.com/user-attachments/assets/b7aebcfb-ce0d-4ef1-b976-ea08c2c5f3ae)

Regards,
Rafał Arciszewski

**Comment by improperaffo** [comment]
The maximum MCS order for the DL channel can either be 27 or 28 depending on which msc table you are using (28 for `qam64` and 27 for `qam256`). In SRS you can also specify a minimum and maximum MCS within a table:
```
  pdsch:
    min_ue_mcs: 0                           # Optional UINT (0). Sets a minimum PDSCH MCS value to be used for all UEs. Supported: [0 - 28].
    max_ue_mcs: 28                          # Optional UINT (28). Sets a maximum PDSCH MCS value to be used for all UEs. Supported: [0 - 28].
    mcs_table: qam64                        # Optional TEXT (qam64). Sets the MCS table to use for PDSCH. Supported: [qam64, qam256].
```

Looking at the logs, it seems that you have some bit error rate in the DL channel. So, despite having a CQI of 15, the Outer-layer Link Adaptation (OLLA) might be lowering your MCS to 26 to reduce the coding rate in an effort to reduce retransmissions. You could try to set `olla_cqi_inc_step` to 0 to verify this.
```
  pdsch:
    olla_cqi_inc_step: 0                # Optional FLOAT (0.001). Sets the outer-loop link adaptation (OLLA) increment value. The value 0 means that OLLA is disabled. Supported: [0 - 1].
```

**Comment by improperaffo** [comment]
Regarding UL MIMO, which UE are you using? Do you know if it supports UL MIMO?

**Reply by RafalArciszewski** [reply]
@improperaffo  thanks for the tips.
I am using UE that supports UL MIMO. I achieved on other gNB following trougputs in uplink: 4x1 -> 45.4M, 4x2 -> 90.8M, 4x4 -> 166M.  I am not quite sure why UL troughput didn't double in 4x4 comparing to 4x2, but we observe it also in DL. 

Regarding DL, even with perfect RF conditions and no BLER there is no MCS more than 26. What is peculiar when there is UL traffic ongoing I can see the srs allocating MCS 27 in DL direction:

```
  pdsch:
    mcs_table: "qam256"
    min_ue_mcs: 0           
    max_ue_mcs: 28          
    olla_cqi_inc_step: 0     
  pusch:
    mcs_table: "qam256"
```

DL traffic:
![obraz](https://github.com/user-attachments/assets/7e98b97a-ec80-498f-b7f6-a650935d6b9f)

UL traffic:
![obraz](https://github.com/user-attachments/assets/ef13ad4d-7513-4d54-bc0e-06bdc6173297)


Even if I set min_ue_mcs=27 and max_ue_mcs = 27, I still get 26.
When I set min_ue_mcs=16 and max_ue_mcs=16, I get 16 so the mechanizm is working, but not for mcs>26
I've tested also min_ue_mcs, max_ue_mcs for QAM64 and it works fine. So the problem is with setting mcs>26 with QAM256.
