### DISCUSSION TITLE
cu_up: nru: is not in the config anymore. Which config I should use?

### DISCUSSION THREAD

**Discussion by fllay** [srsran/srsRAN_Project#1048] [General Help] [answered]
It seems that this config is not available anymore in latest release. I use the following configuration for CU

```
gnb_id: 531
gnb_id_bit_length: 32
ran_node_name: cu_cp_01

#slicing:                           
#  -                                   
#    sst: 1                               
#    sd: 0                              

#amf:
#  addr:  192.168.68.42
#  bind_addr: 192.168.68.210

cu_cp:
  inactivity_timer: 7200
  amf:
    addr: 192.168.68.42
    port: 38412
    bind_addr: 192.168.68.210
    supported_tracking_areas:
      - tac: 7
        plmn_list:
          - plmn: "00101"
            tai_slice_support_list:
              - sst: 1
  mobility:
    trigger_handover_from_measurements: true
    cells:
      - nr_cell_id: 0x2130
        periodic_report_cfg_id: 1
        ncells:
          - nr_cell_id: 0x2131
            report_configs: [ 2 ]
      - nr_cell_id: 0x2131
        periodic_report_cfg_id: 1
        ncells:
          - nr_cell_id: 0x2130
            report_configs: [ 2 ]
    report_configs:
      - report_cfg_id: 1
        report_type: periodical
        report_interval_ms: 1024
      - report_cfg_id: 2
        report_type: event_triggered
        event_triggered_report_type: a3
        meas_trigger_quantity: rsrp
        meas_trigger_quantity_offset_db: 2
        hysteresis_db: 0
        time_to_trigger_ms: 100
        report_interval_ms: 1024

  f1ap:
    bind_addr: 192.168.68.210


#cu_up:
#  nru:
#    bind_addr: 192.168.68.213
#    udp_max_rx_msgs: 256

log:
  filename: /tmp/cu.log
  all_level: debug


pcap:
  ngap_filename: /tmp/cu_ngap.pcap     # Optional TEXT (/tmp/gnb_ngap.pcap). Path for NGAP PCAPs. 
  ngap_enable: true                    # Optional BOOLEAN (false). Enable/disable NGAP packet capture. Supported: [false, true].
  n3_filename: /tmp/cu_n3.pcap         # Optional TEXT (/tmp/gnb_n3.pcap). Path for N3 PCAPs. 
  n3_enable: true                      # Optional BOOLEAN (false). Enable/disable N3 packet capture. Supported: [false, true].
  e1ap_filename: /tmp/cu_e1ap.pcap     # Optional TEXT (/tmp/gnb_e1ap.pcap). Path for E1AP PCAPs. 
  e1ap_enable: true                    # Optional BOOLEAN (false). Enable/disable E1AP packet capture. Supported: [false, true].
  f1ap_filename: /tmp/cu_f1ap.pcap     # Optional TEXT (/tmp/gnb_f1ap.pcap). Path for F1AP PCAPs. 
  f1ap_enable: true                    # Optional BOOLEAN (false). Enable/disable F1AP packet capture. Supported: [false, true].
  f1u_filename: /tmp/cu_f1u.pcap       # Optional TEXT (/tmp/gnb_f1ap.pcap). Path for F1AP PCAPs. 
  f1u_enable: true                     # Optional BOOLEAN (false). Enable/disable F1AP packet capture. Supported: [false, true].
```
and I can connect to the internet. Now, `nru` is not available 

```
cu_up:
  nru:
    bind_addr: 192.168.68.213
    udp_max_rx_msgs: 256
```

I cannot connect to the internet when I am using CU and DU split on different machine. Other configs I should use instead? This is what I got when I run `srscu` with help

```
pi@pi5:~/src/srsRAN_Project/build/apps/cu$ ./srscu cu_up f1u -h

--== srsRAN CU (commit a041e3162d) ==--

F1-U parameters
Usage: ./srscu cu_up f1u [OPTIONS]

Options:
  -h,--help                   Print this help message and exit
  --socket TEXT ...           Configures UDP/IP socket parameters of the F1-U interface
pi@pi5:~/src/srsRAN_Project/build/apps/cu$ ./srscu cu_up ngu -h

--== srsRAN CU (commit a041e3162d) ==--

NG-U parameters
Usage: ./srscu cu_up ngu [OPTIONS]

Options:
  -h,--help                   Print this help message and exit
  --no_core BOOLEAN           Allow gNB to run without a core
  --socket TEXT ...           Configures UDP/IP socket parameters of the N3 interface
```

**Comment by fllay** [comment]
I can find valid configuration but still It cannot connect to the internet. The CU machine with wlan0 interface has two IPs assigned to it. 192.168.68.210 and 192.168.68.213. I tried to bind these two IPs combination but it still does not work. Any idea please? 

```
gnb_id: 531
gnb_id_bit_length: 32
ran_node_name: cu_cp_01

#slicing:                           
#  -                                   
#    sst: 1                               
#    sd: 0                              

#amf:
#  addr:  192.168.68.42
#  bind_addr: 192.168.68.210

cu_cp:
  inactivity_timer: 7200
  amf:
    addr: 192.168.68.42
    port: 38412
    bind_addr: 192.168.68.210
    supported_tracking_areas:
      - tac: 7
        plmn_list:
          - plmn: "00101"
            tai_slice_support_list:
              - sst: 1
  mobility:
    trigger_handover_from_measurements: true
    cells:
      - nr_cell_id: 0x2130
        periodic_report_cfg_id: 1
        ncells:
          - nr_cell_id: 0x2131
            report_configs: [ 2 ]
      - nr_cell_id: 0x2131
        periodic_report_cfg_id: 1
        ncells:
          - nr_cell_id: 0x2130
            report_configs: [ 2 ]
    report_configs:
      - report_cfg_id: 1
        report_type: periodical
        report_interval_ms: 1024
      - report_cfg_id: 2
        report_type: event_triggered
        event_triggered_report_type: a3
        meas_trigger_quantity: rsrp
        meas_trigger_quantity_offset_db: 2
        hysteresis_db: 0
        time_to_trigger_ms: 100
        report_interval_ms: 1024

  f1ap:
    bind_addr: 192.168.68.213


cu_up:
#  nru:
#    bind_addr: 192.168.68.213
#    udp_max_rx_msgs: 256
  f1u:
      socket:                               # Define UDP/IP socket(s) for F1-U interface.
        -                                     # Socket 1
          bind_addr: 192.168.68.210
#          ext_addr: 8.8.8.8                     # Optional TEXT. Sets the address that is reported as the F1-U bind address. If empty, the real bind address is used.
#          udp:
#            max_rx_msgs: 256                        # Optional UINT (256). Sets the maximum packets read from the socket in a single syscall.
#            pool_threshold: 0.9                     # Optional FLOAT (0.9). Sets the pool occupancy threshold, after which packets are dropped. Supported [0 - 1.0].

  ngu: 
    no_core: false                        # Optional BOOLEAN (false). Setting to true allows the gNB to run without a core. Supported: [0, 1].
    socket:                               # Define socket(s) for NG-U interface.
      -                                     # Socket 1 
        bind_addr: 192.168.68.213                  # Optional TEXT (auto). Sets local IP address to bind for N3 interface. Format: IPV4 or IPV6 IP address.
#        udp:
#          max_rx_msgs: 256                      # Optional INT (256). Sets the maximum number of messages RX from a socket in a single syscall.
#          pool_threshold: 0.9                   # Optional FLOAT (0.9). Sets the pool occupancy threshold, after which packets are dropped. Supported: [0.0 - 1.0].
#          dscp:                                 # Optional UINT. Sets the Differentiated Services Code Point. Supported: [0 - 63].


log:
  filename: /tmp/cu.log
  all_level: debug


pcap:
  ngap_filename: /tmp/cu_ngap.pcap     # Optional TEXT (/tmp/gnb_ngap.pcap). Path for NGAP PCAPs. 
  ngap_enable: true                    # Optional BOOLEAN (false). Enable/disable NGAP packet capture. Supported: [false, true].
  n3_filename: /tmp/cu_n3.pcap         # Optional TEXT (/tmp/gnb_n3.pcap). Path for N3 PCAPs. 
  n3_enable: true                      # Optional BOOLEAN (false). Enable/disable N3 packet capture. Supported: [false, true].
  e1ap_filename: /tmp/cu_e1ap.pcap     # Optional TEXT (/tmp/gnb_e1ap.pcap). Path for E1AP PCAPs. 
  e1ap_enable: true                    # Optional BOOLEAN (false). Enable/disable E1AP packet capture. Supported: [false, true].
  f1ap_filename: /tmp/cu_f1ap.pcap     # Optional TEXT (/tmp/gnb_f1ap.pcap). Path for F1AP PCAPs. 
  f1ap_enable: true                    # Optional BOOLEAN (false). Enable/disable F1AP packet capture. Supported: [false, true].
  f1u_filename: /tmp/cu_f1u.pcap       # Optional TEXT (/tmp/gnb_f1ap.pcap). Path for F1AP PCAPs. 
  f1u_enable: true                     # Optional BOOLEAN (false). Enable/disable F1AP packet capture. Supported: [false, true].
```

**Comment by fllay** [comment]
Update on my question.

Each component is run bare metal on separated machines. 

open5gs IP: 192.168.68.42
cu IP: 192.168.68.210, 192.168.68.213, 192.168.68.214 on the same interface
du IP:192.168.68.36

CU Config file
```
nb_id: 531
gnb_id_bit_length: 32
ran_node_name: cu_cp_01

cu_cp:
  inactivity_timer: 7200
  amf:
    addr: 192.168.68.42
    port: 38412
    bind_addr: 192.168.68.210
    supported_tracking_areas:
      - tac: 7
        plmn_list:
          - plmn: "00101"
            tai_slice_support_list:
              - sst: 1
  mobility:
    trigger_handover_from_measurements: true
    cells:
      - nr_cell_id: 0x2130
        periodic_report_cfg_id: 1
        ncells:
          - nr_cell_id: 0x2131
            report_configs: [ 2 ]
      - nr_cell_id: 0x2131
        periodic_report_cfg_id: 1
        ncells:
          - nr_cell_id: 0x2130
            report_configs: [ 2 ]
    report_configs:
      - report_cfg_id: 1
        report_type: periodical
        report_interval_ms: 1024
      - report_cfg_id: 2
        report_type: event_triggered
        event_triggered_report_type: a3
        meas_trigger_quantity: rsrp
        meas_trigger_quantity_offset_db: 2
        hysteresis_db: 0
        time_to_trigger_ms: 100
        report_interval_ms: 1024

  f1ap:
    bind_addr: 192.168.68.213


cu_up:
  f1u:
      socket:                               # Define UDP/IP socket(s) for F1-U interface.
        -                                     # Socket 1
          bind_addr: 192.168.68.210


  ngu:
    socket:                               # Define socket(s) for NG-U interface.
      -                                     # Socket 1 
        bind_addr: 192.168.68.213                 # Optional TEXT (auto). Sets local IP address to bind for N3 interface. Format: IPV4 or IPV6 IP address.

```

DU Config file
```
gnb_id: 531
gnb_id_bit_length: 32
gnb_du_id: 0

f1ap:
  cu_cp_addr: 192.168.68.213
  bind_addr: 192.168.68.36

ru_sdr:
  device_driver: uhd
  device_args: type=b200,num_recv_frames=64,num_send_frames=64
  srate: 23.04
  otw_format: sc12
  tx_gain: 82
  rx_gain: 50


cell_cfg:
  dl_arfcn: 632628                                                # ARFCN of the downlink carrier>
  band: 78                                                        # The NR band.
  channel_bandwidth_MHz: 20                                       # Bandwith in MHz. Number of PR>
  common_scs: 30                                                  # Subcarrier spacing in kHz use>
  plmn: "00101"                                                   # PLMN broadcasted by the gNB.
  tac: 7                                                          # Tracking area code (needs to >
  pci: 1                                                          # Physical cell ID.
  nof_antennas_dl: 2
  nof_antennas_ul: 2
  sector_id: 0
  pdsch:
    mcs_table: qam256
```

and pcap files
[pcap.zip](https://github.com/user-attachments/files/18987608/pcap.zip)

**Reply by alvasMan** [reply]
I deleted all commented lines to make it clearer to read.

**Comment by alvasMan** [comment]
You don't have any configuration in the DU for the F1-U. It is trying to bind to localhost. You can see this in frame 5 of the E1AP pcap.

Try adding the following to the DU config:

```
f1u:
  socket:
    -
      bind_addr: 192.168.68.36  # Address that the DU F1-U socket will bind to.        
```
