### DISCUSSION TITLE
New release: MIMO 4x4 and improved performance

### DISCUSSION THREAD

**Discussion by ismagom** [srsran/srsRAN_Project#109] [Announcements]
Hi all,

Last week we pushed another release! 

The main feature of this new release is 4-layer MIMO. To run it, you need a 4-channel SDR, such as the N310 or a 4-antenna RU. Then select 4 DL antennas in the config and you are ready to go.

In this picture we are running 50 MHz TDD 4x4 MIMO with a COTS Handset and the N310. Check out **rank 4** NSG:

![PXL_20230630_165149589](https://github.com/srsran/srsRAN_Project/assets/2768811/b3f54790-90fe-4f03-a4b0-05dd064a49cc)

Besides this, we have also done improvements on CPU performance and the handling of some TDD patterns such as DDDXU. See this picture, where we are running 100 MHz TDD in 2x2 configuration and again the N310... **more than 700Mbps!!**

![pxl_20230630_164412879](https://github.com/srsran/srsRAN_Project/assets/2768811/c62e39f3-ff96-47ad-aea9-4484ac2423b0)

And finally, we continue to grow the number of O-RUs we support. This week we have added Picocom and Foxconn RU. As always, we provide example configs. 

Enjoy it!

**Comment by mrouili** [comment]
Hi, I couldn't find the example configuration files for the N310 for these configurations in the configs folder, could you please provide them and are there any ones for the x310 ? Thank you

**Reply by ismagom** [reply]
This is an example configuration to use the N310 in MIMO mode: 

```
ru_sdr:
  device_driver: uhd                # The RF driver name.
  device_args: send_frame_size=8000,recv_frame_size=8000            # Optionally pass arguments to the selected RF driver.
  clock: external                      # Specify the clock source used by the RF.
  sync: external                       # Specify the sync source used by the RF.
  srate: 122.88                      # RF sample rate might need to be adjusted according to selected bandwidth.
  tx_gain: 55                       # Transmit gain of the RF might need to adjusted to the given situation.
  rx_gain: 40                       # Receive gain of the RF might need to adjusted to the given situation.
  expert_cfg: 
    low_phy_thread_profile: quad

cell_cfg:
  dl_arfcn: 650000                  # ARFCN of the downlink carrier (center frequency).
  band: 78                           # The NR band.
  channel_bandwidth_MHz: 100         # Bandwith in MHz. Number of PRBs will be automatically derived.
  common_scs: 30                    # Subcarrier spacing in kHz used for data.
  plmn: "00101"                     # PLMN broadcasted by the gNB.
  tac: 7                            # Tracking area code (needs to match the core configuration).
  pci: 1                            # Physical cell ID.
  pdsch: 
   mcs_table: qam256
   nof_ports: 2
  nof_antennas_dl: 2
  nof_antennas_ul: 1
  ssb: 
    ssb_block_power_dbm: 5
```

**Reply by peihaoY** [reply]
When utilizing this configuration, I encountered several issues: 
1. INI was unable to parse cell_cfg.pdsch.nof_port. Could you provide an updated example of the configuration file?
2. When I set nof_antennas_dl > 1 or mcs_table: qam256, the terminal displays: 
        'srsGNB ERROR: Invalid configuration DU cell detected. 
       >Nof. DL antennas 2 cannot be greater than 1 with using fallback DCI format.' 
This is because I configured:
      dedicated:
           ss2_type: common                         # Search Space type, has to be set to common
           dci_format_0_1_and_1_1: false       # Set correct DCI format (fallback),
However, if I do not configure these two lines, my UE cannot establish a connection with the gNB. They appear to be conflicting.
My complete configuration file is as follows.
[n310mimo.zip](https://github.com/srsran/srsRAN_Project/files/14214554/n310mimo.zip)

**Reply by pgawlowicz** [reply]
Please check here: https://github.com/srsran/srsRAN_Project/blob/main/configs/mimo_usrp.yml
also check our config reference: https://docs.srsran.com/projects/project/en/latest/user_manuals/source/config_ref.html

**Reply by peihaoY** [reply]
I checked the gNB configuration reference and wanted to ask, does the srsue formed by srsRAN_4G not support MIMO?

**Reply by pgawlowicz** [reply]
No, srsUE does not support MIMO.

**Reply by peihaoY** [reply]
Thanks. That's where my system conflicts come in. So do you think it would be very difficult to modify srsue's code for MIMO by myself?

**Reply by pgawlowicz** [reply]
It is a very complex task.

**Reply by fahad-ece** [reply]
> It is a very complex task.

Hi @pgawlowicz,

Hopefully you are doing well. If we use the default configuration files for 5G SA COTS UE setup then theoretically what will be the maximum throughput on the Downlink? Is there any straight-forward way to calculate that? Please let me know. Thank you.

**Reply by pgawlowicz** [reply]
I think around 70-80Mbps in DL, you can use one of the available 5G NR data rate calculators, for example:
https://5g-tools.com/5g-nr-throughput-calculator/

FDD, SISO, BW=20Hz, SCS=15kHz

**Reply by anasalbakri** [reply]
> This is an example configuration to use the N310 in MIMO mode:
> 
> ```
> ru_sdr:
>   device_driver: uhd                # The RF driver name.
>   device_args: send_frame_size=8000,recv_frame_size=8000            # Optionally pass arguments to the selected RF driver.
>   clock: external                      # Specify the clock source used by the RF.
>   sync: external                       # Specify the sync source used by the RF.
>   srate: 122.88                      # RF sample rate might need to be adjusted according to selected bandwidth.
>   tx_gain: 55                       # Transmit gain of the RF might need to adjusted to the given situation.
>   rx_gain: 40                       # Receive gain of the RF might need to adjusted to the given situation.
>   expert_cfg: 
>     low_phy_thread_profile: quad
> 
> cell_cfg:
>   dl_arfcn: 650000                  # ARFCN of the downlink carrier (center frequency).
>   band: 78                           # The NR band.
>   channel_bandwidth_MHz: 100         # Bandwith in MHz. Number of PRBs will be automatically derived.
>   common_scs: 30                    # Subcarrier spacing in kHz used for data.
>   plmn: "00101"                     # PLMN broadcasted by the gNB.
>   tac: 7                            # Tracking area code (needs to match the core configuration).
>   pci: 1                            # Physical cell ID.
>   pdsch: 
>    mcs_table: qam256
>    nof_ports: 2
>   nof_antennas_dl: 2
>   nof_antennas_ul: 1
>   ssb: 
>     ssb_block_power_dbm: 5
> ```
Hi @pgawlowicz @ismagom 

This configuration doesn't work for me no matter whether I'm using Amarisot UE or not. 
I wanna use it with Amarisoft UE over ZMQ. 
But, It simply pops out the error: 
--== srsRAN gNB (commit d5fa4f0ecb) ==--

INI was not able to parse cell_cfg.pdsch.nof_ports

even when running help -h, nof-ports indeed is not a parameter under cell_cfg.pdsch 
So, was this configuration based on a special test build or commit? or am I missing something?

**Comment by khooi8913** [comment]
Hi, is there any further detail on the specific Foxconn O-RU models that are currently supported? From the example configs, I can see that the RPQN4800E is supported, not sure about the RPQN780X series?

**Reply by brendan-mcauliffe** [reply]
Hi @khooi8913, 

We have not tested other Foxconn O-RUs. That being said, assuming that the only difference is the supported frequency range, then yes. You will have to adjust the configuration file accordingly.

**Reply by khooi8913** [reply]
Hi @brendan-mcauliffe, 

Thanks for clarifying. One follow-up question: can you also share the firmware version used for the RPQN4800E?
It would be helpful when engaging with the vendor. Thanks again!

**Reply by brendan-mcauliffe** [reply]
We are using Firmware v3.1.13q.551p1

**Reply by khooi8913** [reply]
Thanks a lot!

**Comment by OsmanMertYilmaz** [comment]
Hi, does srsUE support 4-layer MIMO? Does it send the necessary CSI feedback to gNodeB? When I examined the srsUE codes, I saw that it calculates for 2 layers, am I missing something?

If srsUE does not perform these calculations, what exactly is the reason for this? (Computation complexity, etc.)

Thank you in advance for your feedback.

**Reply by pgawlowicz** [reply]
no, srsUE does not support MIMO in 5G SA mode. Only 2x2 MIMO in 4G mode.

**Reply by OsmanMertYilmaz** [reply]
Hello Piotr,

First of all, thank you for your answer. Will there be MIMO support for srsUE in 5G SA? Is there a specific reason why it is available in LTE but not in 5G NR? 

Finally, is the application you use for the phone a special application? Is it possible to access this application from phones with 5G support?

**Reply by pgawlowicz** [reply]
currently, we are not developing srsUE. It is unlikely that it will change in the near future. We use AmarisoftUE, which is a software implementation of a 5G UE.

**Reply by OsmanMertYilmaz** [reply]
Hello Piotr,

Is there Multi-USRP support? Can we implement 4x4 MIMO structure with 2 USRP?

**Reply by pgawlowicz** [reply]
Hi, multi-USRP is not supported.

**Reply by OsmanMertYilmaz** [reply]
Piotr, me again :(

Is there any obstacle to running srsRAN with phones that support n78? Can I run it after programming my SIM card?

There is no data given for S23 in the link below, but I don't see any reason why it wouldn't work.
"https://docs.srsran.com/projects/project/en/latest/knowledge_base/source/cots_ues/source/index.html#tested-cots-ues"

There is a tutorial in the link given below, but there is something that confuses me. Can we set the configurable SIMs we have with the "SysmoISIM-SJA2" program? Or did you use a special SIM card?

"https://docs.srsran.com/projects/project/en/latest/tutorials/source/cotsUE/source/index.html#overview"

If I can get it to work as given in the Tutorial I'll be happy to share the results with you for the S23.

**Reply by pgawlowicz** [reply]
In theory, it should work smoothly, but it's always essential to verify.

You should be able to use any programmable SIM with compatible programming software; the tutorial simply provides one example.

Piotr

**Comment by Moussa-Guemdani** [comment]
> Hi all,
> 
> Last week we pushed another release!
> 
> The main feature of this new release is 4-layer MIMO. To run it, you need a 4-channel SDR, such as the N310 or a 4-antenna RU. Then select 4 DL antennas in the config and you are ready to go.
> 
> In this picture we are running 50 MHz TDD 4x4 MIMO with a COTS Handset and the N310. Check out **rank 4** NSG:
> 
> ![PXL_20230630_165149589](https://private-user-images.githubusercontent.com/2768811/250271097-b3f54790-90fe-4f03-a4b0-05dd064a49cc.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3ODQzMDEsIm5iZiI6MTczMzc4NDAwMSwicGF0aCI6Ii8yNzY4ODExLzI1MDI3MTA5Ny1iM2Y1NDc5MC05MGZlLTRmMDMtYTRiMC0wNWRkMDY0YTQ5Y2MuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDlUMjI0MDAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDJiMTNlYmI0MjBkMWIzMTUzMzY4MTkxNGU3YjhhMmE0OWJkNWJhM2JkMjRhMDAzY2FiOTMzNzdmMTg0NTUxNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.kITn6s-lhGY4l3Y9OsTu6rYEK5buEccBfI76SfuyTSk)
> 
> Besides this, we have also done improvements on CPU performance and the handling of some TDD patterns such as DDDXU. See this picture, where we are running 100 MHz TDD in 2x2 configuration and again the N310... **more than 700Mbps!!**
> 
> ![pxl_20230630_164412879](https://private-user-images.githubusercontent.com/2768811/250271329-c62e39f3-ff96-47ad-aea9-4484ac2423b0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3ODQzMDEsIm5iZiI6MTczMzc4NDAwMSwicGF0aCI6Ii8yNzY4ODExLzI1MDI3MTMyOS1jNjJlMzlmMy1mZjk2LTQ3YWQtYWVhOS00NDg0YWMyNDIzYjAuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDlUMjI0MDAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2Q3OTRkYjk1YzBiNGQwNDcyODlmZjY2NjE1YmZlMjExZmQ1NDBiNWZlMmY3NTcwMjU2ODY0OGE2YmU2ZjI1OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.pCfPGccQxo7avDtPqnoeTpaYG23-oT7RChEJ0t4g64A)
> 
> And finally, we continue to grow the number of O-RUs we support. This week we have added Picocom and Foxconn RU. As always, we provide example configs.
> 
> Enjoy it!

Hello,
can we achieve this with usrp x310?

**Reply by OsmanMertYilmaz** [reply]
I think you can most likely achive. We achieved using USRP X410. But your pc must be powerful enough.

**Reply by gabrielzb19** [reply]
Hi @osmanmerty I'm currently using an x410, but when deploying the gNB I have an error saying: Error: failed receiving packet. RfnocError: OpTimeout: Control operation timed out waiting for ACK.
Can you provide the most basic .yaml that worked for you please? Sorry for the inconveniences.

**Reply by OsmanMertYilmaz** [reply]
Hi, sure.

```
cu_cp:
  amf:
    addr: 10.53.1.2                                             # The address or hostname of the AMF.
    port: 38412
    bind_addr: 10.53.1.1                                        # A local IP that the gNB binds to for traffic from the AMF.
    supported_tracking_areas:
      - tac: 7
        plmn_list:
          - plmn: "00101"
            tai_slice_support_list:
              - sst: 1

ru_sdr:
  device_driver: uhd
  device_args: addr=192.168.20.2,type=x4xx,num_recv_frames=64,num_send_frames=64
  sync: internal
  clock: internal
  srate: 122.88 # 30.72, 61.44, 122.88
  tx_gain: 50
  rx_gain: 50


cell_cfg:
  dl_arfcn: 650000
  band: 78
  channel_bandwidth_MHz: 100
  common_scs: 30
  plmn: "00101"
  tac: 7
  pci: 1
  nof_antennas_dl: 2
  nof_antennas_ul: 2
  pdsch:
    mcs_table: qam256
  ssb:
    ssb_period: 20

pcap:
  mac_enable: false
  mac_filename: /tmp/gnb_mac.pcap
  ngap_enable: false
  ngap_filename: /tmp/gnb_ngap.pcap
```
