### DISCUSSION TITLE
Measurement-based handover is not working

### DISCUSSION THREAD

**Discussion by BGarcs** [srsran/srsRAN_Project#1105] [General Help]
Dear all
I am implementing the Handover feature using a CU-DU split, such that the two DUs are connected to a single CU and at the same time each DU has its own B210. 

Generally, when forcing Handover using the `ho <serving pci> <rnti> <target pci>` command I have no problems, although I can't claim that it works every time either. The real problem is with the handover based on measurements, because although the `pci` change does work (based on the information provided by G-NetTrack) the internet does not work until after 2 minutes approximately. I have noticed that when the `pci` change occurs many different `rnti` are assigned to my UE, however I do not know if this is the reason why the internet does not work.

Has anyone had something similar happen or know the reason why this might be happening?

Thank you very much!

**Comment by BGarcs** [comment]
As an update.

I am still trying to get the Handover working, looking at the logs of my two DU's I have seen the following type of error, which repeats with different `rnti` as time goes on:
![DUlog1](https://github.com/user-attachments/assets/9e874cca-ec78-485a-ac7a-b7b23f0153c5)
![Dulog2](https://github.com/user-attachments/assets/e936f846-b72e-458a-87be-d62f6a520adf)

After seeing that I made modifications based on the post [292](https://github.com/srsran/srsRAN_Project/discussions/292) with that I have managed to get the handover working a couple of times a little more consistently, however it is still “random” whether or not the handover will work when moving the UE. 

In addition to that, sometimes I get the following error:
`[DU-MNG  ] [W] ue=0: RLF detected with cause="MAC max KOs reached". Timer of 4000 msec to release UE started...`

I would be grateful if you could help me solve this problem.
Thank you very much!

**Reply by fllay** [reply]
May I ask which modification exactly? I have the same setting as you. Two B210s. It can switch between DU but the reason for switching is not Handover.  It can be seen from the log that It cannot measure neighbor cell.
```
2025-03-11T05:02:59.897023 [RRC     ] [D] ue=2 c-rnti=0x4601: Containerized measurementReport: [
  {
    "UL-DCCH-Message": {
      "message": {
        "c1": {
          "measurementReport": {
            "criticalExtensions": {
              "measurementReport": {
                "measResults": {
                  "measId": 1,
                  "measResultServingMOList": [
                    {
                      "servCellId": 0,
                      "measResultServingCell": {
                        "physCellId": 1,
                        "measResult": {
                          "cellResults": {
                            "resultsSSB-Cell": {
                              "rsrp": 40,
                              "rsrq": 60,
                              "sinr": 55
                            }
                          },
                          "rsIndexResults": {
                            "resultsSSB-Indexes": [
                              {
                                "ssb-Index": 0,
                                "ssb-Results": {
                                  "rsrp": 40,
                                  "rsrq": 60,
                                  "sinr": 55
                                }
                              }
                            ]
                          }
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        }
      }
    }
  }
]
```

and It can be seen that it did switch DU but the reason is  otherFailure not Handover.

```
2025-03-11T05:04:47.164214 [RRC     ] [D] ue=3 c-rnti=0x4609: Containerized rrcReestablishmentRequest: [
  {
    "UL-CCCH-Message": {
      "message": {
        "c1": {
          "rrcReestablishmentRequest": {
            "rrcReestablishmentRequest": {
              "ue-Identity": {
                "c-RNTI": 0,
                "physCellId": 1,
                "shortMAC-I": "1011100110111000"
              },
              "reestablishmentCause": "otherFailure",
              "spare": "0"
            }
          }
        }
      }
    }
  }
]
```

I synchronize both B210s with 1pps and 10MHz clock. But still no  neighbor cell measurement. I test that it did use 10MHz check by unplug the 10Mhz cable and see that gnb cannot be run. However, when I unplug the 1pps cable. It still can be run. I am not sure that the B210 are using external 1pps.  For my set up, the internet can still be used.

**Reply by BGarcs** [reply]
Hi @fllay 

This is the configuration file of one of my DUs at the moment (Sorry for so many comments), the other DU is almost identical:

```
gnb_id: 411                   #ID numerico asociado al gNB (Opcional)
gnb_du_id: 0                  #ID del gNB_DU
gnb_id_bit_length: 32

f1ap:
  cu_cp_addr: 127.0.10.1
  bind_addr: 127.0.10.2

nru:
  bind_addr: 127.0.10.2
    
cell_cfg:
  dl_arfcn: 650000
  band: 78
  channel_bandwidth_MHz: 20
  common_scs: 30
  plmn: "99970"
  tac: 7
  pci: 0
  sector_id: 0
  prach:  #Physical Random Access Channel
    prach_root_sequence_index: 0 
      
  pusch:  #Physical Downlink Shared Channel
  #  mcs_table: qam256    #256QAM de Modulation and Coding Scheme en el Uplink  
    max_puschs_per_slot: 6                 # Optional UINT (16). Sets the maximum number of PUSCH grants per slot. Supprted: [1 - 16].
            
  pdsch:  #Physical Uplink Shared Channel
  #  mcs_table: qam256    #256QAM de Modulation and Coding Scheme en el Downlink
    max_alloc_attempts: 6                  # Optional UINT (35). Sets the maximum number of DL or UL PDCCH grant allocation attempts per slot before scheduler skips the slot. Supported: [1 - 35].
    max_pdschs_per_slot: 6                 # Optional UINT (35). Sets the maximum number of PDSCH grants per slot, including SIB, RAR, Paging and UE data grants. Supported: [1 - 35]
  
  #pdcch:  #Physicall Downlink Control Channel
  #  common:
  #    ss0_index: 0                                                # Optional UINT (0). Sets the SearchSpace#0 index. Supported: [0 - 15].
  #    coreset0_index: 12                                          # Optional INT. Sets the CORESET 0 index. Supported: [0 - 15].
  #  dedicated:
  #    ss2_type: common                                            # Optional TEXT (ue_dedicated). Sets the SearchSpace type for UE dedicated SearchSpace#2. Supported: [common, ue_dedicated].
  #    dci_format_0_1_and_1_1: false                               # Optional BOOLEAN (true). Sets whether to use non-fallback or fallback DCI format in UE SearchSpace#2. Supported: [false, true].
      
  pucch:  #Physical Uplink Control Channel
    sr_period_ms: 20                        # Optional UINT (20). Sets the SR period in milliseconds. Supported: [1,2,4,8,10,16,20,40,80,160,320].
    f1_intraslot_freq_hop: true             # Optional BOOLEAN (false). Enables intra-slot frequency hopping for PUCCH F1. Supported: [false, true].
    f0_or_f1_nof_cell_res_sr: 15             # Optional UINT (8). Sets the number of PUCCH F0 or F1 resources available per cell for SR. Supported: [1 - 50].    
    #nof_ue_res_harq_per_set: 8              # Optional UINT (8). Sets the number of PUCCH resources available per UE for HARQ for each PUCCH resource set. Supported: [1 - 8].
    
    #nof_cell_harq_pucch_res_sets: 2         # Optional UINT (2). Sets the number of separate PUCCH resource sets for HARQ-ACK that are available in the cell. The higher the number of sets, the lower the chances UEs have to share the same PUCCH resources. Supported: [1 - 10].
    #f2_or_f3_or_f4_nof_cell_res_csi: 16      # Optional UINT (8). Sets the number of PUCCH F2, F3 or F4 resources available per cell for CSI. Supported: [0 - 100].

  csi:  #Channel State Information
    csi_rs_period: 40                       # Optional UINT (20). Sets the CSI-RS period in milliseconds. Supported: [10, 20, 40, 80].
    
ru_sdr:
  device_driver: uhd
  device_args: type=b200,num_recv_frames=64,num_send_frames=64
  srate: 23.04
  otw_format: sc12  
  sync: internal
  tx_gain: 80 #60
  rx_gain: 50

log:
  filename: /tmp/du0_handover.log
  all_level: info #none/error/warning/info/debug

pcap:
  mac_enable: true
  mac_filename: /tmp/du0_handover_mac.pcap
  f1ap_enable: false
  f1ap_filename: /tmp/du0_handover_f1ap.pcap
  f1u_enable: false
  f1u_filename: /tmp/du0_handover_f1u.pcap
  
metrics:
    enable_json_metrics: true       # Enable reporting metrics in JSON format
    addr: 172.19.1.4                # Metrics-server IP
    port: 55555                     # Metrics-server Port
```

I basically added this portion of code to it:

  ```
pusch:  #Physical Downlink Shared Channel
  #  mcs_table: qam256    #256QAM de Modulation and Coding Scheme en el Uplink  
    max_puschs_per_slot: 6                 # Optional UINT (16). Sets the maximum number of PUSCH grants per slot. Supprted: [1 - 16].
            
  pdsch:  #Physical Uplink Shared Channel
  #  mcs_table: qam256    #256QAM de Modulation and Coding Scheme en el Downlink
    max_alloc_attempts: 6                  # Optional UINT (35). Sets the maximum number of DL or UL PDCCH grant allocation attempts per slot before scheduler skips the slot. Supported: [1 - 35].
    max_pdschs_per_slot: 6                 # Optional UINT (35). Sets the maximum number of PDSCH grants per slot, including SIB, RAR, Paging and UE data grants. Supported: [1 - 35]
      
  pucch:  #Physical Uplink Control Channel
    sr_period_ms: 20                        # Optional UINT (20). Sets the SR period in milliseconds. Supported: [1,2,4,8,10,16,20,40,80,160,320].
    f1_intraslot_freq_hop: true             # Optional BOOLEAN (false). Enables intra-slot frequency hopping for PUCCH F1. Supported: [false, true].
    f0_or_f1_nof_cell_res_sr: 15             # Optional UINT (8). Sets the number of PUCCH F0 or F1 resources available per cell for SR. Supported: [1 - 50].    
    #nof_ue_res_harq_per_set: 8              # Optional UINT (8). Sets the number of PUCCH resources available per UE for HARQ for each PUCCH resource set. Supported: [1 - 8].
    
    #nof_cell_harq_pucch_res_sets: 2         # Optional UINT (2). Sets the number of separate PUCCH resource sets for HARQ-ACK that are available in the cell. The higher the number of sets, the lower the chances UEs have to share the same PUCCH resources. Supported: [1 - 10].
    #f2_or_f3_or_f4_nof_cell_res_csi: 16      # Optional UINT (8). Sets the number of PUCCH F2, F3 or F4 resources available per cell for CSI. Supported: [0 - 100].

  csi:  #Channel State Information
    csi_rs_period: 40                       # Optional UINT (20). Sets the CSI-RS period in milliseconds. Supported: [10, 20, 40, 80].
```
With it I managed to perform 2 successful Handover, say move the UE from DU0 to DU1, wait a minute, move from DU1 to DU0 and wait another minute, all this without losing internet connectivity. When I moved again from DU0 to DU1 the pci change was made to the corresponding DU1 but I lost connectivity to the internet, although the UE still shows me that it is connected to the network and the 5G symbol. I am testing with a Samsung A55 using Whatsapp calls with a device that is off the network. I should also mention that the case I mentioned with 2 successful handovers only worked for me once, I have not been able to replicate the result despite the configuration files being the same.

In my case I don't have an external clock to synchronize both B210, I have tried to use in some occasions a pair of GPS antennas, such that each B210 uses one antenna, which didn't solve me the problem.

I remain attentive to any suggestion to find or solve this problem!
