### DISCUSSION TITLE
How to verify RAN slicing capability with release24.10?

### DISCUSSION THREAD

**Discussion by andy112233445566** [srsran/srsRAN_Project#1107] [General Help]
I have completed the multi-slice simulation through release 24.10 (topology as shown in the picture1 below). I am using srsUE (with ZMQ) + srsRAN (with ZMQ) + free5gc, and it is integrated with GNU-Radio Companion([ref](https://github.com/srsran/srsRAN_Project/issues/327)) and with UL DL functioning normally (as shown in the picture2 below). 

picture1:
![image](https://github.com/user-attachments/assets/d12199c5-02be-4440-a887-5ac0cb17c475)
picture2:
<img width="1348" alt="20250317_srsrue_console1" src="https://github.com/user-attachments/assets/d5795fa6-3b0a-4276-819e-0e7e269fe333" />

**Comment by pgawlowicz** [comment]
Nice, you can assign different share of PRBs to each slice and then run iperf:
```
cell_cfg:
...
  slicing:                              # Optional TEXT. Configure network slicing options. This can only be set via the configuration file.
    -                                     # Configure Slice 1
      sst: 1                                  # Optional UINT (1). Sets the Slice Service Type. Supported: [0 - 255].
      sd: 0                                   # Optional UINT (0). Sets the Service Differentiator. Supported: [0-16777215].
      sched_cfg:                              # Scheduler configuration for the slice
        min_prb_policy_ratio: 0                 # Optional UINT (0). Sets the minimum percentage of PRBs to be allocated to the slice. Supported [0 - 100].
        max_prb_policy_ratio: 100               # Optional UINT (100). Sets the maximum percentage of PRBs to be allocated to the slice. Supported [1 - 100].
```

**Reply by newt2105** [reply]
> Nice, you can assign different share of PRBs to each slice and then run iperf:
> 
> ```
> cell_cfg:
> ...
>   slicing:                              # Optional TEXT. Configure network slicing options. This can only be set via the configuration file.
>     -                                     # Configure Slice 1
>       sst: 1                                  # Optional UINT (1). Sets the Slice Service Type. Supported: [0 - 255].
>       sd: 0                                   # Optional UINT (0). Sets the Service Differentiator. Supported: [0-16777215].
>       sched_cfg:                              # Scheduler configuration for the slice
>         min_prb_policy_ratio: 0                 # Optional UINT (0). Sets the minimum percentage of PRBs to be allocated to the slice. Supported [0 - 100].
>         max_prb_policy_ratio: 100               # Optional UINT (100). Sets the maximum percentage of PRBs to be allocated to the slice. Supported [1 - 100].
> ```

Hi @pgawlowicz , `min_prb_policy_ratio` and `max_prb_policy_ratio` is PRB for downlink or uplink?
When I set prb:
```
cell_cfg:
  slicing:
    - sst: 1
      sd: 000001
      sched_cfg:                              # Scheduler configuration for the slice
        min_prb_policy_ratio: 95                # Optional UINT (0). Sets the minimum percentage of PRBs to be allocated to the slice. Supported [0 - 100].
        max_prb_policy_ratio: 100 
    - sst: 1
      sd: 000002
      sched_cfg:                              # Scheduler configuration for the slice
        min_prb_policy_ratio:  1                # Optional UINT (0). Sets the minimum percentage of PRBs to be allocated to the slice. Supported [0 - 100].
        max_prb_policy_ratio:  2
    - sst: 1
      sd: 000003
      sched_cfg:                              # Scheduler configuration for the slice
        min_prb_policy_ratio: 1                 # Optional UINT (0). Sets the minimum percentage of PRBs to be allocated to the slice. Supported [0 - 100].
        max_prb_policy_ratio: 2  
  dl_arfcn: 368500                  # ARFCN of the downlink carrier (center frequency).
  band: 3                           # The NR band.
  channel_bandwidth_MHz: 10         # Bandwith in MHz. Number of PRBs will be automatically derived.
  common_scs: 15                    # Subcarrier spacing in kHz used for data.
  plmn: "00101"                     # PLMN broadcasted by the gNB.
  tac: 7                         # Tracking area code (needs to match the core configuration).
  pdcch:
    common:
      ss0_index: 0                  # Set search space zero index to match srsUE capabilities
      coreset0_index: 6             # Set search CORESET Zero index to match srsUE capabilities
    dedicated:
      ss2_type: ue_dedicated           # Search Space type, has to be set to common
      dci_format_0_1_and_1_1: true # Set correct DCI format (fallback)
  prach:
    prach_config_index: 1           # Sets PRACH config to match what is expected by srsUE
    total_nof_ra_preambles: 64      # Sets number of available PRACH preambles
    nof_ssb_per_ro: 1               # Sets the number of SSBs per RACH occasion.
    nof_cb_preambles_per_ssb: 64    # Sets the number of contention based preambles per SSB.
``` 
I'm using first slice, then I run` kpm_mon_xapp` and run: `sudo ip netns exec ue1 iperf -c 10.45.1.1 -u -b 100M -i 1 -t 500`
. here is the output:
```
RIC Indication Received from gnbd_001_001_00019b_0 for Subscription ID: 4, KPM Report Style: 4
E2SM_KPM RIC Indication Content:
-ColletStartTime:  2025-05-15 03:27:01
-Measurements Data:
--UE_id: 0
---granulPeriod: 1000
---Metric: DRB.UEThpDl, Value: [4]
---Metric: DRB.UEThpUl, Value: [33460]
---Metric: RRU.PrbTotDl, Value: [8]
---Metric: RRU.PrbTotUl, Value: [87]
---Metric: RRU.PrbAvailDl, Value: [48]
---Metric: RRU.PrbUsedDl, Value: [4]
---Metric: RRU.PrbAvailUl, Value: [7]
---Metric: RRU.PrbUsedUl, Value: [45]
``` 
I don't see 95-100% PRB in DL or UL. Can you explain?
