### DISCUSSION TITLE
COTS UE cannot find network

### DISCUSSION THREAD

**Discussion by victorlupas** [srsran/srsRAN_Project#1122] [General Help]
Hi, I am using srsRAN Project and Open5GS for a project and for now I just want to see if my personal phone can detect the network. I followed the documentation of both srsRAN Project and Open5GS for COTS UE but my phone (Samsung Galaxy S24) cannot see the network. In my set-up I used a USRP B205 and the gNB is working with the following config file (I also saw on the spectrum analyzer the transmitted signal, it was ok):
```
cu_cp:
  amf:
    addr: 127.0.1.100
    port: 38412
    bind_addr: 127.0.0.1
    supported_tracking_areas:
      - tac: 7
        plmn_list:
          - plmn: "00101"
            tai_slice_support_list:
              - sst: 1

ru_sdr:
  device_driver: uhd
  device_args: type=b200,num_recv_frames=64,num_send_frames=64
  clock: internal
  #sync: gpsdo
  srate: 23.04
  otw_format: sc12
  tx_gain: 80
  rx_gain: 40

cell_cfg:
  dl_arfcn: 153620
  band: 28
  channel_bandwidth_MHz: 10
  common_scs: 15
  plmn: "00101"
  tac: 7
  pci: 1

log:
  filename: /tmp/gnb.log
  all_level: info

pcap:
  mac_enable: true
  mac_filename: /tmp/gnb_mac.pcap
  ngap_enable: true
  ngap_filename: /tmp/gnb_ngap.pcap

metrics:
  enable_json_metrics: true
```
