### DISCUSSION TITLE
2x2 MIMO on USRP x310 issues

### DISCUSSION THREAD

**Discussion by mrouili** [srsran/srsRAN_Project#114] [General Help]
Hello srs community, 

I am able to run  5G gNB configuration at 70Mhz TDD (n78) , 92.16 srate, using a USRP x310 without issues on SISO. I get around 200mbps on DL and about 20 on UL. However, when I try MIMO 2x2, the DL and UL rates are extremely low 0-3mbps. I tried different bandwith configurations (20Mhz,40Mhz,50Mhz) and sample rates but the problem persists. I am using the USRP's internal clock and not a GPSDO. 

Any ideas on what could be causing this issue ? am I missing something to enable MIMO correctly ?

**Comment by ismagom** [comment]
Hi @mrouili, can you share the console trace output? It prints useful metrics like ri and cqi.

Also, when doing MIMO make sure the 2 TX antennas are orthogonal to each other. The TX and RX can be parallel since duplexing is TDD.

**Reply by mrouili** [reply]
Hi @ismagom, thank you for your assistance. Since I've started this thread I have also tested with the USRP x410 in both SISO and MIMO. I am unable to get a consistent configuration on both. I'm pretty confident that I'm most likely using wrong configurations for this one. 

As for the x310 in MIMO, here are the trace outputs you requested. This is based on the N310 configuration that you have provided me with for 50Mhz 2x2 MIMO, the only thing I have changed is the srate ( 92.16 instead of 122.88 as it is not supported by the x310) and the TX/RX values to the appropriate ones for the x310 (20 and 25). As you instructed the the 2 TX antennas are orthogonal to each other. 

```
Cell pci=1, bw=50 MHz, dl_arfcn=650000 (n78), dl_freq=3750.0 MHz, dl_ssb_arfcn=648960, ul_freq=3750.0 MHz

==== gNodeB started ===
Type <t> to view trace
Late: 0; Underflow: 2; Overflow: 0;
t

           -----------------DL----------------|------------------UL--------------------
 pci rnti  cqi  ri  mcs  brate   ok  nok  (%) | pusch  mcs  brate   ok  nok  (%)    bsr
   1 4602   11   1   17   7.2k    8    4  33% |  20.7   20    17k    4    0   0%    0.0
   1 4602   10   1    0      0    0    0   0% |  29.4   28   4.4k    1    0   0%    0.0
   1 4602   13   1    0      0    0    0   0% |   n/a    0      0    0    0   0%    0.0
   1 4602   13   1    0      0    0    0   0% |   n/a    0      0    0    0   0%    0.0
   1 4602   14   1    0      0    0    0   0% |  32.9   28   4.4k    1    0   0%    0.0
   1 4602   14   1    0      0    0    0   0% |   n/a    0      0    0    0   0%    0.0
   1 4602   13   1    0      0    0    0   0% |   n/a    0      0    0    0   0%    0.0
   1 4602   13   1    0      0    0    0   0% |   n/a    0      0    0    0   0%    0.0
   1 4602   14   1    0      0    0    0   0% |   n/a    0      0    0    0   0%    0.0
   1 4602   13   1    0      0    0    0   0% |   n/a    0      0    0    0   0%    0.0
   1 4603  n/a   1    3   2.4k    1    0   0% |   n/a    0      0    0    0   0%    0.0
   1 4602   13   1    0      0    0    0   0% |   n/a    0      0    0    0   0%    0.0

           -----------------DL----------------|------------------UL--------------------
 pci rnti  cqi  ri  mcs  brate   ok  nok  (%) | pusch  mcs  brate   ok  nok  (%)    bsr
   1 4603   12   2   21   2.2M  175    3   1% |  31.3   26   1.3M  141    8   5%    0.0
   1 4603   13   2   22   810k   91    1   1% |  31.7   26   698k  112    2   1%    0.0
   1 4603   15   2   27   221k   67    1   1% |  32.3   25   546k  120    0   0%    0.0
   1 4603   15   2   27    11k    9    0   0% |  34.0   24   139k  140    0   0%    0.0
   1 4603   14   1    0      0    0    0   0% |   n/a    0      0    0    0   0%    0.0
   1 4603   14   1   25   7.3k    2    0   0% |  31.8   25    44k   28    1   3%    0.0
   1 4603   13   1   26    23M  259  142  35% |  25.2   23   477k  195   36  15%  2.81k
Late: 0; Underflow: 5; Overflow: 0;
```
With the x410, I am running into similar issues however no configuration is working correctly so far in either SISO or MIMO, here's the trace for that:

```
Cell pci=1, bw=100 MHz, dl_arfcn=650000 (n78), dl_freq=3750.0 MHz, dl_ssb_arfcn=647328, ul_freq=3750.0 MHz

==== gNodeB started ===
Type <t> to view trace
Late: 7717; Underflow: 2908; Overflow: 0;
Late: 7519; Underflow: 3091; Overflow: 0;
Late: 7707; Underflow: 2988; Overflow: 0;
Late: 6941; Underflow: 2955; Overflow: 0;
Late: 6817; Underflow: 2885; Overflow: 0;
Late: 8474; Underflow: 3046; Overflow: 0;
Late: 8906; Underflow: 2920; Overflow: 0;
Late: 6988; Underflow: 2919; Overflow: 0;
Late: 6554; Underflow: 3249; Overflow: 0;
Late: 8488; Underflow: 2871; Overflow: 0;
Late: 7629; Underflow: 2908; Overflow: 0;
Late: 6856; Underflow: 3114; Overflow: 0;
Late: 8150; Underflow: 2846; Overflow: 0;
Late: 7209; Underflow: 2677; Overflow: 0;
Late: 7500; Underflow: 3054; Overflow: 0;
Late: 6866; Underflow: 2948; Overflow: 0;
Late: 8473; Underflow: 3090; Overflow: 0;
Late: 8244; Underflow: 2622; Overflow: 0;
Late: 7900; Underflow: 2833; Overflow: 0;
Late: 8071; Underflow: 2930; Overflow: 0;
Late: 7679; Underflow: 2711; Overflow: 0;
Late: 7879; Underflow: 2840; Overflow: 0;
Late: 7827; Underflow: 2763; Overflow: 0;
```
Please let me know what you think and if there are any configurations that I can use to achieve higher DL and UL , especially on the x410 since it should be able to support high bandwidth MIMO 4x4 scenarios. 

Thank you very much !

**Reply by ismagom** [reply]
In the MIMO 2x2 case, everything looks good. Reasonable CQI, ri of 2, low BLER in DL and UL. What application are you using to generate traffic? For initial testing I would recomend iperf2 UDP.

Regarding the X410, unfortunately we don't have one in the lab. Maybe you need to tweak the buffer sizes. I would start running the UHD benchmark application with identical sampling rates, number of channels and device args

**Reply by mrouili** [reply]
Hi @ismagom, thank you for your answer ! I am using the Ookla speedtest app on android and running speedtest for traffic, I'm not sure that iperf would make that much of a difference since I used them all in the past and they mostly have the same results. On SISO i have another problem which is very low and unstable UL, as you can see from the trace below using SISO with the x310 70mhz, I am able to get good DL speeds but the UL is very low and unstable, any ideas on how to fix this ? thanks !
```
Cell pci=1, bw=70 MHz, dl_arfcn=641000 (n78), dl_freq=3615.0 MHz, dl_ssb_arfcn=639264, ul_freq=3615.0 MHz

==== gNodeB started ===
Type <t> to view trace
Late: 0; Underflow: 0; Overflow: 1;
t

           -----------------DL----------------|------------------UL--------------------
 pci rnti  cqi  ri  mcs  brate   ok  nok  (%) | pusch  mcs  brate   ok  nok  (%)    bsr
   1 4601   15   1   25    16k   15    0   0% |  29.5   26    43k   10    0   0%    0.0
   1 4601   15   1   27   365k   64    1   1% |  31.2   26   262k   68    0   0%    0.0
   1 4601   15   1   27   700k   95    0   0% |  25.2   25   319k  126   17  11%  7.59k
   1 4601   15   1   27   2.9M  208    6   2% |  28.5   26   1.2M  152    6   3%  2.01k
   1 4601   15   1   27   560k  105    2   1% |  28.4   26   1.5M  131   20  13%    160
   1 4601   15   1   27   1.1M  147    2   1% |  31.1   26   1.3M  173    3   1%   10.0
   1 4601   15   1   27   138k   34    0   0% |  32.2   26   364k   40    2   4%    0.0
   1 4601   15   1   27    44k    9    2  18% |  31.6   28    17k    4    0   0%    0.0
   1 4601   15   1   27   795k  104    0   0% |  28.3   26   452k   81    8   8%    198
   1 4601   15   1   27   4.3M  155    2   1% |  32.0   26   320k  115    3   2%   28.0
   1 4601   15   1   27   2.9M  194    2   1% |  32.0   26   632k  171    0   0%   80.0

           -----------------DL----------------|------------------UL--------------------
 pci rnti  cqi  ri  mcs  brate   ok  nok  (%) | pusch  mcs  brate   ok  nok  (%)    bsr
   1 4601   15   1   27   1.6M  236    1   0% |  30.9   26   1.2M  192    0   0%  3.91k
   1 4601   15   1   27   2.8M  203    5   2% |  31.5   26   900k  179    4   2%   10.0
   1 4601   15   1   27   553k  101    3   2% |  22.3   22   1.0M  116   51  30%   10.0
   1 4601   15   1   27   249k   49    0   0% |  11.3   18   414k   41  137  76%  7.59k
   1 4601   15   1   27    25M  200   20   9% |   9.0   16   816k   94   89  48%    535
   1 4601   15   1   27   116M  755   29   3% |   2.0    7   1.2M  162   34  17%  1.04k
   1 4601   15   1   27   185M 1087   15   1% |  -0.9    3   1.5M  213   21   8%    535
   1 4601   15   1   27   129M  787    5   0% |  -0.3    4   1.9M  207   35  14%   59.0
   1 4601   15   1   27   164M  974   13   1% |  -3.7    2   2.0M  296   33  10%  20.5k
   1 4601   15   1   27   151M  917   25   2% |  -6.0    1   2.2M  371   40   9%   71.0
   1 4601   15   1   27   144M  883   11   1% |  -6.2    1   1.7M  300   46  13%  3.91k

           -----------------DL----------------|------------------UL--------------------
 pci rnti  cqi  ri  mcs  brate   ok  nok  (%) | pusch  mcs  brate   ok  nok  (%)    bsr
   1 4601   15   1   26    92M  587   23   3% |  18.0   21   1.4M  146   80  35%   14.0
   1 4601   15   1   26    17M  131    7   5% |  17.2   24   642k   47  132  73%    102
   1 4601   15   1   27    25M  180    0   0% |  18.3   25   773k   64  116  64%    142
   1 4601   15   1   27    46M  312    3   0% |  22.6   26   781k   98  100  50%   10.0
   1 4601   15   1   27    23M  162    1   0% |  20.2   25   482k   67  102  60%  3.91k
   1 4601   15   1   27   113M  694   17   2% |  31.7   27   1.3M  215    7   3%    384
   1 4601   15   1   27   165M  958    9   0% |  29.8   27   1.6M  195   26  11%   38.0
   1 4601   15   1   27   150M  904    3   0% |  30.4   27   1.5M  233    6   2%  1.45k
   1 4601   15   1   27    45M  287    1   0% |  31.7   26   826k  133    0   0%    0.0
   1 4601   15   1   27   562k   19    0   0% |  31.0   28    20k    4    0   0%    0.0
   1 4601   15   1   27   567k  249    3   1% |  28.0   28    14M  164   75  31%  1.04k

           -----------------DL----------------|------------------UL--------------------
 pci rnti  cqi  ri  mcs  brate   ok  nok  (%) | pusch  mcs  brate   ok  nok  (%)    bsr
   1 4601   15   1   27   434k  222    0   0% |  28.9   28   8.9M  147   55  27%  28.6k
   1 4601   15   1   27   439k  243    5   2% |  28.7   28    11M  157   50  24%  28.6k
   1 4601   15   1   27   477k  263    2   0% |  28.6   28    11M  154   59  27%  28.6k
   1 4601   15   1   27   444k  256    2   0% |  28.6   28    12M  156   71  31%  3.91k
   1 4601   15   1   27   1.0M  232    3   1% |  28.9   28    12M  159   70  30%  28.6k
   1 4601   15   1   27   428k  236    2   0% |  27.3   28    10M  148   66  30%  1.53k
   1 4601   15   1   27   376k  217    3   1% |  29.1   28   9.1M  140   60  30%  13.8k
   1 4601   15   1   27   456k  195    4   2% |  28.5   28   9.5M  154   47  23%  14.7k
   1 4601   15   1   27   250k  140    3   2% |  30.1   27   5.9M  170   25  12%    0.0
   1 4601   14   1   26   784k   39    3   7% |  21.1   24   258k   54   56  50%    0.0
   1 4601   15   1   27    11k    9    0   0% |  28.1   26    55k   13    0   0%    0.0

           -----------------DL----------------|------------------UL--------------------
 pci rnti  cqi  ri  mcs  brate   ok  nok  (%) | pusch  mcs  brate   ok  nok  (%)    bsr
   1 4601   15   1   27    984    1    0   0% |  32.5   25    30k   21    0   0%    0.0
   1 4601   15   1   27    94M  563    4   0% |  32.0   27   942k  141    0   0%  1.04k
   1 4601   15   1   27   212M 1179    3   0% |  31.8   27   2.4M  233    3   1%  1.45k
   1 4601   15   1   27   215M 1190    0   0% |  31.8   27   2.3M  261    1   0%  1.45k
   1 4601   15   1   27   215M 1190    0   0% |  32.1   27   2.1M  260    2   0%    745
   1 4601   15   1   27   216M 1197    0   0% |  32.1   27   2.1M  246    1   0%    720
   1 4601   15   1   27   215M 1193    0   0% |  32.1   27   2.3M  276    1   0%  1.04k
   1 4601   15   1   27   217M 1197    0   0% |  32.4   28   2.1M  245    0   0%    535
   1 4601   15   1   27   217M 1198    0   0% |  31.8   28   2.2M  238    4   1%  2.01k
   1 4601   15   1   27   217M 1198    1   0% |  32.1   27   2.3M  234    0   0%  1.45k
   1 4601   15   1   27   179M 1001    1   0% |  31.6   27   2.1M  209    4   1%    0.0
```

**Reply by ismagom** [reply]
Can you try limiting the UL MCS to a lower value, like 25 for instance. You can do it with this argument: 

```
cell_cfg:
  pusch:
    max_ue_mcs: 25
```
I think we might need to improve the MCS table. 

Are you using an external clock?

**Reply by mrouili** [reply]
Limiting the UL MCS made no difference. We have the Leo bodnar external clock that was recommended in the deployment guides, however due to the location of our testbed and lab, we are currently unable to use it with the x310 USRP since it doesn't pick up the GPS signal where the USRP is located and we are working on solving this issue. So for now we are using the x310's internal clock. Do you think that this is the reason why the UL is bad ? could it be the same the reason why MIMO is not working properly for both DL and UL ?

**Reply by ismagom** [reply]
Well it could be a reason yes. It really depends on the accuracy of your clock in particular. 

However, to use the external Leo bodnar clock I don't think you need GPS signal. That device just has a better internal clock. Have you tried without it locking the GPS signal?

**Reply by mrouili** [reply]
I just tried the clock without a GPS at 10mhz frequency. Unfortunately, it didn't result in any difference compared to using the x310's internal clock. I even tried a different USRP x310 and again, same results.

**Reply by ismagom** [reply]
when you tried with the external clock with no GPS, did you set? 

```
  clock: external                        # Specify the clock source used by the RF.
  sync: external                         # Specify the sync source used by the RF.
```

**Reply by mrouili** [reply]
Yes I did, here's how my sdr/cell config looks like : 

```

ru_sdr:
  device_driver: uhd                                            # The RF driver name.
  #device_args: type=x300
  #device_args: send_frame_size=8000,recv_frame_size=8000,master_clock_rate=245.76e6
  device_args: send_frame_size=8000,recv_frame_size=8000,master_clock_rate=184.32e6                                           # Optionally pass arguments to the selected RF driver.
  clock: external                                                       # Specify the clock source used by the RF.
  sync: external                                                        # Specify the sync source used by the RF.
  srate: 92.16   #61.44 46.08 122.88 184.32                             # RF sample rate might need to be adjusted according to selected bandwidth.
  #otw_format: sc12
  tx_gain: 20                                                   # Transmit gain of the RF might need to adjusted to the given situation.
  rx_gain: 25 
  #lo_offset: 50
  #freq_offset: 30000000
  time_alignment_calibration: -200
  expert_cfg: 
    low_phy_thread_profile: quad
    
expert_phy: 
  nof_ul_threads: 3
  nof_pdsch_threads: 3

cell_cfg:
                                               
  dl_arfcn: 641000 #505200 650000 639000 632628                  # (3615 MHz) ARFCN of the downlink carrier (center frequency).
  #dl_arfcn: 505200                                              # (3555 MHz) ARFCN of the downlink carrier (center frequency).
  band: 78                                                      # The NR band.
  channel_bandwidth_MHz: 70                                    # Bandwith in MHz. Number of PRBs will be automatically derived.
  common_scs: 30                                                # Subcarrier spacing in kHz used for data.
  plmn: "00101"                                                 # PLMN broadcasted by the gNB.
  tac: 1                                                     # Tracking area code (needs to match the core configuration).
  pci: 1                                                     # Physical cell ID.
  nof_antennas_ul: 1
  nof_antennas_dl: 1 #2  
  pdsch: 
   mcs_table: qam256
   #nof_ports: 2
  ssb: 
   ssb_block_power_dbm: 5
   #ssb_period: 20 
  #pusch:
  #  max_ue_mcs: 20
               
slicing:
  - sst: 1
    sd: 000001
 # - sst: 2
 #   sd: 000002
```
and here's the config i used with the leo bodnar clock:

[
![GPS_10M_96K](https://github.com/srsran/srsRAN_Project/assets/94928015/e6fa1ff3-5ebc-43a4-9e41-8dff4912ad11)
](url)
