### DISCUSSION TITLE
How to select ARFCN for N79

### DISCUSSION THREAD

**Discussion by robwasab** [srsran/srsRAN_Project#1174] [General Help] [answered]
Hi,

I'm trying to get a gNB working on N79 with a Peplink UE which uses a Quectel RM520N-GL modem. 

I got the One Plus example on N78 working between the gNB and the UE by following the COTS UE example in the documentation. Programmed the SIM cards and added the IMSI to 5G core. 

The next step is to get it working on N79, but here is where the system stops working... or at least appears to.
I've tried a variety of ARFCNs within N79. It appears as though it's not working but I can't tell if the UE is just scanning the entire band and it can't find the SSB broadcast since I have very little visibility into what the UE is doing. 

My current theory is that there's something special about he ARFCN choice (nuance) that I'm not understanding. In the One Plus example, they use 627340. How did they compute / select that number?

I'm currently trying 695400 as my ARFCN since it's on the lower end of the band and I was hoping it would speed up UE attach.

Here is my gNB config file: [gnb_b210_20MHz_oneplus_8t.yml.txt](https://github.com/user-attachments/files/19857651/gnb_b210_20MHz_oneplus_8t.yml.txt)

I would appreciate some help in figuring out an ARFCN number to get N79 working and any background literature that would help me understand what is going on.

Thank you.

**Comment by robertfalkenberg** [comment]
Hi @robwasab,

Here you will find a comprehensive overview of the NR frequency bands: https://www.sqimway.com/nr_band.php

**Reply by robertfalkenberg** [reply, marked as answer]
Here's an example of `ru_sdr` config section using band `n79` with USRP B210 SISO:

```yml
ru_sdr:
  device_driver: uhd                # The RF driver name.
  device_args: type=b200            # Optionally pass arguments to the selected RF driver.
  otw_format: sc12
  srate: 61.44                      # RF sample rate might need to be adjusted according to selected bandwidth.
  tx_gain: 70                       # Transmit gain of the RF might need to adjusted to the given situation.
  rx_gain: 25                       # Receive gain of the RF might need to adjusted to the given situation.

cell_cfg:
  dl_arfcn: 710000                  # ARFCN of the downlink carrier (center frequency).
  band: 79                          # The NR band.
  channel_bandwidth_MHz: 50         # Bandwith in MHz. Number of PRBs will be automatically derived.
  common_scs: 30                    # Subcarrier spacing in kHz used for data.
  plmn: "00101"                     # PLMN broadcasted by the gNB.
  tac: 7                            # Tracking area code (needs to match the core configuration).
  pci: 1                            # Physical cell ID.
  nof_antennas_dl: 1
  nof_antennas_ul: 1
```

Tested with Telit FN990A28
