### DISCUSSION TITLE
Intra-gNB handover using two RUs

### DISCUSSION THREAD

**Discussion by radutipurita** [srsran/srsRAN_Project#1195] [General Help]
Hello,

I am currently working on a project where I would like to deploy two base stations so that I can gather more channel state information elements. After doing a bit of research I came across [this discussion](https://github.com/srsran/srsRAN_Project/discussions/815) and in the responses it is mentioned that inter gNB handover is not supported. That said, the  [documentation documents](https://docs.srsran.com/projects/project/en/latest/tutorials/source/handover/source/index.html) mention that intra handover is supported.
I was curious if it would be possible to run a intra handover setup by using two single channel SDRs instead of the dual channel USRP. The SDR we are using is the BladeRF and we have managed to make it work with just one RU. We have tried to setup with two SDRs but it does not seem to recognize the second SDR. This is our current yaml file:

```

gnb_id: 411
gnb_id_bit_length: 32
   
cu_cp:
  amf:
    addr: open5gs-amf-ngap.core
    bind_addr: 10.42.0.181
    supported_tracking_areas:
      - tac: 1
        plmn_list:
          - plmn: "00108"
            tai_slice_support_list:
              - sst: 1
                sd: 0
  inactivity_timer: 7200

  mobility:
    trigger_handover_from_measurements: true                    # Set the CU-CP to trigger handover when neighbor cell measurements arrive
    cells:                                                      # List of cells available for handover known to the cu-cp
      - nr_cell_id: 0x19B0                                        # Cell ID for cell 1 
        periodic_report_cfg_id: 1                                 # Set the periodic report configuration ID for this cell
        ncells:                                                   # Neighbor cell(s) available for handover
          - nr_cell_id: 0x19B1                                      # Cell ID of neighbor cell available for handover
            report_configs: [ 2 ]                                   # Report configurations to configure for this neighbor cell
      - nr_cell_id: 0x19B1                                        # Cell ID for cell 2
        periodic_report_cfg_id: 1                                 # Set the periodic report configuration ID for this cell
        ncells:                                                   # Neighbor cell(s) available for handover 
          - nr_cell_id: 0x19B0                                      # Cell ID of neighbor cell available for handover
            report_configs: [ 2 ]                                   # Report configurations to configure for this neighbor cell
    report_configs:                                             # Sets the report configuration for triggering handover
      - report_cfg_id: 1                                          # Report config ID 1 
        report_type: periodical                                   # Sets the report type as periodical
        report_interval_ms: 480                                   # Sets to report every 480ms 
      - report_cfg_id: 2                                          # Report config ID 2
        report_type: event_triggered                              # Sets the report type as event triggered
        event_triggered_report_type: a3                           # Sets the event triggered report type as A3               
        meas_trigger_quantity: rsrp                               # Sets the measurement trigger quantity as rsrp
        meas_trigger_quantity_offset_db: 3                        # Sets the measurement trigger quantity offset to 3dB
        hysteresis_db: 0                                          # Sets the hysteresis to 0dB
        time_to_trigger_ms: 100                                   # Sets the time to trigger to 100ms



cells:
  -
    pci: 1
    prach:
      prach_root_sequence_index: 0
  -
    pci: 2
    prach:
      prach_root_sequence_index: 64
ru_sdr:
  device_driver: bladerf
  srate: 23.04
  otw_format: sc16
  tx_gain: 66
  rx_gain: 15

cell_cfg:
  dl_arfcn: 632628
  band: 78
  channel_bandwidth_MHz: 20
  common_scs: 30
  plmn: "00108"
  tac: 1
  slicing:
    - sst: 1
      sd: 0
  pci: 1
  tdd_ul_dl_cfg:
    dl_ul_tx_period: 4
    nof_dl_slots: 2
    nof_dl_symbols: 10
    nof_ul_slots: 1
    nof_ul_symbols: 0
  nof_antennas_ul: 1
  nof_antennas_dl: 1
  pdsch:
    mcs_table: qam256
  pusch:
    mcs_table: qam64
    max_ue_mcs: 27
  pucch:
    sr_period_ms: 10

log:
  filename: /tmp/gnb.log
  all_level: debug

pcap:
  mac_enable: false
  mac_filename: /tmp/gnb_mac.pcap
  ngap_enable: false
  ngap_filename: /tmp/gnb_ngap.pcap

metrics:
    autostart_stdout_metrics: 1

```

Thank you in advance for any suggestions, and I apologize if I'm overlooking something obvious, I'm still a beginner in this field.

Best regards,
Radu

**Comment by BGarcs** [comment]
Hello @radutipurita, 

I have been working on the same thing for a while now. I am trying to deploy an Intra-gNB Handover using two USRP B210, instead of the X310 suggested in the tutorial. I suggest you try to make a CU-DU split, such that you have a single CU and two DU connected to it, and in turn each DU has its own USRP. If you are going to run everything using a single PC you would have to run 3 terminals, one running the CU and the other two running a DU each.

Cheers!

**Reply by kkcjh** [reply]
Hello@BGarcs 
I am currently using two USRP B210 devices to set up two 5G base stations (srsRAN) each, and they are connected to the same core network (open5GS). When a mobile phone connects, it can perform cell reselection rather than cell handover. I would like to ask if it is possible to configure neighbor cell relationships between the two base stations in this scenario. This is because the official tutorials I have seen are for configuring cell handover mechanisms when a single X310 is used to open multiple cells, and there is no mention of cell handover content for multiple 5G base stations like mine.
Looking forward to any reply from you, and I would be extremely grateful！

**Reply by improperaffo** [reply]
Hi @kkcjh it is possible to have handover between two USRP B210, but they should be two DUs connected to the same CU.
You can follow discussion #803

**Reply by kkcjh** [reply]
Thank you very much for your reply. I will try your suggestion.

**Reply by BGarcs** [reply]
Hi @kkcjh and @improperaffo, 
I have continued to work with this and sometimes I do handover and sometimes cell reselection, I have not been able to standardize it so that handover always works. The main problem is that apparently the CU has problems registering the cells, so even though the UE is in coverage of both it is not able to “see” cell B at all times if it is connected to cell A (You can check the Network Survey app on Android to see if your UE sees the neighboring cells). 
In my case it happens to me that if I am connected to my DU 1 I am able to see my DU 2 cell, but being in DU 2 I can't see the one in DU 1, which generates that my equipment does not report measurements and of the neighboring cells and therefore the decision to run the handover is not taken.
If anyone is facing a similar problem or already solved it I would appreciate your help.
Best regards!

**Reply by fllay** [reply]
I have similar problem and still cannot solve it. In log file, I found something  weird .

```
2025-06-23T03:52:58.804179 [CU      ] [I] Built in Release mode using commit d5fa4f0ecb on branch main
2025-06-23T03:52:58.806152 [CONFIG  ] [D] Input configuration (all values): 
metrics:
  enable_log: false
  enable_verbose: false
  enable_json: false
  addr: 127.0.0.1
  port: 55555
  layers:
    enable_app_usage: false
    enable_pdcp: false
  periodicity:
    cu_cp_report_period: 1000
periodicity:
  app_usage_report_period: 1000
log:
  filename: /tmp/cu.log
  lib_level: debug
  e2ap_level: debug
  config_level: debug
  hex_max_size: 0
  pdcp_level: debug
  rrc_level: debug
  ngap_level: debug
  nrppa_level: debug
  e1ap_level: debug
  f1ap_level: debug
  cu_level: debug
  sec_level: debug
  e1ap_json_enabled: false
  f1ap_json_enabled: false
buffer_pool:
  nof_segments: 1048576
  segment_size: 2048
remote_control:
  enabled: false
  bind_address: 127.0.0.1
  port: 8001
cu_cp:
  max_nof_dus: 6
  max_nof_cu_ups: 6
  max_nof_ues: 8192
  max_nof_drbs_per_ue: 8
  inactivity_timer: 7200
  request_pdu_session_timeout: 3
  amf:
    no_core: false
    amf_reconnection_retry_time: 1000
    amf:
      addr: 192.168.68.42
      port: 38412
      bind_addr: 192.168.68.210
      bind_interface: auto
      sctp_rto_initial: 120
      sctp_rto_min: 120
      sctp_rto_max: 500
      sctp_init_max_attempts: 3
      sctp_max_init_timeo: 500
      sctp_hb_interval: 30000
      sctp_assoc_max_retx: 10
      sctp_nodelay: false
      supported_tracking_areas:
        - tac: 7
          plmn_list:
            - plmn: 00101
              tai_slice_support_list:
                - sst: "\x01"
                  sd: 16777215
  mobility:
    trigger_handover_from_measurements: true
    cells:
      nr_cell_id: 6733826
      periodic_report_cfg_id: 1
      gnb_id_bit_length: 22
      ncells:
        nr_cell_id: 6733825
        report_configs: 2
    report_configs:
      report_cfg_id: 2
      report_type: event_triggered
      event_triggered_report_type: a3
      meas_trigger_quantity_offset_db: 2
      hysteresis_db: 0
      meas_trigger_quantity: rsrp
      time_to_trigger_ms: 100
      report_interval_ms: 0
  rrc:
    force_reestablishment_fallback: false
    rrc_procedure_timeout_ms: 720
  security:
    integrity: not_needed
    confidentiality: required
    nea_pref_list: nea0,nea2,nea1,nea3
    nia_pref_list: nia2,nia1,nia3
  f1ap:
    procedure_timeout: 1000
  e1ap:
    procedure_timeout: 1000
cu_up:
  f1u:
    socket:
      - bind_addr: 192.168.68.210
        ext_addr: auto
        udp:
          max_rx_msgs: 256
          pool_threshold: 0.899999976
  warn_on_drop: false
  log:
    pdcp_level: debug
    sdap_level: debug
    gtpu_level: debug
    f1u_level: debug
    cu_level: debug
    hex_max_size: 0
  pcap:
    n3_filename: /tmp/cu_n3.pcap
    n3_enable: true
    f1u_filename: /tmp/cu_f1u.pcap
    f1u_enable: true
    e1ap_filename: /tmp/cu_e1ap.pcap
    e1ap_enable: true
  metrics:
    periodicity:
      cu_up_report_period: 1000
    layers:
      enable_pdcp: false
  ngu:
    no_core: false
    gtpu:
      gtpu_queue_size: 8192
      gtpu_reordering_timer: 0
      rate_limiter_period: 100
    socket:
      - bind_addr: 192.168.68.213
        bind_interface: auto
        ext_addr: auto
        udp:
          max_rx_msgs: 256
          pool_threshold: 0.899999976
gnb_id: 411
gnb_id_bit_length: 22
ran_node_name: cu_cp_01
pcap:
  ngap_filename: /tmp/cu_ngap.pcap
  ngap_enable: true
  f1ap_filename: /tmp/cu_f1ap.pcap
  f1ap_enable: true
  e1ap_filename: /tmp/cu_e1ap.pcap
  e1ap_enable: true
  e2ap_cu_cp_filename: /tmp/cu_cp_e2ap.pcap
  e2ap_cu_cp_enable: false
  e2ap_cu_up_filename: /tmp/cu_up_e2ap.pcap
  e2ap_cu_up_enable: false
slicing:
  - sst: "\x01"
e2:
  enable_cu_cp_e2: false
  addr: 127.0.0.1
  port: 36421
  bind_addr: 127.0.0.1
  sctp_rto_initial: 120
  sctp_rto_min: 120
  sctp_rto_max: 500
  sctp_init_max_attempts: 3
  sctp_max_init_timeo: 500
  e2sm_kpm_enabled: false
  e2sm_rc_enabled: false
  enable_cu_up_e2: false
gnb_cu_up_id: 0
2025-06-23T03:53:01.289978 [CU      ] [D] Required CPU features: neon
```
In `mobility:` section It shows only one cell in `cells` list. However, in the CU config file, there are two cells.  

```
gnb_id: 411
gnb_id_bit_length: 22
ran_node_name: cu_cp_01

#slicing:                           
#  -                                   
#    sst: 1                               
#    sd: 0                              


cu_cp:
  inactivity_timer: 7200
  amf:
    addr: 192.168.68.42
    port: 38412
    bind_addr: 192.168.68.210
    supported_tracking_areas:
      - tac: 7
        plmn_list:
          - plmn: "00101"
            tai_slice_support_list:
              - sst: 1
  mobility:
    trigger_handover_from_measurements: true
    cells:
      - nr_cell_id: 0x66C001
        periodic_report_cfg_id: 1
        ncells:
          - nr_cell_id: 0x66C002
            report_configs: [ 2 ]
      - nr_cell_id: 0x66C002
        periodic_report_cfg_id: 1
        ncells:
          - nr_cell_id: 0x66C001
            report_configs: [ 2 ]

    report_configs:
      - report_cfg_id: 1
        report_type: periodical
        report_interval_ms: 480
      - report_cfg_id: 2
        report_type: event_triggered
        event_triggered_report_type: a3
        meas_trigger_quantity: rsrp
        meas_trigger_quantity_offset_db: 2
        hysteresis_db: 0
        time_to_trigger_ms: 100
#        report_interval_ms: 480

  f1ap:
    bind_addr: 192.168.68.213


cu_up:
  f1u:
      socket:                               # Define UDP/IP socket(s) for F1-U interface.
        -                                     # Socket 1
          bind_addr: 192.168.68.210

  ngu:
    socket:                               # Define socket(s) for NG-U interface.
      -                                     # Socket 1 
        bind_addr: 192.168.68.213                 # Optional TEXT (auto). Sets local IP address to bind for N3 interface. Format: IPV4 or IPV6 IP address.


log:
  filename: /tmp/cu.log
  all_level: debug


pcap:
  ngap_filename: /tmp/cu_ngap.pcap     # Optional TEXT (/tmp/gnb_ngap.pcap). Path for NGAP PCAPs. 
  ngap_enable: true                    # Optional BOOLEAN (false). Enable/disable NGAP packet capture. Supported: [false, true].
  n3_filename: /tmp/cu_n3.pcap         # Optional TEXT (/tmp/gnb_n3.pcap). Path for N3 PCAPs. 
  n3_enable: true                      # Optional BOOLEAN (false). Enable/disable N3 packet capture. Supported: [false, true].
  e1ap_filename: /tmp/cu_e1ap.pcap     # Optional TEXT (/tmp/gnb_e1ap.pcap). Path for E1AP PCAPs. 
  e1ap_enable: true                    # Optional BOOLEAN (false). Enable/disable E1AP packet capture. Supported: [false, true].
  f1ap_filename: /tmp/cu_f1ap.pcap     # Optional TEXT (/tmp/gnb_f1ap.pcap). Path for F1AP PCAPs. 
  f1ap_enable: true                    # Optional BOOLEAN (false). Enable/disable F1AP packet capture. Supported: [false, true].
  f1u_filename: /tmp/cu_f1u.pcap       # Optional TEXT (/tmp/gnb_f1ap.pcap). Path for F1AP PCAPs. 
  f1u_enable: true                     # Optional BOOLEAN (false). Enable/disable F1AP packet capture. Supported: [false, true].
```

When I start the first CU I got 

```
2025-06-23T03:57:09.418743 [CU-CP   ] [D]  - nci=0x66c001 complete=yes gnb_id=411 pci=1 band=78 ssb_arfcn=632256 ssb_scs=30kHz ncells=[ 0x66c002 ]
2025-06-23T03:57:09.418744 [CU-CP   ] [D]  - nci=0x66c002 complete=no gnb_id=411 pci=? band=? ssb_arfcn=? ssb_scs=? ncells=[ 0x66c001 ]
```

and when I start 2nd DU I got 

```
2025-06-23T04:02:12.273383 [CU-CP   ] [D]  - nci=0x66c001 complete=yes gnb_id=411 pci=1 band=78 ssb_arfcn=632256 ssb_scs=30kHz ncells=[ 0x66c002 ]
2025-06-23T04:02:12.273384 [CU-CP   ] [D]  - nci=0x66c002 complete=yes gnb_id=411 pci=2 band=78 ssb_arfcn=632256 ssb_scs=30kHz ncells=[ 0x66c001 ]
```

It seems that it knows `ncells`. When I am using  `Network Survey app` I could not see the neighbor cell and It can switch cells but not handover.  I still don't know what is wrong.

**Reply by BGarcs** [reply]
I am facing the same problem, but in my case I run the CU and I get the following:
```
2025-07-09T02:43:44.072078 [CU-CP   ] [D] Configured cells:
2025-07-09T02:43:44.072078 [CU-CP   ] [D]  - nci=0x19b0 complete=no gnb_id=411 pci=? band=? ssb_arfcn=? ssb_scs=? ncells=[ 0x19b1 ]
2025-07-09T02:43:44.072078 [CU-CP   ] [D]  - nci=0x19b1 complete=no gnb_id=411 pci=? band=? ssb_arfcn=? ssb_scs=? ncells=[ 0x19b0 ]
```

Then I run a DU (pci=0) and nothing appears but when I run the second DU (pci=1) I get this:
```
2025-07-09T02:49:02.881169 [CU-CP   ] [D] Configured cells:
2025-07-09T02:49:02.881170 [CU-CP   ] [D]  - nci=0x19b0 complete=yes gnb_id=411 pci=0 band=78 ssb_arfcn=632256 ssb_scs=30kHz ncells=[ 0x19b1 ]
2025-07-09T02:49:02.881170 [CU-CP   ] [D]  - nci=0x19b1 complete=no gnb_id=411 pci=? band=? ssb_arfcn=? ssb_scs=? ncells=[ 0x19b0 ]
```

Finally, when I connect the UE I just get this:
```
2025-07-09T02:49:25.915790 [CU-CP   ] [D] Configured cells:
2025-07-09T02:49:25.915791 [CU-CP   ] [D]  - nci=0x19b0 complete=yes gnb_id=411 pci=0 band=78 ssb_arfcn=632256 ssb_scs=30kHz ncells=[ 0x19b1 ]
2025-07-09T02:49:25.915791 [CU-CP   ] [D]  - nci=0x19b1 complete=yes gnb_id=411 pci=1 band=78 ssb_arfcn=632256 ssb_scs=30kHz ncells=[ 0x19b0 ]
```

I still don't understand what the problem is, I thought it was a USRP synchronization problem so I am using a function generator to generate a 10MHz waveform and a 1PPS waveform to synchronize both radios in frequency and time. However I have not been able to completely solve the problem and what's more, sometimes the system works and the system is able to perform handovers for periods of time (5-10 minutes), but then I try to run the system without changing anything and it does not work in the same way.

Has anyone made any progress or know what could be the reason for this kind of inconsistencies?

I am waiting for any answer from any of you and thank you very much in advance!
Best regards!

**Reply by aibtw** [reply]
I see something similar to @fllay , in my gNB config mobility section I defined 2 cells, but in the logs mobility section only 1 is reported: 
in my gNB configs:
```
cu_cp:
  amf:
    addr: 127.0.1.100 # Replace this section with your AMF settings.
    bind_addr: 127.0.0.1
    supported_tracking_areas:
      - tac: 7
        plmn_list:
          - plmn: "99970"
            tai_slice_support_list:
              - sst: 1
  mobility:
    trigger_handover_from_measurements: true
    cells:
      - nr_cell_id: 0x66C000
        periodic_report_cfg_id: 1     # This will configure a periodical report config for the serving cell.
        ncells:
          - nr_cell_id: 0x66C001
            report_configs: [ 2 ]
      - nr_cell_id: 0x66C001
        periodic_report_cfg_id: 1
        ncells:
          - nr_cell_id: 0x66C000
            report_configs: [ 2 ]
    report_configs:
      - report_cfg_id: 1
        report_type: periodical
        report_interval_ms: 1024
      - report_cfg_id: 2
        report_type: event_triggered
        event_triggered_report_type: a3
        meas_trigger_quantity: rsrp
        meas_trigger_quantity_offset_db: 6
        hysteresis_db: 0
        time_to_trigger_ms: 100
        report_interval_ms: 1024

```

and in my gnb.log
```
cu_cp:
  max_nof_dus: 6
  max_nof_cu_ups: 6
  max_nof_ues: 8192
  max_nof_drbs_per_ue: 8
  inactivity_timer: 7200
  request_pdu_session_timeout: 3
  amf:
    no_core: false
    amf_reconnection_retry_time: 1000
    amf:
      addr: 127.0.1.100
      port: 38412
      bind_addr: 127.0.0.1
      bind_interface: auto
      sctp_rto_initial: 120
      sctp_rto_min: 120
      sctp_rto_max: 500
      sctp_init_max_attempts: 3
      sctp_max_init_timeo: 500
      sctp_hb_interval: 30000
      sctp_assoc_max_retx: 10
      sctp_nodelay: false
      supported_tracking_areas:
        - tac: 7
          plmn_list:
            - plmn: 99970
              tai_slice_support_list:
                - sst: "\x01"
                  sd: 16777215
  mobility:
    trigger_handover_from_measurements: true
    cells:
      nr_cell_id: 6733825
      periodic_report_cfg_id: 1
      gnb_id_bit_length: 22
      ncells:
        nr_cell_id: 6733824
        report_configs: 2
    report_configs:
      report_cfg_id: 2
      report_type: event_triggered
      event_triggered_report_type: a3
      meas_trigger_quantity_offset_db: 6
      hysteresis_db: 0
      meas_trigger_quantity: rsrp
      time_to_trigger_ms: 100
      report_interval_ms: 1024
```

The behavior I am facing (release 25.10) is that the UE always "tries" to attach to the first cell, but never succeeds. 

I tried to remove the mobility section, and try to do manual (forced) handover using the ho command in the cli, and it works fine (UE can connect to any cell and I can force it to handover to another cell). But as soon as I add the mobility section, the UE refuses to connect.
Mobility configs is working fine on release 24.10.1 though, seems like an issue in the newer commits.
