### DISCUSSION TITLE
oran-sc RIC handover using two B210s

### DISCUSSION THREAD

**Discussion by fllay** [srsran/srsRAN_Project#1256] [General Help] [answered]
I am trying to test  oran-sc RIC handover using two B210s. My set up is in the following figure

![Screenshot 2568-06-16 at 22 49 19](https://github.com/user-attachments/assets/7c418643-f779-412c-8fe2-3380679d04a8)

RIC is a docker stack running on machine 1 and I enable this line on the docker-compose.yaml

```
 e2term:
    container_name: ric_e2term
    hostname: e2term
    image: nexus3.o-ran-sc.org:10002/o-ran-sc/ric-plt-e2:${E2TERM_VER}
    #Uncomment ports to use the RIC from outside the docker network.
    ports:
      - "36421:36421/sctp"
```

The configurations for CU in machine 2 are `cu.yaml` and `e2.yaml`

- `cu.yaml` 

```
gnb_id: 531
gnb_id_bit_length: 32
ran_node_name: cu_cp_01

cu_cp:
  inactivity_timer: 7200
  amf:
    addr: 192.168.68.42
    port: 38412
    bind_addr: 192.168.68.210
    supported_tracking_areas:
      - tac: 7
        plmn_list:
          - plmn: "00101"
            tai_slice_support_list:
              - sst: 1
  mobility:
    trigger_handover_from_measurements: true
    cells:
      - nr_cell_id: 0x2130
        periodic_report_cfg_id: 1
        ncells:
          - nr_cell_id: 0x2131
            report_configs: [ 2 ]
      - nr_cell_id: 0x2131
        periodic_report_cfg_id: 1
        ncells:
          - nr_cell_id: 0x2130
            report_configs: [ 2 ]
    report_configs:
      - report_cfg_id: 1
        report_type: periodical
        report_interval_ms: 1024
      - report_cfg_id: 2
        report_type: event_triggered
        event_triggered_report_type: a3
        meas_trigger_quantity: rsrp
        meas_trigger_quantity_offset_db: 2
        hysteresis_db: 0
        time_to_trigger_ms: 100
      #  report_interval_ms: 1024

  f1ap:
    bind_addr: 192.168.68.213


cu_up:
  f1u:
      socket:                               # Define UDP/IP socket(s) for F1-U interface.
        -                                     # Socket 1
          bind_addr: 192.168.68.210

  ngu:
    socket:                               # Define socket(s) for NG-U interface.
      -                                     # Socket 1 
        bind_addr: 192.168.68.213                 # Optional TEXT (auto). Sets local IP address to bind for N3 interface. Format: IPV4 or IPV6 IP address.


log:
  filename: /tmp/cu.log
  all_level: debug


pcap:
  ngap_filename: /tmp/cu_ngap.pcap     # Optional TEXT (/tmp/gnb_ngap.pcap). Path for NGAP PCAPs. 
  ngap_enable: true                    # Optional BOOLEAN (false). Enable/disable NGAP packet capture. Supported: [false, true].
  n3_filename: /tmp/cu_n3.pcap         # Optional TEXT (/tmp/gnb_n3.pcap). Path for N3 PCAPs. 
  n3_enable: true                      # Optional BOOLEAN (false). Enable/disable N3 packet capture. Supported: [false, true].
  e1ap_filename: /tmp/cu_e1ap.pcap     # Optional TEXT (/tmp/gnb_e1ap.pcap). Path for E1AP PCAPs. 
  e1ap_enable: true                    # Optional BOOLEAN (false). Enable/disable E1AP packet capture. Supported: [false, true].
  f1ap_filename: /tmp/cu_f1ap.pcap     # Optional TEXT (/tmp/gnb_f1ap.pcap). Path for F1AP PCAPs. 
  f1ap_enable: true                    # Optional BOOLEAN (false). Enable/disable F1AP packet capture. Supported: [false, true].
  f1u_filename: /tmp/cu_f1u.pcap       # Optional TEXT (/tmp/gnb_f1ap.pcap). Path for F1AP PCAPs. 
  f1u_enable: true                     # Optional BOOLEAN (false). Enable/disable F1AP packet capture. Supported: [false, true].
```

- `e2.yaml`

```
e2:
  enable_cu_up_e2: true
  enable_cu_cp_e2: true
  e2sm_kpm_enabled: true            # Enable KPM service module
  e2sm_rc_enabled: true             # Enable RC service module
  addr: 192.168.68.152                   # RIC IP address
  bind_addr: 192.168.68.210           # A local IP that the E2 agent binds to for traffic from the RIC. ONLY required if running the RIC on a separate machine. 
  #addr: 10.0.2.10                   # RIC IP address
  #bind_addr: 10.0.2.1               # A local IP that the E2 agent binds to for traffic from the RIC. ONLY required if running the RIC on a separate machine. 
  port: 36421                       # RIC port


metrics:
  enable_log: false
  enable_json: false

  periodicity:
    app_usage_report_period: 1000
    cu_up_report_period: 1000
    cu_cp_report_period: 1000

  layers:
    enable_pdcp: false
    enable_e1ap: false
    enable_app_usage: true
```

DU1 is on machine 4 with the following configurations

- `du1.yaml`

```
gnb_id: 531
gnb_id_bit_length: 32
gnb_du_id: 0

f1ap:
  cu_cp_addr: 192.168.68.213
  bind_addr: 192.168.68.30

f1u:
  socket:
    - bind_addr: 192.168.68.30

ru_sdr:
  device_driver: uhd
  device_args: type=b200,num_recv_frames=64,num_send_frames=64,time_source=external
  srate: 23.04
  otw_format: sc12
  tx_gain: 55
  rx_gain: 40
#  clock: external                        # Optional TEXT (default). Specify the RF device clock source (i.e., 10MHz reference oscillator). Supported: [default, internal, external, gpsdo].
#  sync: external                         # Optional TEXT (default). Specify the RF device time synchronization source (i.e., 1PPS reference). Supported: [default, internal, external, gpsdo].


cell_cfg:
  dl_arfcn: 632628                                                # ARFCN of the downlink carrier>
  band: 78                                                        # The NR band.
  channel_bandwidth_MHz: 20                                       # Bandwith in MHz. Number of PR>
  common_scs: 30                                                  # Subcarrier spacing in kHz use>
  plmn: "00101"                                                   # PLMN broadcasted by the gNB.
  tac: 7                                                          # Tracking area code (needs to >
  pci: 1                                                          # Physical cell ID.
  nof_antennas_dl: 1
  nof_antennas_ul: 1
  sector_id: 1
  pdsch:
    mcs_table: qam256

log:
  filename: /tmp/du.log
  all_level: debug

pcap:
  mac_enable: false
  mac_filename: /tmp/du_mac.pcap
  f1ap_enable: false
  f1ap_filename: /tmp/du_f1ap.pcap
  f1u_enable: false
  f1u_filename: /tmp/du_f1u.pcap
``` 

- `e2du.yaml`

```
e2:
  enable_du_e2: true                # Enable DU E2 agent (one for each DU instance)
  e2sm_kpm_enabled: true            # Enable KPM service module
  e2sm_rc_enabled: true             # Enable RC service module
  addr: 192.168.68.152                   # RIC IP address
  bind_addr: 192.168.68.30           # A local IP that the E2 agent binds to for traffic from the RIC. ONLY required if running the RIC on a separate machine. 
  #addr: 10.0.2.10                   # RIC IP address
  #bind_addr: 10.0.2.1               # A local IP that the E2 agent binds to for traffic from the RIC. ONLY required if running the RIC on a separate machine. 
  port: 36421                       # RIC port


metrics:
  autostart_stdout_metrics: false
  enable_log: false
  enable_json: false

  periodicity:
    du_report_period: 1000

  layers:
    enable_ru: true
    enable_sched: true
    enable_rlc: true
    enable_mac: true
    enable_executor: true
    enable_du_low: true
```

DU2 is on machine 3 with the following configurations

- `du2.yaml`

```
gnb_id: 531
gnb_id_bit_length: 32
gnb_du_id: 1

f1ap:
  cu_cp_addr: 192.168.68.213
  bind_addr: 192.168.68.152

f1u:
  socket:
    - bind_addr: 192.168.68.152

ru_sdr:
  device_driver: uhd
  device_args: type=b200,num_recv_frames=64,num_send_frames=64,time_source=external
  srate: 23.04
  otw_format: sc12
  tx_gain: 55
  rx_gain: 40
#  clock: external                      
#  sync: external                        


cell_cfg:
  dl_arfcn: 650000               #632628                          # ARFCN of the downlink carrier>
  band: 78                                                        # The NR band.
  channel_bandwidth_MHz: 20                                       # Bandwith in MHz. Number of PR>
  common_scs: 30                                                  # Subcarrier spacing in kHz use>
  plmn: "00101"                                                   # PLMN broadcasted by the gNB.
  tac: 7                                                          # Tracking area code (needs to >
  pci: 2                                                          # Physical cell ID.
  nof_antennas_dl: 1
  nof_antennas_ul: 1
  sector_id: 2
  pdsch:
    mcs_table: qam256

log:
  filename: /tmp/du.log
  all_level: debug

pcap:
  mac_enable: false
  mac_filename: /tmp/du_mac.pcap
  f1ap_enable: false
  f1ap_filename: /tmp/du_f1ap.pcap
  f1u_enable: false
  f1u_filename: /tmp/du_f1u.pcap
``` 

- `e2du.yaml`

```
e2:
  enable_du_e2: true                # Enable DU E2 agent (one for each DU instance)
  e2sm_kpm_enabled: true            # Enable KPM service module
  e2sm_rc_enabled: true             # Enable RC service module
  addr: 192.168.68.152                   # RIC IP address
  bind_addr: 192.168.68.152           # A local IP that the E2 agent binds to for traffic from the RIC. ONLY required if running the RIC on a separate machine. 
  #addr: 10.0.2.10                   # RIC IP address
  #bind_addr: 10.0.2.1               # A local IP that the E2 agent binds to for traffic from the RIC. ONLY required if running the RIC on a separate machine. 
  port: 36421                       # RIC port


metrics:
  autostart_stdout_metrics: false
  enable_log: false
  enable_json: false

  periodicity:
    du_report_period: 1000

  layers:
    enable_ru: true
    enable_sched: true
    enable_rlc: true
    enable_mac: true
    enable_executor: true
    enable_du_low: false
```

I verified that the handover can be done using `ho` command in CU. 

When RIC is up I  got the following 
```
ric_submgr          | 1750085837413 1/RMR [INFO] ric message routing library on SI95 p=4560 mv=3 flg=00 id=a (f447e29 4.9.4 built: Dec 13 2023)
ric_submgr          | 2025/06/16 14:57:17 Serving xapp framework at http://[::]:8088
ric_appmgr          | redis: got 7 elements in COMMAND reply, wanted 6
ric_appmgr          | 2025/06/16 14:57:18 Serving app manager at http://[::]:8080
ric_rtmgr_sim       | 2025/06/16 14:57:18 POST /ric/v1/handles/e2t  body: {"E2TAddress":"10.0.2.10:38000"} elapsed: 10.646µs
ric_submgr          | RMR is ready now ...
```

and CU is up the RIC output is 

```
ric_rtmgr_sim       | 2025/06/16 14:58:53 POST /ric/v1/handles/associate-ran-to-e2t  body: [{"E2TAddress":"10.0.2.10:38000","ranNamelist":["gnbd_001_001_00000213_1"]}] elapsed: 18.756µs
ric_rtmgr_sim       | 2025/06/16 14:58:53 POST /ric/v1/handles/associate-ran-to-e2t  body: [{"E2TAddress":"10.0.2.10:38000","ranNamelist":["gnb_001_001_00000213"]}] elapsed: 6.888µs
```

when both DUs are up

- DU1 

```
ric_rtmgr_sim       | 2025/06/16 15:04:10 POST /ric/v1/handles/associate-ran-to-e2t  body: [{"E2TAddress":"10.0.2.10:38000","ranNamelist":["gnbd_001_001_00000213_0"]}] elapsed: 33.541µs
```

- DU2

```
ric_rtmgr_sim       | 2025/06/16 15:04:21 POST /ric/v1/handles/associate-ran-to-e2t  body: [{"E2TAddress":"10.0.2.10:38000","ranNamelist":["gnbd_001_001_00000213_1"]}] elapsed: 10.759µs
```

Then I verify this set up by using the kpm app for active DU

```
./kpm_mon_xapp.py --e2_node_id=gnbd_001_001_00000213_0 
1750087918467 30/RMR [INFO] ric message routing library on SI95 p=4562 mv=3 flg=00 id=a (f447e29 4.9.4 built: Dec 13 2023)
Subscribe to E2 node ID: gnbd_001_001_00000213_0, RAN func: e2sm_kpm, Report Style: 1, metrics: ['DRB.UEThpUl', 'DRB.UEThpDl']
Successfully subscribed with Subscription ID:  2yb0MlQnvnHzOjsYYbNdPu0Ayw3
Received Subscription ID to E2EventInstanceId mapping: 2yb0MlQnvnHzOjsYYbNdPu0Ayw3 -> 1
{'response': 'OK', 'status': 200, 'payload': '{}', 'ctype': 'application/json', 'attachment': None, 'mode': 'plain'}
10.0.2.13 - - [16/Jun/2025 15:31:59] "POST /ric/v1/subscriptions/response HTTP/1.1" 200 -

RIC Indication Received from gnbd_001_001_00000213_0 for Subscription ID: 1, KPM Report Style: 1
E2SM_KPM RIC Indication Content:
-ColletStartTime:  2025-06-16 15:32:00
-Measurements Data:
-granulPeriod: 1000
--Metric: DRB.UEThpUl, Value: [1.0]
--Metric: DRB.UEThpDl, Value: [0.0]
```

Then I try handover xApp with all possible combinations

```
root@python_xapp_runner:/opt/xApps# ./simple_rc_ho_xapp.py --e2_node_id gnbd_001_001_00000213_1  --plmn 00101 --amf_ue_ngap_id 1 --target_nr_cell_id 0x2131
1750088083480 38/RMR [INFO] ric message routing library on SI95 p=4560 mv=3 flg=00 id=a (f447e29 4.9.4 built: Dec 13 2023)
15:34:44 Sending HO command to E2 node ID: gnbd_001_001_00000213_1, PLMN: 00101, AMF UE NGAP ID: 1, UE F1AP ID: 1, Target NR Cell ID: 8497
root@python_xapp_runner:/opt/xApps# ./simple_rc_ho_xapp.py --e2_node_id gnbd_001_001_00000213_1  --plmn 00101 --amf_ue_ngap_id 1 --target_nr_cell_id 0x2130
1750088096604 46/RMR [INFO] ric message routing library on SI95 p=4560 mv=3 flg=00 id=a (f447e29 4.9.4 built: Dec 13 2023)
15:34:57 Sending HO command to E2 node ID: gnbd_001_001_00000213_1, PLMN: 00101, AMF UE NGAP ID: 1, UE F1AP ID: 1, Target NR Cell ID: 8496
root@python_xapp_runner:/opt/xApps# ./simple_rc_ho_xapp.py --e2_node_id gnbd_001_001_00000213_0  --plmn 00101 --amf_ue_ngap_id 1 --target_nr_cell_id 0x2131
1750088114984 54/RMR [INFO] ric message routing library on SI95 p=4560 mv=3 flg=00 id=a (f447e29 4.9.4 built: Dec 13 2023)
15:35:16 Sending HO command to E2 node ID: gnbd_001_001_00000213_0, PLMN: 00101, AMF UE NGAP ID: 1, UE F1AP ID: 1, Target NR Cell ID: 8497
root@python_xapp_runner:/opt/xApps# ./simple_rc_ho_xapp.py --e2_node_id gnbd_001_001_00000213_0  --plmn 00101 --amf_ue_ngap_id 1 --target_nr_cell_id 0x2130
1750088125643 62/RMR [INFO] ric message routing library on SI95 p=4560 mv=3 flg=00 id=a (f447e29 4.9.4 built: Dec 13 2023)
15:35:26 Sending HO command to E2 node ID: gnbd_001_001_00000213_0, PLMN: 00101, AMF UE NGAP ID: 1, UE F1AP ID: 1, Target NR Cell ID: 8496
```

All of command give me no feedback and no handover. I am not sure about `amf_ue_ngap_id ` parameter and how to determine `e2_node_id ` and  corresponding `cell_id`?  Will this set up with two B210s ever work? Any idea please.

**Comment by pgawlowicz** [comment, marked as answer]
Hi, the counterpart E2 HO code in the srsRAN-5G project will be published with the next release (this or next week).

**Reply by fllay** [reply]
Thank you very much for information.

**Reply by fllay** [reply]
I confirmed that E2 HO is working now. I am using the following config files.


CU:
`cu.yaml`

```
gnb_id: 411
gnb_id_bit_length: 22
ran_node_name: cu_cp_01

#slicing:                           
#  -                                   
#    sst: 1                               
#    sd: 0                              


cu_cp:
  inactivity_timer: 7200
  amf:
    addr: 192.168.68.42
    port: 38412
    bind_addr: 192.168.68.210
    supported_tracking_areas:
      - tac: 7
        plmn_list:
          - plmn: "00101"
            tai_slice_support_list:
              - sst: 1
  mobility:
    trigger_handover_from_measurements: false
    cells:
      - nr_cell_id: 0x66C001
        periodic_report_cfg_id: 1
        ncells:
          - nr_cell_id: 0x66C002
            report_configs: [ 2 ]
      - nr_cell_id: 0x66C002
        periodic_report_cfg_id: 1
        ncells:
          - nr_cell_id: 0x66C001
            report_configs: [ 2 ]

    report_configs:
      - report_cfg_id: 1
        report_type: periodical
        report_interval_ms: 480
      - report_cfg_id: 2
        report_type: event_triggered
        event_triggered_report_type: a3
        meas_trigger_quantity: rsrp
        meas_trigger_quantity_offset_db: 2
        hysteresis_db: 0
        time_to_trigger_ms: 100
#        report_interval_ms: 480

  f1ap:
    bind_addr: 192.168.68.213


cu_up:
  f1u:
      socket:                               # Define UDP/IP socket(s) for F1-U interface.
        -                                     # Socket 1
          bind_addr: 192.168.68.210

  ngu:
    socket:                               # Define socket(s) for NG-U interface.
      -                                     # Socket 1 
        bind_addr: 192.168.68.213                 # Optional TEXT (auto). Sets local IP address to bind for N3 interface. Format: IPV4 or IPV6 IP address.


log:
  filename: /tmp/cu.log
  all_level: debug


pcap:
  ngap_filename: /tmp/cu_ngap.pcap     # Optional TEXT (/tmp/gnb_ngap.pcap). Path for NGAP PCAPs. 
  ngap_enable: true                    # Optional BOOLEAN (false). Enable/disable NGAP packet capture. Supported: [false, true].
  n3_filename: /tmp/cu_n3.pcap         # Optional TEXT (/tmp/gnb_n3.pcap). Path for N3 PCAPs. 
  n3_enable: true                      # Optional BOOLEAN (false). Enable/disable N3 packet capture. Supported: [false, true].
  e1ap_filename: /tmp/cu_e1ap.pcap     # Optional TEXT (/tmp/gnb_e1ap.pcap). Path for E1AP PCAPs. 
  e1ap_enable: true                    # Optional BOOLEAN (false). Enable/disable E1AP packet capture. Supported: [false, true].
  f1ap_filename: /tmp/cu_f1ap.pcap     # Optional TEXT (/tmp/gnb_f1ap.pcap). Path for F1AP PCAPs. 
  f1ap_enable: true                    # Optional BOOLEAN (false). Enable/disable F1AP packet capture. Supported: [false, true].
  f1u_filename: /tmp/cu_f1u.pcap       # Optional TEXT (/tmp/gnb_f1ap.pcap). Path for F1AP PCAPs. 
  f1u_enable: true                     # Optional BOOLEAN (false). Enable/disable F1AP packet capture. Supported: [false, true].
```

DU1:
`du2.yaml`

```
gnb_id: 411
gnb_id_bit_length: 22
gnb_du_id: 0

f1ap:
  cu_cp_addr: 192.168.68.213
  bind_addr: 192.168.68.30

f1u:
  socket:
    - bind_addr: 192.168.68.30

ru_sdr:
  device_driver: uhd
  device_args: type=b200,num_recv_frames=64,num_send_frames=64
  srate: 23.04
  otw_format: sc12
  tx_gain: 70
  rx_gain: 40
  #clock: external                        # Optional TEXT (default). Specify the RF device clock source (i.e., 10MHz reference oscillator). Supported: [default, internal, external, gpsdo].
  #sync: external                         # Optional TEXT (default). Specify the RF device time synchronization source (i.e., 1PPS reference). Supported: [default, internal, external, gpsdo].



cell_cfg:
  dl_arfcn: 632628                                                # ARFCN of the downlink carrier>
  band: 78                                                        # The NR band.
  channel_bandwidth_MHz: 20                                       # Bandwith in MHz. Number of PR>
  common_scs: 30                                                  # Subcarrier spacing in kHz use>
  plmn: "00101"                                                   # PLMN broadcasted by the gNB.
  tac: 7                                                          # Tracking area code (needs to >
  pci: 1                                                          # Physical cell ID.
  nof_antennas_dl: 1
  nof_antennas_ul: 1
  sector_id: 1
  pdsch:
    mcs_table: qam256

log:
  filename: /tmp/du.log
  all_level: debug

pcap:
  mac_enable: false
  mac_filename: /tmp/du_mac.pcap
  f1ap_enable: false
  f1ap_filename: /tmp/du_f1ap.pcap
  f1u_enable: false
  f1u_filename: /tmp/du_f1u.pcap
```
`e2du.yaml`

```
e2:
  enable_du_e2: true                # Enable DU E2 agent (one for each DU instance)
  e2sm_kpm_enabled: true            # Enable KPM service module
  e2sm_rc_enabled: true             # Enable RC service module
  addr: 192.168.68.152                   # RIC IP address
  bind_addr: 192.168.68.30           # A local IP that the E2 agent binds to for traffic from the RIC. ONLY required if running the RIC on a separate machine. 
  #addr: 10.0.2.10                   # RIC IP address
  #bind_addr: 10.0.2.1               # A local IP that the E2 agent binds to for traffic from the RIC. ONLY required if running the RIC on a separate machine. 
  port: 36421                       # RIC port


metrics:
  autostart_stdout_metrics: false
  enable_log: false
  enable_json: false

  periodicity:
    du_report_period: 1000

  layers:
    enable_ru: true
    enable_sched: true
    enable_rlc: true
    enable_mac: true
    enable_executor: true
    enable_du_low: true
```

DU2:
`du2.yaml`

```
gnb_id: 411
gnb_id_bit_length: 22
gnb_du_id: 1

f1ap:
  cu_cp_addr: 192.168.68.213
  bind_addr: 192.168.68.152

f1u:
  socket:
    - bind_addr: 192.168.68.152

ru_sdr:
  device_driver: uhd
  device_args: type=b200,num_recv_frames=64,num_send_frames=64
  srate: 23.04
  otw_format: sc12
  tx_gain: 70
  rx_gain: 40
  #clock: external                        # Optional TEXT (default). Specify the RF device clock source (i.e., 10MHz reference oscillator). Supported: [default, internal, external, gpsdo].
  #sync: external                         # Optional TEXT (default). Specify the RF device time synchronization source (i.e., 1PPS reference). Supported: [default, internal, external, gpsdo].



cell_cfg:
  dl_arfcn: 632628                                                # ARFCN of the downlink carrier>
  band: 78                                                        # The NR band.
  channel_bandwidth_MHz: 20                                       # Bandwith in MHz. Number of PR>
  common_scs: 30                                                  # Subcarrier spacing in kHz use>
  plmn: "00101"                                                   # PLMN broadcasted by the gNB.
  tac: 7                                                          # Tracking area code (needs to >
  pci: 2                                                          # Physical cell ID.
  nof_antennas_dl: 1
  nof_antennas_ul: 1
  sector_id: 2
  pdsch:
    mcs_table: qam256

log:
  filename: /tmp/du.log
  all_level: debug

pcap:
  mac_enable: false
  mac_filename: /tmp/du_mac.pcap
  f1ap_enable: false
  f1ap_filename: /tmp/du_f1ap.pcap
  f1u_enable: false
  f1u_filename: /tmp/du_f1u.pcap
```

`e2du.yaml`

```
e2:
  enable_du_e2: true                # Enable DU E2 agent (one for each DU instance)
  e2sm_kpm_enabled: true            # Enable KPM service module
  e2sm_rc_enabled: true             # Enable RC service module
  addr: 192.168.68.152                   # RIC IP address
  bind_addr: 192.168.68.152           # A local IP that the E2 agent binds to for traffic from the RIC. ONLY required if running the RIC on a separate machine. 
  #addr: 10.0.2.10                   # RIC IP address
  #bind_addr: 10.0.2.1               # A local IP that the E2 agent binds to for traffic from the RIC. ONLY required if running the RIC on a separate machine. 
  port: 36421                       # RIC port


metrics:
  autostart_stdout_metrics: false
  enable_log: false
  enable_json: false

  periodicity:
    du_report_period: 1000

  layers:
    enable_ru: true
    enable_sched: true
    enable_rlc: true
    enable_mac: true
    enable_executor: true
    enable_du_low: false
```

When CU and both DUs are started, it shows 
```
ric_rtmgr_sim       | 2025/06/24 14:52:02 POST /ric/v1/handles/associate-ran-to-e2t  body: [{"E2TAddress":"10.0.2.10:38000","ranNamelist":["gnb_001_001_00019b"]}] elapsed: 10.096µs
ric_rtmgr_sim       | 2025/06/24 14:52:02 POST /ric/v1/handles/associate-ran-to-e2t  body: [{"E2TAddress":"10.0.2.10:38000","ranNamelist":["gnbc_001_001_00019b_0"]}] elapsed: 14.658µs
ric_rtmgr_sim       | 2025/06/24 14:52:14 POST /ric/v1/handles/associate-ran-to-e2t  body: [{"E2TAddress":"10.0.2.10:38000","ranNamelist":["gnbd_001_001_00019b_0"]}] elapsed: 10.08µs
ric_rtmgr_sim       | 2025/06/24 14:52:17 POST /ric/v1/handles/associate-ran-to-e2t  body: [{"E2TAddress":"10.0.2.10:38000","ranNamelist":["gnbd_001_001_00019b_1"]}] elapsed: 11.613µs
```
in oransc docker.

It can be observed that for CU, `ranNamelist ` is  `gnbc_001_001_00019b_0` and for DU1 and DU2, `ranNamelist ` are 
`gnbd_001_001_00019b_0` and `gnbd_001_001_00019b_1` respectively. 

RIC handover can be trigged by 
```
./simple_rc_ho_xapp.py --e2_node_id gnb_001_001_00019b  --plmn 00101 --amf_ue_ngap_id 6 --target_nr_cell_id  0x66C002
```
or 
```
./simple_rc_ho_xapp.py --e2_node_id gnb_001_001_00019b  --plmn 00101 --amf_ue_ngap_id 6 --target_nr_cell_id  0x66C001
```
The successful response is something like
```
1750777544061 139/RMR [INFO] ric message routing library on SI95 p=4560 mv=3 flg=00 id=a (f447e29 4.9.4 built: Dec 13 2023)
15:05:45 Sending HO command to E2 node ID: gnb_001_001_00019b, PLMN: 00101, AMF UE NGAP ID: 6, UE F1AP ID: 1, Target NR Cell ID: 6733825
Received RIC_CONTROL_ACK
```


One last thing is, how can I get `AMF UE NGAP ID` programmatically? Now I have to check `cu.log` for the current value of `AMF UE NGAP ID` ? And, what is the `UE F1AP ID` and how can I get that value?


BTW, I can also comfirm that PRB control RIC now is working perfectly. I can even check what the number of assigned PRB of the UE since now the monitoring support that. Thank you.
