### DISCUSSION TITLE
Inaccurate time_alignment/ToA Estimate with Benetel RAN650 in outdoor deployment.

### DISCUSSION THREAD

**Discussion by ujjwalpawar** [srsran/srsRAN_Project#1260] [General Help]
Setup: 
srsRAN 22.10.1 (d5fa4f0ecbcee45167755c03643212f1a3a96e47)

- Benetel RAN650 with external Antenna
- Using DPDK based setup with intel 810 NIC
- SRS is enabled. 
- SRS Parameter used : 

```
  srs:
    srs_period_ms: 320
    srs_max_nof_sym_per_slot: 6          
    srs_nof_sym_per_resource: 4             
    srs_tx_comb: 2                       
    srs_cyclic_shift_reuse: 1             
    srs_sequence_id_reuse: 1
```
I’m using the output of the estimate function from [time_alignment_estimator_dft_impl.cpp](https://github.com/srsran/srsRAN_Project/blob/main/lib/phy/support/time_alignment_estimator/time_alignment_estimator_dft_impl.cpp) to estimate the Time of Arrival (ToA). However, regardless of the UE's distance from the base station, the estimated value consistently falls between 150 ns and 300 ns. For instance, when the UE is just 10 meters away, the function returns a value in this range. Even when the UE is over 300 meters away, the estimate still remains between 150 ns and 300 ns.
