### DISCUSSION TITLE
gNB-FlexRIC connection error

### DISCUSSION THREAD

**Discussion by rolandmartinson7890** [srsran/srsRAN_Project#170] [General Help] [answered]
Hello srsRAN folks.

I am getting this error when I am trying to connect my gNB to FlexRIC.
I can see that the port that the gNB is trying to connect to to access FlexRIC is different that what FlexRIC is exposing. I am also not sure if FlexRIC is constantly listening. When I check open ports, I do not see 36422.

Could anyone help with this. Here are the outputs from FlexRIC and gNB: 

### **FlexRIC output**
[iApp]: Initializing ... 
[iApp]: nearRT-RIC IP Address = 127.0.0.1, PORT = 36422
fd created with 6 
nearRT-RIC: /flexric/src/lib/ap/dec/e2ap_msg_dec_asn.c:2406: e2ap_create_pdu: Assertion `rval.code == RC_OK && "Are you sending data in ATS_ALIGEND_BASIC_PER syntax?"' failed.
Aborted (core dumped)

**### gNB output:**

Lower PHY in executor blocking mode.

--== srsRAN gNB (commit 1afd7240f) ==--

Connecting to AMF on 10.53.1.2:38412
Available radio types: uhd and zmq.
Connecting to NearRT-RIC on 127.0.0.1:36421
Cell pci=1, bw=10 MHz, dl_arfcn=368500 (n3), dl_freq=1842.5 MHz, dl_ssb_arfcn=368410, ul_freq=1747.5 MHz

==== gNodeB started ===
Type <t> to view trace

**Comment by pgawlowicz** [comment]
Hi, did you use proper FlexRIC branch and our patch?
See our tutorial here:
https://docs.srsran.com/projects/project/en/latest/tutorials/source/flexric/source/index.html#id2

**Reply by rolandmartinson7890** [reply]
Yes I did.

From the guide I think this basically does the job (after downloading the patch and pasting it in the flexric root folder):

git clone https://gitlab.eurecom.fr/mosaic5g/flexric.git
cd flexric
git checkout e2ap-v2
git apply -v ./flexric.patch
mkdir build
cd build
cmake ../
make
make install

**Reply by undeathkhaoz** [reply]
While i was installing, at the 'make install' step, i needed to execute it as sudo. 
Did you check if there were any errors during the installation?

**Reply by rolandmartinson7890** [reply]
@undeathkhaoz I guess that works as well. My trick was to just do the whole installation as root (sudo su).

**Comment by pgawlowicz** [comment, marked as answer]
you can set the IP and port of the RIC in the config:

```
e2:
  enable_du_e2: true                     # Enable DU E2 agent (one for each DU instance)
  e2sm_kpm_enabled: true                 # Enable KPM service module
  addr: 127.0.0.1                        # RIC IP address"
  port: 36421                            # RIC port
```
