### DISCUSSION TITLE
Low Uplink (UL) data rate using USRP B210

### DISCUSSION THREAD

**Discussion by arman-maghsoudnia** [srsran/srsRAN_Project#230] [General Help] [answered]
Hi,

We are using a B210 USRP with the srsRAN. When we connect our COTS UE (OnePlus Nord CE 3) to the network, we are experiencing low UL data rate in our setup. We have checked the spectrum analyzer and we have no interference and the power is very good. For DL we have a reasonable data rate of 50 Mbps. But for the UL we got 3 Mbps and the "MCS" is always very low. I will share the config and the trace of the gNB here as well. 
Note that we use Open5gs as our core.
We have tried n3 FDD as well and it is all the same. 
Thanks for your help.

Our gNB configuration:
```
gnb_id: 2240

slicing:low for the UL
 - sst: 1
   sd: 0
   
amf:
  addr: 10.43.39.166
  bind_addr: 10.16.0.50
Our gNB configuration:
ru_sdr:
  device_driver: uhd
  device_args:
  srate: 23.04
  otw_format: sc12
  tx_gain: 80
  rx_gain: 75

cell_cfg:
  dl_arfcn: 632628
  band: 78
  channel_bandwidth_MHz: 20
  common_scs: 30`
  plmn: "00102"
  tac: 1
  pci: 1
  nof_antennas_ul: 1
  nof_antennas_dl: 1
  pdsch:
    mcs_table: qam256
  pusch:
    mcs_table: qam256

log:
  filename: /tmp/gnb.log
  all_level: debug

pcap:
  mac_enable: false
  mac_filename: /tmp/gnb_mac.pcap
  ngap_enable: false
  ngap_filename: /tmp/gnb_ngap.pcap
```

Our gNB traces:
```
pci rnti  cqi  ri  mcs  brate   ok  nok  (%)  dl_bs | pusch  mcs  brate   ok  nok  (%)    bsr
   1 4602   15   1   26   765k  108    2   1%      0 |   1.4    0   437k  325    0   0%      0
   1 4602   15   1   26   215k   63    0   0%      0 |   2.9    1   228k  156    0   0%      0
   1 4602   15   1   26   6.4M  200    0   0%   331k |   2.5    1   176k  125    5   3%     53
   1 4602   15   1   27    61M 1398    2   0%   311k |   2.2    0   862k  591    0   0%  10.6k
   1 4602   15   1   27    60M 1394    4   0%   586k |   2.9    0   948k  559    3   0%      0
   1 4602   15   1   27    61M 1400    0   0%   462k |   2.8    1   567k  424    1   0%  1.04k
   1 4602   15   1   26    58M 1389   11   0%   215k |   1.5    0   628k  461    4   0%    299
   1 4602   15   1   27    61M 1399    1   0%   185k |   2.1    0   525k  419    0   0%    535
   1 4602   15   1   27    53M 1221    2   0%   184k |   2.9    1   632k  407   15   3%  1.04k
   1 4602   15   1   27    44M 1027    1   0%      0 |   6.0    3   445k  286    5   1%      0
   1 4602   15   1   26    12k   10    1   9%      0 |   2.3    0    52k   38    0   0%      0

           -----------------DL-----------------------|------------------UL--------------------
 pci rnti  cqi  ri  mcs  brate   ok  nok  (%)  dl_bs | pusch  mcs  brate   ok  nok  (%)    bsr
   1 4602   15   1   26    41k   26    0   0%      0 |   1.4    0    97k   70    0   0%      0
   1 4602   15   1   27   528k   62    0   0%      0 |   1.2    0   429k  305    0   0%   108k
   1 4602   15   1   26    99k   94    1   1%      0 |   0.6    0   849k  600    0   0%   300k
   1 4602   15   1   26   194k  152    1   0%      0 |   0.3    0   849k  600    0   0%   300k
   1 4602   15   1   26   165k  160    2   1%     58 |  -0.7    0   849k  600    0   0%   300k
   1 4602   15   1   26   155k  149    1   0%      0 |  -3.8    0   849k  600    0   0%   300k```
   1 4602   15   1   26    99k  101    0   0%     58 |  -4.8    0   849k  600    0   0%   300k
   1 4602   15   1   27   105k  104    0   0%      0 |  -3.1    0   849k  600    0   0%   300k
   1 4602   15   1   26   107k  106    1   0%      0 |  -0.5    0   908k  600    0   0%   300k
   1 4602   15   1   27   625k  158    1   0%     58 |   0.7    1   1.2M  600    0   0%   300k
   1 4602   15   1   26   184k  160    0   0%     58 |   0.7    1   1.5M  598    2   0%   300k

           -----------------DL-----------------------|------------------UL--------------------
 pci rnti  cqi  ri  mcs  brate   ok  nok  (%)  dl_bs | pusch  mcs  brate   ok  nok  (%)    bsr
   1 4602   15   1   26   278k  215    2   0%     58 |   1.0    2   2.2M  600    0   0%   300k
   1 4602   15   1   26   302k  269    1   0%     58 |   2.3    3   3.1M  576   24   4%   300k
   1 4602   15   1   26   177k  148    1   0%      0 |   1.7    1   1.4M  600    0   0%   300k
   1 4602   15   1   27   189k  155    0   0%     58 |   1.6    1   1.5M  600    0   0%   300k
   1 4602   15   1   26   207k  159    1   0%      0 |   0.9    1   1.8M  600    0   0%   300k
   1 4602   15   1   27   186k  143    1   0%      0 |   0.5    2   2.0M  600    0   0%   300k
   1 4602   15   1   27   240k  199    0   0%      0 |   0.5    3   2.9M  600    0   0%  17.8k
   1 4602   15   1   26   222k   84    1   1%      0 |   2.1    2   470k  220   44  16%  1.45k
   1 4602   15   1   26    30k   15    0   0%      0 |   3.4    2    52k   49    0   0%      0
   1 4602   15   1   27   205k   36    0   0%      0 |   1.3    0   152k  102    0   0%    745
   1 4602   15   1   26   133k   26    1   3%      0 |   2.0    1   114k   79    0   0%      0

```
