### DISCUSSION TITLE
Failed to start gNB when using SCS 15 kHz for N78 band

### DISCUSSION THREAD

**Discussion by HaoxinSEU** [srsran/srsRAN_Project#243] [General Help] [answered]
Hi community,

We are testing different bands and SCS with srsRAN. When using the band N78 and setting the SCS `common_scs` to be 30 kHz, we can successfully start the gNB, and UEs can connect to the network. However, when we change the SCS to 15kHz, the gNB failed to start and gave the error:
```
/opt/srsRAN_Project/lib/scheduler/config/serving_cell_config_factory.cpp:90: srsran::config_helpers::cell_config_builder_params_extended::cell_config_builder_params_extended(const srsran::cell_config_builder_params&): 
Assertion `ssb_arfcn.has_value()' failed - Unable to derive SSB location correctly.
```

We also test N41 band, and both 15 kHz and 30 kHz SCS allow us to start the gNB. So we don't know if 15 kHz SCS is not implemented for N78, or we made some mistakes in our gNB configuration file?

Below is our gNB configuration for N78, SCS=15kHz. Thanks for your help!

Best regards,
Haoxin

```
gnb_id: 2352

slicing:
 - sst: 1
   sd: 0

amf:
  addr: 10.43.130.192
  bind_addr: 10.16.0.56

ru_sdr:
  device_driver: uhd
  device_args:
  srate: 23.04
  otw_format: sc12
  tx_gain: -80
  rx_gain: 70

cell_cfg:
  dl_arfcn: 636660
  band: 78
  channel_bandwidth_MHz: 20
  common_scs: 15
  plmn: "00101"
  tac: 1
  pci: 1
  tdd_ul_dl_cfg:
    dl_ul_tx_period: 10
    nof_dl_slots: 6
    nof_ul_slots: 3
  nof_antennas_ul: 1
  nof_antennas_dl: 1
  pdsch:
    mcs_table: qam256
  pusch:
    mcs_table: qam64
    max_ue_mcs: 9
  pucch:
    sr_period_ms: 20

expert_phy:
  nof_ul_threads: 8
  nof_dl_threads: 2
  nof_pdsch_threads: 2
  pusch_dec_max_iterations: 2

log:
  filename: /tmp/gnb.log
  all_level: debug

pcap:
  mac_enable: false
  mac_filename: /tmp/gnb_mac.pcap
  ngap_enable: false
  ngap_filename: /tmp/gnb_ngap.pcap

```
