### DISCUSSION TITLE
Explicitly provide gNB IP address for E2 in gNB configuration

### DISCUSSION THREAD

**Discussion by HaoxinSEU** [srsran/srsRAN_Project#246] [Ideas & Suggestions]
Hi community,

We want to report one thing about the documentation for the E2 interface.

We hope to implement FlexRIC and srsRAN, so we follow all the instructions on the [documentation page](https://docs.srsran.com/projects/project/en/latest/tutorials/source/flexric/source/index.html#o-ran-nearrt-ric-and-xapp), and use the provided E2 configuration for gNB:
```
e2:
  enable_du_e2: true                # Enable DU E2 agent (one for each DU instance)
  e2sm_kpm_enabled: true            # Enable KPM service module
  addr: 10.16.0.77                   # RIC IP address
  port: 36421                       # RIC port
```
But we get the following errors when launching the gNB, and it cannot connect to FlexRIC.
```
Connecting to NearRT-RIC on 10.16.0.77:36421
Failed to connect SCTP socket to 10.16.0.77:36421. error="Connection refused" timeout=1ms
srsGNB ERROR: Failed to create SCTP gateway.
```
 
Finally we find that it's necessary to add the gNB IP address under the `e2` field, and after adding it, gNB can successfully connect to FlexRIC. So our gNB configuration looks like this now:
```
e2:
  enable_du_e2: true
  e2sm_kpm_enabled: true
  addr: 10.16.0.77
  bind_addr: 10.16.0.73
  port: 36421
```

I believe this is a common problem for SCTP bind when running the gNB and FlexRIC on different machines. And it's really confusing because in the documentation this `bind_addr` field is not mentioned. Thus, it would be nice if you can add this `bind_addr` field in the [RIC section of documentation](https://docs.srsran.com/projects/project/en/latest/tutorials/source/flexric/source/index.html#configuration).

Thanks.
