### DISCUSSION TITLE
10 MHz bandwidth

### DISCUSSION THREAD

**Discussion by improperaffo** [srsran/srsRAN_Project#286] [General Help] [answered]
Dear all,

my team and I are trying to transmit over a 10 MHz bandwidth. For that, we set `srate: 11.52`. When we run the code we get the following error:
```
/opt/srsRAN_Project/include/srsran/ran/phy_time_unit.h:105: constexpr srsran::phy_time_unit::value_type srsran::phy_time_unit::to_samples(U) const [with U = unsigned int; srsran::phy_time_unit::value_type = long int]: 
Assertion `is_sample_accurate(sampling_rate_Hz)' failed - Incompatible sampling rate 11.52 MHz with time 817408.
```
It seems that `(std::abs(value) * sampling_rate_Hz) % (SCS_REF_HZ * N_F_REF * KAPPA))` in `include/srsran/ran/phy_time_unit.h:89` is not zero. In fact we believe it to be 4789.5.

Similarly, when we want to run a 30 MHz bandwidth (using `srate: 34.56`), we get 
```
/opt/srsRAN_Project/include/srsran/ran/phy_time_unit.h:105: constexpr srsran::phy_time_unit::value_type srsran::phy_time_unit::to_samples(U) const [with U = unsigned int; srsran::phy_time_unit::value_type = long int]: 
Assertion `is_sample_accurate(sampling_rate_Hz)' failed - Incompatible sampling rate 34.56 MHz with time 817408.
```

What else should we set in our configuration to fix this problem?
Thank you

**Comment by yagoda** [comment]
Hi,

Can you share the config you using?

Thanks,
Justin

**Reply by improperaffo** [reply]
```
gnb_id: 107

slicing:
 - sst: 1
   sd: 0
   
amf:
  addr: 10.43.206.196
  bind_addr: 10.16.0.182

ru_sdr:
  device_driver: uhd
  device_args:
  # clock:
  # sync:
  srate: 11.52
  otw_format: sc12
  tx_gain: 80
  rx_gain: 50

cell_cfg:
  dl_arfcn: 632628
  band: 78
  channel_bandwidth_MHz: 10
  common_scs: 30
  plmn: "00102"
  tac: 1
  pci: 1
  tdd_ul_dl_cfg:
    dl_ul_tx_period: 4
    nof_dl_slots: 2
    nof_dl_symbols: 7
    nof_ul_slots: 1
    nof_ul_symbols: 6
  nof_antennas_ul: 1
  nof_antennas_dl: 1
  pdsch:
    mcs_table: qam256
  pusch:
    mcs_table: qam256
  pucch:
    sr_period_ms: 4

e2:
  enable_du_e2: false
  e2sm_kpm_enabled: true
  addr: 10.43.183.80
  bind_addr: 10.16.0.182
  port: 36421

log:
  filename: /tmp/gnb.log
  all_level: info

pcap:
  mac_enable: false
  mac_filename: /tmp/gnb_mac.pcap
  ngap_enable: false
  ngap_filename: /tmp/gnb_ngap.pcap
```
