### DISCUSSION TITLE
UE cannot see the 5G SA network

### DISCUSSION THREAD

**Discussion by alvaroalfaro612** [srsran/srsRAN_Project#31] [General Help]
Hello,

I am trying to create a network with srsRAN project and Open5Gs. The connection between both seems to be working looking at the Open5Gs logs: 
```
03/14 16:21:38.801: [amf] INFO: gNB-N2 accepted[127.0.0.1] in master_sm module (../src/amf/amf-sm.c:668)
03/14 16:21:38.801: [amf] INFO: [Added] Number of gNBs is now 1 (../src/amf/context.c:973)
03/14 16:21:38.801: [amf] INFO: gNB-N2[127.0.0.1] max_num_of_ostreams : 30 (../src/amf/amf-sm.c:707)
```
But the UE (Xiami Redmi Note 5G) is not able to see the network when looking manually for it.

I have the same problem with srsRAN 5G SA, while srsRAN 4G network is working fine.

I have already tried all of the recommendation of this [app note](https://docs.srsran.com/projects/4g/en/next/app_notes/source/5g_sa_COTS/source/index.html) :

- Tried with different and even commercial PLMN for the SIM.
- Forcing 5G connection with NSG android app.
- Run the **deactivate-5g.script** for USIM configuration.

Anyone knows what can be happening?

Thanks in advance!

**Comment by gustavobsch** [comment]
Are you using a GPSDO on your SDR? you should read notes in #10

**Reply by alvaroalfaro612** [reply]
Today I am going to try again with an external clock. I will check also the information you provide in the link, thanks!

**Comment by alvaroalfaro612** [comment]
After  trying with a GPSDO, I am still not able to see the network.

Depending of the band configuration I see one or two **Late, underflow, overflow** messages.

Also, after checking my UE here [Xiaomi Redmi Note 10 5G](https://cacombos.com/device/M2103K19G), it seems that it is only to use SA at bands 28 and 41, so I am using these bands. Also tried with Poco F3 and also it is not seeing the network.

I don´t really know what should I try now...

**Comment by gustavobsch** [comment]
You might need to enable debugging and provide some logs

**Comment by alvaroalfaro612** [comment]
This is the YAML file for gnb configuration:

```
amf:
  addr: 127.0.0.5                 # The address or hostname of the AMF.
  bind_addr: 127.0.0.1              # A local IP that the gNB binds to for traffic from the AMF.

rf_driver:
  device_driver: uhd                # The RF driver name.
  device_args: type=b200,clock=external            # Optionally pass arguments to the selected RF driver.
  clock:                            # Specify the clock source used by the RF.
  sync:                             # Specify the sync source used by the RF.
  srate: 30.72                    # RF sample rate might need to be adjusted according to selected bandwidth.
  tx_gain: 50                       # Transmit gain of the RF might need to adjusted to the given situation.
  rx_gain: 60                       # Receive gain of the RF might need to adjusted to the given situation.

cell_cfg:
  dl_arfcn: 537999                 # ARFCN of the downlink carrier (center frequency).
  band: 41                          # The NR band.
  channel_bandwidth_MHz: 30         # Bandwith in MHz. Number of PRBs will be automatically derived.
  common_scs: 15                    # Subcarrier spacing in kHz used for data.
  plmn: "00102"                     # PLMN broadcasted by the gNB.
  tac: 7                            # Tracking area code (needs to match the core configuration).
  pci: 1                            # Physical cell ID.
      
log:
  filename: ./tmp/gnb.log            # Path of the log file.
  all_level: warning                # Logging level applied to all layers.

pcap:
  mac_enable: false                 # Set to true to enable MAC-layer PCAPs.
  mac_filename: /tmp/gnb_mac.pcap   # Path where the MAC PCAP is stored.
  ngap_enable: false                # Set to true to enable NGAP PCAPs.
  ngap_filename: /tmp/gnb_ngap.pcap # Path where the NGAP PCAP is stored.

```
**Logs from the Open5Gs:**
> 03/15 15:42:44.183: [amf] INFO: gNB-N2 accepted[127.0.0.1]:48263 in ng-path module (../src/amf/ngap-sctp.c:113)
> 03/15 15:42:44.183: [amf] INFO: gNB-N2 accepted[127.0.0.1] in master_sm module (../src/amf/amf-sm.c:668)
> 03/15 15:42:44.183: [amf] INFO: [Added] Number of gNBs is now 1 (../src/amf/context.c:973)
> 03/15 15:42:44.183: [amf] INFO: gNB-N2[127.0.0.1] max_num_of_ostreams : 30 (../src/amf/amf-sm.c:707)

Logs from srsRAN:

> 2023-03-15T14:49:46.296275 [RF      ] [W] Radio realtime event: Type=start-of-burst Source=tx Timestamp=70170411
> 2023-03-15T14:50:43.940790 [RF      ] [W] Radio realtime event: Type=end-of-burst Source=tx Timestamp=na
> 2023-03-15T14:50:43.941427 [ALL     ] [E] Cannot push anymore tasks into the radio worker queue. maximum size is 2048

**Stdout from srsRAN:**

> Available radio types: uhd.
> 
> --== srsRAN gNB (commit 0523be699) ==--
> 
> [INFO] [UHD] linux; GNU C++ version 9.4.0; Boost_107100; UHD_4.4.0.HEAD-0-g5fac246b
> Making USRP object with args 'type=b200,clock=external'
> Cell pci=1, bw=30 MHz, dl_arfcn=537999 (n41), dl_freq=2689.995 MHz, dl_ssb_arfcn=536910, ul_freq=2689.995 MHz
> 
> ==== gNodeB started ===
> Type <t> to view trace

Everything seems to be working but I cannot see the network.
