### DISCUSSION TITLE
100MHz 2x2 OFH RAN650 - max throughput

### DISCUSSION THREAD

**Discussion by mateuszmichalskiacc** [srsran/srsRAN_Project#325] [General Help]
Hello everyone,

I'm trying to reach max DL tput with Benetel RAN650 RU in 2x2 configuration, using Amarisoft UE
Unfortunately, what I'm observing is that, when there is full BW transmission (100MHz 30kHz, all PRBs), the DL BLER increases and reaching max MCS and tput is not possible (avg. MCS 24.7). The smaller grants (less PRBs, allows to reach avg. MCS >25).

We have observed similar issue with N310 as a RU, but that was possible to fix with higher number of DL PHY threads and max_proc_delay, however this time I can't fix this.
Any idea how I can improve my config, or maybe is it known issue?

```
amf:
  addr: 10.0.128.51                                             # The address or hostname of the AMF.
  bind_addr: 10.0.128.50                                            # A local IP that the gNB binds to for traffic from the AMF.

ru_ofh:
  ru_bandwidth_MHz: 100                                           # RU instantaneous bandwidth.
  t1a_max_cp_dl: 392                                              # Maximum T1a on Control-Plane for Downlink in microseconds.
  t1a_min_cp_dl: 258                                              # Minimum T1a on Control-Plane for Downlink in microseconds.
  t1a_max_cp_ul: 300                                              # Maximum T1a on Control-Plane for Uplink in microseconds.
  t1a_min_cp_ul: 285                                              # Minimum T1a on Control-Plane for Uplink in microseconds.
  t1a_max_up: 300                                                 # Maximum T1a on User-Plane in microseconds.
  t1a_min_up: 155
  is_prach_cp_enabled: 0                                      # Configures if Control-Plane messages should be used to receive PRACH messages.
  compr_method_ul: bfp                                            # Uplink compression method.
  compr_bitwidth_ul: 9                                            # Uplink IQ samples bitwidth after compression.
  compr_method_dl: bfp                                            # Downlink compression method.
  compr_bitwidth_dl: 9                                            # Downlink IQ samples bitwidth after compression.
  compr_method_prach: bfp                                         # PRACH compression method.
  compr_bitwidth_prach: 9                                        # PRACH IQ samples bitwidth after compression.
  enable_ul_static_compr_hdr: true                                # Configures if the compression header is present for uplink User-Plane messages (false) or not present (true).
  enable_dl_static_compr_hdr: true                                # Configures if the compression header is present for downlink User-Plane messages (false) or not present (true).
  iq_scaling: 5.5                                                # IQ samples scaling factor applied before compression, should be a positive value smaller than 10.
  cells:
    - network_interface: enp1s0f3                                 # Ethernet interface name used to communicate with the RU.
      ru_mac_addr: xxxxxxxxxxxxxxx                              # RU MAC address.
      du_mac_addr: xxxxxxxxxxxxxxxx                             # DU MAC address.
      vlan_tag: 5                                                 # VLAN tag value.
      prach_port_id: [4]                                          # PRACH eAxC port value.
      dl_port_id: [0, 1]                                          # Downlink eAxC port values.
      ul_port_id: [0]                                          # Uplink eAxC port values.

cell_cfg:
  dl_arfcn: 650112                                                # 20mhz cell on 100mhz benetel center-freq = 3751.68
  band: 77                                                        # The NR band.
  channel_bandwidth_MHz: 100                                      # Bandwith in MHz. Number of PRBs will be automatically derived.
  common_scs: 30                                                  # Subcarrier spacing in kHz used for data.
  plmn: "00101"                                                   # PLMN broadcasted by the gNB.
  tac: 1                                                          # Tracking area code (needs to match the core configuration).
  pci: 91                                                          # Physical cell ID.
  nof_antennas_dl: 2                                              # Downlink number of antennas.
  nof_antennas_ul: 1                                              # Uplink number of anntennas.
  prach:
    prach_config_index: 7                                         # PRACH configuration index.
    prach_root_sequence_index: 1
    zero_correlation_zone: 0
    prach_frequency_start: 0

  pdsch:
    mcs_table: qam256
    olla_target_bler: 0.05
    olla_max_cqi_offset: 2
    max_rb_size: 275
    max_pdschs_per_slot: 6
    max_alloc_attempts: 6


  tdd_ul_dl_cfg:
    dl_ul_tx_period: 10                     # Optional INT (10). Sets the TDD pattern periodicity in slots. The combination of this value and the chosen numerology must lead to a TDD periodicity of 0.5, 0.625, 1, 1.25, 2, 2.5, 3, 4, 5 or 10 milliseconds. Supported: [2 - 80].
    nof_dl_slots: 7                         # Optional INT (6). Number of consecutive full Downlink slots. Supported: [0-80].
    nof_dl_symbols: 6                       # Optional INT (0). Number of Downlink symbols at the beginning of the slot following full Downlink slots. Supported: [0-13].
    nof_ul_slots: 2                         # Optional INT (3). Number of consecutive full Uplink slots. Supported: [0 - 80].
    nof_ul_symbols: 4                       # Optional INT (0). Number of Uplink symbols at the end of the slot preceding the first full Uplink slot. Supported: [0-13].


expert_phy:
  max_proc_delay: 6

expert_execution:
  threads:
    upper_phy:
      nof_pdsch_threads: 4
        # nof_pusch_threads: 2
      nof_dl_threads: 2
      nof_ul_threads: 2
    ofh:
      enable_dl_parallelization: 1

  affinities:
      l1_dl_cpus: 31,30,29,28                             # Optional TEXT. Sets the number of CPU cores assigned to L1 downlink tasks. Supported: [1 - Number of available cores].
      l1_ul_cpus: 25,9                                # Optional TEXT. Sets the number of CPU cores assigned to L1 uplink tasks. Supported: [1 - Number of available cores].
      l2_cell_cpus: 24,8                              # Optional TEXT. Sets the number of CPU cores assigned to L2 cells tasks. Supported: [1 - Number of available cores].
      low_priority_cpus: 23,7                         # Optional TEXT. Sets the number of CPU cores assigned to low priority tasks. Supported: [1 - Number of available cores].
      l1_dl_pinning: mask                            # Optional TEXT. Sets the policy used for assigning CPU cores to L1 downlink tasks.
      l1_ul_pinning: mask                         # Optional TEXT. Sets the policy used for assigning CPU cores to L1 uplink tasks.
      l2_cell_pinning: mask                         # Optional TEXT. Sets the policy used for assigning CPU cores to L2 cell tasks.
      low_priority_pinning: mask                      # Optional TEXT. Sets the policy used for assigning CPU cores to low priority tasks.

log:
  filename: /run/gnb.log                                          # Path of the log file.
  all_level: info                                              # Logging level applied to all layers.
    #ofh_level: debug
    #broadcast_enabled: true
    #mac_level: debug
    #phy_level: debug

    #lib_level : debug
    #phy_level : debug
pcap:
  #mac_enable: false                                               # Set to true to enable MAC-layer PCAPs.
  #mac_filename: /tmp/gnb_mac.pcap                                 # Path where the MAC PCAP is stored.
  #ngap_enable: false                                              # Set to true to enable NGAP PCAPs.
  #ngap_filename: /tmp/gnb_ngap.pcap                               # Path where the NGAP PCAP is stored
```
