### DISCUSSION TITLE
E1 and F1 interfaces configuration on srsRAN or the code where E1 and F1 generates the messages.

### DISCUSSION THREAD

**Discussion by rajindersin** [srsran/srsRAN_Project#340] [General Help]
How to find the E1 and F1 interfaces configuration on srsRAN or the code where E1 and F1 generates the messages.

Thanks

**Comment by pgawlowicz** [comment]
Hi,
E1 code is here: https://github.com/srsran/srsRAN_Project/tree/main/lib/e1ap
F1 code is here:  https://github.com/srsran/srsRAN_Project/tree/main/lib/f1ap and https://github.com/srsran/srsRAN_Project/tree/main/lib/f1u

You can analyze the messages in Wireshark see here: https://docs.srsran.com/projects/project/en/latest/user_manuals/source/outputs.html

The pcap files needs the following configuration section to be in place:
```
pcap: 
  e1ap_filename: /tmp/gnb_e1ap.pcap     # Optional TEXT (/tmp/gnb_e1ap.pcap). Path for E1AP PCAPs. 
  e1ap_enable: true                    # Optional BOOL (false). Enable/disable E1AP packet capture.
  f1ap_filename: /tmp/gnb_f1ap.pcap     # Optional TEXT (/tmp/gnb_f1ap.pcap). Path for F1AP PCAPs. 
  f1ap_enable: true                    # Optional BOOL (false). Enable/disable F1AP packet capture.
```
