### DISCUSSION TITLE
srsRAN23.10+srsUE23.11+zmq fails to work under 20MHz

### DISCUSSION THREAD

**Discussion by Zplusless** [srsran/srsRAN_Project#350] [General Help]
Dear all,
We have noticed that the srsRAN gNB + srsUE tutorial has add support for 20MHz ("Limited to 5, 10, 15 or 20 MHz Bandwidth (BW)" in [srsRAN gNB with srsUE — srsRAN Project documentation](https://docs.srsran.com/projects/project/en/latest/tutorials/source/srsUE/source/index.html)) after the release of srsUE23.11. 

We are trying to achieve higher throughput by adopt higher bandwidth. We start by modifying config files that work well under 10MHz. However, it fails to work when we change the `channel_bandwidth_MHz` to 20. We also change the srate and the base_srate of device_args to 23.04e6. `CRC failed` is witnessed in the ue.log.

```
2023-12-04T04:04:03.302181 [PHY1-NR] [W] [  180] PBCH-MIB: CRC failed
2023-12-04T04:04:03.312800 [PHY1-NR] [W] [  190] PBCH-MIB: CRC failed
2023-12-04T04:04:03.323418 [PHY1-NR] [W] [  200] PBCH-MIB: CRC failed
```

The configs and logs are as follows:
[gnb.log.txt](https://github.com/srsran/srsRAN_Project/files/13541887/gnb.log.txt)
[gnb_zmq.yaml.txt](https://github.com/srsran/srsRAN_Project/files/13541888/gnb_zmq.yaml.txt)
[ue.log.txt](https://github.com/srsran/srsRAN_Project/files/13541889/ue.log.txt)
[ue_zmq.conf.txt](https://github.com/srsran/srsRAN_Project/files/13541890/ue_zmq.conf.txt)

**Comment by pgawlowicz** [comment]
Hi, Could you add the following in your UE config and provide your feedback:
```
[rat.nr]
bands = 3
nof_carriers = 1
max_nof_prb = 106
nof_prb = 106
```
We will update the tutorial.

**Reply by Zplusless** [reply]
After adding the above to the UE config, it no longer gets stuck at `Attaching UE...` BUT comes several lines of `Random Access Transmission`:
```
Built in Release mode using commit eea87b1d8 on branch master.

Opening 1 channels in RF device=zmq with args=tx_port=tcp://127.0.0.1:2001,rx_port=tcp://127.0.0.1:20
Supported RF device list: UHD zmq file
CHx base_srate=23.04e6
Current sample rate is 1.92 MHz with a base rate of 23.04 MHz (x12 decimation)
CH0 rx_port=tcp://127.0.0.1:2000
CH0 tx_port=tcp://127.0.0.1:2001
Current sample rate is 23.04 MHz with a base rate of 23.04 MHz (x1 decimation)
Current sample rate is 23.04 MHz with a base rate of 23.04 MHz (x1 decimation)
Waiting PHY to initialize ... done!
Attaching UE...
Random Access Transmission: prach_occasion=0, preamble_index=0, ra-rnti=0xf, tti=971
Random Access Transmission: prach_occasion=0, preamble_index=0, ra-rnti=0xf, tti=1001
Random Access Transmission: prach_occasion=0, preamble_index=0, ra-rnti=0xf, tti=1031
Random Access Transmission: prach_occasion=0, preamble_index=0, ra-rnti=0xf, tti=1061
Random Access Transmission: prach_occasion=0, preamble_index=0, ra-rnti=0xf, tti=1091
Random Access Transmission: prach_occasion=0, preamble_index=0, ra-rnti=0xf, tti=1121
Random Access Transmission: prach_occasion=0, preamble_index=0, ra-rnti=0xf, tti=1151
```
[gnb.log.txt](https://github.com/srsran/srsRAN_Project/files/13545870/gnb.log.txt)
[gnb_zmq.yaml.txt](https://github.com/srsran/srsRAN_Project/files/13545871/gnb_zmq.yaml.txt)
[ue.log.txt](https://github.com/srsran/srsRAN_Project/files/13545872/ue.log.txt)
[ue_zmq.conf.txt](https://github.com/srsran/srsRAN_Project/files/13545873/ue_zmq.conf.txt)

**Reply by pgawlowicz** [reply]
ah, forgot about the gnb config change, Please try this:

```

cell_cfg:
  dl_arfcn: 368500                  # ARFCN of the downlink carrier (center frequency).
  band: 3                           # The NR band.
  channel_bandwidth_MHz: 20         # Bandwith in MHz. Number of PRBs will be automatically derived.
  common_scs: 15                    # Subcarrier spacing in kHz used for data.
  plmn: "00101"                     # PLMN broadcasted by the gNB.
  tac: 7                            # Tracking area code (needs to match the core configuration).
  pdcch:
    common:
      ss0_index: 0                  # Set search space zero index to match srsUE capabilities
      coreset0_index: 12            # Set search CORESET Zero index to match srsUE capabilities
    dedicated:
      ss2_type: common              # Search Space type, has to be set to common
      dci_format_0_1_and_1_1: false # Set correct DCI format (fallback)
  prach:
    prach_config_index: 1           # Sets PRACH config to match what is expected by srsUE
```
