### DISCUSSION TITLE
ZMQ Based gNB Performace Issue

### DISCUSSION THREAD

**Discussion by hpacherkar** [srsran/srsRAN_Project#361] [General Help]
I am trying to test zmq based communication to get better DL speed ( before it was 0.06 mbps, tested with B210 and Pixel 6)
I am trying some performance options for the configuration also ran the performance script. 
As seen in the screenshot below the gnb is kind of stuck and logs also stopped printing.  When UE is started it does goes out of sync "PBCH-MIB: CRC failed"
![image](https://github.com/srsran/srsRAN_Project/assets/54899971/92527988-a09b-457f-8d7d-1007c27bc710)
I have tried alot of config options, after a lot of config errors this is what i have in the attached config file.
[gnb_zmq.zip](https://github.com/srsran/srsRAN_Project/files/13595993/gnb_zmq.zip)
Any help with the config would be appreciated, I aim to get max DL UL speed with ZMQ based connection and then use that as base to replicate the same with b210 and pixel 6.

**Comment by herlesupreeth** [comment]
For now I would suggest to remove the following configuration from your gNB config file and give it a try. You should be able to get atleast 35mbps (thats what is the maximum I got over 10 Mhz). Band 3 is a FDD band so setting TDD configuration does not make sense

```
  tdd_ul_dl_cfg: 
    dl_ul_tx_period: 10                     # Optional INT (10). Sets the TDD pattern periodicity in slots. The combination of this value and the chosen numerology must lead to a TDD periodicity of 0.5, 0.625, 1, 1.25, 2, 2.5, 3, 4, 5 or 10 milliseconds. Supported: [2 - 80].
    nof_dl_slots: 6                         # Optional INT (6). Number of consecutive full Downlink slots. Supported: [0-80].
    nof_dl_symbols: 8                       # Optional INT (8). Number of Downlink symbols at the beginning of the slot following full Downlink slots. Supported: [0-13].
    nof_ul_slots: 3                         # Optional INT (3). Number of consecutive full Uplink slots. Supported: [0 - 80].
    nof_ul_symbols: 0                       # Optional INT (0). Number of Uplink symbols at the end of the slot preceding the first full Uplink slot. Supported: [0-13].
    pattern2: 
      dl_ul_tx_period: 10                       # Optional INT (10). Sets the TDD pattern periodicity in slots. The combination of this value and the chosen numerology must lead to a TDD periodicity of 0.5, 0.625, 1, 1.25, 2, 2.5, 3, 4, 5 or 10 milliseconds. Supported: [2 - 80].
      nof_dl_slots: 6                           # Optional INT (6). Number of consecutive full Downlink slots. Supported: [0-80].
      nof_dl_symbols: 8
      nof_ul_slots: 3
      nof_ul_symbols: 0

expert_phy: 
  max_proc_delay: 2
  pusch_dec_max_iterations: 6
  pusch_dec_enable_early_stop: true

expert_execution:
  threads:
    upper_phy:
      pdsch_processor_type: auto
      nof_pdsch_threads: 4
      # nof_pusch_threads: 2
      nof_ul_threads: 2
      nof_dl_threads: 2
    ofh:
      enable_dl_parallelization: 1
```

Also, I would suggest do the changes mentioned in this comment for CORESET#0 index and corresponding changes in srsUE config file - https://github.com/srsran/srsRAN_Project/discussions/298#discussioncomment-7774564

**Reply by hpacherkar** [reply]
srsUe was able to connect with this 
![image](https://github.com/srsran/srsRAN_Project/assets/54899971/1bf1d8a7-207e-47fc-8383-74b158eec8ca)

But the DL is still nearly 0
![image](https://github.com/srsran/srsRAN_Project/assets/54899971/c113669b-1a69-4db2-bb9d-d37d42e94480)

**Reply by herlesupreeth** [reply]
Please set as following in UE config file and give it a try

```
[rf]
freq_offset = 0
tx_gain = 80
#rx_gain = 40
srate = 23.04e6

[rat.nr]
bands = 3
nof_carriers = 1
dl_nr_arfcn = 368500
ssb_nr_arfcn = 367930
max_nof_prb = 106
nof_prb = 106
```

**Reply by hpacherkar** [reply]
No change, same speed consistently 
![image](https://github.com/srsran/srsRAN_Project/assets/54899971/ab086d8a-14b1-4a7f-b40a-535512b9e503)

**Reply by hpacherkar** [reply]
FYI i am using srsue release version 23-11 and srsgnb release version 23-10. Also I have checked the network speed using UERANSIM to make sure core network or the UPF is not at fault.

**Reply by herlesupreeth** [reply]
First, I would recommend using iperf rather than speedtest-cli to measure the throughput since you never know whether the server it picks is good or not and also have to go via internet

Second, changing the UE configuration file and gNB configuration file as follows should get you more DL throughput. Btw, I tested it at my end using ZMQ and 20 Mhz BW and I was able to get 75 mbps UL throughput using UDP iperf

In UE configuration file

```
[rf]
freq_offset = 0
tx_gain = 80
#rx_gain = 40
srate = 23.04e6

# Example for ZMQ-based operation with TCP transport for I/Q samples
device_name = zmq
device_args = tx_port=tcp://SRS_UE_IP:2001,rx_port=tcp://SRS_GNB_IP:2000,id=ue,base_srate=23.04e6

[rat.nr]
bands = 3
nof_carriers = 1
dl_nr_arfcn = 368500
ssb_nr_arfcn = 368410
max_nof_prb = 106
nof_prb = 106
```

In gNB configuration file

```
ru_sdr:
  device_driver: zmq                                                                          # The RF driver name.
  device_args: tx_port=tcp://SRS_GNB_IP:2000,rx_port=tcp://SRS_UE_IP:2001,base_srate=23.04e6  # Optionally pass arguments to the selected RF driver.
  srate: 23.04                                                                                # RF sample rate might need to be adjusted according to selected bandwidth.
  tx_gain: 75                                                                                 # Transmit gain of the RF might need to adjusted to the given situation.
  rx_gain: 75                                                                                 # Receive gain of the RF might need to adjusted to the given situation.

cell_cfg:
  dl_arfcn: 368500                                                                            # ARFCN of the downlink carrier (center frequency).
  band: 3                                                                                     # The NR band.
  channel_bandwidth_MHz: 20                                                                   # Bandwith in MHz. Number of PRBs will be automatically derived.
  common_scs: 15                                                                              # Subcarrier spacing in kHz used for data.
  plmn: "PLMN"                                                                                # PLMN broadcasted by the gNB.
  tac: 1                                                                                      # Tracking area code (needs to match the core configuration).
  pci: 1                                                                                      # Physical cell ID.
  pdcch:
    dedicated:
      ss2_type: common                                                                        # Search Space type, has to be set to common
      dci_format_0_1_and_1_1: false                                                           # Set correct DCI format (fallback)
    common:
      ss0_index: 0
      coreset0_index: 13
  prach:
    prach_config_index: 1
```
