### DISCUSSION TITLE
tdd_ul_dl_cfg field default configuration

### DISCUSSION THREAD

**Discussion by fllay** [srsran/srsRAN_Project#397] [General Help] [answered]
Hi
I am using a configuration in the following
```
amf:
  addr: 192.168.68.125                                                # The address or hostname of the AMF.
  bind_addr: 192.168.68.125                                            # A local IP that the gNB binds to for traffic from the AMF.

ru_sdr:
  device_driver: uhd                                            # The RF driver name.
  device_args: type=b200,num_recv_frames=64,num_send_frames=64  # Optionally pass arguments to the selected RF driver.
  clock: internal                                                       # Specify the clock source used by the RF.
  sync: internal                                                        # Specify the sync source used by the RF.
  srate: 23.04                                                  # RF sample rate might need to be adjusted according to selected bandwidth.
  otw_format: sc12
  tx_gain: 79                                                  # Transmit gain of the RF might need to adjusted to the given situation.
  rx_gain: 60                                                   # Receive gain of the RF might need to adjusted to the given situation.

cell_cfg:
  dl_arfcn: 632628                                                # ARFCN of the downlink carrier (center frequency).
  band: 78                                                        # The NR band.
  channel_bandwidth_MHz: 20                                       # Bandwith in MHz. Number of PRBs will be automatically derived.
  common_scs: 30                                                  # Subcarrier spacing in kHz used for data.
  plmn: "00101"                                                   # PLMN broadcasted by the gNB.
  tac: 7                                                          # Tracking area code (needs to match the core configuration).
  pci: 1                                                          # Physical cell ID.
  nof_antennas_dl: 2
  nof_antennas_ul: 2
  ssb:
    ssb_period: 10
  pdsch:
    mcs_table: qam256
log:
  filename: /tmp/gnb.log                                          # Path of the log file.
  all_level:  warning                                               # Logging level applied to all layers.
  #phy_rx_symbols_filename: /tmp/iq.log

pcap:
  mac_enable: false                                               # Set to true to enable MAC-layer PCAPs.
  mac_filename: /tmp/gnb_mac.pcap                                 # Path where the MAC PCAP is stored.
  ngap_enable: false                                              # Set to true to enable NGAP PCAPs.
  ngap_filename: /tmp/gnb_ngap.pcap                               # Path where the NGAP PCAP is stored.
```

I did not specify `tdd_ul_dl_cfg` section. What is the default value of this section?

**Comment by herlesupreeth** [comment, marked as answer]
Default configuration of TDD pattern is 6D1S3U

6 Downlink slots
1 Flexible slot with 8 DL symbols
3 Uplink slots

**Reply by fllay** [reply]
Please help me to understand TDD pattern.  In the configuration file, I use sub-carrier spacing 30kkz (u = 1). To use   6D1S3U TDD pattern, the value of `dl_ul_tx_period: ` should be 5, right?  I look at the document and see this value 

```
 tdd_ul_dl_cfg: 
    dl_ul_tx_period: 10                     # Optional INT (10). Sets the TDD pattern periodicity in slots. The combination of this value and the chosen numerology must lead to a TDD periodicity of 0.5, 0.625, 1, 1.25, 2, 2.5, 3, 4, 5 or 10 milliseconds. Supported: [2 - 80].
    nof_dl_slots: 6                         # Optional INT (6). Number of consecutive full Downlink slots. Supported: [0-80].
    nof_dl_symbols: 8                       # Optional INT (8). Number of Downlink symbols at the beginning of the slot following full Downlink slots. Supported: [0-13].
    nof_ul_slots: 3                         # Optional INT (3). Number of consecutive full Uplink slots. Supported: [0 - 80].
    nof_ul_symbols: 0                       # Optional INT (0). Number of Uplink symbols at the end of the slot preceding the first full Uplink slot. Supported: [0-13].
    pattern2: 
      dl_ul_tx_period: 10                       # Optional INT (10). Sets the TDD pattern periodicity in slots. The combination of this value and the chosen numerology must lead to a TDD periodicity of 0.5, 0.625, 1, 1.25, 2, 2.5, 3, 4, 5 or 10 milliseconds. Supported: [2 - 80].
      nof_dl_slots: 6                           # Optional INT (6). Number of consecutive full Downlink slots. Supported: [0-80].
      nof_dl_symbols: 8                         # Optional INT (8). Number of Downlink symbols at the beginning of the slot following full Downlink slots. Supported: [0-13]
      nof_ul_slots: 3                           # Optional INT (3). Number of consecutive full Uplink slots. Supported: [0 - 80].
      nof_ul_symbols: 0                         # Optional INT (0). Number of Uplink symbols at the end of the slot preceding the first full Uplink slot. Supported: [0-13].
```

and `scs` value of 
```
cell_cfg: 
  pci: 1                                # Required UINT (1). Sets the Physical Cell ID. Supported: [0-1007].
  dl_arfcn: 536020                      # Required UINT (536020). Sets the Downlink ARFCN.
  band: auto                            # Optional TEXT (auto). Sets the NR band being used for the cell. If not specified, will be set automatically based on ARFCN. Supported: all release 17 bands.
  common_scs: 15                        # Required UINT (15). Sets the subcarrier spacing in KHz to be used by the cell. Supported: [15, 30].
```
So the  6D1S3U is valid. However, if I set `common_scs: 30 `  to 30kHz, what will the default value of TDD pattern since I think that 6D1S3U will be invalid due to 20 available slots for  `common_scs: 30` and `dl_ul_tx_period: 10 `. Or if I did not specify  `tdd_ul_dl_cfg` section, it will be adjust `dl_ul_tx_period:` so that the number of available slots is always 10?
