### DISCUSSION TITLE
Need to understand TDD pattern configuration in general

### DISCUSSION THREAD

**Discussion by wei-lou** [srsran/srsRAN_Project#400] [General Help] [answered]
I want to configure TDD radio frame pattern in DDDSUDDDSU format and Special slot format as 10:2:2. Here is my configuration for tdd_ul_dl_cfg.  

```
  tdd_ul_dl_cfg:
    dl_ul_tx_period: 5                   
    nof_dl_slots: 3                        
    nof_dl_symbols: 10                
    nof_ul_slots: 1                        
    nof_ul_symbols: 2                      
``` 
From the gnb log from SIB1 message, I do see correct configuration there

```
    "tdd-UL-DL-ConfigurationCommon": {
      "referenceSubcarrierSpacing": "kHz30",
      "pattern1": {
        "dl-UL-TransmissionPeriodicity": "ms2p5",
        "nrofDownlinkSlots": 3,
        "nrofDownlinkSymbols": 10,
        "nrofUplinkSlots": 1,
        "nrofUplinkSymbols": 2
      }
``` 
But the gnb program just aborted due to error as such.
```
--== srsRAN gNB (commit 55c984b55) ==--

Connecting to AMF on 192.168.70.210:38412
Initializing Open Fronthaul Interface sector=0: ul_comp=[BFP,9], dl_comp=[BFP,9], prach_comp=[BFP,9] prach_cp_enabled=true, downlink_broadcast=false.
Warning: Configured PRACH occasion collides with PUCCH RBs ([0..1) intersects [0..12)). Some interference between PUCCH and PRACH is expected.
Warning: Configured PRACH occasion collides with PUCCH RBs ([0..1) intersects [0..12)). Some interference between PUCCH and PRACH is expected.
Cell pci=78, bw=40 MHz, dl_arfcn=643464 (n78), dl_freq=3651.96 MHz, dl_ssb_arfcn=642432, ul_freq=3651.96 MHz

==== gNodeB started ===
Type <t> to view trace
/home/labuser/srsRAN_Project/lib/ofh/receiver/../support/prach_context_repository.h:118: void srsran::ofh::prach_context::write_iq(unsigned int, unsigned int, unsigned int, srsran::span<const std::complex<float> >):
Assertion `symbol < nof_symbols' failed - Invalid symbol index.
Aborted
``` 
So why is this error and what should be the correct configuration for my application?

Thanks,
