### DISCUSSION TITLE
Throughput gap between different TDD periods

### DISCUSSION THREAD

**Discussion by HaoxinSEU** [srsran/srsRAN_Project#404] [General Help] [answered]
Hello,

When using different TDD periods, it seems that the maximum throughput is different.

For example, we are using USRP with 20 MHz BW, when setting the period as 10 slots:
```
  tdd_ul_dl_cfg: 
    dl_ul_tx_period: 10                   
    nof_dl_slots: 6                        
    nof_dl_symbols: 6               
    nof_ul_slots: 3                       
    nof_ul_symbols: 6                   
```
The throughput for DL and UL is 57.7 Mbps and 17.9 Mbps respectively.

When setting the period as 4 slots:
```
  tdd_ul_dl_cfg: 
    dl_ul_tx_period: 4                   
    nof_dl_slots: 2                       
    nof_dl_symbols: 6               
    nof_ul_slots: 1                       
    nof_ul_symbols: 6 
```
The throughput for DL and UL is 52.7 and 14.7 Mbps.

There are more UL symbols in the period now, but the UL throughput decreases. In theory the control overhead should not change. So we are wondering if this difference is normal and what could be the reason?

Any insight will be much appreciated!
