### DISCUSSION TITLE
Start mac layer srsRAN without attach UE.

### DISCUSSION THREAD

**Discussion by muril666** [srsran/srsRAN_Project#446] [General Help] [answered]
Is it possible start gNb for generate Downlink traffic (for example) without attach procedure to UE. Can i config gNb use strongly one type of msc and allocate rb block?

**Comment by pgawlowicz** [comment, marked as answer]
yes, it is possible. You need to add this to your config file:

in `cell_cfg` section:
```
cell_cfg:
...
  pdsch: 
    min_ue_mcs: 10                  # Optional UINT (0). Sets a minimum PDSCH MCS value to be used for all UEs. Supported: [0 - 28].
    max_ue_mcs: 10                  # Optional UINT (28). Sets a maximum PDSCH MCS value to be used for all UEs. Supported: [0 - 28].

  pusch: 
    min_ue_mcs: 10                  # Optional UINT (0). Sets a minimum PUSCH MCS value to be used for all UEs. Supported: [0 - 28].
    max_ue_mcs: 10                  # Optional UINT (28). Sets a maximum PUSCH MCS value to be used for all UEs. Supported: [0 - 28].
```

and a new `test_mode` section:
```
test_mode: 
  test_ue: 
    rnti: 0x4601                                # Optional ENUM (0). Sets the C-RNTI of the UE. Supported: [0 - 65519].
    pdsch_active: 1                             # Optional BOOLEAN (1). Enables the PDSCH of the UE.
    pusch_active: 1                             # Optional BOOLEAN (1). Enables the PUSCH of the UE.
    cqi: 15                                     # Optional UINT (15). Sets the Channel Quality Information to be forwarded to the test UE. Supported: [1 - 15].
    pmi: 0                                      # Optional UINT (0). Sets the Precoder Matrix Indicator to be forwarded to test UE. Supported: [0 - 3].
    ri: 1                                       # Optional UINT (1). Sets the Rank Indicator to be forwarded to the test UE. Supported: [1 - 4].
    i_1_1: 0                                    # Optional INT (0). Sets the Precoder Matrix codebook index "i_1_1" to be forwarded to test UE, in the case of more than 2 antennas. Supported: [0 - 7].
    i_1_3: 0                                    # Optional INT (0). Sets the Precoder Matrix codebook index "i_1_3" to be forwarded to test UE, in the case of more than 2 antennas. Supported: [0 - 1].
    i_2: 0                                      # Optional INT (0). Sets the Precoder Matrix codebook index "i_2" to be forwarded to test UE, in the case of more than 2 antennas. Supported: [0 - 3].
```


Please check https://docs.srsran.com/projects/project/en/latest/user_manuals/source/config_ref.html for more details. 

Note that in ZMQ-based setup, you will still need to connect a UE (srsUE), as sample reception is driving the internal gnb timers. But the srsUE does not have to send any traffic. 

To check that the traffic is generated, please type `t` in gnb console. You should get sth like this:
```
==== gNodeB started ===
Type <t> to view trace
t

           -----------------DL-----------------------|------------------UL--------------------
 pci rnti  cqi  ri  mcs  brate   ok  nok  (%)  dl_bs | pusch  mcs  brate   ok  nok  (%)    bsr
   1 4601   15   1   10   7.1M  993    0   0%    10M |  99.9   10   8.1M  993    0   0%  81.5M
   1 4602   15   1    0      0    0    0   0%      0 |   n/a    0      0    0    0   0%      0
   1 4601   15   1   10   7.1M  994    0   0%    10M |  99.9   10   8.1M  994    0   0%  81.5M
   1 4602   15   1    0      0    0    0   0%      0 |   n/a    0      0    0    0   0%      0
   1 4601   15   1   10   7.1M  994    0   0%    10M |  99.9   10   8.1M  994    0   0%  81.5M
   1 4602   15   1    0      0    0    0   0%      0 |   n/a    0      0    0    0   0%      0
   1 4601   15   1   10   7.1M  994    0   0%    10M |  99.9   10   8.1M  994    0   0%  81.5M
   1 4602   15   1    0      0    0    0   0%      0 |   n/a    0      0    0    0   0%      0

```
where the `rnti=4601` is the test_ue, while the `rnti=4602` is the connected srsUE. 

For the over the air setup (i.e., with USRP) you do not need to connect any UE.
