### DISCUSSION TITLE
Is is possible to stress test srsRAN DU Without UE Connection

### DISCUSSION THREAD

**Discussion by Zplusless** [srsran/srsRAN_Project#493] [General Help] [answered]
Hi everyone! I'm currently working on a project involving srsRAN.  My goal is to conduct stress testing on the Distributed Unit (DU) component of srsRAN.  My question is: Is it possible to simulate the network load or stress conditions to evaluate the DU's performance/computation resource usage under different workloads without attaching a UE? I see some code in `apps/examples/`. Is it possible to run DU individually and simulate UL/DL loads?

Thanks in advance!

**Comment by pgawlowicz** [comment]
Hi,
Please check the `test_mode` in the gnb config: https://docs.srsran.com/projects/project/en/latest/user_manuals/source/config_ref.html
and also see answere here: https://github.com/srsran/srsRAN_Project/discussions/446

**Reply by Zplusless** [reply]
Thanks, we have run test_mode successfully following your tutorial. 
Another question: is it possible to control the bitrate in test_mode?

**Reply by pgawlowicz** [reply]
you can set the `cqi` for the `test_ue`.

also remove this part, as this fixes the MCS:
```
cell_cfg:
...
  pdsch: 
    min_ue_mcs: 10                  # Optional UINT (0). Sets a minimum PDSCH MCS value to be used for all UEs. Supported: [0 - 28].
    max_ue_mcs: 10                  # Optional UINT (28). Sets a maximum PDSCH MCS value to be used for all UEs. Supported: [0 - 28].

  pusch: 
    min_ue_mcs: 10                  # Optional UINT (0). Sets a minimum PUSCH MCS value to be used for all UEs. Supported: [0 - 28].
    max_ue_mcs: 10                  # Optional UINT (28). Sets a maximum PUSCH MCS value to be used for all UEs. Supported: [0 - 28].
```
