### DISCUSSION TITLE
max_proc_delay = 1 not working.

### DISCUSSION THREAD

**Discussion by arman-maghsoudnia** [srsran/srsRAN_Project#505] [General Help] [answered]
Hi,
There is an available configuration named max_proc_delay.
 ```
expert_phy: 
max_proc_delay: 5                         # Optional INT (5). Sets the maximum allowed DL processing delay in slots. Supported: [1 - 30].
```

Previously when I used to set it to 1, it worked perfectly fine. But now after updating the code to the latest, when I set it to 1 the UE cannot connect to the network anymore. Do you have any idea what can be the cause?

**Comment by AlaiaL** [comment]
Hi Arman,

Can you share your gNB configuration?   
Also, could you set the log level to `debug`, do a quick run and share the gNB log?

You can set the log level to debug in this section of the gNB configuration:
```
log:
  filename: /tmp/gnb.log            # Path of the log file.
  all_level: debug                          # Logging level applied to all layers.
```


Thanks,

Alex

**Reply by arman-maghsoudnia** [reply]
Sorry for the late reply. Here is the data:

gnb config:
```
gnb_id: 107

slicing:
 - sst: 1
   sd: 0

amf:
  addr: 10.43.212.207
  bind_addr: 10.42.0.129

ru_sdr:
  device_driver: uhd
  device_args:
  # clock:
  # sync:
  srate: 23.040
  otw_format: sc16
  tx_gain: 80
  rx_gain: 40

cell_cfg:
  dl_arfcn: 650000
  band: 78
  channel_bandwidth_MHz: 20
  common_scs: 30
  plmn: "00102"
  tac: 1
  pci: 1
  tdd_ul_dl_cfg:
    dl_ul_tx_period: 4
    nof_dl_slots: 2
    nof_dl_symbols: 7
    nof_ul_slots: 1
    nof_ul_symbols: 6
  nof_antennas_ul: 1
  nof_antennas_dl: 1
  pdsch:
    mcs_table: qam256
  pusch:
    mcs_table: qam64
  pucch:
    sr_period_ms: 2

expert_phy:
  max_proc_delay: 1


e2:
  enable_du_e2: false
  e2sm_kpm_enabled: true
  addr: 127.0.0.1
  bind_addr: 10.42.3.88
  port: 36421

log:
  filename: /tmp/gnb.log
#  all_level: customlog

pcap:
  mac_enable: false
  mac_filename: /tmp/gnb_mac.pcap
  ngap_enable: false
  ngap_filename: /tmp/gnb_ngap.pcap
```

The gnb log is attached. 
[gnb.log](https://github.com/srsran/srsRAN_Project/files/14905261/gnb.log)

**Reply by AlaiaL** [reply]
Hello Arman,

I have checked the logs and found there the issue. When the UE tries to connect, the first uplink packet fails to process because it cannot find the context needed to decode it:

```
2024-04-08T12:12:59.619114 [Upper PHY] [W] [  566.15] Received notification for processing an uplink slot, but no PUSCH/PUCCH PDUs are expected to be processed in the slot.
```

This happens because some queues size are calculated based on the parameter `max_proc_delay: 1`, so in this case, with this specific configuration, the queue is too small and the context gets overwritten. 
I tried to reproduce it locally using zmq, but it was working for me. 
I saw in the logs that the cpu is not in performance mode. You can test it with the cpu in performance mode and check if that helps to connect it.
Another solution for this would be to set `max_proc_delay: 2`, that will create a bigger queue and the context will not be lost.

 We will update this behavior in the April release.

Thanks, 

Alex

**Reply by arman-maghsoudnia** [reply]
Hi Alex,

I guess I can run the following script provided by the SRS team to set the CPU to performance mode, right? https://github.com/srsran/srsRAN_Project/blob/main/scripts/srsran_performance
If yes, I already did it and tried to connect again, but again it does not connect. 
Setting the variable to `max_proc_delay: 2` will fix the problem but it will increase the latency which is not favorable for some applications. As I said it used to work when I had executed the gNB code with this commit ID: `b5621f12d4cc97b816b5147e9705acad7a965fe8 `. But after updating to later releases, it stopped working with `max_proc_delay: 2`. This is the configuration I used to use back then when it was working:

```
gnb_id: 107

amf:
  addr: 10.43.186.29
  bind_addr: 10.42.2.83

ru_sdr:
  device_driver: uhd
  device_args: 
  srate: 23.04
  otw_format: sc16
  tx_gain: 65
  rx_gain: 15

cell_cfg:
  dl_arfcn: 632628
  band: 78
  channel_bandwidth_MHz: 20
  common_scs: 30
  plmn: "00101"
  tac: 1
  pci: 1
  tdd_ul_dl_cfg:
    dl_ul_tx_period: 4
    nof_dl_slots: 2
    nof_dl_symbols: 6
    nof_ul_slots: 1
    nof_ul_symbols: 7
  nof_antennas_ul: 1
  nof_antennas_dl: 1
  pdsch:
    mcs_table: qam256
  pusch:
    mcs_table: qam64
    min_k2: 1
  pucch:
    sr_period_ms: 2
    min_k1: 1

expert_phy:
  max_proc_delay: 1
```

Shall I creat an issue from this discussion, so you can fix it in the new release?
