### DISCUSSION TITLE
srsRAN RU emulator

### DISCUSSION THREAD

**Discussion by sauka** [srsran/srsRAN_Project#517] [Announcements]
Hey,

In the recent release we have added O-RAN radio unit (RU) emulator in srsRAN. It allows to perform end-to-end tests of the srsRAN CU/DU software solution in a 7.2 split scenario using the test mode.
The RU emulator implements some basic RU functionalities and can be run in a separate PC. Its current version performs the following tasks:
- parses configuration file, configures a NIC interface using DPDK enabling reception and transmission of Open Fronthaul (OFH) packets
- analyzes incoming OFH traffic
- responds to incoming C-Plane UL packets of standard channel filter with a dummy U-Plane UL packets

## Configuration
Dummy U-Plane UL packets can be generated using static IQ data compression parameters. Allowed options include:
- 9-bit BFP compression
- 16-bit no-compression

The RU emulator accepts a configuration file in the YAML format just like the gNB application. Below you can find an example of such file:

```
log:
  filename: /tmp/ru_em.log
  level: warning

dpdk:
  eal_args: "--lcores (0-1)@(0-15)"

ru_emu:
  cells:
  - bandwidth: 100
    network_interface: 0000:01:00.1
    ru_mac_addr: 80:61:5f:0d:df:ab
    du_mac_addr: 64:b3:79:10:00:37
    vlan_tag: 2
    ul_port_id: [0]
    compr_method_ul: "bfp"
    compr_bitwidth_ul: 9
```

It is important to provide matching network configurations for both the gNB application (please refer to `ru_ofh` [configuration parameters](https://docs.srsran.com/projects/project/en/latest/user_manuals/source/config_ref.html#configuration-parameters)) and the RU emulator.

For the details on installing DPDK and binding a NIC port to it please refer to this srsRAN tutorial:
https://docs.srsran.com/projects/project/en/latest/tutorials/source/dpdk/source/index.html

## Running end-to-end test
Here are the example commands for running the gNB application in test mode and the RU emulator:
- run the gNB:
`sudo apps/gnb/gnb -c cell_cfg.yml ru_emulator.yml amf --no_core true test_mode test_ue --rnti 0x1 --ri 4`
([all](https://docs.srsran.com/projects/project/en/latest/user_manuals/source/config_ref.html#configuration-parameters) `test_mode` configuration parameters)

- run the RU emulator:
`sudo tests/integrationtests/ofh/ru_emulator -c ru_em.yml`

If everything is configured correctly, you should be able to see an output from the RU emulator similar to the following one:

```
EAL: Detected CPU lcores: 16
EAL: Detected NUMA nodes: 1
EAL: Detected shared linkage of DPDK
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: Selected IOVA mode 'VA'
EAL: VFIO support initialized
EAL: Using IOMMU type 1 (Type 1)
EAL: Ignore mapping IO port bar(2)
EAL: Probe PCI driver: net_ixgbe (8086:10fb) device: 0000:01:00.1 (socket -1)
TELEMETRY: No legacy callbacks, legacy socket not created
Running. Waiting for incoming packets...
Cell #0: 2024-03-15 17:08:11 Received 14 UL C-Plane packets
Cell #0: 2024-03-15 17:08:12 Received 401 UL C-Plane packets
Cell #0: 2024-03-15 17:08:13 Received 795 UL C-Plane packets
Cell #0: 2024-03-15 17:08:14 Received 1195 UL C-Plane packets
Cell #0: 2024-03-15 17:08:15 Received 1595 UL C-Plane packets
```

At the gNB side, press `t` to enable the trace and observe reported DL and UL throughput.

**Comment by Zplusless** [comment]
Thanks for the detailed tutorial. Is the utilization of DPDK a prerequisite for operating an RU emulator?

**Reply by sauka** [reply]
Yes, for running the RU emulator app the DPDK is mandatory

**Reply by Zplusless** [reply]
After the release of srsRAN-24.04, I have noticed an update that introduces UNIX sockets in this [commit](https://github.com/srsran/srsRAN_Project/commit/b1c73250612ef3252ef5b3b594b5ab71d0e62798). 

Just an information update in case anyone needs it.

**Comment by mmailand** [comment]
Hello,
thanks for the great work, I tried the ru_emulator, but it seems that I cannot get the configuration right. 

For the gNB I get the following log:
```
--== srsRAN gNB (commit 4d9f22329) ==--

Initializing the Open Fronthaul Interface for sector#0: ul_compr=[BFP,9], dl_compr=[BFP,9], prach_compr=[BFP,9], prach_cp_enabled=false, downlink_broadcast=true.
Operating a 20MHz cell over a RU with instantaneous bandwidth of 100MHz
Warning: Configured PRACH occasion collides with PUCCH RBs ([0..1) intersects [0..3)). Some interference between PUCCH and PRACH is expected.
Warning: Configured PRACH occasion collides with PUCCH RBs ([0..1) intersects [0..3)). Some interference between PUCCH and PRACH is expected.
Cell pci=1, bw=20 MHz, dl_arfcn=650000 (n78), dl_freq=3750.0 MHz, dl_ssb_arfcn=649632, ul_freq=3750.0 MHz

==== gNodeB started ===
Type <t> to view trace
2024-03-20T08:50:25.796544 [OFH     ] [W] Missed incoming User-Plane PRACH messages for slot '250.18' and sector#0
2024-03-20T08:50:25.806558 [OFH     ] [W] Missed incoming User-Plane PRACH messages for slot '251.18' and sector#0
2024-03-20T08:50:25.816581 [OFH     ] [W] Missed incoming User-Plane PRACH messages for slot '252.18' and sector#0
2024-03-20T08:50:25.821061 [OFH     ] [W] Missed incoming User-Plane uplink messages for slot '252.7', symbol '0' and sector#0
2024-03-20T08:50:25.821063 [OFH     ] [W] Missed incoming User-Plane uplink messages for slot '252.7', symbol '1' and sector#0
2024-03-20T08:50:25.821063 [OFH     ] [W] Missed incoming User-Plane uplink messages for slot '252.7', symbol '2' and sector#0
2024-03-20T08:50:25.821064 [OFH     ] [W] Missed incoming User-Plane uplink messages for slot '252.7', symbol '3' and sector#0
2024-03-20T08:50:25.821065 [OFH     ] [W] Missed incoming User-Plane uplink messages for slot '252.7', symbol '4' and sector#0
2024-03-20T08:50:25.821065 [OFH     ] [W] Missed incoming User-Plane uplink messages for slot '252.7', symbol '5' and sector#0
2024-03-20T08:50:25.821066 [OFH     ] [W] Missed incoming User-Plane uplink messages for slot '252.7', symbol '6' and sector#0
```
and for the ru_emulator:
```
EAL: Detected CPU lcores: 16
EAL: Detected NUMA nodes: 1
EAL: Detected shared linkage of DPDK
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: Selected IOVA mode 'VA'
EAL: VFIO support initialized
EAL: Using IOMMU type 1 (Type 1)
EAL: Probe PCI driver: net_ixgbe_vf (8086:10ed) device: 0000:05:10.1 (socket -1)
TELEMETRY: No legacy callbacks, legacy socket not created
2024-03-20T08:32:32.692718 [ALL     ] [I] Task worker "ru_rx" started...
2024-03-20T08:32:32.692892 [ALL     ] [I] Task worker "ru_emu_#0" started...
Running. Waiting for incoming packets...
2024-03-20T08:32:32.786758 [RU_EMU  ] [I] Started the DPDK ethernet frame receiver
2024-03-20T08:38:45.595610 [RU_EMU  ] [D] Packet direction is downlink
2024-03-20T08:38:45.595612 [RU_EMU  ] [D] Packet direction is downlink
2024-03-20T08:38:45.595832 [RU_EMU  ] [D] Discarding U-Plane packet
2024-03-20T08:38:45.595843 [RU_EMU  ] [D] Discarding U-Plane packet
2024-03-20T08:38:45.595872 [RU_EMU  ] [D] Discarding U-Plane packet
2024-03-20T08:38:45.595872 [RU_EMU  ] [D] Discarding U-Plane packet
2024-03-20T08:38:45.595910 [RU_EMU  ] [D] Discarding U-Plane packet
````
Could you please provide reference configuration for the gNB and the ru_emulator.
thanks for you time.

**Reply by sauka** [reply]
Hey @mmailand ,

Thanks for your interest!

> [W] Missed incoming User-Plane PRACH messages for slot '250.18' and sector#0

This warning is expected since the RU emulator doesn't send U-Plane packets with PRACH. It can be safely ignored when running the gNB in test mode. Another option is disabling PRACH C-Plane in the `ru_ofh` configuration by setting  `is_prach_cp_enabled` to `false`.


Can you see a counter of received UL C-Plane in the RU console output? If not, then either the packets do not arrive or they are being discarded. Capturing the traffic on the NIC and checking a pcap may help here.


Here is an excerpt from the configuration files used in the example command above that was working with the example RU emulator config:
```
ru_ofh:
  t1a_max_cp_dl: 470
  t1a_min_cp_dl: 258
  t1a_max_cp_ul: 500
  t1a_min_cp_ul: 285
  t1a_max_up: 196
  t1a_min_up: 50
  is_prach_cp_enabled: true
  is_dl_broadcast_enabled: false
  ignore_ecpri_payload_size: true
  compr_method_ul: bfp
  compr_bitwidth_ul: 9
  compr_method_dl: bfp
  compr_bitwidth_dl: 9
  compr_method_prach: bfp
  compr_bitwidth_prach: 9
  enable_ul_static_compr_hdr: true
  enable_dl_static_compr_hdr: true
  iq_scaling: 1.0
  cells:
  - network_interface: 0000:51:00.1 
    ru_mac_addr: 80:61:5f:0d:df:ab
    du_mac_addr: 64:b3:79:10:00:37
    vlan_tag: 2 
    prach_port_id: [4]
    dl_port_id: [0, 1, 2, 3]
    ul_port_id: [0]

cell_cfg:
  dl_arfcn: 625000
  band: 78
  channel_bandwidth_MHz: 100
  common_scs: 30
  plmn: "00101"
  tac: 7
  pci: 1
  prach:
    prach_config_index: 159
    prach_root_sequence_index: 1
    zero_correlation_zone: 0
    prach_frequency_start: 12
  nof_antennas_dl: 4
  nof_antennas_ul: 1
  tdd_ul_dl_cfg:
    nof_dl_symbols: 7
    nof_dl_slots: 7
    nof_ul_slots: 2

hal:
  eal_args: "--lcores (0-1)@(4-11)"
```

**Reply by mmailand** [reply]
Hello @sauka,

I got it working, but I think there is a bug in the vlan handling of the ru_emulator.
If I use the configuration with the vlan_tag: [1-255] I get the correct vlan id in the ethernet frame. 
At 256 there seems to be an overflow, for vlan_tag 256 I get frames with the vlan id of 0, for 257 an frame with 1 and so on. 

Thanks for your time.

**Reply by sauka** [reply]
Thanks for reporting this @mmailand, we will provide a fix in the next release.

**Comment by Zplusless** [comment]
Hi @sauka, in our environment, the RU_emulator works with no throughput. According to the log, the  packets are dropped by DPDK. More details are [here](https://github.com/srsran/srsRAN_Project/discussions/530).

Thanks you very much if you could provide some guidance.

**Reply by Zplusless** [reply]
problem solved, thanks

**Comment by mateusomattos** [comment]
Hi @sauka. Taking advantage of the post, I would like to know if there is a tutorial for running and configuring `ofh_integration_test`. I'd like to know how to configure the t1a more optimally.

**Reply by sauka** [reply]
Hi @mateusomattos ,

Using the `ofh_integration_test` is not the best approach to tune `t1a`. It rather has to be done empirically, as it depends on many setup factors. If you have a setup with a real RU that provides KPIs for OFH traffic (C/U-Plane earlies/lates), then I'd suggest to tune timing parameters with your particular RU.

The goal is to find such t1a* values that make transmission window as wide as possible to minimize the probability of late packets. 

The t1a_max value is easier to find, as it defines when the transmission window opens and when most OFH traffic will actually be sent. If it is  misconfigured, i.e. the value is too high, your RU will complain instantly about 'early' packets. The t1a_min is harder to find: it defines when the transmission window closes, and since the probability of sending traffic right at the end is much lower, your RU may not give you any feedback while you change this parameter. The approach can be to first make the tx window as narrow as possible and move it as late as possible (so set low values for t1a* and make the difference between min and max as small as possible, i..e. one OFDM symbol duration):
```

--------|                      |----------|ota_time // theoretical window
-----------------------------|  |---------|ota_time // test tx window

```
Start moving this initial tx window (i.e. increase both min and max `t1a` values) and check the RU KPIs for the point when it stops complaining about late packets. This will give you the t1a_min value. Once min is found, you can start increasing t1a_max value until the RU starts reporting 'earlies' in its KPIs.

**Comment by aliasadi2001** [comment]
Hello @mmailand ,

I'm having some trouble with the configuration of my srsRAN setup. Could someone please assist me by providing the configuration files for 'cell_cfg.yml', 'ru_emulator.yml', and 'ru_em.yml'? I believe there might be an issue with my current configuration.

Thank you in advance for your help!

**Reply by sauka** [reply]
Hey @aliasadi2001 

Did you try with one of the examples shared above? Can you share your configs and what issues do you have with them? I can take a look and give an advise what to change to make it working

**Comment by liyuanzhe-BUPT** [comment]
Hi @sauka , noticed some new parameters of test mode in the official [Configuration Reference](https://docs.srsran.com/projects/project/en/latest/user_manuals/source/config_ref.html):

```yaml
test_mode:
  enable: false                          # Optional BOOLEAN (false). Set to true to enable CU-UP test mode. Supported: [true, false].
  integrity_enable: false                # Optional BOOLEAN (false). Set to true to enable PDCP integrity testing. Supported: [true, false].
  ciphering_enable: false                # Optional BOOLEAN (false). Set to true to enable PDCP ciphering testing. Supported: [true, false].
  nea_algo: 2                            # Optional UINT (2). Sets the NEA algo to use for testing. Supported: [0, 1, 2, 3].
  nia_algo: 2                            # Optional UINT (2). Sets the NIA algo to use for testing. Supported: [1, 2, 3].
```

It seems that CU-UP is supported in test mode. If I'm correct, the original version of test mode included only the MAC and PHY layers. Is there a tutorial on deploying the new version of test mode? Thank you in advance.
