### DISCUSSION TITLE
how to save gnb trace result

### DISCUSSION THREAD

**Discussion by initChat** [srsran/srsRAN_Project#539] [General Help] [answered]
I config on gnb_zmq.conf files to have log as below. Currently I recieve /tmp/gnb.log and PCAP of MAC
```
log:
  filename: /tmp/gnb.log            # Path of the log file.
  all_level: info                   # Logging level applied to all layers.
  hex_max_size: 0
  tracing_filename: /tmp/gnb_trace.log
pcap:
  mac_enable: true                 # Set to true to enable MAC-layer PCAPs.
  mac_filename: /tmp/gnb_mac.pcap   # Path where the MAC PCAP is stored.
  ngap_enable: true                # Set to true to enable NGAP PCAPs.
  ngap_filename: /tmp/gnb_ngap.pcap # Path where the NGAP PCAP is stored.
  e2ap_enable: true                 # Set to true to enable E2AP PCAPs.
  e2ap_filename: /tmp/gnb_e2ap.pcap # Path where the E2AP PCAP is stored.
```
the gNB runs and shows trace on screen. However it does not save on file
![Screenshot from 2024-04-02 14-33-07](https://github.com/srsran/srsRAN_Project/assets/40858099/7586539c-79e3-4093-a783-ec323e8a0940)

what do I miss? I would like the trace file for further investigation. Or should I use only the /tmp/gnb.log file?

**Comment by pgawlowicz** [comment]
please use:
```
log: 
    tracing_filename:
```

**Reply by initChat** [reply]
i set
```
log: 
 tracing_filename: /tmp/gnb_trace.log
```
the file is shown on tmp folder, but have nothing written on it

**Reply by frankist** [reply]
Hey, we leave the trace points disabled by default so that they get compiled away when not being used. As an example, you can go to the file `du_traces.h` to see which trace points we have for the DU. You will notice that we have compile-time flags (e.g. `SRSRAN_L2_TRACE`) to enable or disable them.

If the output file is not too large, you can open them with chrome://tracing.

**Reply by initChat** [reply]
Ok, I see the du_traces.h file, Thank you.
I wonder on the chrome://tracing. How to see it?

**Reply by Zplusless** [reply]
open chrome and type chrome://tracing. you will enter [The Trace Event Profiling Tool](https://www.chromium.org/developers/how-tos/trace-event-profiling-tool/). Then you can load the gnb_trace.log and see the events.

**Reply by Zplusless** [reply]
Hi @frankist thanks for your guidance. The method you proposed are L1 AND L2 event traces, not the trace that @pchat-imm has mentioned. So how can I save the gnb output with 't' typed  to a file? Probably with a time stamp? So I can trace how brate changes over time.

Thanks in advance.

**Reply by pgawlowicz** [reply, marked as answer]
Hi @Zplusless,
you need to enable the following:
```
metrics: 
  enable_json_metrics: true
```

Unfortunately, the metrics are not saved to a file but sent over UDP socket. You can receive it with python and write to file. Check the example python UDP receiver:  
[metric_receiver.py.txt](https://github.com/srsran/srsRAN_Project/files/14865674/metric_receiver.py.txt)

**Reply by Zplusless** [reply]
Thanks @pgawlowicz . We will try this method.

**Reply by pgawlowicz** [reply]
@Zplusless did it work?

**Reply by Zplusless** [reply]
Yes, it works well. Thanks for your guidance.

**Reply by YuvrajDutta121EC** [reply]
@pgawlowicz  Hey, I am also trying to save the trace results but I am actually using the CU-DU spilt and running these services using docker.

I tried to run the python script from inside DU container setting up everything that you have mentioned  but the logs are not showing for my case. 
Kindly can you provide any tips?

**Reply by pgawlowicz** [reply]
Hi @YuvrajDutta121EC 

The metrics can be received and printed to stdout using a Python script.

Firstly, the metrics output and remote control can be enabled by adding the following to your configuration file:

```
metrics:
  enable_json: true
remote_control:
  bind_addr: 0.0.0.0
  port: 8001
  enabled: true
```
With this enabled, the websocket will listen on 127.0.0.1:8001. The metrics can be subscribed and written to stdout in real-time while the gNB is running using the following Python code:

```
#!/usr/bin/env python3

from contextlib import suppress
import os
import json
from time import sleep
import websocket

def _on_open(ws: websocket.WebSocketApp):
    ws.send(json.dumps({"cmd": "metrics_subscribe"}))

def _on_message(_ws: websocket.WebSocketApp, message: str):
    with suppress(json.JSONDecodeError):
        metric = json.loads(message)
        if "cmd" not in metric:
            print(json.dumps(metric))

if __name__ == "__main__":
    ws_app = websocket.WebSocketApp(
        "ws://" + os.environ["WS_URL"],
        on_open=_on_open,
        on_message=_on_message,
    )
    while ws_app.run_forever():  # Returns False when the connection is closed
        sleep(1)
```

You must specify the address and port of the websocket via environment variable `WS_URL`, e.g. start the script as follows:

```
WS_URL="127.0.0.1:8001" ./metrics_ws_receiver.py
```

This script will need to be run in parallel with the gNB to successfully print the metrics. The metrics will be written to stdout.

The script is here: https://github.com/srsran/srsRAN_Project/blob/main/docker/telegraf/ws_adapter.py

The metrics are generated on a layer basis, and each layer can be enabled through the configuration file.

```
metrics:
  layers:                    # Enable metrics per layer
    enable_executor: true    # false to disable
    enable_app_usage: true   # false to disable
    enable_ngap: true        # false to disable
    enable_rrc: true         # false to disable
    enable_e1ap: true        # false to disable
    enable_pdcp: true        # false to disable
    enable_sched: true       # false to disable
    enable_rlc: true         # false to disable
    enable_mac: true         # false to disable
    enable_du_low: true      # false to disable
    enable_ru: true          # false to disable
```
