### DISCUSSION TITLE
RAN650 and Intel E810-XXVDA4T network adapter

### DISCUSSION THREAD

**Discussion by hakegard** [srsran/srsRAN_Project#555] [General Help] [answered]
We are trying to connect Benetel RAN650 to the srsRAN using the E810 network card from Intel. We have some problems with synchronization and have tried both PTP and GPS synchronization. DPDK is not installed.

- Connecting the O-RU to the O-DU using GPS synchronization:
	- phc2sys is used to synchronize the system clock to the PHC of the NIC.
	- Wireshark shows that packets are flowing through the FH interface. Both U- and C-plane packets (type 1 and 3) are transmitted from the O-DU, while U-plane packets are transmitted from the O-RU. 
	- The kpi.sh application in the O-RU shows that some U-plan packets arrive late (some 10s or some 100s per log line). Number of TX packets are 0.
	- The gnb-log on OFH level shows late downlink messages. May this indicate that the problem is within the O-DU and not the sync between the O-DU and O-RU?
	- The UEs do not see the network, and there is no indication of RRC frames being transmitted.
- Connecting the O-RU to the O-DU using PTP synchronization.
	- The initiation script in the O-RU stops waiting the PTP sync, although logging shows that the O-RU receives PTP packets and synchronises.
	- Wireshark shows that the workstation transmits PTP delay requests and the O-RU PTP delay responses. The O-RU does not send PTP delay requests.

Has anyone experienced something similar and has some device on how to proceed?

**Comment by hakegard** [comment]
We are still struggling with this issue. UEs connecting to the network using a USRP as RU are not seeing the network using the RAN650 as RU, and there are no signs in the logs that RRC connection establishment is initiated. The CU/DU runs on an AMD Ryzen Threadripper with 64 CPUs and 256 GB RAM. A 4x4 MIMO antenna from Panorama (DWMM4[G]-6-60) is used, and the operation frequency is in the n77u band. The current status is:

- 	GPS synchronization between DU and RU works fine.
- 	The configuration files in the srsRAN documentation are used. By adjusting the delay profile parameters t1a…, the kpi.sh application in the RU indicates that all UP and CP packets arrive on time. The number of TX packets is still zero.
- 	After testing different RU parameter settings, the long PRACH format with LF compression format enabled is selected.
- 	Monitoring the fronthaul interface with wireshark shows that O-FH packets go in both directions over the fiber. None of the other PCAP files indicate any communication between the UEs and the DU.
- 	Combinations of MIMO settings (2x2, 4x2 and 4x4), bandwidths (20MHz, 40 MHz, 80 MHz and 100 MHz), and gaincontrol (15-30 dB) are tested. Also, other parameters are modified (such as downlink scaling in the RU and various parameters in the DU) and tested. Increasing the distance to UEs, in case saturation in the UEs is the problem, is tested. 
- 	The gnb.log file consists of lines like:
![image](https://github.com/srsran/srsRAN_Project/assets/4134065/42108cc0-b675-4d6c-b56a-439b036e7a5b)

Any assistance or proposals on how to solve this issue are very appreciated. Advice from Benetel support is to get assistance from the srsRAN community… Configuration files, logs etc. can be provided if it might help in the diagnostics.

**Reply by ismagom** [reply]
Hi @hakegard , 

I share here some config it works well in our setup: 

gnb config: 

```
cell_cfg:
  dl_arfcn: 640000
  band: 78
  channel_bandwidth_MHz: 100
  tdd_ul_dl_cfg:
    nof_dl_symbols: 6
    nof_ul_symbols: 4
    nof_dl_slots: 7
    nof_ul_slots: 2
  ssb: 
     ssb_period: 10
     ssb_block_power_dbm: -21
  prach: 
      prach_config_index: 7
      prach_root_sequence_index: 1
      zero_correlation_zone: 0
      prach_frequency_start: 0
  pusch:
    dmrs_additional_position: 2
  pdsch:
    dmrs_additional_position: 2

ru_ofh:
  t1a_max_cp_dl: 470
  t1a_min_cp_dl: 419
  t1a_max_cp_ul: 336
  t1a_min_cp_ul: 285
  t1a_max_up: 345
  t1a_min_up: 294
  ta4_max: 200
  ta4_min: 0
  is_prach_cp_enabled: false
  compr_method_ul: bfp
  compr_bitwidth_ul: 9
  compr_method_dl: bfp
  compr_bitwidth_dl: 9
  compr_method_prach: bfp
  compr_bitwidth_prach: 9
  enable_ul_static_compr_hdr: true
  enable_dl_static_compr_hdr: true
  iq_scaling: 10
```

Make sure the TDD pattern matches in the RU config. This is then the config we use in the RU (/etc/ru_config.cfg)

```
# MIMO mode - the radio can operate in 1_3, 2_4, 1_2_3_4_4x2 or 1_2_3_4_4x4 mode
# Variable name : mimo_mode
# Valid options : 1_3
#                 2_4
#                 1_2_3_4_4x2
#                 1_2_3_4_4x4
mimo_mode=1_2_3_4_4x2

# FPGA downlink scaling in steps of 6 dB (0, 6, 12 and 18 can be set)
# Variable name : downlink_scaling
# Valid options : 0
#                 6
#                 12
#                 18
downlink_scaling=6

# PRACH format
# Variable name : prach_format
# Valid options : short
#                 long
prach_format=long

# Short form PRACH compression settings (note uncompressed mode is not supported when RU is in 4x2 or 4x4 mode)
# Variable name : compression
# Valid options : static_uncompressed
#                 dynamic_uncompressed
#                 static_compressed
#                 dynamic_compressed
compression=static_compressed

# Long form PRACH compression settings
# Variable name : lf_prach_compression_enable
# Valid options : true
#                 false
lf_prach_compression_enable=true

# C-Plane per-symbol workaround
# Variable name : cplane_per_symbol_workaround
# Valid options : enabled
#                 disabled
cplane_per_symbol_workaround=disabled

# CUPLANE dl couplling sectionID              
# Variable name : cuplane_dl_coupling_sectionId
# Valid options : enabled                      
#                 disabled                     
cuplane_dl_coupling_sectionID=disabled         
                                               
# FlexRAN PRACH workaround                     
# Variable name : flexran_prach_workaround     
# Valid options : enabled                      
#                 disabled                     
flexran_prach_workaround=disabled              
                                               
#DL_UL special slot tunning                    
#Variable name : dl_ul_tuning_special_slot     
#Valid options : 0x0                           
#                0xfd00000                     
dl_ul_tuning_special_slot=0xfd00000            
```

Also, I would recommend sticking with 100 MHz 4x2 configuration. I think it's what works best. 

Once you see no lates in kpi.sh, can you check if you see signal radiating out of the antenna 1?

**Comment by hakegard** [comment]
Hi @ismagom,

Thanks for your response. The spectrum at the output of antenna 1 looks like this:

![image](https://github.com/srsran/srsRAN_Project/assets/4134065/afa21ccc-1129-41e8-aa6f-1ca7ec78aea4)

The center frequency is 3.88 GHz, so the signal is within the bandwidth 3.83-3.93 GHz. It is however sparse compared to the spectrum from the USRP (40 MHz BW, one TX antenna, no UE connected):

![image](https://github.com/srsran/srsRAN_Project/assets/4134065/f1383005-0e30-4e55-9b5b-f3a7f07dfe8f)

The configuration files are as follows:

gnb config:
![image](https://github.com/srsran/srsRAN_Project/assets/4134065/1e601458-db24-4fe6-b63c-a453957dfe28)

/etc/ru_config.cfg:
![image](https://github.com/srsran/srsRAN_Project/assets/4134065/ada5efc6-8e80-4395-8f72-74bb6d750746)

/etc/tdd.xml:
![image](https://github.com/srsran/srsRAN_Project/assets/4134065/65c59432-8d31-4808-844f-76c9a38651c5)

It seems as only the two first antennas transmit power:
![image](https://github.com/srsran/srsRAN_Project/assets/4134065/68ee61b0-985d-4bb7-8db1-027ad459348b)

When starting the gnb, we get the following terminal output:

![image](https://github.com/srsran/srsRAN_Project/assets/4134065/79f2859f-1dab-4fe9-a721-4dbc0612442f)

Sorry for the long message. Hopefully, it might give an indication why we are not able to connect.

**Reply by ismagom** [reply]
Check the gnb config. It's not the same as the one I provided.

Do you see lates/earlies in kpi.sh command in the RU?

**Comment by hakegard** [comment]
Thanks again @ismagom for spending time on this. It is much appreciated. I have ordered the gnb config to make sure that it is as similar to yours as possible. 
```
amf:
  addr: 127.0.0.5                                               
  bind_addr: 127.0.0.1                                            

cell_cfg:
  dl_arfcn: 658666                                                
  band: 77                                                    
  common_scs: 30                                                  
  plmn: "24271"                                                   
  tac: 7                                                          
  pci: 1                                                          
  nof_antennas_dl: 4                                              
  nof_antennas_ul: 2     
  
  channel_bandwidth_MHz: 100                                      
  tdd_ul_dl_cfg: 
    nof_dl_symbols: 6                       
    nof_ul_symbols: 4                      
    nof_dl_slots: 7                         
    nof_ul_slots: 2                                           
  ssb:
    ssb_period: 10
    ssb_block_power_dbm: -21
  prach: 
      prach_config_index: 7
      prach_root_sequence_index: 1
      zero_correlation_zone: 0
      prach_frequency_start: 0
  pusch:
    dmrs_additional_position: 2
  pdsch:
    dmrs_additional_position: 2

ru_ofh:
  t1a_max_cp_dl: 470
  t1a_min_cp_dl: 419
  t1a_max_cp_ul: 336
  t1a_min_cp_ul: 285
  t1a_max_up: 345
  t1a_min_up: 294
  ta4_max: 200
  ta4_min: 0                                            
  is_prach_cp_enabled: false                                      
  compr_method_ul: bfp                                            
  compr_bitwidth_ul: 9                                            
  compr_method_dl: bfp                                            
  compr_bitwidth_dl: 9                                            
  compr_method_prach: bfp                                         
  compr_bitwidth_prach: 9                                         
  enable_ul_static_compr_hdr: true                                
  enable_dl_static_compr_hdr: true                               
  iq_scaling: 10                                                
  cells:
    - network_interface: enp74s0f0np0                                 
      ru_mac_addr: 70:b3:d5:xx:xx:xx                               
      du_mac_addr: 50:7c:6f:xx:xx:xx                              
      vlan_tag: 3                                              
      prach_port_id: [4]                                          
      dl_port_id: [0, 1, 2, 3]                                          
      ul_port_id: [0,2] 
``` 
There are a few differences. We have the n77 version of RAN650, so the lowest frequency allowed is 3.7 GHz. We know however that the UEs handle our frequency band as it works with the USRPs. kpi.sh indicates that all packets arrive on time:

```
root@benetelru:~# kpi.sh
 SAMPLE_TIME          | RX_TOTAL             | RX_ON_TIME           | RX_EARLY             | RX_LATE              | RX_ON_TIME_C         | RX_EARLY_C           | RX_LATE_C            | TX_TOTAL             
 15:58:58.439973      | 4124                 | 3959                 | -0                   | -0                   | 164                  | -0                   | -0                   | -0                   
 15:58:59.434145      | 7295                 | 6958                 | -0                   | -0                   | 335                  | -0                   | -0                   | -0                   
 15:59:00.432488      | 7463                 | 7360                 | -0                   | -0                   | 360                  | -0                   | -0                   | -0                   
 15:59:01.433490      | 6204                 | 5877                 | -0                   | -0                   | 202                  | -0                   | -0                   | -0                   
 15:59:02.432892      | 16853                | 16121                | -0                   | -0                   | 1014                 | -0                   | -0                   | -0                   
 15:59:03.432391      | 22516                | 20921                | -0                   | -0                   | 1262                 | -0                   | -0                   | -0                   
 15:59:04.433627      | 14893                | 14045                | -0                   | -0                   | 774                  | -0                   | -0                   | -0       

```

Selecting prach_frequency_start=0 gives the following warning:
```
Warning: Configured PRACH occasion collides with PUCCH RBs ([0..1) intersects [0..3)). Some interference between PUCCH and PRACH is expected.

``` 
If we select e.g. prach_frequency_start=2 there is no warning.

Unfortunately, the result is as before, also when varying parameters such as the gaincontrol and also bandwidth (40 MHz) as we know that the UEs support this bandwidth. Any suggestion on what else that can be tried? Is it normal to get these warnings in the gnb log file?

```
2024-05-07T09:03:36.748628 [OFH     ] [W] Detected '4' late downlink C-Plane messages in the transmitter queue for slot '478.2'
2024-05-07T09:03:36.748633 [OFH     ] [W] Detected '4' late downlink U-Plane messages in the transmitter queue for slot '478.2', symbol '0'
2024-05-07T09:03:36.748688 [OFH     ] [W] Failed to dispatch Control-Plane type 1 message for slot '499.2'
2024-05-07T09:03:36.748693 [OFH     ] [W] Failed to dispatch message in the downlink data flow User-Plane for slot '499.2'

```
