### DISCUSSION TITLE
Issues regarding handover testing

### DISCUSSION THREAD

**Discussion by laxmandvb** [srsran/srsRAN_Project#598] [General Help] [answered]
We are trying intra DU handover. we are able to create two cells with  PCI = 1, 2 and connected to RUs. But unable to include mobility related parameters in the gNB configuration file.  Under section srsRAN gNB Handover, we are unable to download sample configuarion file "handover_x310.yml". 

Request you to provide sample configuration file for handover and guide us for successful hand over testing.

Regards,
Laxmaiah.

**Comment by pgawlowicz** [comment]
Hi, thanks for pointing this out. The link will be fixed soon.

**Reply by brendan-mcauliffe** [reply]
@pgawlowicz @laxmandvb this issue has been fixed.

**Reply by laxmandvb** [reply]
Thanks for the support

**Comment by HaoxinSEU** [comment]
Hi @brendan-mcauliffe,

Thanks for the update! We are excited to see the new features.

However, with the provided `handover_x310.yml`, we get the error:
```
For external cells, the gnb_id_bit_length, pci, band, ssb_arfcn, ssb_scs, ssb_period, ssb_offset and ssb_duration must be configured in the mobility config
srsGNB ERROR: Invalid configuration detected.
```

It seems that we need to provide more configurations in `cu_cp:mobility:cells` session. Can you give some hints on this? Thanks so much!

We are using the latest main branch (commit `1483bda3091420cf7270eacdf31de932865c6294`), and the configuration is:
```
gnb_id: 147
gnb_id_bit_length: 32

amf:
  addr: 10.43.31.80
  bind_addr: 10.42.1.79

ru_sdr:
  device_driver: uhd
  device_args: type=x300
  tx_gain: 20
  rx_gain: 15
  srate: 92.16
  lo_offset: 45
  clock: internal
  sync: internal
  time_alignment_calibration: 0

cell_cfg:
  dl_arfcn: 640000
  band: 78
  channel_bandwidth_MHz: 20
  common_scs: 30
  nof_antennas_dl: 1
  nof_antennas_ul: 1
  plmn: "00103"
  tac: 1

cells:
  -
    pci: 1
    prach:
      prach_root_sequence_index: 0
  -
    pci: 2
    prach:
      prach_root_sequence_index: 64

cu_cp:
  mobility:
    trigger_handover_from_measurements: true
    cells:
      - nr_cell_id: 0x19B0
        periodic_report_cfg_id: 1
        ncells:
          - nr_cell_id: 0x19B1
            report_configs: [ 1 ]
      - nr_cell_id: 0x19B1
        periodic_report_cfg_id: 1
        ncells:
          - nr_cell_id: 0x19B0
            report_configs: [ 1 ]
    report_configs:
      - report_cfg_id: 1
        report_type: periodical
        report_interval_ms: 480
      - report_cfg_id: 2
        report_type: event_triggered
        a3_report_type: rsrp
        a3_offset_db: 3
        a3_hysteresis_db: 0
        a3_time_to_trigger_ms: 100
```
