### DISCUSSION TITLE
UE can't reach core after handover

### DISCUSSION THREAD

**Discussion by yc541** [srsran/srsRAN_Project#614] [General Help] [answered]
We have been testing the F1 HO and found that after the HO the UE can't reach the core and loses the Internet. 

The Radio is a USRP X310, with UHD 4.0. SRS version is on the 24_04 release and the core is the containerized Open5GS (one the same machine) that comes with SRS. The UE is a Xiaomi 12 (also tested with a Oneplus Nord 5G).

I have followed the HO guide and created the gnb config (2-cell on the same USRP) based on [handover_x310.yml](https://docs.srsran.com/projects/project/en/latest/_downloads/62f212bed3a5a5140a5aed6abfee257f/handover_x310.yml)

When the UE is just attached to one of the cells (after turning off flight mode), it can ping the core and has Internet. But once the HO happens the UE can't ping the core any more and loses the Internet. Both UEs have the same behavior.

Please see the attached logs, pcaps and gnb config. There are two HO events in the F1 pcap at about 17 and 39 seconds. 

[F1 HO logs.zip](https://github.com/srsran/srsRAN_Project/files/15293630/F1.HO.logs.zip)

**Comment by robertfalkenberg** [comment]
Can you please re-run your config and in addition enable PCAPs at MAC and GTP-U, while doing a constant ping between core and UE?

```yml
pcap:
  mac_enable: true                 # Set to true to enable MAC-layer PCAPs.
  mac_filename: /tmp/gnb_mac.pcap   # Path where the MAC PCAP is stored.
  ngap_enable: true                # Set to true to enable NGAP PCAPs.
  ngap_filename: /tmp/gnb_ngap.pcap # Path where the NGAP PCAP is stored.
  f1ap_enable: true
  f1ap_filename: /tmp/gnb_f1ap.pcap
  e1ap_enable: true
  e1ap_filename: /tmp/gnb_e1ap.pcap
  gtpu_enable: true
  gtpu_filename: /tmp/gnb_gtpu.pcap

```
