### DISCUSSION TITLE
XIaomi 11 Lite 5G NE SA problems

### DISCUSSION THREAD

**Discussion by Salex406** [srsran/srsRAN_Project#64] [General Help] [answered]
Hello. 
I have USRP b205 mini (China copy), installation of Open5gs and srsRAN. According to open5gs logs, amf runs without errors.
As for UE, I use Xiaomi 11 Lite 5G NE with MIUI Global 13.0.5. I enabled hidden setting "5G SA". SIM is sysmoISIM-SJA2 SIM.
My UE connects perfectly to srsRAN 4g, to oai 5G NSA, but it don't work with srsRAN 5G SA network (example config for usrp B200).
I also tried different settings (NR only or LTE/NR), sometimes UE can see my network,  but even if it sees network, it doesn't connect, amf log shows nothing.

I saw this UE in support list, so, maybe anyone will share thoughts or SIM configuration.

**Comment by fllay** [comment]
Hi 

I wrote a script for SIM card.

```
# script to be used with pySim-shell.py which is part of the Osmocom pysim package,
# found at https://osmocom.org/projects/pysim/wiki
set echo true

# this script will deactivate all 5G related services and files.  This can be used
# in case you do not wish to use any 5G services, or you do not wish to configure
# the 5G specific files on the USIM card.  The card will then behave like a 3G USIM
# without any 5G capability, using the default fall-back mechanisms specified by 3GPP.

# TODO: add your card-specific ADM pin at the end of the verify_adm line below
verify_adm XXXXX
# Key Provisioning
select MF
select ADF.USIM 
select DF.5GS 
select EF.SUCI_Calc_Info 
update_binary_decoded '{ "prot_scheme_id_list": [ {"priority": 0, "identifier": 2, "key_index": 1}, {"priority": 1, "identifier": 1, "key_index": 2}, {"priority": 2, "identifier": 0, "key_index": 0}], "hnet_pubkey_list": [ {"hnet_pubkey_identifier": 27, "hnet_pubkey": "0272DA71976234CE833A6907425867B82E074D44EF907DFB4B3E21C1C2256EBCD1"}, {"hnet_pubkey_identifier": 30, "hnet_pubkey": "5A8D38864820197C3394B92613B20B91633CBD897119273BF8E4A6F4EEC0A650"}]}'


# Routing Indicator
select MF
select ADF.USIM 
select DF.5GS 
select EF.Routing_Indicator
update_binary 0071ffff

# Service Table
select MF
select ADF.USIM 
select EF.UST 
ust_service_deactivate 124
ust_service_deactivate 125
```
Please edit `verify_adm XXXXX` to your ADM KEY.
I have a trouble for a while but the key here is to deactivate service 124 `ust_service_deactivate 124`

Also, you may need to check the config file

```
amf:
  addr: 127.0.0.2                 # The address or hostname of the AMF. 127.0.1.1
  bind_addr: 127.0.0.1              # A local IP that the gNB binds to for traffic from the AMF. 127.0.0.1

rf_driver:
  device_driver: uhd                # The RF driver name.
  device_args: type=b200, num_recv_frames=64,num_send_frames=64            # Optionally pass arguments to the selected RF driver.
  clock: internal                   # Specify the clock source used by the RF.
  sync: internel                    # Specify the sync source used by the RF.
  srate: 23.04                      # 30.72 11.52 RF sample rate might need to be adjusted according to selected bandwidth.
  tx_gain: 89                       # Transmit gain of the RF might need to adjusted to the given situation.
  rx_gain: 40                       # Receive gain of the RF might need to adjusted to the given situation.
  #time_alignment_calibration:  100  # Set time stamp offset
  #device_args: num_recv_frames=64,num_send_frames=64,recv_frame_size=9232,send_frame_size=9232
cell_cfg:
  dl_arfcn: 368500                  # ARFCN of the downlink carrier (center frequency).
  band: 3                           # The NR band.
  channel_bandwidth_MHz: 20         # Bandwith in MHz. Number of PRBs will be automatically derived.
  common_scs: 15                    # Subcarrier spacing in kHz used for data.
  plmn: "99970"                     # PLMN broadcasted by the gNB.
  tac: 7                            # Tracking area code (needs to match the core configuration).
  pci: 1                            # Physical cell ID.
      
log:
  filename: /tmp/gnb.log            # Path of the log file.
  all_level: warning                # Logging level applied to all layers.

pcap:
  mac_enable: false                 # Set to true to enable MAC-layer PCAPs.
  mac_filename: /tmp/gnb_mac.pcap   # Path where the MAC PCAP is stored.
  ngap_enable: false                # Set to true to enable NGAP PCAPs.
  ngap_filename: /tmp/gnb_ngap.pcap # Path where the NGAP PCAP is stored.
```

Just try to set `tx_gain: 89 ` so that it have enough TX power, otherwise, UE will not see the gNB. I used default setting for `tx_gain` it does not work for me.
