### DISCUSSION TITLE
Maximum Number of Supported UEs in srsRAN

### DISCUSSION THREAD

**Discussion by Ali78k** [srsran/srsRAN_Project#647] [General Help] [answered]
Hey Community. What is the maximum number of supported UEs in srsRAN?
Please, If you have the correlated information about the followed scenarios, explain with details:
1- Open5Gs CN + srsRAN DU/CU + USRP
2- Open5Gs CN + srsRAN Enterprise + USRP
3- Open5Gs CN + srsRAN Enterprise + RU (such as [this guide](https://docs.srsran.com/projects/project/en/latest/tutorials/source/oranRU/source/index.html))

Sincerely Thankfull.

**Comment by fllay** [comment, marked as answer]
The is a configuration in the configuration files to set the maximum number of UEs. For example

```
#   This file contains the PUCCH configuration for the gNB to support:
#   - SR period 20ms or 40ms.
#   - CSI period 20ms or 40ms.
#   - Max 128 UEs.

#   NOTEs:
#   - This configuration is optimized for TDD 7D-2U configuration, but it still works for TDD configurations
#     with more than 2 UL slots.
#   - This configuration might work for more than 128 UEs, although it hasn't been tested for those scenarios.

cell_cfg:
  pucch:
    sr_period_ms: 20   # This can be set either 20 or 40 ms.
    f1_nof_cell_res_sr: 50
    f2_nof_cell_res_csi: 50
  csi:
    csi_rs_period: 40  # This can be set either 20 or 40 ms.
  ul_common:
    max_ul_grants_per_slot: 64
    max_pucchs_per_slot: 63
  pusch:
    max_puschs_per_slot: 1
  tdd_ul_dl_cfg:
    nof_dl_symbols: 7
    nof_dl_slots: 7
    nof_ul_slots: 2
```
However, I think that the maximum number can be arbitrary set depend on the scheduler using in the RAN stack and 128, 64, 32 are just a parameter in the scheduler in srsRAN stack. As seen in the configuration file, there are so many parameters for these specific maximum number of UEs.  Please correct me if I am wrong. I am still leaning 5g stack. Thank you
