### DISCUSSION TITLE
7.2 Split [srsran 4G UE compatibility with b210 SDR]

### DISCUSSION THREAD

**Discussion by cueltschey** [srsran/srsRAN_Project#651] [General Help] [answered]
I only see COTS UE and AmariUE compatibility on the setup guide for 7.2 but we would like to use the 4G srsue since we plan to modify it for our NTIA project. Is this configuration possible?

**Comment by pgawlowicz** [comment]
Hi, it should be possible, but I guess it was never tested. However, srsUE supports BW up to 20MHz and scs=15khz.
Moreover, you have to use the following section in gnb config file:
```
cell_cfg:
  ...
  channel_bandwidth_MHz: 20         # Bandwith in MHz. Number of PRBs will be automatically derived.
  common_scs: 15                    # Subcarrier spacing in kHz used for data
  pdcch:
    common:
      ss0_index: 0                  # Set search space zero index to match srsUE capabilities
      coreset0_index: 12            # Set search CORESET Zero index to match srsUE capabilities
    dedicated:
      ss2_type: common              # Search Space type, has to be set to common
      dci_format_0_1_and_1_1: false # Set correct DCI format (fallback)
  prach:
    prach_config_index: 1           # Sets PRACH config to match what is expected by srsUE
```

Please provide your feedback on this setup.

**Reply by cueltschey** [reply]
![image](https://github.com/srsran/srsRAN_Project/assets/68715119/715e3a77-06e2-4484-8cfa-f00740ebe3e5)

Below is the config file for the benetel ran 550 RU we are modifying. We try to add the ssb_scs but alot of other information is needed as well.
```
gnb_id: 1
amf:
  addr: 127.0.1.100                                               # The address or hostname of the AMF.
  bind_addr: 127.0.0.1                                            # A local IP that the gNB binds to for traffic from the AMF.

ru_ofh:
  t1a_max_cp_dl: 500                                              # Maximum T1a on Control-Plane for Downlink in microseconds.
  t1a_min_cp_dl: 450                                              # Minimum T1a on Control-Plane for Downlink in microseconds.
  t1a_max_cp_ul: 350                                              # Maximum T1a on Control-Plane for Uplink in microseconds.
  t1a_min_cp_ul: 290                                              # Minimum T1a on Control-Plane for Uplink in microseconds.
  t1a_max_up: 360                                                 # Maximum T1a on User-Plane in microseconds.
  t1a_min_up: 300                                                 # Minimum T1a on User-Plane in microseconds.
  ta4_max: 200                                                    # Maximum Ta4 on User-Plane in microseconds.
  ta4_min: 0                                                      # Minimum Ta4 on User-Plane in microseconds.
  is_prach_cp_enabled: true                                      # Configures if Control-Plane messages should be used to receive PRACH messages.
  compr_method_ul: bfp                                            # Uplink compression method.
  compr_bitwidth_ul: 9                                            # Uplink IQ samples bitwidth after compression.
  compr_method_dl: bfp                                            # Downlink compression method.
  compr_bitwidth_dl: 9                                            # Downlink IQ samples bitwidth after compression.
  compr_method_prach: bfp                                         # PRACH compression method.
  compr_bitwidth_prach: 9                                         # PRACH IQ samples bitwidth after compression.
  enable_ul_static_compr_hdr: false                                # Configures if the compression header is present for uplink User-Plane messages (false) or not present (true).
  enable_dl_static_compr_hdr: false                                # Configures if the compression header is present for downlink User-Plane messages (false) or not present (true).
  iq_scaling: 4.5                                                 # IQ samples scaling factor applied before compression, should be a positive value smaller than 10.
  cells:
  - network_interface: enp1s0f1                                   # Ethernet interface name used to communicate with the RU.
    ru_mac_addr: 70:b3:d5:e1:5b:06                                # RU MAC address.
    du_mac_addr: 80:61:5f:0d:df:ab                                # DU MAC address.
    vlan_tag_cp: 3                                                # VLAN tag value for C-Plane.
    vlan_tag_up: 3                                                # VLAN tag value for U-Plane.
    prach_port_id: [4,5]                                          # PRACH eAxC port value.
    dl_port_id: [0,1]                                             # Downlink eAxC port values.
    ul_port_id: [0,1]                                             # Uplink eAxC port values.

cell_cfg:
  dl_arfcn: 640000                                                # ARFCN of the downlink carrier (center frequency).
  band: 78                                                        # The NR band.
  channel_bandwidth_MHz: 20                                       # Bandwith in MHz. Number of PRBs will be automatically derived.
  common_scs: 15                                                  # Subcarrier spacing in kHz used for data.
  plmn: "00101"                                                   # PLMN broadcasted by the gNB.
  tac: 7                                                          # Tracking area code (needs to match the core configuration).
  pci: 1                                                          # Physical cell ID.
  nof_antennas_dl: 2
  nof_antennas_ul: 2
  pdcch:
    common:
      ss0_index: 0                  # Set search space zero index to match srsUE capabilities
      coreset0_index: 12            # Set search CORESET Zero index to match srsUE capabilities
    dedicated:
      ss2_type: common              # Search Space type, has to be set to common
      dci_format_0_1_and_1_1: false # Set correct DCI format (fallback)  
  prach:
    prach_config_index: 1                                     # PRACH configuration index.
    prach_root_sequence_index: 1                                  # PRACH root sequence index.
    zero_correlation_zone: 0                                      # Zero correlation zone.
    prach_frequency_start: 2                                      # Offset in PRBs of lowest PRACH transmission occasion in frequency domain respective to PRB 0.
    preamble_trans_max: 50
    power_ramping_step_db: 4
  tdd_ul_dl_cfg:
    dl_ul_tx_period: 10                                           # Optional INT (10). Sets the TDD pattern periodicity in slots. The combination of this value and the chosen numerology must lead to a TDD periodicity of 0.5, >
    nof_dl_slots: 7                                               # Optional INT (6). Number of consecutive full Downlink slots. Supported: [0-80].
    nof_dl_symbols: 6                                             # Optional INT (0). Number of Downlink symbols at the beginning of the slot following full Downlink slots. Supported: [0-13].
    nof_ul_slots: 2                                               # Optional INT (3). Number of consecutive full Uplink slots. Supported: [0 - 80].
    nof_ul_symbols: 4
  ssb:
    ssb_block_power_dbm: -20
  pdsch:
    mcs_table: qam256
  pusch:
    p0_nominal_with_grant: -76
log:
  filename: /tmp/gnb.log                                          # Path of the log file.
  all_level: warning

pcap:
  mac_enable: false                                               # Set to true to enable MAC-layer PCAPs.
  mac_filename: /tmp/gnb_mac.pcap                                 # Path where the MAC PCAP is stored.
  ngap_enable: false                                              # Set to true to enable NGAP PCAPs.
  ngap_filename: /tmp/gnb_ngap.pcap                               # Path where the NGAP PCAP is stored.

```
