### DISCUSSION TITLE
Osmocom Developer Conference 2024

### DISCUSSION THREAD

**Discussion by brendan-mcauliffe** [srsran/srsRAN_Project#668] [Events]
@herlesupreeth attended [OsmoDevCon2024](https://osmocom.org/projects/osmo-dev-con/wiki/OsmoDevCon2024) in May, where he presented _"srsRAN Project - Application in UL heavy traffic scenarios"_. 

The Osmocom Developer Conference is an annual event where Osmocom developers from various Osmocom projects and invited speakers meet. Supreeth's presentation goes through some of the most recent developments in srsRAN Project and demonstrates how to configure and use srsRAN Project for high uplink traffic scenarios such as automotive test tracks, media broadcasting, and AR/XR services.  

You can find a recording of his presentation [here](https://media.ccc.de/v/osmodevcon2024-214-srsran-project-application-in-ul-heavy-traffic-scenarios). 

The PDF of his presentation can be downloaded [here](https://github.com/user-attachments/files/15786404/2024_05_SRS_OsmoDevCon24.pdf). 

To achieve the configuration shown in the demo, the following parameters can be added to your configuration file: 

```
cell_cfg:
  pdsch:
    olla_target_bler: 0.1
    mcs_table: qam256
  pusch:
    olla_target_bler: 0.1
    mcs_table: qam256
    min_k2: 2
  pucch:
    min_k1: 2
  tdd_ul_dl_cfg:
    dl_ul_tx_period: 10
    nof_dl_slots: 2
    nof_dl_symbols: 10
    nof_ul_slots: 7
    nof_ul_symbols: 0
```
