### DISCUSSION TITLE
No TOTAL_TX on benetel 550 with srsRAN gNB

### DISCUSSION THREAD

**Discussion by cueltschey** [srsran/srsRAN_Project#677] [General Help] [answered]
Hey all,
We are running an srsRAN project gNB on a server, connected to a Benetel RU through a switch with PTP on it. We have set up everything as close to what is recommended in this guide: 

https://docs.srsran.com/projects/project/en/latest/tutorials/source/oranRU/source/rus/r550.html

Thus far we have gottent the benetel to connect to the gNB via DPDK, but we have yet to see any TX packets in the KPIs.

When we run the kpi.sh script on the RU we see that all RX packets are recieved on time, but the TX_TOTAL remains 0.
Additionally the gnb log (/tmp/gnb.log) says "Missing incoming user plane PRACH message in slot 'xxx.yy' "

We have been thinking the issue has to do with misconfigured eaxc uplink ports, but nothing we have tried is working.

Below I have included all of the relevant config files we are using, as well as some additional logs from the benetel.

Any help would be appreciated.

**Comment by cueltschey** [comment]
[logs_and_configs.zip](https://github.com/user-attachments/files/15878048/logs_and_configs.zip)

**Comment by andrepuschmann** [comment]
Likely a VLAN and/or MAC address mismatch or misconfiguration. Please check the DU MAC address registers in the RU.

**Reply by cueltschey** [reply]
Thanks, that's a good suggestion,
I've been looking for a way to resolve this by changing either the MAC address or the VLAN. The way I have it now is that the gNB is configured to point to the RU using VLAN port 1 like so:

```
ru_ofh:
  t1a_max_cp_dl: 479                                              # Maximum T1a on Control-Plane for Downlink in microseconds.
  t1a_min_cp_dl: 419                                              # Minimum T1a on Control-Plane for Downlink in microseconds.
  t1a_max_cp_ul: 336                                              # Maximum T1a on Control-Plane for Uplink in microseconds.
  t1a_min_cp_ul: 285                                              # Minimum T1a on Control-Plane for Uplink in microseconds.
  t1a_max_up: 345                                                 # Maximum T1a on User-Plane in microseconds.
  t1a_min_up: 294                                                  # Minimum T1a on User-Plane in microseconds.
  ta4_max: 200                                                    # Maximum Ta4 on User-Plane in microseconds.
  ta4_min: 0                                                     # Minimum Ta4 on User-Plane in microseconds.
  is_prach_cp_enabled: false                                      # Configures if Control-Plane messages should be used to receive PRACH messages.
  compr_method_ul: bfp                                            # Uplink compression method.
  compr_bitwidth_ul: 9                                            # Uplink IQ samples bitwidth after compression.
  compr_method_dl: bfp                                            # Downlink compression method.
  compr_bitwidth_dl: 9                                            # Downlink IQ samples bitwidth after compression.
  compr_method_prach: bfp                                         # PRACH compression method.
  compr_bitwidth_prach: 9                                         # PRACH IQ samples bitwidth after compression.
  enable_ul_static_compr_hdr: true                                # Configures if the compression header is present for uplink User-Plane messages (false) or not present (true).
  enable_dl_static_compr_hdr: true                                # Configures if the compression header is present for downlink User-Plane messages (false) or not present (true).
  iq_scaling: 10                                                  # IQ samples scaling factor applied before compression, should be a positive value smaller than 10.
  cells:
    - network_interface: 0000:01:00.1 # Ethernet interface name used to communicate with the RU.
      ru_mac_addr: 70:b3:d5:e1:5c:ce                              # RU MAC address.
      du_mac_addr: 90:e3:ba:00:12:32                              # DU MAC address.
      vlan_tag_cp: 1                                              # VLAN tag value for C-Plane.
      vlan_tag_up: 1                                              # VLAN tag value for U-Plane.
      prach_port_id: [4, 5]                                       # PRACH eAxC port value.
      dl_port_id: [0, 1, 2, 3]                                    # Downlink eAxC port values.
      ul_port_id: [0, 1]                                          # Uplink eAxC port values.
```

I also have the VLAN ports and MAC address configure on the RU to point to the ethernet nic of the DU:

```
LOG_INFO "Disable transmission during radio initialisation"
/usr/bin/registercontrol -w 0xc0300 -x 0x0

LOG_INFO "Set expected DU MAC Address for C-Plane Traffic (C0319/C031A)"
/usr/bin/registercontrol -w C031A -x 0x90e3
/usr/bin/registercontrol -w C0319 -x 0xba001232

LOG_INFO "Set expected DU MAC Address for U-Plane Traffic (C0315/C0316)"
/usr/bin/registercontrol -w C0316 -x 0x90e3
/usr/bin/registercontrol -w C0315 -x 0xba001232

LOG_INFO "Set required DU VLAN Tag Control Information for uplink U-Plane Traffic (C0318)"
/usr/bin/registercontrol -w C0318 -x 0x1

LOG_INFO "Set expected DU VLAN Tag Control Information for downlink U-Plane Traffic (C0330)"
/usr/bin/registercontrol -w C0330 -x 0x1

LOG_INFO "Set expected DU VLAN Tag Control Information for downlink C-Plane Traffic (C0331)"
/usr/bin/registercontrol -w C0331 -x 0x1

LOG_INFO "Aligning FPGA uplink timing to arrival of uplink frame(C0303)"
/usr/bin/registercontrol -w c0303 -x 0x20E
```

Can you give me any further insight into how I may be misconfiguring these. Any help is greatly appreciated.
