### DISCUSSION TITLE
UE cannot ping when using CU-DU split

### DISCUSSION THREAD

**Discussion by HaoxinSEU** [srsran/srsRAN_Project#707] [General Help] [answered]
Hi community,

Thank you for the support on F1 interface and CU&DU split!

We are trying to test it with our setup. We successfully launched both CU and DU, and they seemed to be connected to each other. Our phone can connect to the DU, and shows the 5G logo. However, our phone does not have Internet connection (e.g., cannot ping).

The logs on Open5GS AMF and SMF do not show any errors, and the console output of CU and DU looks also fine, as DU console even shows some traffic.

Does anyone have some ideas what the problem can be? Thank you very much!

Here is our test:
CU configuration:
```                     
gnb_id: 531                    
gnb_id_bit_length:            
ran_node_name: cu_cp_01 

slicing:                          
  -                                
    sst: 1                        
    sd: 0                              

amf:
  addr: open5gs-amf-ngap.open5gs
  bind_addr: 10.42.1.75

cu_cp:
  inactivity_timer: 7200
  plmns: "00103"
  tacs: "1"
  f1ap:
    bind_addr: 10.42.1.75                 # Optional TEXT (127.0.10.1). Sets the bind address used by the F1-C interface.

log:
  filename: /tmp/cu.log
  all_level: debug
```
DU configuration:
```                                   
gnb_id: 531
gnb_id_bit_length:

f1ap:
  cu_cp_addr: 10.42.1.75
  bind_addr: 10.42.1.115

nru:                             
  queue_size: 2048                 
  bind_addr: 10.42.1.115

ru_sdr:
  device_driver: uhd
  device_args: 
  srate: 23.04
  otw_format: sc12
  tx_gain: 80
  rx_gain: 40

cell_cfg:
  dl_arfcn: 640000
  band: 78
  channel_bandwidth_MHz: 20
  common_scs: 30
  plmn: "00103"
  tac: 1
  pci: 1

log:
  filename: /tmp/du.log
  all_level: debug
```
CU console output:
```
--== srsRAN CU (commit 4e8dec77c) ==--

N2: Connection to AMF on open5gs-amf-ngap.open5gs:38412 completed
F1-C: Listening for new connections on 10.42.1.75:38471...
==== CU started ===
Type <h> to view help
```
DU console output:
```
--== srsRAN DU (commit 4e8dec77c) ==--


The PRACH detector will not meet the performance requirements with the configuration {Format B4, ZCZ 0, SCS 30kHz, Rx ports 1}.
Lower PHY in quad executor mode.
Cell pci=1, bw=20 MHz, 1T1R, dl_arfcn=640000 (n78), dl_freq=3600.0 MHz, dl_ssb_arfcn=639648, ul_freq=3600.0 MHz

==== DU started ===
Type <h> to view help
Late: 30; Underflow: 106; Overflow: 1;
t

          |--------------------DL---------------------|-------------------------UL------------------------------
 pci rnti | cqi  ri  mcs  brate   ok  nok  (%)  dl_bs | pusch  rsrp  mcs  brate   ok  nok  (%)    bsr     ta  phr
   1 4602 |  15 1.0   18   5.9k    8    0   0%      3 |  29.2 -15.5   25    25k    6    0   0%      0   512n   11
   1 4602 |  15 1.0   27   8.8k   12    0   0%      0 |  28.4 -17.4   28    39k    8    0   0%      0   732n   11
   1 4602 |  15 1.0   27   3.3k    5    0   0%      0 |  17.6 -28.0   26    17k    3    2  40%      0     1u    6
   1 4602 |  15 1.0   27    672    1    0   0%      0 |   n/a   n/a    0      0    0    0   0%      0   260n    6
```

**Comment by pgawlowicz** [comment]
can the UE ping core network? did you enable IP forwarding on the PC running open5gs?

**Reply by HaoxinSEU** [reply]
Hi Piotr,

The UE cannot ping UPF (10.45.0.1). And IP forwarding should be fine. Because if we use the monolithic gNB, then the UE can connect and ping.

Thanks!

**Reply by HaoxinSEU** [reply]
We run tcpdump on the `ogstun` interface in UPF, and no traffic is captured. But if we directly run the monolithic gNB, we can see the traffic on this interface.

So we are wondering if we configure the user plane of CU/DU wrongly, then the traffic cannot reach UPF?

**Reply by herlesupreeth** [reply]
@HaoxinSEU Please send the configuration files of 5GC, all logs at info level, F1Ap, NGAP and RLC pcap

**Reply by HaoxinSEU** [reply]
Hi @herlesupreeth,

Thanks for your reply!

Here are the logs and pcaps of CU and DU, and also the configuration for UPF, SMF and AMF.

[open5gs_config.zip](https://github.com/user-attachments/files/16109315/open5gs_config.zip)
[logs_and_pcap.zip](https://github.com/user-attachments/files/16109319/logs_and_pcap.zip)

**Reply by HaoxinSEU** [reply]
Some updates:

We tried to ping from UPF to UE, and use `tcpdump udp` on DU, we can see some packets:
```
12:02:41.659888 IP 127.0.10.1.2152 > srs-du.2152: UDP, length 107
12:02:42.684916 IP 127.0.10.1.2152 > srs-du.2152: UDP, length 107
12:02:43.707886 IP 127.0.10.1.2152 > srs-du.2152: UDP, length 107
12:02:44.731879 IP 127.0.10.1.2152 > srs-du.2152: UDP, length 107
12:02:45.756905 IP 127.0.10.1.2152 > srs-du.2152: UDP, length 107
```
Where the source IP `127.0.10.1` is the default `bind_addr` for CU, and not the correct bind IP for our network. In our setup, the CU has IP `10.42.1.75`, which is used as the `bind_addr` for `f1ap` and `amf`. Therefore, we also add this field into the CU configuration:
```
cu_up: 
  nru:                                 
    bind_addr: 10.42.1.75   
```
But then, we get an error when running the CU:
```
--== srsRAN CU (commit 4e8dec77c) ==--

N2: Connection to AMF on open5gs-amf-ngap.open5gs:38412 completed
F1-C: Listening for new connections on 10.42.1.75:38471...
Failed to bind UDP socket to 10.42.1.75:2152. Address already in use
srsRAN ERROR: Unable to allocate the required NG-U network resources
```
We are wondering if the `bind_addr` of f1ap and nru cannot be the same?

**Reply by herlesupreeth** [reply]
> srsRAN ERROR: Unable to allocate the required NG-U network resources

Thats because NR-U interface on CU also uses port 2152 (standard and cannot be changed). And, I think you are running open5gs on the same machine, in this case UPF would also be binding to port 2152.

You would have to run open5gs or atleast the UPF on another machine or bind on different address/interface

**Reply by herlesupreeth** [reply]
btw, I didnt find any issues in the logs you posted above except that I dont see any traffic being pushed to the gNB

**Reply by improperaffo** [reply, marked as answer]
I don't think the problem is the UPF, @HaoxinSEU is using Kubernetes. So the UPF and the CU are in different pods and will bind to different interfaces.

The issue seems to be that the CU is using the same port (2152) for binding to both the NG-U and F1-U virtual interface, as the pod only has one interface (eth0) they conflict with each other. 

It might be good to use two different ports for NG-U and F1-U connections, or to being able to choose the F1-U port in the config.

**Reply by herlesupreeth** [reply]
> The issue seems to be that the CU is using the same port (2152) for binding to both the NG-U and F1-U

You are right.

> It might be good to use two different ports for NG-U and F1-U connections

Usage of 2152 is as per spec so I dont think we can use any other port

One thing, which can be done is to have two different address for same interface and use as follows

```
amf:
  addr: open5gs-amf-ngap.open5gs
  bind_addr: 10.42.1.76

cu_cp:
  f1ap:
    bind_addr: 10.42.1.75
```
