### DISCUSSION TITLE
Handover between 2 DUs when using CU-DU split

### DISCUSSION THREAD

**Discussion by HaoxinSEU** [srsran/srsRAN_Project#715] [General Help] [answered]
Hi community,

We are trying to trigger handover between 2 DUs in the CU-DU split setup.

Our setup is like: one CU connects to two DUs, and each DU is connecting to its own SDR, and with `pci` 1 and 2 respectively.

If we trigger the handover from the CU console, i.e., by running `ho 1 4601 2`, we can see that the UE is indeed pushed to the other DU. And in the log we can see 
```
[CU-CP   ] [I] ue=2: Trigger inter DU handover from source_du=1 to target_du=0
```
However, we cannot make the handover work by measurement. In the RRC message, we see that the UE only reports the serving cell measurements, but nothing for the neighboring cells. So if we change the SDR gain to make the neighboring cell's signal very strong, the UE just disconnects from the original cell, and reconnects to the neighbor, as there is no logs about handover in CU.

We are wondering what could be the issue for this? Thank you for your help!

Here are the configurations for the CU and two DUs:

CU:
```
gnb_id: 531                       
gnb_id_bit_length: 32              
ran_node_name: cu_cp_01     

slicing:                           
  -                                   
    sst: 1                               
    sd: 0                              

amf: 
  addr: open5gs-amf-ngap.open5gs
  bind_addr: 10.42.1.75

cu_cp:
  inactivity_timer: 7200     
  plmns: "00103"
  tacs: "1"           
 
  mobility:
    trigger_handover_from_measurements: true  
    cells:                                    
      - nr_cell_id: 0x2130                
        periodic_report_cfg_id: 1            
        ncells:                               
          - nr_cell_id: 0x2131                 
            report_configs: [ 2 ]                
      - nr_cell_id: 0x2131                    
        periodic_report_cfg_id: 1            
        ncells:                             
          - nr_cell_id: 0x2130                  
            report_configs: [ 2 ]               
    report_configs:                           
      - report_cfg_id: 1                      
        report_type: periodical               
        report_interval_ms: 480                 
      - report_cfg_id: 2                        
        report_type: event_triggered            
        a3_report_type: rsrp                    
        a3_offset_db: 2                      
        a3_hysteresis_db: 0                     
        a3_time_to_trigger_ms: 100             
  f1ap: 
    bind_addr: 10.42.1.75               
   
cu_up: 
  nru:                               
    bind_addr: 10.42.1.75               
    udp_max_rx_msgs: 256                  

log:
  filename: /tmp/cu.log
  all_level: debug
```
DU1:
```
gnb_id: 531
gnb_id_bit_length: 32
gnb_du_id: 0

f1ap:
  cu_cp_addr: 10.42.1.75
  bind_addr: 10.42.1.115

nru:                                # Interface between CU and CU-UP
  queue_size: 2048                      # Optional INT (2048). Sets the F1-U PDU queue size in bytes. 
  bind_addr: 10.42.1.115

ru_sdr:
  device_driver: bladerf
  device_args: "rx_gain=manual"
  # clock:
  # sync:
  srate: 23.04
  otw_format: sc16
  tx_gain: 66
  rx_gain: 15

cell_cfg:
  dl_arfcn: 640000
  band: 78
  channel_bandwidth_MHz: 20
  common_scs: 30
  plmn: "00103"
  tac: 1
  pci: 1

log:
  filename: /tmp/du.log
  all_level: info

```
DU2:
```
gnb_id: 531
gnb_id_bit_length: 32
gnb_du_id: 1

f1ap:
  cu_cp_addr: 10.42.1.75
  bind_addr: 10.42.0.182

nru:                            
  queue_size: 2048                   
  bind_addr: 10.42.0.182

ru_sdr:
  device_driver: uhd
  device_args: type=b200,num_recv_frames=64,num_send_frames=64
  srate: 23.04
  otw_format: sc12
  tx_gain: 80
  rx_gain: 40

cell_cfg:
  dl_arfcn: 640000
  band: 78
  channel_bandwidth_MHz: 20
  common_scs: 30
  plmn: "00103"
  tac: 1
  pci: 2

log:
  filename: /tmp/du.log
  all_level: debug
```

**Comment by FabianEckermann** [comment]
Hi @HaoxinSEU,
can you provide logs and PCAPs for this?
See https://docs.srsran.com/projects/project/en/latest/user_manuals/source/outputs.html on how to enable them.

**Reply by HaoxinSEU** [reply]
Hi Fabian,

Thank you for your reply! Here is the logs and pcaps on both the CU and two DUs.

Thanks,
Haoxin

[logs_and_pcap.zip](https://github.com/user-attachments/files/16131192/logs_and_pcap.zip)

**Reply by FabianEckermann** [reply]
In the logs I can see, that you connect DU2 after the UE was attached to DU1. Can you try to connect both DUs before attaching the UE?

**Reply by HaoxinSEU** [reply]
Hi Fabian,

Thank you for the hint. We tried to launch both DUs first, then connect the UE. The result is the same as before, and the UE does not do handover...

Here are the logs and pcaps.
[logs_and_pcap_launch_all.zip](https://github.com/user-attachments/files/16131413/logs_and_pcap_launch_all.zip)

**Reply by HaoxinSEU** [reply]
We notice one potential issue here.

In our setup, we set `nr_cell_id` to be `gnb_id` (HEX) concatenated with 0 or 1. So that CU can consider that both DUs are managed by itself. Then in the `mobility` configuration, we don't specify fields such as `ssb_arfcn`, `ssb_period`...  But then we see in the CU log, the configured cell seems to be incomplete for DU2:
```
2024-07-09T07:43:18.881526 [CU-CP   ] [D] Measurement objects:
2024-07-09T07:43:18.881527 [CU-CP   ] [D]  - ssb_freq=639648: ssb_freq=639648 ssb_scs=30kHz smtc1: periodicity=10 offset=0 dur=5
2024-07-09T07:43:18.881527 [CU-CP   ] [D] Configured cells:
2024-07-09T07:43:18.881528 [CU-CP   ] [D]  - nci=0x2130 complete=yes gnb_id=531 pci=1 band=78 ssb_arfcn=639648 ssb_scs=30kHz ncells=[ 0x2131 ]
2024-07-09T07:43:18.881529 [CU-CP   ] [D]  - nci=0x2131 complete=no gnb_id=0 pci=? band=? ssb_arfcn=? ssb_scs=? ncells=[ 0x2130 ]
```

But if we add these fields back, but the CU cannot run, and gives the error:
```
--== srsRAN CU (commit 4e8dec77c) ==--

cell=0x2131: For cells managed by the CU-CP the gnb_id_bit_length, pci, band, ssb_arfcn, ssb_scs, ssb_period, ssb_offset and ssb_duration must not be configured in the mobility config
srsRAN ERROR: Invalid configuration detected.
```

So we are wondering if these fields can cause some problems?

**Reply by HaoxinSEU** [reply]
Hi Fabian,

And also, we see that in the RRC message, `reportConfigToAddModList` only contains `report_cfg_id: 1`, but the second part `report_cfg_id: 2` is missing in the message.... Do you think this could also be a problem? Thank you so much! :) 
```
"reportConfigToAddModList": [
                    {
                      "reportConfigId": 1,
                      "reportConfig": {
                        "reportConfigNR": {
                          "reportType": {
                            "periodical": {
                              "rsType": "ssb",
                              "reportInterval": "ms480",
                              "reportAmount": "infinity",
                              "reportQuantityCell": {
                                "rsrp": true,
                                "rsrq": true,
                                "sinr": true
                              },
                              "maxReportCells": 4,
                              "reportQuantityRS-Indexes": {
                                "rsrp": true,
                                "rsrq": true,
                                "sinr": true
                              },
                              "maxNrofRS-IndexesToReport": 4,
                              "includeBeamMeasurements": true,
                              "useAllowedCellList": false
                            }
                          }
                        }
                      }
                    }
                  ],
```

**Reply by FabianEckermann** [reply]
Hi @HaoxinSEU,
we found the issue and fixed it. It will soon be in the main branch

**Reply by HaoxinSEU** [reply]
Hi Fabian,

Thanks for the reply! Look forward to the fix. :)

Best,
Haoxin

**Comment by abcd11abcd** [comment]
Is this problem fixed? I'm also facing the same issue for handovers.

**Reply by FabianEckermann** [reply, marked as answer]
This should be fixed now. You will need to set different `secor_id`s for the cells in the DU config.

**Reply by HaoxinSEU** [reply]
Thanks for your help! @FabianEckermann

**Reply by shench17** [reply]
Is this problem fixed? I'm also facing the same issue for handovers. My UE also reports nothing for the neighboring cells, Could you kindly provide the latest configuration files for CU and two DUs? @HaoxinSEU

**Comment by fllay** [comment]
I tried the new release. It seems to be ok. One thing from `cu.log`, sometime I got

```
2024-08-01T06:18:52.843539 [CU-CP   ] [D]  - ssb_freq=632256: ssb_freq=632256 ssb_scs=30kHz smtc1: periodicity=10 offset=0 dur=5
2024-08-01T06:18:52.843540 [CU-CP   ] [D] Configured cells:
2024-08-01T06:18:52.843541 [CU-CP   ] [D]  - nci=0x2130 complete=yes gnb_id=531 pci=1 band=78 ssb_arfcn=632256 ssb_scs=30kHz ncells=[ 0x2131 ]
2024-08-01T06:18:52.843542 [CU-CP   ] [D]  - nci=0x2131 complete=yes gnb_id=531 pci=2 band=78 ssb_arfcn=632256 ssb_scs=30kHz ncells=[ 0x2130 ]
```

and I also got

```
2024-08-01T06:12:59.554670 [CU-CP   ] [D] Measurement objects:
2024-08-01T06:12:59.554671 [CU-CP   ] [D]  - ssb_freq=632256: ssb_freq=632256 ssb_scs=30kHz smtc1: periodicity=10 offset=0 dur=5
2024-08-01T06:12:59.554672 [CU-CP   ] [D] Configured cells:
2024-08-01T06:12:59.554673 [CU-CP   ] [D]  - nci=0x2130 complete=yes gnb_id=531 pci=1 band=78 ssb_arfcn=632256 ssb_scs=30kHz ncells=[ 0x2131 ]
2024-08-01T06:12:59.554673 [CU-CP   ] [D]  - nci=0x2131 complete=no gnb_id=531 pci=? band=? ssb_arfcn=? ssb_scs=? ncells=[ 0x2130 ]
```

Is this normal?  I set two DU (B210) about 5 meters apart and set TX power gain about 50 dB and walk with a phone back and forth.

This is the config files

CU

```
gnb_id: 531                       
gnb_id_bit_length: 32              
ran_node_name: cu_cp_01     

#slicing:                           
#  -                                   
#    sst: 1                               
#    sd: 0                              

amf: 
  addr:  192.168.68.42
  bind_addr: 192.168.68.211

cu_cp:
  inactivity_timer: 7200     
  plmns: "00101"
  tacs: "7"           
 
  mobility:
    trigger_handover_from_measurements: true  
    cells:                                    
      - nr_cell_id: 0x2130                
        periodic_report_cfg_id: 1            
        ncells:                               
          - nr_cell_id: 0x2131                 
            report_configs: [ 2 ]                
      - nr_cell_id: 0x2131                    
        periodic_report_cfg_id: 1            
        ncells:                             
          - nr_cell_id: 0x2130                  
            report_configs: [ 2 ]               
    report_configs:                           
      - report_cfg_id: 1                      
        report_type: periodical               
        report_interval_ms: 480                 
      - report_cfg_id: 2                        
        report_type: event_triggered            
        a3_report_type: rsrp                    
        a3_offset_db: 2                      
        a3_hysteresis_db: 0                     
        a3_time_to_trigger_ms: 100             
  f1ap: 
    bind_addr: 192.168.68.211


#cu_up:
#  nru:
#    bind_addr: 192.168.68.211


log:
  filename: /tmp/cu.log
  all_level: debug


pcap:
  ngap_enable: false
  ngap_filename: /tmp/cu_ngap.pcap
```

DU1

```
gnb_id: 531
gnb_id_bit_length: 32
gnb_du_id: 0

f1ap:
  cu_cp_addr: 192.168.68.211
  bind_addr: 192.168.68.29
nru:
  bind_addr: 192.168.68.29

ru_sdr:
  device_driver: uhd
  device_args: type=b200,num_recv_frames=64,num_send_frames=64
  srate: 23.04
  otw_format: sc12  
  tx_gain: 50
  rx_gain: 40


cell_cfg:
  dl_arfcn: 632628                                                # ARFCN of the downlink carrier>
  band: 78                                                        # The NR band.
  channel_bandwidth_MHz: 20                                       # Bandwith in MHz. Number of PR>
  common_scs: 30                                                  # Subcarrier spacing in kHz use>
  plmn: "00101"                                                   # PLMN broadcasted by the gNB.
  tac: 7                                                          # Tracking area code (needs to >
  pci: 1                                                          # Physical cell ID.
  nof_antennas_dl: 1
  nof_antennas_ul: 1
  sector_id: 0
  pdsch:
    mcs_table: qam256

log:
  filename: /tmp/du.log
  all_level: warning

pcap:
  mac_enable: false
  mac_filename: /tmp/du_mac.pcap
  f1ap_enable: false
  f1ap_filename: /tmp/du_f1ap.pcap
  f1u_enable: false
  f1u_filename: /tmp/du_f1u.pcap
```


DU2

```
gnb_id: 531
gnb_id_bit_length: 32
gnb_du_id: 1

f1ap:
  cu_cp_addr: 192.168.68.211
  bind_addr: 192.168.68.152
nru:
  bind_addr: 192.168.68.152

ru_sdr:
  device_driver: uhd
  device_args: type=b200,num_recv_frames=64,num_send_frames=64
  srate: 23.04
  otw_format: sc12
  tx_gain: 50
  rx_gain: 40


cell_cfg:
  dl_arfcn: 632628                                                # ARFCN of the downlink carrier>
  band: 78                                                        # The NR band.
  channel_bandwidth_MHz: 20                                       # Bandwith in MHz. Number of PR>
  common_scs: 30                                                  # Subcarrier spacing in kHz use>
  plmn: "00101"                                                   # PLMN broadcasted by the gNB.
  tac: 7                                                          # Tracking area code (needs to >
  pci: 2                                                          # Physical cell ID.
  nof_antennas_dl: 1
  nof_antennas_ul: 1
  sector_id: 1
  pdsch:
    mcs_table: qam256

log:
  filename: /tmp/du.log
  all_level: warning

pcap:
  mac_enable: false
  mac_filename: /tmp/du_mac.pcap
  f1ap_enable: false
  f1ap_filename: /tmp/du_f1ap.pcap
  f1u_enable: false
  f1u_filename: /tmp/du_f1u.pcap
```

and It seems to do measurement for both cells

```
"reportConfigToAddModList": [
                    {
                      "reportConfigId": 1,
                      "reportConfig": {
                        "reportConfigNR": {
                          "reportType": {
                            "periodical": {
                              "rsType": "ssb",
                              "reportInterval": "ms480",
                              "reportAmount": "infinity",
                              "reportQuantityCell": {
                                "rsrp": true,
                                "rsrq": true,
                                "sinr": true
                              },
                              "maxReportCells": 4,
                              "reportQuantityRS-Indexes": {
                                "rsrp": true,
                                "rsrq": true,
                                "sinr": true
                              },
                              "maxNrofRS-IndexesToReport": 4,
                              "includeBeamMeasurements": true,
                              "useAllowedCellList": false
                            }
                          }
                        }
                      }
                    },
                    {
                      "reportConfigId": 2,
                      "reportConfig": {
                        "reportConfigNR": {
                          "reportType": {
                            "eventTriggered": {
                              "eventId": {
                                "eventA3": {
                                  "a3-Offset": {
                                    "rsrp": 2
                                  },
                                  "reportOnLeave": false,
                                  "hysteresis": 0,
                                  "timeToTrigger": "ms100",
                                  "useAllowedCellList": false
                                }
                              },
                              "rsType": "ssb",
                              "reportInterval": "ms1024",
                              "reportAmount": "infinity",
                              "reportQuantityCell": {
                                "rsrp": true,
                                "rsrq": true,
                                "sinr": true
                              },
                              "maxReportCells": 4,
                              "reportQuantityRS-Indexes": {
                                "rsrp": true,
                                "rsrq": true,
                                "sinr": true
                              },
                              "includeBeamMeasurements": false
                            }
                          }
                        }
                      }
                    }
                  ],
```
