### DISCUSSION TITLE
UE does not connect to the network

### DISCUSSION THREAD

**Discussion by merimdzaferagic** [srsran/srsRAN_Project#716] [General Help] [answered]
I am trying to get the srsRAN Project set up with the Benetel RU650. I am using a server with: 
```
  Model name:            Intel(R) Xeon(R) Gold 6338N CPU @ 2.20GHz
    CPU family:          6
    Model:               106
    Thread(s) per core:  2
    Core(s) per socket:  32
    Socket(s):           2
    Stepping:            6
    CPU max MHz:         3500.0000
    CPU min MHz:         800.0000
```
I am using the following config files: 

DU:
```
# This example configuration outlines how to configure the srsRAN Project CU/DU to use an O-RU and split 7.2. This is specifically for use
# with the Benetel R550 RU. This config will create a single TDD MIMO cell transmitting in band 78, with 20 MHz bandwidth and 30 kHz sub-carrier-spacing.
# The parameters used to configure the RU are found in the `ru_ofh` sub-section. This configuration makes used of the OFH Lib from SRS to enable split 7.2.
gnb_id: 1
amf:
  addr: 127.0.0.7                                               # The address or hostname of the AMF.
  bind_addr: 127.0.0.1                                            # A local IP that the gNB binds to for traffic from the AMF.

ru_ofh:
  t1a_max_cp_dl: 500                                              # Maximum T1a on Control-Plane for Downlink in microseconds.
  t1a_min_cp_dl: 450                                              # Minimum T1a on Control-Plane for Downlink in microseconds.
  t1a_max_cp_ul: 350                                              # Maximum T1a on Control-Plane for Uplink in microseconds.
  t1a_min_cp_ul: 290                                              # Minimum T1a on Control-Plane for Uplink in microseconds.
  t1a_max_up: 360                                                 # Maximum T1a on User-Plane in microseconds.
  t1a_min_up: 300                                                 # Minimum T1a on User-Plane in microseconds.
  ta4_max: 560                                                    # Maximum Ta4 on User-Plane in microseconds.
  ta4_min: 0                                                      # Minimum Ta4 on User-Plane in microseconds.
  is_prach_cp_enabled: true                                      # Configures if Control-Plane messages should be used to receive PRACH messages.
  compr_method_ul: bfp                                            # Uplink compression method.
  compr_bitwidth_ul: 9                                            # Uplink IQ samples bitwidth after compression.
  compr_method_dl: bfp                                            # Downlink compression method.
  compr_bitwidth_dl: 9                                            # Downlink IQ samples bitwidth after compression.
  compr_method_prach: bfp                                         # PRACH compression method.
  compr_bitwidth_prach: 9                                         # PRACH IQ samples bitwidth after compression.
  enable_ul_static_compr_hdr: false                                # Configures if the compression header is present for uplink User-Plane messages (false) or not present (true).
  enable_dl_static_compr_hdr: false                                # Configures if the compression header is present for downlink User-Plane messages (false) or not present (true).
  iq_scaling: 6.5                                                 # IQ samples scaling factor applied before compression, should be a positive value smaller than 10.
  cells:
  - network_interface: ens4f0                                   # Ethernet interface name used to communicate with the RU.
    ru_mac_addr: 70:b3:d5:e1:54:2f                                # RU MAC address.
    du_mac_addr: 40:a6:b7:3f:85:3c                                # DU MAC address.
    vlan_tag_cp: 5                                                # VLAN tag value for C-Plane.
    vlan_tag_up: 5                                                # VLAN tag value for U-Plane.
    prach_port_id: [4,5]                                          # PRACH eAxC port value.
    dl_port_id: [0,1]                                             # Downlink eAxC port values.
    ul_port_id: [0,1]                                             # Uplink eAxC port values.

cell_cfg:
  dl_arfcn: 660000                                                # ARFCN of the downlink carrier (center frequency).
  band: 77                                                        # The NR band.
  channel_bandwidth_MHz: 20                                       # Bandwith in MHz. Number of PRBs will be automatically derived.
  common_scs: 30                                                  # Subcarrier spacing in kHz used for data.
  plmn: "99940"                                                   # PLMN broadcasted by the gNB.
  tac: 7                                                          # Tracking area code (needs to match the core configuration).
  pci: 1                                                          # Physical cell ID.
  nof_antennas_dl: 2
  nof_antennas_ul: 2
  prach:
    prach_config_index: 159                                       # PRACH configuration index.
    prach_root_sequence_index: 1                                  # PRACH root sequence index.
    zero_correlation_zone: 0                                      # Zero correlation zone.
    prach_frequency_start: 2                                      # Offset in PRBs of lowest PRACH transmission occasion in frequency domain respective to PRB 0.
    preamble_trans_max: 50
    power_ramping_step_db: 4
  tdd_ul_dl_cfg:
    dl_ul_tx_period: 10                                           # Optional INT (10). Sets the TDD pattern periodicity in slots. The combination of this value and the chosen numerology must lead to a TDD periodicity of 0.5, >
    nof_dl_slots: 7                                               # Optional INT (6). Number of consecutive full Downlink slots. Supported: [0-80].
    nof_dl_symbols: 6                                             # Optional INT (0). Number of Downlink symbols at the beginning of the slot following full Downlink slots. Supported: [0-13].
    nof_ul_slots: 2                                               # Optional INT (3). Number of consecutive full Uplink slots. Supported: [0 - 80].
    nof_ul_symbols: 4
  ssb:
    ssb_block_power_dbm: -20
  pdsch:
    mcs_table: qam256
  pusch:
    p0_nominal_with_grant: -76
log:
  filename: /tmp/gnb.log                                          # Path of the log file.
  all_level: info
  phy_level: debug

pcap:
  mac_enable: false                                               # Set to true to enable MAC-layer PCAPs.
  mac_filename: /tmp/gnb_mac.pcap                                 # Path where the MAC PCAP is stored.
  ngap_enable: false                                              # Set to true to enable NGAP PCAPs.
  ngap_filename: /tmp/gnb_ngap.pcap                               # Path where the NGAP PCAP is stored.
```

I am also using the following RU config: 
```
# Config file for Benetel RANx50 radio units
# Please place this file in /etc

# MIMO mode - the radio can operate in 1_3, 2_4, 1_2_3_4_4x2 or 1_2_3_4_4x4 mode
# Variable name : mimo_mode
# Valid options : 1_3
#                 2_4
#                 1_2_3_4_4x2
#                 1_2_3_4_4x4
mimo_mode=1_3

# FPGA downlink scaling in steps of 6 dB (0, 6, 12 and 18 can be set)
# Variable name : downlink_scaling
# Valid options : 0
#                 6
#                 12
#                 18
downlink_scaling=6

# PRACH format
# Variable name : prach_format
# Valid options : short
#                 long
prach_format=short

# Short form PRACH compression settings (note uncompressed mode is not supported when RU is in 4x2 or 4x4 mode)
# Variable name : compression
# Valid options : static_uncompressed
#                 dynamic_uncompressed
#                 static_compressed
#                 dynamic_compressed
compression=dynamic_compressed

# Long form PRACH compression settings
# Variable name : lf_prach_compression_enable
# Valid options : true
#                 false
lf_prach_compression_enable=true

# C-Plane per-symbol workaround
# Variable name : cplane_per_symbol_workaround
# Valid options : enabled
#                 disabled
cplane_per_symbol_workaround=disabled


# CUPLANE dl couplling sectionID
# Variable name : cuplane_dl_coupling_sectionI
# Valid options : enabled
#                 disabled
cuplane_dl_coupling_sectionID=disabled

# FlexRAN PRACH workaround
# Variable name : flexran_prach_workaround
# Valid options : enabled
#                 disabled
flexran_prach_workaround=disabled

#DL_UL special slot tunning
#Variable name : dl_ul_tuning_special_slot
#Valid options : 0x0
#                0xfd00000
#dl_ul_tuning_special_slot=0xfd00000
dl_tuning_special_slot=0x13b6
```

And the tdd.xml is as follows:
```
<xml>
    <tdd-config version="1.0">
            <description>DDDDDDDSUU</description>
                        <pattern index="1">
                                <slots>DDDD</slots>
                                <numerology>1</numerology>
                                <periodicity>2</periodicity>
                                <special-slot-symbols></special-slot-symbols>
                        </pattern>
                        <pattern index="2">
                                <slots>DDDSUU</slots>
                                <numerology>1</numerology>
                                <periodicity>3</periodicity>
                                <special-slot-symbols>DDDDDDGGGGUUUU</special-slot-symbols>
                        </pattern>
    </tdd-config>
</xml>
```

The DU and RU are both synced over PTP: 
- DU sync screenshot:
<img width="965" alt="Screenshot 2024-07-09 at 13 23 12" src="https://github.com/srsran/srsRAN_Project/assets/27142644/3c40648f-9d90-4cef-b243-ea4939f2abdc">

- RU sync screenshot: 
<img width="1332" alt="Screenshot 2024-07-09 at 13 24 23" src="https://github.com/srsran/srsRAN_Project/assets/27142644/43dd31df-eb0d-4162-b30b-fa8c567b752c">

On the RU side, from kpi.sh I can see the following:
```
 SAMPLE_TIME          | RX_TOTAL             | RX_ON_TIME           | RX_EARLY             | RX_LATE              | RX_ON_TIME_C         | RX_EARLY_C           | RX_LATE_C            | TX_TOTAL
 12:25:28.109514      | 45072                | 41669                | -0                   | -0                   | 3410                 | -0                   | -0                   | -0
 12:25:29.104640      | 45010                | 41549                | -0                   | -0                   | 3394                 | -0                   | -0                   | -0
 12:25:30.101207      | 45042                | 41564                | -0                   | -0                   | 3388                 | -0                   | -0                   | -0
 12:25:31.103105      | 45041                | 41636                | -0                   | -0                   | 3408                 | -0                   | -0                   | -0
 12:25:32.101820      | 45042                | 41600                | -0                   | -0                   | 3402                 | -0                   | -0                   | -0
 12:25:33.101903      | 45041                | 41596                | -0                   | -0                   | 3392                 | -0                   | -0                   | -0
```

I am attaching the gnb.log. It does not show any lates. However, the phone still does not see the network. The same phone connects to the same configu (just adjusted to the usrp setup). A few things that I have noticed are the following: 
```
root@benetelru:~# TXMeanPower
TX 1 TSSI: 40.8938 dBm
TX 2 TSSI: -inf dBm
TX 3 TSSI: 15.5117 dBm
TX 4 TSSI: -inf dBm
```

```
root@benetelru:~# RXMeanPower
RX 1 RSSI: No signal dBm
RX 2 RSSI: No signal dBm
RX 3 RSSI: No signal dBm
RX 4 RSSI: No signal dBm
```

And the dpd stats:
```
root@benetelru:~# oru_dpd_stats
Timestamp = 2024-07-09T12:28:35Report DPD status

--------------------
TX1
ExtPathDelay.fifoDelay : 157
ExtPathDelay.interpolationIndex : 8

dpdErrorCode: 13318
dpdPercentComplete: 0
dpdPerformanceMetric: 0
dpdIterCount: 475
dpdUpdateCount: 5
dpdSyncStatus: 1
dpdModelTable: 0
dpdMeanTuPower: -12.036348
dpdPeakTuPower: -4.432714
dpdMeanTxPower: -7.570714
dpdPeakTxPower: 0.491848
dpdMeanOrxPower: -10.462380
dpdPeakOrxPower: 3.010300
dpdDirectEvm: 1.735963
dpdIndirectEvm: 1.164708
dpdSelectError: 0.246680
dpdIndirectError: 0.218804
dpdErrorStatus0 (metrics:actions): 192:0
dpdErrorStatus1 (metrics:actions): 192:0
dpdPersistentErrorStatus0 (metrics:actions): 0:0
dpdPersistentErrorStatus1 (metrics:actions): 0:0
reservedPM: 3542030
reservedTP: 3708961
reservedPR: 3708961
--------------------

--------------------
TX2
ExtPathDelay.fifoDelay : 0
ExtPathDelay.interpolationIndex : 0

dpdErrorCode: 0
dpdPercentComplete: 0
dpdPerformanceMetric: 0
dpdIterCount: 0
dpdUpdateCount: 0
dpdSyncStatus: 0
dpdModelTable: 0
dpdDirectEvm: 0.000000
dpdIndirectEvm: 0.000000
dpdSelectError: 0.000000
dpdIndirectError: 0.000000
dpdErrorStatus0 (metrics:actions): 0:0
dpdErrorStatus1 (metrics:actions): 0:0
dpdPersistentErrorStatus0 (metrics:actions): 0:0
dpdPersistentErrorStatus1 (metrics:actions): 0:0
reservedPM: 0
reservedTP: 0
reservedPR: 0
--------------------

--------------------
TX3
ExtPathDelay.fifoDelay : 156
ExtPathDelay.interpolationIndex : 13

dpdErrorCode: 13319
dpdPercentComplete: 0
dpdPerformanceMetric: 0
dpdIterCount: 461
dpdUpdateCount: 0
dpdSyncStatus: 1
dpdModelTable: 0
dpdMeanTuPower: -48.882384
dpdPeakTuPower: -23.407675
dpdMeanTxPower: -48.882384
dpdPeakTxPower: -23.407675
dpdMeanOrxPower: -38.808637
dpdPeakOrxPower: -18.092924
dpdDirectEvm: 1.548542
dpdIndirectEvm: 1.548542
dpdSelectError: 0.000000
dpdIndirectError: 0.000000
dpdErrorStatus0 (metrics:actions): 0:0
dpdErrorStatus1 (metrics:actions): 0:0
dpdPersistentErrorStatus0 (metrics:actions): 0:0
dpdPersistentErrorStatus1 (metrics:actions): 0:0
reservedPM: 144330
reservedTP: 63566
reservedPR: 548757
--------------------

--------------------
TX4
ExtPathDelay.fifoDelay : 0
ExtPathDelay.interpolationIndex : 0

dpdErrorCode: 0
dpdPercentComplete: 0
dpdPerformanceMetric: 0
dpdIterCount: 0
dpdUpdateCount: 0
dpdSyncStatus: 0
dpdModelTable: 0
dpdDirectEvm: 0.000000
dpdIndirectEvm: 0.000000
dpdSelectError: 0.000000
dpdIndirectError: 0.000000
dpdErrorStatus0 (metrics:actions): 0:0
dpdErrorStatus1 (metrics:actions): 0:0
dpdPersistentErrorStatus0 (metrics:actions): 0:0
dpdPersistentErrorStatus1 (metrics:actions): 0:0
reservedPM: 0
reservedTP: 0
reservedPR: 0
--------------------
```
[gnb.log](https://github.com/user-attachments/files/16143229/gnb.log)

**Comment by merimdzaferagic** [comment]
A small update. The UE is connecting to the network now. For now, it only works with 20MHz and 1 antenna in the uplink. I will work on it a bit more and post an update on the setup.

**Comment by merimdzaferagic** [comment, marked as answer]
The issue is now fixed. It was a stupid problem with the eaxc.xml files. They were previously modified for a different setup, and therefore the mapping was completely wrong. After I changed them back, the 2x2 setup with 20MHz works well. I am using a Nokia XR20 with sysmoUSIM. These Nokia phones only work with `99940` testing PLMN. I am using a Benetel RU650.

I am still not able to run the 100MHz config with 2x2. Seems to be an issue with the long PRACH configuration. If anyone has a suggestion, it would be helpful. 

I am attaching the configuration and the correct eaxc_1_2t.xml file below in case someone runs into similar issues. 

DU config file: 
```yaml
# This example configuration outlines how to configure the srsRAN Project CU/DU to use an O-RU and split 7.2. This is specifically for use
# with the Benetel R550 RU. This config will create a single TDD MIMO cell transmitting in band 78, with 20 MHz bandwidth and 30 kHz sub-carrier-spacing.
# The parameters used to configure the RU are found in the `ru_ofh` sub-section. This configuration makes used of the OFH Lib from SRS to enable split 7.2.
gnb_id: 1
amf:
  addr: 127.0.0.7                                               # The address or hostname of the AMF.
  bind_addr: 127.0.0.1                                            # A local IP that the gNB binds to for traffic from the AMF.

ru_ofh:
  t1a_max_cp_dl: 500
  t1a_min_cp_dl: 258
  t1a_max_cp_ul: 465
  t1a_min_cp_ul: 285
  t1a_max_up: 250
  t1a_min_up: 50
  ta4_max: 600                                                    # Maximum Ta4 on User-Plane in microseconds.
  ta4_min: 100
  is_prach_cp_enabled: true
  is_dl_broadcast_enabled: true
  compr_method_ul: bfp                                            # Uplink compression method.
  compr_bitwidth_ul: 9                                            # Uplink IQ samples bitwidth after compression.
  compr_method_dl: bfp                                            # Downlink compression method.
  compr_bitwidth_dl: 9                                            # Downlink IQ samples bitwidth after compression.
  compr_method_prach: bfp                                         # PRACH compression method.
  compr_bitwidth_prach: 9                                         # PRACH IQ samples bitwidth after compression.
  enable_ul_static_compr_hdr: false                                # Configures if the compression header is present for uplink User-Plane messages (false) or not present (true).
  enable_dl_static_compr_hdr: false                                # Configures if the compression header is present for downlink User-Plane messages (false) or not present (true).
  iq_scaling: 5.5                                                 # IQ samples scaling factor applied before compression, should be a positive value smaller than 10.
  cells:
  - network_interface: ens4f0                                   # Ethernet interface name used to communicate with the RU.
    ru_mac_addr: 70:b3:d5:e1:54:2f                                # RU MAC address.
    du_mac_addr: 40:a6:b7:3f:85:3c                                # DU MAC address.
    vlan_tag_cp: 5                                                # VLAN tag value for C-Plane.
    vlan_tag_up: 5                                                # VLAN tag value for U-Plane.
    prach_port_id: [4,5]                                          # PRACH eAxC port value.
    dl_port_id: [0,1]                                             # Downlink eAxC port values.
    ul_port_id: [0,1]                                             # Uplink eAxC port values.

cell_cfg:
  dl_arfcn: 660000                                                 # ARFCN of the downlink carrier (center frequency).
  band: 77                                                        # The NR band.
  channel_bandwidth_MHz: 20                                       # Bandwith in MHz. Number of PRBs will be automatically derived.
  common_scs: 30                                                  # Subcarrier spacing in kHz used for data.
  plmn: "99940"                                                   # PLMN broadcasted by the gNB.
  tac: 7                                                          # Tracking area code (needs to match the core configuration).
  pci: 1                                                          # Physical cell ID.
  nof_antennas_dl: 2
  nof_antennas_ul: 2
  prach:
    prach_config_index: 159                                      # PRACH configuration index.
    prach_root_sequence_index: 1                                  # PRACH root sequence index.
    zero_correlation_zone: 0                                      # Zero correlation zone.
    prach_frequency_start: 2                                      # Offset in PRBs of lowest PRACH transmission occasion in frequency domain respective to PRB 0.
    preamble_trans_max: 50
    power_ramping_step_db: 4
  tdd_ul_dl_cfg:
    dl_ul_tx_period: 10                                           # Optional INT (10). Sets the TDD pattern periodicity in slots. The combination of this value and the chosen numerology must lead to a TDD periodicity of 0.5, >
    nof_dl_slots: 7                                               # Optional INT (6). Number of consecutive full Downlink slots. Supported: [0-80].
    nof_dl_symbols: 6                                             # Optional INT (0). Number of Downlink symbols at the beginning of the slot following full Downlink slots. Supported: [0-13].
    nof_ul_slots: 2                                               # Optional INT (3). Number of consecutive full Uplink slots. Supported: [0 - 80].
    nof_ul_symbols: 4
  ssb:
    ssb_period: 20
  pdsch:
    mcs_table: qam256
  pusch:
    p0_nominal_with_grant: -76
log:
  filename: /tmp/gnb.log                                          # Path of the log file.
  all_level: info
  phy_level: debug
  ofh_level: info 


pcap:
  mac_enable: false                                              # Set to true to enable MAC-layer PCAPs.
  mac_filename: /tmp/gnb_mac.pcap                                 # Path where the MAC PCAP is stored.
  ngap_enable: false                                              # Set to true to enable NGAP PCAPs.
  ngap_filename: /tmp/gnb_ngap.pcap                               # Path where the NGAP PCAP is stored.
```

ru_config.cfg
```shell
# Config file for Benetel RANx50 radio units
# Please place this file in /etc

# MIMO mode - the radio can operate in 1_3, 2_4, 1_2_3_4_4x2 or 1_2_3_4_4x4 mode
# Variable name : mimo_mode
# Valid options : 1_3
#                 2_4
#                 1_2_3_4_4x2
#                 1_2_3_4_4x4
mimo_mode=1_3

# FPGA downlink scaling in steps of 6 dB (0, 6, 12 and 18 can be set)
# Variable name : downlink_scaling
# Valid options : 0
#                 6
#                 12
#                 18
downlink_scaling=6

# PRACH format
# Variable name : prach_format
# Valid options : short
#                 long
prach_format=short

# Short form PRACH compression settings (note uncompressed mode is not supported when RU is in 4x2 or 4x4 mode)
# Variable name : compression
# Valid options : static_uncompressed
#                 dynamic_uncompressed
#                 static_compressed
#                 dynamic_compressed
compression=dynamic_compressed

# Long form PRACH compression settings
# Variable name : lf_prach_compression_enable
# Valid options : true
#                 false
lf_prach_compression_enable=true

# C-Plane per-symbol workaround
# Variable name : cplane_per_symbol_workaround
# Valid options : enabled
#                 disabled
cplane_per_symbol_workaround=disabled


# CUPLANE dl couplling sectionID
# Variable name : cuplane_dl_coupling_sectionI
# Valid options : enabled
#                 disabled
cuplane_dl_coupling_sectionID=disabled

# FlexRAN PRACH workaround
# Variable name : flexran_prach_workaround
# Valid options : enabled
#                 disabled
flexran_prach_workaround=disabled

#DL_UL special slot tunning
#Variable name : dl_ul_tuning_special_slot
#Valid options : 0x0
#                0xfd00000
#dl_ul_tuning_special_slot=0xfd00000
dl_tuning_special_slot=0x13b6
```

tdd.xml
```xml
<xml>
    <tdd-config version="1.0">
            <description>DDDDDDDSUU</description>
                        <pattern index="1">
                                <slots>DDDD</slots>
                                <numerology>1</numerology>
                                <periodicity>2</periodicity>
                                <special-slot-symbols></special-slot-symbols>
                        </pattern>
                        <pattern index="2">
                                <slots>DDDSUU</slots>
                                <numerology>1</numerology>
                                <periodicity>3</periodicity>
                                <special-slot-symbols>DDDDDDGGGGUUUU</special-slot-symbols>
                        </pattern>
    </tdd-config>
</xml>
```

eaxc_1_2t.xml
```xml
<xml>
    <eaxc-config version="1.0">
        <antenna antenna-id="0">
                        <eaxc-id type="downlink">
                                <du-port-id>0</du-port-id>
                                <band-sector>0</band-sector>
                                <cc-id>0</cc-id>
                                <ru-port-id>0</ru-port-id>
                        </eaxc-id>
                        <eaxc-id type="uplink">
                                <du-port-id>0</du-port-id>
                                <band-sector>0</band-sector>
                                <cc-id>0</cc-id>
                                <ru-port-id>0</ru-port-id>
                        </eaxc-id>
                        <eaxc-id type="prach">
                                <du-port-id>0</du-port-id>
                                <band-sector>0</band-sector>
                                <cc-id>0</cc-id>
                                <ru-port-id>4</ru-port-id>
                        </eaxc-id>
                </antenna>
        <antenna antenna-id="1">
                        <eaxc-id type="downlink">
                                <du-port-id>0</du-port-id>
                                <band-sector>0</band-sector>
                                <cc-id>0</cc-id>
                                <ru-port-id>1</ru-port-id>
                        </eaxc-id>
                        <eaxc-id type="uplink">
                                <du-port-id>0</du-port-id>
                                <band-sector>0</band-sector>
                                <cc-id>0</cc-id>
                                <ru-port-id>1</ru-port-id>
                        </eaxc-id>
                        <eaxc-id type="prach">
                                <du-port-id>0</du-port-id>
                                <band-sector>0</band-sector>
                                <cc-id>0</cc-id>
                                <ru-port-id>5</ru-port-id>
                        </eaxc-id>
                </antenna>
        <antenna antenna-id="2">
                        <eaxc-id type="downlink">
                                <du-port-id>0</du-port-id>
                                <band-sector>0</band-sector>
                                <cc-id>0</cc-id>
                                <ru-port-id>2</ru-port-id>
                        </eaxc-id>
                        <eaxc-id type="uplink">
                                <du-port-id>0</du-port-id>
                                <band-sector>0</band-sector>
                                <cc-id>0</cc-id>
                                <ru-port-id>2</ru-port-id>
                        </eaxc-id>
                        <eaxc-id type="prach">
                                <du-port-id>0</du-port-id>
                                <band-sector>0</band-sector>
                                <cc-id>0</cc-id>
                                <ru-port-id>6</ru-port-id>
                        </eaxc-id>
                </antenna>
        <antenna antenna-id="3">
                        <eaxc-id type="downlink">
                                <du-port-id>0</du-port-id>
                                <band-sector>0</band-sector>
                                <cc-id>0</cc-id>
                                <ru-port-id>3</ru-port-id>
                        </eaxc-id>
                        <eaxc-id type="uplink">
                                <du-port-id>0</du-port-id>
                                <band-sector>0</band-sector>
                                <cc-id>0</cc-id>
                                <ru-port-id>3</ru-port-id>
                        </eaxc-id>
                        <eaxc-id type="prach">
                                <du-port-id>0</du-port-id>
                                <band-sector>0</band-sector>
                                <cc-id>0</cc-id>
                                <ru-port-id>7</ru-port-id>
                        </eaxc-id>
                </antenna>
    </eaxc-config>
</xml>
```
