### DISCUSSION TITLE
Received data is not in JSON format

### DISCUSSION THREAD

**Discussion by aibtw** [srsran/srsRAN_Project#722] [General Help] [answered]
Hi, 

I saw a previous post in https://github.com/srsran/srsRAN_Project/discussions/539#discussioncomment-9008517, I am interested getting the trace metrics forwarded through UDP socket so I tried that method. However, the Python script shows me something like this:
```
Received data is not in JSON format: {
  "timestamp": 1720615295.03,
  "cell_metrics": {
    "error_indication_count": 0,
    "average_latency": 18,
    "latency_histogram": [
      {
        "latency_bin": {
          "latency_bin_start_usec": 0,
          "latency_bin_count": 2000
        }
      },
      {
        "latency_bin": {
          "latency_bin_start_usec": 50,
          "latency_bin_count": 0
        }
      },
      {
        "latency_bin": {
          "latency_bin_start_usec": 100,
          "latency_bin_count": 0
        }
      },
      {
        "latency_bin": {
          "latency_bin_start_usec": 150,
          "latency_bin_count": 0
        }
      },
      {
        "latency_bin": {
          "latency_bin_start_usec": 200,
          "latency_bin_count": 0
        }
      },
      {
        "latency_bin": {
          "latency_bin_start_usec": 250,
          "latency_bin_count": 0
        }
      },
      {
        "latency_bin": {
          "latency_bin_start_usec": 300,
          "latency_bin_count": 0
        }
      },

```

This happened when testing the code in test_mode. I wasn't able to find where the issue is (at gNB side or python script side). Would appreciate the help. The configuration I used is below. 
```
amf:
  addr: 127.0.1.100                                             # The address or hostname of the AMF.
  bind_addr: 127.0.0.1                                          # A local IP that the gNB binds to for traffic from the AMF.

cell_cfg:
  dl_arfcn: 640000                                              
  band: 78                                                     
  channel_bandwidth_MHz: 20                                   
  common_scs: 30                                              
  plmn: "99970"                                                
  tac: 7                                                 
  pci: 1                                            
  nof_antennas_dl: 1
  nof_antennas_ul: 1
  pdsch: 
    min_ue_mcs: 10                
    max_ue_mcs: 10                 
  pusch: 
    min_ue_mcs: 10              
    max_ue_mcs: 10          
    
test_mode: 
  test_ue: 
    rnti: 0x4601                               # Optional ENUM (0). Sets the C-RNTI of the UE. Supported: [0 - 65519].
    nof_ues: 1                            # Optonal UINT (1). Sets the number of test UE(s) created. Supported [0 - 1024].
    pdsch_active: true                    # Optional BOOLEAN (true). Enables the PDSCH of the UE. Supported: [false, true].
    pusch_active: true                    # Optional BOOLEAN (true). Enables the PUSCH of the UE. Supported: [false, true].
    cqi: 15                               # Optional UINT (15). Sets the Channel Quality Information to be forwarded to the test UE. Supported: [1 - 15].
    pmi: 0                                # Optional UINT (0). Sets the Precoder Matrix Indicator to be forwarded to test UE. Supported: [0 - 3].
    ri: 1                                 # Optional UINT (1). Sets the Rank Indicator to be forwarded to the test UE. Supported: [1 - 4].
    i_1_1: 0                              # Optional INT (0). Sets the Precoder Matrix codebook index "i_1_1" to be forwarded to test UE, in the case of more than 2 antennas. Supported: [0 - 7].
    i_1_3: 0                              # Optional INT (0). Sets the Precoder Matrix codebook index "i_1_3" to be forwarded to test UE, in the case of more than 2 antennas. Supported: [0 - 1].
    i_2: 0                                # Optional INT (0). Sets the Precoder Matrix codebook index "i_2" to be forwarded to test UE, in the case of more than 2 antennas. Supported: [0 - 3].

metrics:
  stdout_metrics_period: 1000 
  enable_json_metrics: true
```
