### DISCUSSION TITLE
Picocom PC802 - msg2 not received

### DISCUSSION THREAD

**Discussion by huss-ba** [srsran/srsRAN_Project#736] [General Help]
Hi all, 

We are trying to integrate PC802SCB X3 with srsRAN gNB. We did validate time synchronization for the RU with PICOCOM team. The setup is configured as LLS-C3, also tried to match the RU and DU configurations to use same frequency (3375.0 MHz) and same bandwidth (20MHz), same compression method and bitwidth etc. 

When we initialize the RU, and start the gNB, we can see on the DU side in the logs messages like:
```
2024-07-17T15:17:08.935148 [OFH     ] [I] Received packets: rx_total=4800 rx_early=0, rx_on_time=4800, rx_late=0
2024-07-17T15:17:09.934554 [CU-CP   ] [D] num_f1ap_ues=0 num_rrc_ues=0 num_ngap_ues=0 num_e1ap_ues=0 num_cu_cp_ues=0
2024-07-17T15:17:09.934557 [CU-UP   ] [D] num_e1ap_ues=0 num_cu_up_ues=0
```
So initially we think the communication between DU and RU is successful. 

We then attempt to connect a UE. We see that the UE sent PRACH message (msg1). However, the UE never receives msg2. 

So in gNB logs we start seeing:
```
2024-07-17T15:17:13.110113 [PHY     ] [D] [   86.19] PRACH:  rssi=-100.2dB detected_preambles=[{idx=3 ta=1.69us detection_metric=16.6}] t=115.4us
  rsi=1
  preambles=[0, 64)
  format=B4
  set=unrestricted
  zcz=0
  scs=30kHz
  nof_rx_ports=1
  rssi=-100.2dB
  res=0.1us
  max_ta=12.08us
  detected_preambles=[{idx=3 ta=1.69us detection_metric=16.6}]

2024-07-17T15:17:13.110521 [SCHED   ] [D] [    87.6] Processed slot events:
```
then attempts to send multiple messages, but at the end:
```
2024-07-17T15:17:13.155013 [SCHED   ] [I] [   91.15] UL HARQ rnti=0x4601 cell=0 h_id=0: Discarding HARQ with tbs=11. Cause: Maximum number of reTxs 4 exceeded
``` 
And another rach is detected ... etc. 

The full logs are attached below.
[gnb.txt](https://github.com/user-attachments/files/16269685/gnb.txt)

Also this is what I could extract from the UE side:
![image](https://github.com/user-attachments/assets/2999e090-3a8c-48a6-9f81-b509b3911d1b)

Did anyone face similar issues? 
I found older posts about RAN550 integration and the behavior seems similar, like https://github.com/srsran/srsRAN_Project/discussions/389#discussion-6020698 or https://github.com/srsran/srsRAN_Project/issues/265#issuecomment-1774120912 but unfortunately can't find a solution there. Would be grateful if anyone could help troubleshoot the issue.

We are using srsRAN Project release 24.04, with the following configurations: 
```
amf:
  addr: 127.0.1.100                                               # The address or hostname of the AMF.
  bind_addr: 127.0.0.1                                            # A local IP that the gNB binds to for traffic from the AMF.

ru_ofh:
  t1a_max_cp_dl: 350                                              # Maximum T1a on Control-Plane for Downlink in microseconds.
  t1a_min_cp_dl: 250                                              # Minimum T1a on Control-Plane for Downlink in microseconds.
  t1a_max_cp_ul: 250                                              # Maximum T1a on Control-Plane for Uplink in microseconds.
  t1a_min_cp_ul: 150                                              # Minimum T1a on Control-Plane for Uplink in microseconds.
  t1a_max_up: 200                                                 # Maximum T1a on User-Plane in microseconds.
  t1a_min_up: 80                                                  # Minimum T1a on User-Plane in microseconds.
  ta4_max: 300                                                    # Maximum Ta4 on User-Plane in microseconds.
  ta4_min: 10                                                     # Minimum Ta4 on User-Plane in microseconds.
  is_prach_cp_enabled: true                                      # Configures if Control-Plane messages should be used to receive PRACH messages.
  compr_method_ul: bfp                                            # Uplink compression method.
  compr_bitwidth_ul: 9                                            # Uplink IQ samples bitwidth after compression.
  compr_method_dl: bfp                                            # Downlink compression method.
  compr_bitwidth_dl: 9                                            # Downlink IQ samples bitwidth after compression.
  compr_method_prach: bfp                                         # PRACH compression method.
  compr_bitwidth_prach: 9                                         # PRACH IQ samples bitwidth after compression.
  iq_scaling: 5                                                 # IQ samples scaling factor applied before compression, should be a positive value smaller than 10.
  cells:
    #- network_interface: enp1s0f3                                
    - network_interface: 0000:01:00.3     
      ru_mac_addr: 8c:1f:64:b4:xx:xx
      du_mac_addr: 50:7c:6f:52:xx:xx                             
      vlan_tag_cp: 5                                              
      vlan_tag_up: 5                                              
      mtu: 9000
      prach_port_id: [0,1,2,3]                                          # PRACH eAxC port value.
      dl_port_id: [0,1,2,3]                                             # Downlink eAxC port values.
      ul_port_id: [0,1,2,3]                                             # Uplink eAxC port values.

cell_cfg:
  dl_arfcn: 625000 #620000                                                # ARFCN of the downlink carrier (center frequency).
  band: 78                                                        
  channel_bandwidth_MHz: 20                                       # Bandwith in MHz. Number of PRBs will be automatically derived.
  common_scs: 30                                                  # Subcarrier spacing in kHz used for data.
  nof_antennas_dl: 4                                             # Downlink number of antennas.
  nof_antennas_ul: 4                                              # Downlink number of antennas.  
  plmn: "99970"                                                   # PLMN broadcasted by the gNB.
  tac: 7                                                    
  pci: 1                                                      
  prach:
    prach_config_index: 159                              
    prach_root_sequence_index: 1                                
    zero_correlation_zone: 0                                      
    prach_frequency_start: 0                                      
  tdd_ul_dl_cfg:
    nof_dl_slots: 7
    nof_ul_slots: 2 
    nof_dl_symbols: 6 
    nof_ul_symbols: 4
  ssb: 
    ssb_block_power_dbm: -50                # Optional INT (-16). Sets the SS PBCH block power in dBm. Supported: [-60 - +50].

hal:
   eal_args: "--lcores (0-1)@(0-23) -a 0000:01:00.3"

log:
  filename: /tmp/gnb.log                                          # Path of the log file.
  all_level: debug                                              # Logging level applied to all layers.
  mac_level: debug
  fapi_level: info                   # Optional TEXT (warning). Sets FAPI log level.
  ofh_level: info
```
