### DISCUSSION TITLE
Change the bandwidth of BWP: Need to be less than channel bandwidth

### DISCUSSION THREAD

**Discussion by praghur** [srsran/srsRAN_Project#756] [General Help] [answered]
Hello community. 

I am trying to run a gNB using x310 with cell configuration as shown below:
_cell_cfg:
  dl_arfcn: 632628
  band: 78
  channel_bandwidth_MHz: 20
  common_scs: 30
  nof_antennas_dl: 1
  nof_antennas_ul: 1
  plmn: "99999"
  tac: 1
  pci: 1
pdsch:
    mcs_table: qam256
  ssb:
    ssb_period: 20_

I saw in the discussion thread #52 that the default BWP has the size of the `channel_bandwidth_MHz`. Is there a way to change this setting? If my channel bandwidth is 100 MHz, can I set the BWP bandwidth to anywhere between 20 MHz to 100 MHz? I am fine with having only single BWP for the entire channel bandwidth. But I am curious if the single BWP can be configured to occupy only a certain bandwidth within the entire available channel bandwidth. 

Thanks in advance for any input.

**Comment by herlesupreeth** [comment]
> If my channel bandwidth is 100 MHz, can I set the BWP bandwidth to anywhere between 20 MHz to 100 MHz?

No, its not possible.

> But I am curious if the single BWP can be configured to occupy only a certain bandwidth within the entire available channel bandwidth.

Can you please let us know what is the usecase you are trying to achieve with this?

**Reply by praghur** [reply]
My objective is to measure the latency of critical traffic in presence of background data. The way I am planning to measure this is by reserving the BWP to the critical traffic. The rest of the bandwidth is assumed to be occupied by background data. 

By changing the bandwidth of the BWP, I am trying to simulate the conditions of light background data to a heavy background data. Can you please let me know if there is any other alternative to simulate this? Thanks a lot, in advance.

**Reply by frankist** [reply]
The main objectives of BWPs are: (i) to reduce power consumption in UEs or support less capable UEs (by lowering their Tx/Rx bandwidth), and (ii) to support multiple numerologies in the same cell. On the other hand, RAN slicing allows you to manage the spectrum resources and distribute them across different traffic groups (slices) in a more flexible manner. What you are describing looks more like RAN slicing, and you should not need BWPs for that.

We plan to have RAN slicing fully supported in the MAC scheduler very soon, likely before the end of this month. Maybe with what is already in `dev` you may be able to perform the experiment that you are describing. Maybe @herlesupreeth can confirm this.

**Reply by herlesupreeth** [reply, marked as answer]
> We plan to have RAN slicing fully supported in the MAC scheduler very soon, likely before the end of this month. Maybe with what is already in dev you may be able to perform the experiment that you are describing. Maybe @herlesupreeth can confirm this.

Yes, with the latest code in the main branch you can try out RAN slicing to achieve your objective of reserving a small BW for critical traffic. This you can do by putting the UE having critical traffic on a different slice and setting minimum number of RBs to allocate to that slice. e.g.

```
cell_cfg:
  slicing:
    -
      sst: 1
      sd: 1
      sched_cfg:
        min_prb_policy_ratio: 10
        max_prb_policy_ratio: 10

    -
      sst: 1
      sd: 2
      sched_cfg:
        min_prb_policy_ratio: 0
        max_prb_policy_ratio: 100
```

in this configuration the slice with SST1 and SD 1 is the critical traffic slice and whenever there is traffic it is promised minimum of 10 RBs

**Reply by Onursever** [reply]
Could you please clarify what changes I need to make on the UE side so that it can recognize the slice and SD configured by the gNB? for Multi-UE Emulation with ZMQ.

**Reply by newt2105** [reply]
> > We plan to have RAN slicing fully supported in the MAC scheduler very soon, likely before the end of this month. Maybe with what is already in dev you may be able to perform the experiment that you are describing. Maybe @herlesupreeth can confirm this.
> 
> Yes, with the latest code in the main branch you can try out RAN slicing to achieve your objective of reserving a small BW for critical traffic. This you can do by putting the UE having critical traffic on a different slice and setting minimum number of RBs to allocate to that slice. e.g.
> 
> ```
> cell_cfg:
>   slicing:
>     -
>       sst: 1
>       sd: 1
>       sched_cfg:
>         min_prb_policy_ratio: 10
>         max_prb_policy_ratio: 10
> 
>     -
>       sst: 1
>       sd: 2
>       sched_cfg:
>         min_prb_policy_ratio: 0
>         max_prb_policy_ratio: 100
> ```
> 
> in this configuration the slice with SST1 and SD 1 is the critical traffic slice and whenever there is traffic it is promised minimum of 10 RBs

Hi @herlesupreeth, thanks for the instruction, it's very helpful for me.
But I have some problem, here is my gnb config:
```
cell_cfg:
  slicing:
    - sst: 1
      sd: 000001
      sched_cfg:                              # Scheduler configuration for the slice
        min_prb_policy_ratio: 95                # Optional UINT (0). Sets the minimum percentage of PRBs to be allocated to the slice. Supported [0 - 100].
        max_prb_policy_ratio: 100 
    - sst: 1
      sd: 000002
      sched_cfg:                              # Scheduler configuration for the slice
        min_prb_policy_ratio:  1                # Optional UINT (0). Sets the minimum percentage of PRBs to be allocated to the slice. Supported [0 - 100].
        max_prb_policy_ratio:  2
    - sst: 1
      sd: 000003
      sched_cfg:                              # Scheduler configuration for the slice
        min_prb_policy_ratio: 1                 # Optional UINT (0). Sets the minimum percentage of PRBs to be allocated to the slice. Supported [0 - 100].
        max_prb_policy_ratio: 2  
  dl_arfcn: 368500                  # ARFCN of the downlink carrier (center frequency).
  band: 3                           # The NR band.
  channel_bandwidth_MHz: 10         # Bandwith in MHz. Number of PRBs will be automatically derived.
  common_scs: 15                    # Subcarrier spacing in kHz used for data.
  plmn: "00101"                     # PLMN broadcasted by the gNB.
  tac: 7                         # Tracking area code (needs to match the core configuration).
  pdcch:
    common:
      ss0_index: 0                  # Set search space zero index to match srsUE capabilities
      coreset0_index: 6             # Set search CORESET Zero index to match srsUE capabilities
    dedicated:
      ss2_type: ue_dedicated           # Search Space type, has to be set to common
      dci_format_0_1_and_1_1: true # Set correct DCI format (fallback)
  prach:
    prach_config_index: 1           # Sets PRACH config to match what is expected by srsUE
    total_nof_ra_preambles: 64      # Sets number of available PRACH preambles
    nof_ssb_per_ro: 1               # Sets the number of SSBs per RACH occasion.
    nof_cb_preambles_per_ssb: 64    # Sets the number of contention based preambles per SSB.
``` 
I'm using first slice, then I run kpm_mon_xapp and run: sudo ip netns exec ue1 iperf -c 10.45.1.1 -u -b 100M -i 1 -t 500
. here is the output:
```
RIC Indication Received from gnbd_001_001_00019b_0 for Subscription ID: 4, KPM Report Style: 4
E2SM_KPM RIC Indication Content:
-ColletStartTime:  2025-05-15 03:27:01
-Measurements Data:
--UE_id: 0
---granulPeriod: 1000
---Metric: DRB.UEThpDl, Value: [4]
---Metric: DRB.UEThpUl, Value: [33460]
---Metric: RRU.PrbTotDl, Value: [8]
---Metric: RRU.PrbTotUl, Value: [87]
---Metric: RRU.PrbAvailDl, Value: [48]
---Metric: RRU.PrbUsedDl, Value: [4]
---Metric: RRU.PrbAvailUl, Value: [7]
---Metric: RRU.PrbUsedUl, Value: [45]
``` 

I don't see 95-100% PRB in DL or UL. Can you explain?
Thanks!
