### DISCUSSION TITLE
Scheduling Algorithms

### DISCUSSION THREAD

**Discussion by ThorisoMakhosa** [srsran/srsRAN_Project#780] [Ideas & Suggestions]
Hi Everyone. 

I am experimenting with scheduling algorithms for different use cases, most of the work has been mainly theoretical. Can i ask which scheduling algorithms does srsRAN currently support and how do i configure them for deployment scenarios since they are not available on the configuration files. 

Thank you very much

**Comment by herlesupreeth** [comment]
> Can i ask which scheduling algorithms does srsRAN currently support and how do i configure them for deployment scenarios since they are not available on the configuration files.

srsRAN_Project currently support Round-Robin and Proportional Fair scheduling. Round-Robin is used by default. In order to use PF scheduler you can configure it as follows:

```
cell_cfg:
  sched_expert_cfg:
    policy_sched_cfg:
      pf_sched:
        pf_sched_fairness_coeff: 2.0
```
