### DISCUSSION TITLE
multiple cells in one gnb

### DISCUSSION THREAD

**Discussion by Zplusless** [srsran/srsRAN_Project#794] [General Help] [answered]
Hi srsRAN community,
Could you please guide me on how to modify the gNB configuration so that a single DU can support multiple cells (both configs for working with ZMQ and USRP-b210)? 

Any guidance is appreciated! Thanks in advance!

**Comment by rakeshreddy7397** [comment]
Hi Zplusless,

Any luck in getting multiple cells to run in a single srsDU? please share your insights if any

**Reply by Zplusless** [reply]
Unfortunately, it is not supported. see https://github.com/srsran/srsRAN_Project/discussions/760#discussioncomment-10272988

**Reply by pgawlowicz** [reply]
Actually, it should be now possible to run multiple cells within a single DU, please try with this config:

```
gnb_id: 411
gnb_id_bit_length: 32

cu_cp:
  amf:
    addr: 10.53.1.2
    port: 38412
    bind_addr: 10.53.1.1
    supported_tracking_areas:
      - tac: 7
        plmn_list:
          - plmn: "00101"
            tai_slice_support_list:
              - sst: 1
  inactivity_timer: 7200            # Sets the UE/PDU Session/DRB inactivity timer to 7200 seconds. Supported: [1 - 7200].

ru_sdr:
  srate: 23.04
  device_driver: zmq
  device_args: tx_port0=tcp://*:31100,rx_port0=tcp://127.0.0.1:31681,tx_port1=tcp://*:31598,rx_port1=tcp://127.0.0.1:31310,id=gnb,base_srate=23.04e6
  sync: default
  time_alignment_calibration: 0

cell_cfg:
  nof_antennas_dl: 1
  nof_antennas_ul: 1
  dl_arfcn: 368500
  band: 3
  channel_bandwidth_MHz: 20
  common_scs: 15
  plmn: "00101"
  tac: 7
  pdsch:
    mcs_table: qam256
  pusch:
    mcs_table: qam256

cells:
  - pci: 1
    dl_arfcn: 368500
    band: 3
    common_scs: 15
    prach:
      prach_root_sequence_index: 0
  - pci: 2
    dl_arfcn: 368500
    band: 3
    common_scs: 15
    prach:
      prach_root_sequence_index: 64
```
