### DISCUSSION TITLE
Neighbouring cells reports

### DISCUSSION THREAD

**Discussion by improperaffo** [srsran/srsRAN_Project#803] [General Help] [answered]
Dear all,
we have been trying out the handover feature. We are able to trigger it with the `ho <serving pci> <rnti> <target pci>` command when using a USRP, but when moving to the measurement based handover, we encountered some difficulties.

We have tried setting the `report_configs:` for `ncells:` both to `periodical` and `event_triggered`. Yet, looking at the CU logs, we observe only one or two measurement reports for the neighbour cell right after the user connects, after that the phone only reports measurement for the cell it is connected to.
First one or two measurement reports:
```
2024-09-04T08:53:03.279847 [RRC     ] [D] ue=0 c-rnti=0x4601: Containerized measurementReport: [
  {
    "UL-DCCH-Message": {
      "message": {
        "c1": {
          "measurementReport": {
            "criticalExtensions": {
              "measurementReport": {
                "measResults": {
                  "measId": 1,
                  "measResultServingMOList": [
                    {
                      "servCellId": 0,
                      "measResultServingCell": {
                        "physCellId": 1,
                        "measResult": {
                          "cellResults": {
                            "resultsSSB-Cell": {
                              "rsrp": 51,
                              "rsrq": 65,
                              "sinr": 83
                            }
                          },
                          "rsIndexResults": {
                            "resultsSSB-Indexes": [
                              {
                                "ssb-Index": 0,
                                "ssb-Results": {
                                  "rsrp": 51,
                                  "rsrq": 65,
                                  "sinr": 83
                                }
                              }
                            ]
                          }
                        }
                      }
                    }
                  ],
                  "measResultNeighCells": {
                    "measResultListNR": [
                      {
                        "physCellId": 2,
                        "measResult": {
                          "cellResults": {
                            "resultsSSB-Cell": {
                              "rsrp": 40,
                              "rsrq": 63,
                              "sinr": 54
                            }
                          },
                          "rsIndexResults": {
                            "resultsSSB-Indexes": [
                              {
                                "ssb-Index": 0,
                                "ssb-Results": {
                                  "rsrp": 40,
                                  "rsrq": 63,
                                  "sinr": 54
                                }
                              }
                            ]
                          }
                        }
                      }
                    ]
                  }
                }
              }
            }
          }
        }
      }
    }
  }
]
```
All the remaining measurement reports:
```
 2024-09-04T08:53:03.555412 [RRC     ] [D] ue=0 c-rnti=0x4601: Containerized measurementReport: [
  {
    "UL-DCCH-Message": {
      "message": {
        "c1": {
          "measurementReport": {
            "criticalExtensions": {
              "measurementReport": {
                "measResults": {
                  "measId": 1,
                  "measResultServingMOList": [
                    {
                      "servCellId": 0,
                      "measResultServingCell": {
                        "physCellId": 1,
                        "measResult": {
                          "cellResults": {
                            "resultsSSB-Cell": {
                              "rsrp": 49,
                              "rsrq": 65,
                              "sinr": 73
                            }
                          },
                          "rsIndexResults": {
                            "resultsSSB-Indexes": [
                              {
                                "ssb-Index": 0,
                                "ssb-Results": {
                                  "rsrp": 48,
                                  "rsrq": 65,
                                  "sinr": 73
                                }
                              }
                            ]
                          }
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        }
      }
    }
  }
```
Our CU mobility config (we have tried setting `report_configs:` to `2` and `3`):
```
mobility:
    trigger_handover_from_measurements: true
    cells:
      - nr_cell_id: 0x2130
        periodic_report_cfg_id: 1
        ncells:
          - nr_cell_id: 0x2131
            report_configs: [ 2, 3 ]
      - nr_cell_id: 0x2131
        periodic_report_cfg_id: 1
        ncells:
          - nr_cell_id: 0x2130
            report_configs: [ 2, 3 ]
    report_configs:
      - report_cfg_id: 1
        report_type: periodical
        report_interval_ms: 480
      - report_cfg_id: 2
        report_type: event_triggered
        a3_report_type: rsrp
        a3_offset_db: 2
        a3_hysteresis_db: 0
        a3_time_to_trigger_ms: 100
      - report_cfg_id: 3
        report_type: periodical
        report_interval_ms: 480
```
[Complete CU logs in debug mode](https://github.com/user-attachments/files/16863799/cu.log)

What could be the reason? We tested various different phones, but we were never able to get measurements from neighbouring cells.
Thanks

**Comment by pgawlowicz** [comment]
Could you check the behaviour if you set the following:
```
    cells:
      - nr_cell_id: 0x2130
        periodic_report_cfg_id: 1
        ncells:
          - nr_cell_id: 0x2131
            report_configs: [ 1 ]  --> change to 1 
      - nr_cell_id: 0x2131
        periodic_report_cfg_id: 1
        ncells:
          - nr_cell_id: 0x2130
            report_configs: [ 1 ]  --> change to 1 
```

and also: 
```
    cells:
      - nr_cell_id: 0x2130
        periodic_report_cfg_id: 1
        ncells:
          - nr_cell_id: 0x2131
            report_configs: [ 1, 2 ]  --> change to 1,2 
      - nr_cell_id: 0x2131
        periodic_report_cfg_id: 1
        ncells:
          - nr_cell_id: 0x2130
            report_configs: [ 1, 2 ]  --> change to 1,2
```
