### DISCUSSION TITLE
Failed to bind SCTP socket when setting bind_addr as node IP

### DISCUSSION THREAD

**Discussion by HaoxinSEU** [srsran/srsRAN_Project#812] [General Help] [answered]
Hi community,

We are trying to setup gNB and Open5GS in Kuberentes. We met some weird issues regarding the AMF `bind_addr`.

Our setup includes both Open5GS and gNB in K8S, so all pods are running on the same machine. The gNB is set to use ZMQ for testing.

For gNB configuration, if we set the field `bind_addr` of `amf` as the gNB pod IP, then everything works well. However, if we set this field as the node IP (the computer's IP, following the instructions [here](https://docs.srsran.com/projects/project/en/latest/tutorials/source/k8s/source/index.html#srsran-project-helm-chart)), then we get errors when starting the gNB:
```
Failed to bind SCTP socket to $node_ip. Cannot assign requested address
srsGNB ERROR: Failed to create SCTP gateway.
```
We are wondering why the bind can fail, is it because other pods are also binding to the node's IP?

Here is the configuration of gNB:
```
gnb_id: 332

amf:
  addr: 10.43.202.12
  bind_addr: $node_ip

ru_sdr:
  device_driver: zmq             
  device_args: tx_port=tcp://127.0.0.1:2000,rx_port=tcp://127.0.0.1:2001,base_srate=23.04e6
  srate: 23.04                      
  tx_gain: 75           
  rx_gain: 75              

cell_cfg:
  dl_arfcn: 368500                 
  band: 3                          
  channel_bandwidth_MHz: 20         
  common_scs: 15                 
  plmn: "00101"                  
  tac: 1                           
  pci: 1
  pdcch:
    common:
      ss0_index: 0
      coreset0_index: 12
    dedicated:
      ss2_type: common                
      dci_format_0_1_and_1_1: false
  prach:
    prach_config_index: 1
```
Thanks for any hints!
