### DISCUSSION TITLE
Fail to use the n310 in the 5G SA deploy

### DISCUSSION THREAD

**Discussion by MKSBarbosa** [srsran/srsRAN_Project#835] [General Help]
Hello, Everyone,

I have been trying to use srsRAN in 5G SA mode with Docker ([docker_open5gs](https://github.com/herlesupreeth/docker_open5gs)), but I'm facing issues deploying it with the N310.

Here is my Dockerfile:

```
FROM ubuntu:jammy

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get -y install cmake make gcc g++ pkg-config libfftw3-dev libmbedtls-dev libsctp-dev libyaml-cpp-dev libgtest-dev \
    libzmq3-dev software-properties-common pkg-config net-tools iputils-ping git

RUN apt-get update && \
    apt install -y libboost-all-dev libusb-1.0-0-dev doxygen python3-docutils python3-mako python3-numpy python3-ruamel.yaml python3-setuptools

RUN  git clone https://github.com/EttusResearch/uhd.git

RUN cd uhd/host && \
    mkdir build && \
    cd build && \
    git checkout v4.1.0.0

RUN cd uhd/host/build && \
    cmake ../ && \
    make -j $(nproc) && \ 
    make install && \
    ldconfig && \
    uhd_images_downloader

    RUN git clone https://github.com/srsran/srsRAN_Project.git && \
    cd srsRAN_Project && git checkout 4ac5300d4927b5199af69e6bc2e55d061fc33652 && \
    mkdir build && cd build && \
    cmake ../ -DENABLE_EXPORT=ON -DENABLE_ZEROMQ=ON && make -j`nproc` && make install && \
    ldconfig

ENV UHD_IMAGES_DIR=/usr/share/uhd/images/

CMD cd /mnt/srsran && /mnt/srsran/srsran_init.sh
```
and 

The entrypoint (srsran_init.sh) executes this command: `gnb -c /etc/srsran/gnb.yml -c /etc/srsran/mimo.yml`

And here is my configuration file:

**gnb.yml**

```
amf:
  addr: AMF_IP                                                    # The address or hostname of the AMF.
  bind_addr: SRS_GNB_IP                                           # A local IP that the gNB binds to for traffic from the AMF.

ru_sdr:
  device_driver: uhd                  
  device_args: type=n3xx, addr= 192.168.89.100, send_frame_size=8000,recv_frame_size=8000           
  clock: gpsdo                        
  sync: gpsdo                         
  srate: 30.72                        
  tx_gain: 35                         
  rx_gain: 60                         

cell_cfg:
  dl_arfcn: 368640                    
  band: 3                             
  channel_bandwidth_MHz: 20           
  common_scs: 15                      
  plmn: "00101"                       
  tac: 1                              
  pci: 1                              

log:
  filename: /tmp/gnb.log              
  all_level: info                     

pcap:
  mac_enable: false                   
  mac_filename: /tmp/gnb_mac.pcap     
  ngap_enable: false                  
  ngap_filename: /tmp/gnb_ngap.pcap   
```
I have tried UHD 4.7.0.0, 4.4.0.0, and 4.1.0.0, however, I keep encountering the following error:

```
Attaching to srsgnb
srsgnb  | Configuring component: 'gnb'
srsgnb  |  * Starting system message bus dbus                            [ OK ] 
srsgnb  | avahi-daemon: unrecognized service
srsgnb  | 
srsgnb  | --== srsRAN gNB (commit 4ac5300d4) ==--
srsgnb  | 
srsgnb  | 
srsgnb  | The PRACH detector will not meet the performance requirements with the configuration {Format 0, ZCZ 0, SCS 1.25kHz, Rx ports 1}.
srsgnb  | Lower PHY in quad executor mode.
srsgnb  | N2: Connection to AMF on 172.22.0.10:38412 completed
srsgnb  | Cell pci=1, bw=20 MHz, 2T2R, dl_arfcn=368640 (n3), dl_freq=1843.2 MHz, dl_ssb_arfcn=367230, ul_freq=1748.2 MHz
srsgnb  | 
srsgnb  | Available radio types: uhd and zmq.
srsgnb  | [INFO] [UHD] linux; GNU C++ version 11.4.0; Boost_107400; UHD_4.4.0.HEAD-0-g5fac246b
srsgnb  | [INFO] [LOGGING] Fastpath logging disabled at runtime.
srsgnb  | Making USRP object with args 'type=n3xx,addr=192.168.89.100,send_frame_size=8000,recv_frame_size=8000,master_clock_rate=122.88e6'
srsgnb  | [INFO] [MPMD] Initializing 1 device(s) in parallel with args: mgmt_addr=192.168.89.100,type=n3xx,product=n310,serial=31DA7FF,claimed=False,addr=192.168.89.100,send_frame_size=8000,recv_frame_size=8000,master_clock_rate=122.88e6
srsgnb  | [INFO] [MPM.main] Launching USRP/MPM, version: 3.15.0.0-gaea0e2de
srsgnb  | [INFO] [MPM.main] Spawning RPC process...
srsgnb  | [INFO] [MPM.PeriphManager] Device serial number: 31DA7FF
srsgnb  | [INFO] [MPM.PeriphManager] Initialized 2 daughterboard(s).
srsgnb  | [INFO] [MPM.PeriphManager] init() called with device args `time_source=internal,clock_source=internal'.
srsgnb  | [INFO] [MPM.RPCServer] RPC server ready!
srsgnb  | [INFO] [MPM.RPCServer] Spawning watchdog task...
srsgnb  | Failed to open device with address 'type=n3xx, addr= 192.168.89.100, send_frame_size=8000,recv_frame_size=8000': rpc::timeout: Timeout of 2000ms while calling RPC function 'set_device_id'
srsgnb  | srsRAN ERROR: Unable to create radio session.
srsgnb exited with code 1
```

Can anyone help me solve this?

I am using Ubuntu Server 22, and the N310 is directly connected to the server.
