### DISCUSSION TITLE
CU-DU split DU MAC pcap file  fail to decode in Wireshark

### DISCUSSION THREAD

**Discussion by fllay** [srsran/srsRAN_Project#836] [General Help] [answered]
Hi, I use the following DU configuration file
```
gnb_id: 531
gnb_id_bit_length: 32
gnb_du_id: 0

f1ap:
  cu_cp_addr: 192.168.68.210
  bind_addr: 192.168.68.19
nru:
  bind_addr: 192.168.68.19

ru_sdr:
  device_driver: uhd
  device_args: type=b200,num_recv_frames=64,num_send_frames=64
  srate: 23.04
  otw_format: sc12
  tx_gain: 70
  rx_gain: 50


cell_cfg:
  dl_arfcn: 632628                                                # ARFCN of the downlink carrier>
  band: 78                                                        # The NR band.
  channel_bandwidth_MHz: 20                                       # Bandwith in MHz. Number of PR>
  common_scs: 30                                                  # Subcarrier spacing in kHz use>
  plmn: "00101"                                                   # PLMN broadcasted by the gNB.
  tac: 7                                                          # Tracking area code (needs to >
  pci: 1                                                          # Physical cell ID.
  nof_antennas_dl: 2
  nof_antennas_ul: 2
  sector_id: 0
  pdsch:
    mcs_table: qam256

log:
  filename: /tmp/du.log
  all_level: debug

pcap:
  f1u_filename: /tmp/du1_f1u.pcap      # Optional TEXT (/tmp/gnb_f1u.pcap). Path for F1-U (NRU) PCAPs. 
  f1u_enable: true                     # Optional BOOLEAN (false). Enable/disable F1-U (NRU) packet capture. Supported: [false, true].
  f1ap_filename: /tmp/du1_f1ap.pcap     # Optional TEXT (/tmp/gnb_f1ap.pcap). Path for F1AP PCAPs. 
  f1ap_enable: true                    # Optional BOOLEAN (false). Enable/disable F1AP packet capture. Supported: [false, true].
  rlc_filename: /tmp/du1_rlc.pcap       # Optional TEXT (tmp/gnb_rlc.pcap). Path for RLC PCAPs. 
  rlc_rb_type: all                      # Optional TEXT. Sets the RLC PCAP RB type. Supported: [all, srb, drb].
  rlc_enable: true                     # Optional BOOLEAN (false). Enable/disable RLC packet capture. Supported: [false, true].  
  mac_filename: /tmp/du1_mac.pcap       # Optional TEXT (/tmp/gnb_mac.pcap). Path for MAC PCAPs. 
  mac_type: udp                         # Optional TEXT (udp). Sets the MAC PCAP pcap type. Supported: [DLT or UDP].
  mac_enable: true                     # Optional BOOLEAN (false). Enable/disable MAC packet capture. Supported: [false, true].
  e2ap_filename: /tmp/du1_e2ap.pcap     # Optional TEXT (/tmp/gnb_e2ap.pcap). Path for E2AP PCAPs. 
  e2ap_enable: true                    # Optional BOOLEAN (false). Enable/disable E2AP packet capture. Supported: [false, true].
```

Then, I got the following error

```
pi@pi-n100:~/src/srsRAN_Project/build/apps/du$ sudo ./srsdu -c ~/src/configs/du.yaml

--== srsRAN DU (commit 51e44a642) ==--

Using more than two DL antennas might make the MAC PDU larger than what is supported in the UDP wrapper. Use PCAP DLT type to avoid pcap corruption.
srsRAN ERROR: Invalid configuration detected.
```
and I changed  `mac_type: udp` to `mac_type: dlt`. There is no error and the UE can attached to the network. However, the MAC pcap file cannot decoded in Wireshark.

[du1_mac.pcap.zip](https://github.com/user-attachments/files/17158695/du1_mac.pcap.zip)

It complains about DLT=157 so I set  DLT=157 and Payload protocol=udp. It still cannot correctly decode MAC pcap. I did not see any DLT=157 in the manual as well. Please let me know to set Wireshark to decode this MAC pcap. Thank you BTW, all others pcap can be decoded correctly in Wireshark.
