### DISCUSSION TITLE
URLLC Scheduling

### DISCUSSION THREAD

**Discussion by praghur** [srsran/srsRAN_Project#839] [General Help]
Hello all. 

I want to create a scheduling policy for URLLC traffic in presence of non-critical traffic. When the traffic belongs to a particular slice, it needs to be provided priority compared to traffic with the rest of the slices. 

Is it possible to do this? Any insight on how can I get started on it? Thanks in advance.

**Comment by pgawlowicz** [comment]
Please check this answer: https://github.com/srsran/srsRAN_Project/discussions/756#discussioncomment-10240374

**Comment by frankist** [comment]
@praghur, can you clarify a bit further what you want to do? In particular, would the current approach of setting a minimum number of PRBs not be enough for what you are trying to achieve?

**Comment by praghur** [comment]
Thanks a lot for the tip. Yes that works, actually.

**Reply by praghur** [reply]
Sorry to re-open this item. I tried to change the minimum number of PRBs for each slice. I went from:
```
  slicing:
   - sst: 1
     sd: 0x000001
     sched_cfg:
       min_prb_policy_ratio: 50
       max_prb_policy_ratio: 75
```

To:
```
 slicing:
   - sst: 1
     sd: 0x000001
     sched_cfg:
       min_prb_policy_ratio: 90
       max_prb_policy_ratio: 100
```

I am surprised that this does not change the latency of the UDP packets that I am sending via traceroute. I was thinking that reserving PRBs will improve the latency. I am looking to improve the latency of the data packets sent via the 5G network. Are there any techniques to achieve this? The configuration files for gNBs is attached. The rest of the configuration files are provided in [link](https://github.com/praghur/srsran_OTA/tree/URLLCscheduling/etc/srsran)

Thanks in advance. 
[gnb_x310_1.txt](https://github.com/user-attachments/files/17385347/gnb_x310_1.txt)
