### DISCUSSION TITLE
Maximum Throughput calculation for a specific TDD configuration with srsRAN

### DISCUSSION THREAD

**Discussion by Keilwerth11270** [srsran/srsRAN_Project#854] [General Help]
Hi everyone,
 
I am estimating the maximum throughput in UL and DL for a specific TDD configuration based on the [TS 38 306](https://www.etsi.org/deliver/etsi_ts/138300_138399/138306/15.03.00_60/ts_138306v150300p.pdf).
 
I am using the default TDD config of srsRAN, with 
```
tdd_ul_dl_cfg: 
    dl_ul_tx_period: 10                     
    nof_dl_slots: 6                         
    nof_dl_symbols: 8                       
    nof_ul_slots: 3                         
    nof_ul_symbols: 0                       
    pattern2: 
      dl_ul_tx_period: 10                       
      nof_dl_slots: 6                           
      nof_dl_symbols: 8                         
      nof_ul_slots: 3                           
      nof_ul_symbols: 0  
```

The calculation requires the number of RBs in UL and DL, and a scaling factor. 

With the default TDD config, we have 6 full slots and 8 OFDM symbols in the next slot in DL and 3 full UL slots in the TDD pattern periodicity of 10 slots. So, in 10 slots, DL used 6.57 slots, and UL used 3 slots.

For example, with 20 MHz bandwidth and 30 KHz subcarrier spacing, the number of PRBs is 51. The distribution of PRBs for DL is 33.507, and UL is 15.3. For this calculation, we have not considered additional factors such as DMRS, SLIV etc. and with this, the calculated throughput comes out to be 53.73 Mbps in DL and 26.24 Mbps in UL with scaling factor 1.
 
The measured OTA throughput under the best channel conditions is 42.5 Mbps in DL and 17.9 Mbps in UL.
 
What would be the best way to approximate the number of DL and UL RBs with the default srsRAN configuration? 
And is a scaling factor of 1 correct for srsRAN?
