### DISCUSSION TITLE
Completing implementation of Inter-CU Handover in srsRAN

### DISCUSSION THREAD

**Discussion by AliNawazish** [srsran/srsRAN_Project#863] [General Help]
I want to use inter-CU handover in my project. However, srsRAN 24.04 partially implements inter-CU handover. From what I understand, the NGAP messages and BearerSetup procedure at CU are implemented, but the DU part, specifically creating a target-to-source transparent container to configure UE's protocol stack, is not implemented correctly. This causes issues when the RRC Reconfiguration message is sent to a COTS UE. When UE synchronizes with the new base station, two problems arise: 1). Downlink traffic does not reach COTS UE even though RAN receives it from the core network, and 2). After a while, UE performs RACH to re-synchronize with the new base station since it cannot receive any downlink traffic. 

The setup consists of two n310s running srsRAN 24.04 as base stations, Quectel RM520N-GL as COTS UE, and Open5GS as the core network.
Additionally, the measurement reports for the target base station are not working either. UE is unable to detect the target cell for some reason. However, I am bypassing this issue by manually triggering handover with the handover command `ho source_pci rnti target_pci` provided by the srsRAN terminal. 

I can see PUCCH messages like measurement reports going to the target base station as well. 

Config file for source base station:
```gnb_id: 411
gnb_id_bit_length: 32

amf:
  addr: 127.0.0.20
  bind_addr: 127.0.0.50

ru_sdr:
  device_driver: uhd
  device_args: type=n3xx, addr=192.168.10.2,send_frame_size=8000,recv_frame_size=8000
  tx_gain: 25
  rx_gain: 30
  srate:  30.72
  sync: external
  time_alignment_calibration: 0
  lo_offset: 45
  clock: external

cell_cfg:
  dl_arfcn: 632628
  band: 78
  channel_bandwidth_MHz: 20
  common_scs: 30
  ssb:
    ssb_period: 10
  nof_antennas_dl: 1
  nof_antennas_ul: 1
  plmn: "99999"
  tac: 1

slicing:
  -
    sst: 1
    sd: 1

cells:
  -
    pci: 1
    prach:
      prach_root_sequence_index: 0


cu_cp:
  mobility:
    trigger_handover_from_measurements: true
    cells:
      - nr_cell_id: 0x19B0
        periodic_report_cfg_id: 1
        ncells:
          - nr_cell_id: 0x19C0
            report_configs: [ 3 ]
      - nr_cell_id: 0x19C0
        ncells:
          - nr_cell_id: 0x19B0
            report_configs: [ 3 ]
        gnb_id_bit_length: 32
        pci: 2
        ssb_arfcn: 631872
        band: 78
        ssb_scs: 30
        ssb_period: 10
        ssb_offset: 0
        ssb_duration: 5
    report_configs:
      - report_cfg_id: 1
        report_type: periodical
        report_interval_ms: 480
      - report_cfg_id: 2
        report_type: event_triggered
        a3_report_type: rsrp
        a3_offset_db: 3
        a3_hysteresis_db: 0
        a3_time_to_trigger_ms: 100
      - report_cfg_id: 3
        report_type: periodical
        report_interval_ms: 480
log:
  filename: /tmp/n310.log
  rrc_level: debug
  mac_level: debug
  rlc_level: debug
  fapi_level: warning

pcap:
  mac_enable: true
  mac_filename: /tmp/gnb_mac.pcap
  ngap_enable: true
  ngap_filename: /tmp/gnb_ngap.pcap

metrics:
  autostart_stdout_metrics: true
```

The behavior of first base station:

![first_bs](https://github.com/user-attachments/assets/17bcb4d7-33c2-45b0-a5cb-7c9632f17ed8)

Logs of source base station:

[source_base_station.log](https://github.com/user-attachments/files/17367321/source_base_station.log)

Config file for target base station:
```
gnb_id: 412
gnb_id_bit_length: 32

amf:
  addr: 127.0.0.20
  bind_addr: 127.0.0.80

ru_sdr:
  device_driver: uhd
  device_args: type=n3xx,send_frame_size=8000,recv_frame_size=8000
  tx_gain: 30
  rx_gain: 30
  srate:  30.72
  sync: external
  time_alignment_calibration: 0
  lo_offset: 45
  clock: external

cell_cfg:
  dl_arfcn: 632228
  band: 78
  channel_bandwidth_MHz: 20
  common_scs: 30
  ssb:
    ssb_period: 10
  nof_antennas_dl: 1
  nof_antennas_ul: 1
  plmn: "99999"
  tac: 1

slicing:
  -
    sst: 1
    sd: 1

cells:
  -
    pci: 2
    prach:
      prach_root_sequence_index: 64

cu_cp:
  mobility:
    trigger_handover_from_measurements: true
    cells:
      - nr_cell_id: 0x19C0
        periodic_report_cfg_id: 1
        ncells:
          - nr_cell_id: 0x19B0
            report_configs: [ 1, 2 ]
      - nr_cell_id: 0x19B0
       # periodic_report_cfg_id: 1
        ncells:
          - nr_cell_id: 0x19C0
            report_configs: [ 1, 2 ]
        gnb_id_bit_length: 32
        pci: 1
        ssb_arfcn: 632256
        band: 78
        ssb_scs: 30
        ssb_period: 10
        ssb_offset: 0
        ssb_duration: 5
    report_configs:
      - report_cfg_id: 1
        report_type: periodical
        report_interval_ms: 480
      - report_cfg_id: 2
        report_type: event_triggered
        a3_report_type: rsrp
        a3_offset_db: 3
        a3_hysteresis_db: 0
        a3_time_to_trigger_ms: 40

log:
  filename: /tmp/n310_2.log
  all_level: debug
  fapi_level: warning

pcap:
  mac_enable: true
  mac_filename: /tmp/gnb_2_mac.pcap
  ngap_enable: true
  ngap_filename: /tmp/gnb_2_ngap.pcap

metrics:
  autostart_stdout_metrics: true
```
The behavior of second base station:

![second_bs](https://github.com/user-attachments/assets/c40ac7f0-da8e-4a11-b589-995aa14a06bd)

Logs of target base station:

[target_base_station.log](https://github.com/user-attachments/files/17367325/target_base_station.log)

It seems that the problem is unrelated to the physical layer. When I stop the ping while COTS UE is synchronized with the new base station, it doesn't initiate a new RACH procedure. I am looking for pointers to fix this issue. 

Thanks.
