### DISCUSSION TITLE
Using two different networks to N2 and N3

### DISCUSSION THREAD

**Discussion by maatheusfp** [srsran/srsRAN_Project#890] [General Help] [answered]
Hello! I'm trying to use oai-vpp-upf with srsran gnb. For that, i need to use two differents networks to N2 and N3 interfaces. Is there a possibility to configure it to bind the two interfaces instead of only one? 

```

cu_cp:
  amf:
    addr: 172.22.0.10
    port: 38412
    bind_addr: 172.22.0.1       
    supported_tracking_areas:
      - tac: 1
        plmn_list:
          - plmn: "00101"
            tai_slice_support_list:
              - sst: 1
           
```
