### DISCUSSION TITLE
TDD Configuration Capability

### DISCUSSION THREAD

**Discussion by hayekr** [srsran/srsRAN_Project#892] [General Help] [answered]
Hello,

I am exploring the use of srsRAN with an SDR to operate as a 5G NR gNB. Could anyone provide clarification on the TDD configurations and numerologies supported by srsRAN?

Thank you!

**Comment by herlesupreeth** [comment, marked as answer]
For TDD only 30Khz SCS is supported i.e. numerology 1 and for TDD configuration you can freely set the desired configuration using the below configuration section in the gNB configuration file.

NOTE: There should be atleast 2 DL slots in order to schedule SSB and CSI-RS

```
  tdd_ul_dl_cfg:
    nof_dl_symbols: 10
    nof_dl_slots: 7
    nof_ul_slots: 2
```
