### DISCUSSION TITLE
xapp_oran_moni for FlexRIC prints 0 value for downlink and uplink throughput.

### DISCUSSION THREAD

**Discussion by penhauer** [srsran/srsRAN_Project#980] [General Help] [answered]
Hi SRS,

First of all, I should send my huge regards for your amazing work developing this project. I am trying to run the `xapp_oran_moni` xApp following the "O-RAN NearRT-RIC and xApp" tutorial on your website. It is a bit confusing which srsRAN version I should use. I am mainly looking at release 24_10 (commit 9d5dd742a) with flexric branch `br-flexric` (currently on commit 73650812) but I can see some new commits for srsRAN after release 24_10 as of now. I'm wondering if the release 24_10 is complete by itself or the new commits fix release issues.

The problem is, I get the following output from the `xapp_oran_moni` xApp while running some background traffic from the UE. Specifically, I have tried the release 24_10 with but a ZMQ driver and a UHD setup but the issue is the same. In addition, I have tried the latest commit (e5d5b44b9) and the commit at release 24_04 but no help.

![image](https://github.com/user-attachments/assets/4e78bb26-9640-484b-96d4-9144b73f7721)

Here are some changes I made to the code to make sure the issue is coming from the RAN.
![image](https://github.com/user-attachments/assets/38b1804f-d74b-46f9-81e5-466b780612ad)

As you can see, I've already added the changes discussed [here](https://github.com/srsran/srsRAN_Project/discussions/567#discussioncomment-9209950).

![image](https://github.com/user-attachments/assets/fe16d8e8-08dd-4402-8284-b822f91b259b)

This is the config I use when running gNB:

```
cu_cp:
  amf:
    addr: 10.10.3.200
    port: 38412
    bind_addr: 10.10.3.231
    sctp_nodelay: true

    sctp_rto_initial: 120
    sctp_rto_min: 120
    sctp_rto_max: 500
    no_core: false

    supported_tracking_areas:
      - tac: 1
        plmn_list:
          - plmn: "00101"
            tai_slice_support_list:
              - sst: 1
                sd: 000001
              - sst: 2
                sd: 000002

ru_sdr:
  device_driver: zmq
  device_args: tx_port=tcp://127.0.0.1:2000,rx_port=tcp://127.0.0.1:2001,base_srate=11.52e6
  srate: 11.52
  tx_gain: 75
  rx_gain: 75

cell_cfg:
  dl_arfcn: 368500                  # ARFCN of the downlink carrier (center frequency).
  band: 3                           # The NR band.
  channel_bandwidth_MHz: 10         # Bandwith in MHz. Number of PRBs will be automatically derived.
  common_scs: 15                    # Subcarrier spacing in kHz used for data.
  plmn: "00101"                     # PLMN broadcasted by the gNB.
  tac: 1                            # Tracking area code (needs to match the core configuration).
  pdcch:
    common:
      ss0_index: 0                  # Set search space zero index to match srsUE capabilities
      coreset0_index: 6             # Set search CORESET Zero index to match srsUE capabilities
    dedicated:
      ss2_type: common              # Search Space type, has to be set to common
      dci_format_0_1_and_1_1: false # Set correct DCI format (fallback)
  prach:
    prach_config_index: 1           # Sets PRACH config to match what is expected by srsUE

log:
  filename: /tmp/gnb.log            # Path of the log file.
  all_level: warning                   # Logging level applied to all layers.
  e2ap_level: info                   # Optional TEXT (warning). Sets the E2AP log level.

  hex_max_size: 0

pcap:
  mac_enable: false                
  mac_filename: /tmp/gnb_mac.pcap  
  ngap_enable: false               
  ngap_filename: /tmp/gnb_ngap.pcap


e2:
  enable_cu_e2: true
  enable_du_e2: true

  addr: 129.97.168.82
  port: 36421
  bind_addr: 129.97.168.82
  sctp_rto_initial: 120
  sctp_rto_min: 120
  sctp_rto_max: 500
  sctp_init_max_attempts: 3
  sctp_max_init_timeo: 500
  e2sm_kpm_enabled: true
  e2sm_rc_enabled: true

metrics:
  addr: 127.0.0.1
  port: 55555
  rlc_json_enable: 1                # Enable RLC metrics reporting (need to deliver measurements to E2SM_KPM service model)
  rlc_report_period: 1000           # Set reporting period to 1s
```

**Comment by pgawlowicz** [comment]
add

```
e2:
  ...
  e2sm_kpm_enabled: true            # Enable KPM service module
  e2sm_rc_enabled: true             # Enable RC service module
```

**Reply by penhauer** [reply]
Thank you very much for your answer. I already have those in my config (last 2 lines for e2).

**Reply by pgawlowicz** [reply]
ah true, i did not notice it. 
What does the gnb print if you enable the console trace with `t` ?

**Reply by penhauer** [reply]
I'm doing a ping from the UE when running the xApp.

![image](https://github.com/user-attachments/assets/e2cfe698-03c4-40b8-91dc-5d47676ed79c)

**Reply by pgawlowicz** [reply]
Could you increase traffic volume? for example, increase ping frequency with `-i 0.1`

**Comment by penhauer** [comment, marked as answer]
It appears to be working. I had tested it with iperf3 traffic but I think it was before applying the patch on the style1 function. I think i had forgotten to test it with bigger traffic after the patch. Thank you anyway for the help.

![image](https://github.com/user-attachments/assets/2bab3706-6e2c-4ff4-9641-09c10e57bc19)

**Reply by penhauer** [reply]
There's still an issue with with the setup when I run it with an actual USRP and not simulated UEs. 

![image](https://github.com/user-attachments/assets/81ee939e-e9c7-449c-b77f-8cc7ad6b093a)

**Reply by pgawlowicz** [reply]
that is strange, could you post your gnb config file?

**Reply by penhauer** [reply]
Hi, I realized I hadn't included the 

``` yaml
metrics:
  rlc_json_enable: 1                # Enable RLC metrics reporting (need to deliver measurements to E2SM_KPM service model)
  rlc_report_period: 1000           # Set reporting period to 1s
```

in my config for USRP.

Thank you again for the help.
