### DISCUSSION TITLE
Compatibility Between USRP N210 and srsRAN Project 5G SA

### DISCUSSION THREAD

**Discussion by justinlau21** [srsran/srsRAN_Project#981] [General Help]
Hi everyone,
I’m working on an srsRAN 5G SA project using the USRP N210 with an SBX daughterboard. I’ve encountered a compatibility issue between the required sampling rates for the N210 and the multiples of 1.92 MHz expected by srsRAN.

### Setup:
USRP Model: N210 (With SBX Card)
External Clock: 10 MHz RF connected to the REF connector
Software: srsRAN and Open5GS

### Issue:
It seems that the USRP N210 requires certain sampling rates like 33.33 MHz, 50 MHz, etc., but srsRAN requires the sampling rate to be a multiple of 1.92 MHz, such as 15.36 MHz, 14.4 MHz, etc.

--== srsRAN gNB (commit e5d5b44b9) ==--

The sampling rate must be multiple of 1.92 MHz.
srsRAN ERROR: Invalid configuration detected.

AND

Error: setting Tx sampling rate. Tx Rate 15.36 MHz is invalid. The nearest valid value is 14.285714285714285.

### My questions are:
Compatibility: Is there a way to configure the N210 with SBX daughterboard to operate with srsRAN when the sampling rate needs to be a multiple of 1.92 MHz?
Sampling Rate Matching: Can I use a multiple of 1.92 MHz with USRP N210, even though the hardware might default to 33.33 MHz or 50 MHz? Or should I scale my desired rate to match both hardware and software requirements?
External Clock: How does the 10 MHz external clock connect to this setup, and does it affect the sampling rate compatibility?

### Here is the configuration I am using for the gnb1.yml file:
```
cu_cp:
  amf:
    addr: 127.0.0.5
    port: 38412
    bind_addr: 192.168.10.109
    supported_tracking_areas:
      - tac: 1
        plmn_list:
          - plmn: "00101"
            tai_slice_support_list:
              - sst: 1

ru_sdr:
  device_driver: uhd
  device_args: "type=usrp2,addr=192.168.10.2,name=N210_MMU,serial=E7R23NCUP"
  clock: external
  sync: external
  srate: 15.36  # Ideally a valid multiple of 1.92 MHz
  tx_gain: 45     # Adjusted TX gain
  rx_gain: 60

cell_cfg:
  dl_arfcn: 650000
  band: 77
  channel_bandwidth_MHz: 15  # Bandwidth
  common_scs: 30  # Subcarrier spacing
  plmn: "00101"
  tac: 1
  pci: 1
```

I’m looking for advice on how to properly align the sampling rate expectations of both the USRP N210 and srsRAN, and how to configure the external clock with respect to these sampling rate constraints.
Any help or guidance on this would be greatly appreciated.

Thank you!
