### ISSUE TITLE
Assertion Failure in rlc_tx_am_entity when Connecting OAI CU to srsDU with COTS UE (Open5GS)

### ISSUE THREAD

**Issue by Moussa-Guemdani** [srsran/srsRAN_Project#1019]
Hello srs team,

I am trying to connect OAI CU with srsDU. The connection between the CU and DU is successfully established, but when I attempt to connect a COTS UE, I encounter the following assertion failure:
```
~/srsRAN_Project/lib/rlc/rlc_tx_am_entity.cpp:75:
srsran::rlc_tx_am_entity::rlc_tx_am_entity(srsran::gnb_du_id_t, srsran::du_ue_index_t,
srsran::rb_id_t, const srsran::rlc_tx_am_config&, srsran::rlc_tx_upper_layer_data_notifier&,
srsran::rlc_tx_upper_layer_control_notifier&, srsran::rlc_tx_lower_layer_notifier&,
srsran::rlc_metrics_aggregator&, srsran::rlc_pcap&, srsran::task_executor&,
srsran::task_executor&, srsran::timer_manager&): Assertion
`config.pdcp_sn_len == pdcp_sn_size::size12bits || config.pdcp_sn_len == pdcp_sn_size::size18bits' failed
- Cannot create RLC TX AM, unsupported pdcp_sn_len=invalid. du=0 ue=1 DRB1.
```

Steps to Reproduce

    Setup OAI CU and srsDU.
    Ensure the connection between CU and DU is established.
    Attempt to connect a COTS UE.
    Observe the error in rlc_tx_am_entity.cpp.

Expected Behavior

The COTS UE should attach successfully without triggering an assertion failure.
Observed Behavior

The assertion failure occurs due to an unsupported PDCP SN length (pdcp_sn_len=invalid), which causes the srsDU process to crash.

OAI CU Configuration File:
```
gnb-cu.sa.f1.test.with.srsDU.conf

Active_gNBs = ( "cu-rfsim");
Asn1_verbosity = "none";
Num_Threads_PUSCH = 8;

gNBs =
(
 {
    gNB_ID = 0xe00;
    gNB_name  =  "cu-rfsim";
    tracking_area_code  =  1;
    plmn_list = ({ mcc = 001; mnc = 01; mnc_length = 2; snssaiList = ({ sst = 1; }) });
    nr_cellid = 12345678L;

    tr_s_preference = "f1";

    local_s_if_name     = "lo";
    local_s_address     = "127.0.10.1";
    remote_s_address    = "127.0.10.2";
    #local_s_portc       = 38472;
    #local_s_portd       = 38472;
    #remote_s_portc      = 38472;
    #remote_s_portd      = 38472;

    amf_ip_address = ({ ipv4 = "192.168.1.41"; });

    NETWORK_INTERFACES :
    {
        GNB_IPV4_ADDRESS_FOR_NG_AMF              = "192.168.1.40/24";
        GNB_IPV4_ADDRESS_FOR_NGU                 = "192.168.1.40/24";
        GNB_PORT_FOR_S1U                         = 2152;
    };
  }
);

security = {
  ciphering_algorithms = ( "nea0" );
  integrity_algorithms = ( "nia2", "nia0" );
  drb_ciphering = "yes";
  drb_integrity = "no";
};

```
srsDU Configuration:
                                                                        
```
f1ap:                               
  cu_cp_addr: 192.168.1.41 # 127.0.10.1  (F1_C)              # Required TEXT (127.0.10.1).>
  bind_addr: 192.168.1.40 #127.0.10.2                 # Required TEXT (127.0.10.2). >

nru:                                
  #queue_size: 40960                      # Optional INT (2048). Sets the F1-U PDU que>
  bind_addr: 192.168.1.40 #127.0.10.2       


cell_cfg:
  dl_arfcn: 663334
  band: 77
  channel_bandwidth_MHz: 60
  common_scs: 30
  plmn: "00101"
  tac: 1
  pci: 1

  tdd_ul_dl_cfg:  
    dl_ul_tx_period: 10                     # Optional INT (10). Sets the TDD pattern periodicity in slots. The combination of this value and the chosen numerology must lead to a >
    nof_dl_slots: 6                         # Optional INT (6). Number of consecutive full Downlink slots. Supported: [0-80].
    nof_dl_symbols: 10                       # Optional INT (8). Number of Downlink symbols at the beginning of the slot following full Downlink slots. Supported: [0-13].
    nof_ul_slots: 3                         # Optional INT (3). Number of consecutive full Uplink slots. Supported: [0 - 80].
    nof_ul_symbols: 2                       # Optional INT (0). Number of Uplink symbols at the end of the slot preceding the first full Uplink slot. Supported: [0-13].
    

ru_sdr:
  device_driver: uhd
  device_args: type=x300, addr=192.168.30.2, num_send_frames=32, num_recv_frames=32, send_frame_size=8000, recv_frame_size=8000, stream_args=replay_buffered #, send_buff_size=8160>
  srate: 92.16 #122.88 #184.32  #184.32 #184.32 #122.88  #122.88 #92.16  #92.16 #61.4 , 184.32 MHz
  otw_format: default #sc16 ##default
  clock: default
  sync: default
  tx_gain: 31.5
  rx_gain: 31.5
  time_alignment_calibration: -170
 

metrics:
  enable_json_metrics: true
  autostart_stdout_metrics: true
```
