### ISSUE TITLE
Reduced Downlink Throughput with X310 ?

### ISSUE THREAD

**Issue by dominikheinz** [srsran/srsRAN_Project#1057]
I have a 5G test setup for performance benchmarking.
My setup consists of an X310 that is connected via PCIe to a powerful Dell system (13900k).
This system runs srsRAN.
I also have a UE, that is a Quectel RM520N-GL connected to a Laptop running Ubuntu.
The UE and the GNB are 1m apart, with direct LOS.

I am doing a TCP downlink speedtest with iperf3, `iperf3 -R -c 10.45.0.1 -t 0`.

For whatever reason I only get around 90mbits/sec of throughput max for 100Mhz SISO, - which is strange, because the exact same system has been able to do around ~180mbits/sec of throughput in the past, with the same hardware, software etc.

I double checked the configuration and I don't see why I only get half of the throughput.
However, looking at the tracelog I noticed that the system has some nok (not okay?) transmissions, around 15% or so, - so I assume something isn't right with the channel?
Also, the MCS value is 20.

Testing the same SDR on another computer (An AMD system), although connected via SFP+ instead of PCIe, - is able to provide the expected throughput.

Am I missing anything obvious? Below is a snippet of the tracelog, and the configuration I use for the GNB.

**The Intel system connected via PCIe, that has only half thorughput:**
```
           -----------------DL-----------------------|------------------UL--------------------
 pci rnti  cqi  ri  mcs  brate   ok  nok  (%)  dl_bs | pusch  mcs  brate   ok  nok  (%)    bsr
   1 4609   15   1   20    87M  846  138  14%  18.1k |  26.7   28   319k   49    0   0%  1.45k
   1 4609   15   1   20    80M  812   37   4%   223k |  26.7   28   232k   50    0   0%      0
   1 4609   15   1   20    96M  947  104   9%      0 |  26.6   28   200k   46    0   0%      0
   1 4609   15   1   20    97M  948  142  13%      0 |  26.6   28   200k   46    0   0%      0
   1 4609   15   1   20    91M  891  131  12%   450k |  26.2   28   196k   45    0   0%      0
   1 4609   15   1   20    91M  893  114  11%   213k |  25.8   28   191k   44    0   0%      0
   1 4609   15   1   20    89M  877  131  12%   318k |  26.0   28   205k   47    0   0%      0
   1 4609   15   1   20    81M  812  102  11%   175k |  26.0   28   202k   48    0   0%      0
   1 4609   15   1   20    87M  861   96  10%      0 |  26.5   28   205k   47    0   0%      0
   1 4609   15   1   20    90M  878  120  12%   339k |  26.3   28   196k   45    0   0%      0
   1 4609   15   1   20    82M  795  131  14%   172k |  26.0   28   187k   43    0   0%      0

           -----------------DL-----------------------|------------------UL--------------------
 pci rnti  cqi  ri  mcs  brate   ok  nok  (%)  dl_bs | pusch  mcs  brate   ok  nok  (%)    bsr
   1 4609   15   1   20    90M  867  136  13%   435k |  25.8   28   187k   43    0   0%      0
   1 4609   15   1   20    81M  824   88   9%   248k |  25.3   28   260k   60    1   1%      0
   1 4609   15   1   20    95M  935  127  11%   173k |  25.9   28   200k   46    0   0%      0
   1 4609   15   1   20    93M  903  144  13%   462k |  25.9   28   204k   47    0   0%      0
   1 4609   15   1   20    91M  886  125  12%      0 |  27.0   28   196k   45    0   0%      0
   1 4609   15   1   20    89M  860  128  12%   169k |  24.7   27   220k   60    2   3%      0
   1 4609   15   1   20    84M  862   54   5%   288k |  27.0   28   218k   50    0   0%      0
   1 4609   15   1   20    89M  893   68   7%   258k |  26.6   28   218k   50    0   0%      0
   1 4609   15   1   20    93M  932  107  10%   178k |  26.2   28   196k   45    0   0%      0
   1 4609   15   1   20    76M  757  105  12%   294k |  27.1   28   187k   43    0   0%      0
   1 4609   15   1   20    87M  857  123  12%   197k |  27.1   28   187k   43    0   0%      0
```

**The AMD system that is able to provide the expected throughput:**
```
          |--------------------DL---------------------|-------------------------UL------------------------------
 pci rnti | cqi  ri  mcs  brate   ok  nok  (%)  dl_bs | pusch  rsrp  mcs  brate   ok  nok  (%)    bsr     ta  phr
   1 4605 |  15 1.0   23   137M 1334   12   0%  18.6k |  34.1  -1.2   28   217k   52    0   0%      0      0   18
   1 4605 |  15 1.0   24    99M  928   11   1%      0 |  28.9  -2.0   27   2.0M   80   14  14%      0      0    8
   1 4605 |  15 1.0   24   131M 1245    0   0%  33.2k |  33.6  -3.0   28   468k   60    0   0%      0      0   20
   1 4605 |  15 1.0   25   130M 1273    9   0%  22.7k |  33.7  -3.2   28   471k   72    0   0%      0      0   20
   1 4605 |  15 1.0   27   146M 1309    0   0%  24.2k |  34.1  -3.4   28   218k   50    0   0%      0      0   20
   1 4605 |  15 1.0   27   150M 1234   32   2%  11.2k |  32.6  -5.0   28   213k   49    2   3%      0      0   20
   1 4605 |  15 1.0   22   150M 1306   10   0%  29.6k |  34.7  -2.0   28   210k   49    1   2%      0      0   20
   1 4605 |  15 1.0   25   156M 1328    0   0%  15.5k |  34.1  -2.8   28   226k   51    0   0%      0      0   20
   1 4605 |  15 1.0   26   156M 1328    4   0%  1.42k |  34.1  -2.3   28   218k   50    0   0%      0  -105n   20
   1 4605 |  15 1.0   28   162M 1319    0   0%  28.1k |  34.8  -2.9   28   218k   50    0   0%      0  -146n   20
   1 4605 |  15 1.0   28   161M 1356    0   0%  51.6k |  34.2  -2.9   28   218k   50    0   0%      0      0   20

          |--------------------DL---------------------|-------------------------UL------------------------------
 pci rnti | cqi  ri  mcs  brate   ok  nok  (%)  dl_bs | pusch  rsrp  mcs  brate   ok  nok  (%)    bsr     ta  phr
   1 4605 |  15 1.0   28   157M 1325    1   0%  15.5k |  34.9  -2.8   28   218k   50    0   0%      0  -105n   20
   1 4605 |  15 1.0   25   146M 1266   29   2%  4.88k |  33.6  -2.6   28   206k   52    2   3%      0      0   20
   1 4605 |  15 1.0   25   139M 1311    9   0%      0 |  34.8  -2.8   28   222k   51    0   0%      0      0   20
   1 4605 |  15 1.0   22   126M 1241   35   2%  75.5k |  32.6  -2.5   28   404k   64    1   1%  1.04k  -146n   19
   1 4605 |  15 1.0   22   138M 1329    0   0%  13.7k |  34.5  -3.2   28   241k   61    0   0%      0  -113n   20
   1 4605 |  15 1.0   24   158M 1342    0   0%  19.9k |  35.1  -2.8   28   218k   50    0   0%      0  -113n   20
   1 4605 |  15 1.0   27   153M 1328    0   0%  8.46k |  35.2  -2.8   28   214k   52    0   0%      0   -48n   20
   1 4605 |  15 1.0   28   173M 1354    0   0%    16k |  35.2  -3.2   27   171k   76    0   0%    142  -113n   26
   1 4605 |  15 1.0   28   168M 1348    1   0%  7.57k |  34.8  -3.4   27   168k   74    0   0%      0  -154n   20
   1 4605 |  15 1.0   28   170M 1326    0   0%  7.03k |  34.8  -2.9   28   218k   50    0   0%      0   -97n   21
   1 4605 |  15 1.0   28   160M 1326    0   0%  14.6k |  34.2  -3.6   28   218k   50    0   0%      0  -170n   21
```

Below is the config I am using

```yml
amf:
  addr: 127.0.0.5                   # The address or hostname of the AMF.
  bind_addr: 127.0.0.1              # A local IP that the gNB binds to for traffic from the AMF.

ru_sdr:
  device_driver: uhd                # The RF driver name.
  device_args: type=x300            # Optionally pass arguments to the selected RF driver.
  clock: internal                   # Specify the clock source used by the RF.
  sync: internal                    # Specify the sync source used by the RF.
  srate: 184.32                     # RF sample rate might need to be adjusted according to selected bandwidth.
  tx_gain: 30                       # Transmit gain of the RF might need to adjusted to the given situation.
  rx_gain: 26                       # Receive gain of the RF might need to adjusted to the given situation.
  time_alignment_calibration: -54

cell_cfg:
  dl_arfcn: 650000                  # ARFCN of the downlink carrier (center frequency).
  band: 78                          # The NR band.
  channel_bandwidth_MHz: 100        # Bandwith in MHz. Number of PRBs will be automatically derived.
  common_scs: 30                    # Subcarrier spacing in kHz used for data.
  plmn: "99970"                     # PLMN broadcasted by the gNB.
  tac: 7                            # Tracking area code (needs to match the core configuration).
  pci: 1                            # Physical cell ID.

log:
  filename: /tmp/gnb.log            # Path of the log file.
  all_level: debug                # Logging level applied to all layers.

pcap:
  mac_enable: false                 # Set to true to enable MAC-layer PCAPs.
  mac_filename: /tmp/gnb_mac.pcap   # Path where the MAC PCAP is stored.
  ngap_enable: false                # Set to true to enable NGAP PCAPs.
  ngap_filename: /tmp/gnb_ngap.pcap # Path where the NGAP PCAP is stored.
srs@ws1:~/srsRAN_Project/build86ed/apps/gnb$ cp

```

**Comment by pgawlowicz** [comment]
Please check our tutorials on the gnb performance tuning:
- https://docs.srsran.com/projects/project/en/latest/tutorials/source/tuning/source/index.html
- https://docs.srsran.com/projects/project/en/latest/tutorials/source/testmode/source/index.html

**Comment by dominikheinz** [comment]
> Could you check the CPU utilization with htop?

![Image](https://github.com/user-attachments/assets/c9e883fa-766b-49de-b22a-c32d3e57f56c)

Only 1 core at 100%, but otherwise the system doesn't seem under heavy load.

**Comment by pgawlowicz** [comment]
You need to tune the `expert_execution` parameters in the gnb config, probably you should start with `nof_ul_threads` and `nof_dl_threads`. 
see here: https://docs.srsran.com/projects/project/en/latest/user_manuals/source/config_ref.html

**Comment by dominikheinz** [comment]
@pgawlowicz Okay, I want to try that.

```
expert_execution:
  threads:
    upper_phy:
      nof_ul_threads: 4
      nof_dl_threads: 4
```

This results in an error:

```
INI was not able to parse expert_execution.++
Run with --help for more information.
```

I am currently not in a postition where I can update the srsRAN version on this system.
Was the format of specifying the nof_dl_threads different in an older version of srsRAN?

**Comment by dominikheinz** [comment]
@pgawlowicz The system is running srsRAN 5G gNB version 23.5.0 (5e6f50a20).

**Comment by pgawlowicz** [comment]
OK, please update to the newest version.

**Comment by dominikheinz** [comment]
> OK, please update to the newest version.

As said above, I currently dont have permission to update the srsran version.
That being said, the system with this srsran version already was able to provide double the performance in the past, so the issue shouldnt be having not the latest version.

It seems i can set the threads like so, in this older srsran version:


```yaml
expert_phy:
  max_proc_delay: 4 # I need to set this, otherwise I cant run the gnb..?
  nof_dl_threads: 4
  nof_ul_threads: 4
```

Setting both to 4 doesnt fix the issue. Same performance.
Any other ideas @pgawlowicz ?

I am sure I am missing something obvious. This makes no sense to me.
