### ISSUE TITLE
can we record gNB trace in ms intead of seconds ??

### ISSUE THREAD

**Issue by Mohammed24699** [srsran/srsRAN_Project#1062]
I got the gNB trace in seconds but i want to compare the plots in a software which are given in microseconds. Any leads to know if its possible to change the gNB trace from recording the trace from seconds to ms.

![Image](https://github.com/user-attachments/assets/28413325-864c-4b73-b372-c6c0d61771c5)

**Comment by pgawlowicz** [comment]
You can use the metric interface (https://docs.srsran.com/projects/project/en/latest/user_manuals/source/outputs.html#json-metrics) and change the report periods:

```
metrics:
  addr: 127.0.0.1                       # Optional TEXT:IPV4 (127.0.0.1). Sets the metrics address. Supported: IPV4 address.
  port: 55555                           # Optional UINT. Sets the metrics UPD port. Supported: [0 - 65535].
  pdcp_report_period: 0                 # Optional UINT (0). Sets the PDCP metrics report period.
  rlc_report_period: 0                  # Optional UINT (0). Sets the RLC metrics report period in milliseconds. Supported [0 - inf]
```
