### ISSUE TITLE
SIB19 update in NTN - LEO satellite ephemeris

### ISSUE THREAD

**Issue by Lab1R531** [srsran/srsRAN_Project#1066]
Hi Community!
I successfully conducted the NTN experiment ([LINK](https://docs.srsran.com/projects/project/en/latest/tutorials/source/ntn/source/index.html)) with a GEO satellite using the following system:

- Amarisoft UE with NTN extension (2024-12-23)
- Channel Emulator RF
- srsRAN_Project
- Open5GS

At this point I want to focus on the LEO scenario. Using STK and Matlab I traced the orbit of the satellite that I want to emulate through Channel Emulator.
I have configured the NTN section of the gNodeB with the following file:
```

ntn:
  cell_specific_koffset: 40              # Optional INT (0). Sets the cell-specific k-offset to be used for NTN. Supported: [0 - 1023].
  ntn_ul_sync_validity_dur: 5           # Optional INT. Sets the NTN UL sync validity duration in milliseconds. Supported: [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 120, 180, 240, 900].  
    ta_info: 
    ta_common: 4634000 # 18.87 ms                           # Optional INT (0). Sets the common Timing Advance value. Supported: [0 - 66485757].
    ta_common_drift: -230000 # -46 µs/s                    # Optional INT (0). Sets the common Timing Advance drift value. Supported: [-257303 - 257303].
    ta_common_drift_variant: 0            # Optional INT (0). Sets the common Timing Advance drift variant value. Supported: [0 - 28949].
  ephemeris_info_ecef:
    pos_x: 0                              # Optional INT (0). Sets the X position of the satellite. Supported: [-67108864 - 67108863].
    pos_y:  -2166908 # -2816980.4 m                             # Optional INT (0). Sets the Y position of the satellite. Supported: [-67108864 - 67108863].
    pos_z: 4910784 #  6384019.2 m                            # Optional INT (0). Sets the Z position of the satellite. Supported: [-67108864 - 67108863].
    vel_x: 0                              # Optional INT (0). Sets the X velocity of the satellite. Supported: [-32768 - 32767].
    vel_y: 115246 # 6914.76 m/s                              # Optional INT (0). Sets the Y velocity of the satellite. Supported: [-32768 - 32767].
    vel_z: 50853 # 3051.18 m/s                              # Optional INT (0). Sets the Z velocity of the satellite. Supported: [-32768 - 32767].
cell_cfg:
  sib: # system information block 19 scheduling, SIB19 is the NTN information block
    si_window_length: 5
    si_sched_info:
      - si_period: 16
        sib_mapping: 19
  pucch:
    sr_period_ms: 80
  csi:
    csi_rs_period: 80
  pdsch: # disables HARQ processing
    max_nof_harq_retxs: 0
  prach:
    max_msg3_harq_retx: 0


```

Despite the variable

`ntn_ul_sync_validity_dur: 5 (ms)`

The ephemeris are not really updated. In fact, using the AmarisofUE online GUI it is possible to see the receipt of the SIB19 with always the same information.

How do I update the Ephemerids of the satellite so that the UE is able to maintain synchronism?
