### ISSUE TITLE
How to connect DU, CU split with nearRT RIC

### ISSUE THREAD

**Issue by newt2105** [srsran/srsRAN_Project#1083]
Hi everyone, 
I'm have 4 VM (CU, DU, RIC, Core). I already connected successfully DU, CU and Core together but i'm have some problem when I connect DU or CU with RIC.

Here is the error of CU:

```
--== srsRAN CU (commit 8120ffbce) ==--

N2: Connection to AMF on 10.0.10.96:38412 completed
E2AP: Failed to connect to RIC on 10.0.10.73:36421. error="Connection timed out" timeout=341235ms
F1-C: Listening for new connections on 10.0.10.36:38472...
Segmentation fault
``` 

and their configuration files:
CU:

```
cu_cp:
  f1ap:
    bind_addr:
      10.0.10.36 # Configure the F1AP bind address, this will enable the CU-cp to connect to the DU
  amf:
    addr: 10.0.10.96 # The address or hostname of the AMF.
    bind_addr: 10.0.10.36 # A local IP that the gNB binds to for traffic from the AMF.
    supported_tracking_areas: # Configure the TA associated with the CU-CP
      - tac: 1
        plmn_list:
          - plmn: "00101"
            tai_slice_support_list:
              - sst: 1

e2:
  enable_cu_cp_e2: true                
  enable_cu_up_e2: true                 
  addr: 10.0.10.73
  port: 36421                         
  bind_addr: 10.0.10.36               
  e2sm_kpm_enabled: true              
  e2sm_rc_enabled: true 
``` 

RIC:
```
SM_DIR = "/usr/local/lib/flexric/"

# supported name = NearRT_RIC, E2_Agent, E2_Proxy_Agent, xApp
Name = "NearRT_RIC"
NearRT_RIC_IP = "10.0.10.73"
E2_Port = 36421
E42_Port = 36422
``` 

Can someone deal with this problem before?
