### ISSUE TITLE
PBCH-MIB: CRC failed

### ISSUE THREAD

**Issue by connor01M** [srsran/srsRAN_Project#1110]
Hey SrsRAN, I am having some Issues setting up an OTA 5G network with two USRP x310s.  I have been working on trying to get the UE to connect to the GNB for over a month now and nothing seems to work. The UE just says attaching and never ends up being assigned an IP address. I have attached the CONFIG and logs below. I have tried about a million different configs. I have tried changing the bandwidth, changing the gain, and I have tried like every srate immaginable. No matter what I do, the UE logs says PBCH-MIB: CRC FAILED!!!! I have the two USRP x310s hooked up to an octoclock so that shouldn't be the issue and recently I even tried directly wiring the radios together with SMA cables and attenuators instead of using antennas and that still failed. Any help or suggestions would be greatly appreciated. Thanks!                                

GNB has no problem connecting to AMF or anything like that

UE CONFIG     [rf]
```
#freq_offset = 0
tx_gain = 3 #31.5 #25
#rx_gain = 10 #20 #ive tried like every combination
srate = 11.52e6 #15.36e6
nof_antennas = 1
 
device_name = uhd
device_args = addr=192.168.10.2,clock=external,sync = external, sampling_rate=11.52e6,lo_freq_offset_hz=11.52e6,send_frame_size=1472,recv_frame_size=1472 
time_adv_nsamples = auto #time_adv_nsamples = 300 sampling_rate=23.04e6 lo_freq_offset_hz=23.04e6,None
 

[rat.eutra]
dl_earfcn = 2850
nof_carriers = 0
 
[rat.nr]
bands = 2 #78 #3
dl_nr_arfcn = 386000
ssb_nr_arfcn = 385970    #ssb_nr_arfcn = 386000 #ssb_nr_arfcn = 385970
nof_carriers = 1
max_nof_prb = 25  #53 52 if 10MHZ bandwidth
nof_prb = 25
 
 
[pcap]
enable = none
mac_filename = /tmp/ue_mac.pcap
mac_nr_filename = /tmp/ue_mac_nr.pcap
nas_filename = /tmp/ue_nas.pcap
 
[log]
all_level = debug
phy_lib_level = info
all_hex_limit = 32
filename = /tmp/ue.log
file_max_size = -1
 
[usim]
mode = soft
algo = milenage
opc  = 63BFA50EE6523365FF14C1F45F88737D
k    = 00112233445566778899aabbccddeeff
imsi = 001010123456780
imei = 353490069873319
 
[rrc]
release = 15
ue_category = 4
 
[nas]
apn = srsapn
apn_protocol = ipv4
 
[expert]
lte_sample_rates = true
 
[gw]
#netns = ue1
#ip_devname = tun_srsue
#ip_netmask = 255.255.255.0
 
[gui]
enable = true
```

 
GNB CONFIG
 ```
cu_cp:
  amf:
    addr: 127.0.1.100                                             # The address or hostname of the AMF.
    bind_addr: 127.0.0.1         
    supported_tracking_areas:
      - tac: 7
        plmn_list:
          - plmn: "00101"
            tai_slice_support_list:
              - sst: 1
 
ru_sdr:
  device_driver: uhd
  device_args: type=x300, addr=192.168.10.2, master_clock_rate=184.32e6,send_frame_size=1472, recv_frame_size = 1472 #, send_frame_size=8000, recv_frame_size=8000  send_frame_size=1472, recv_frame_size = 1472192.168.40.2
  clock: external
  sync: external
  srate: 11.52 #15.36 #23.04
  tx_gain: 12 #20 and 31.5 tx
  rx_gain: 8 #1.5 each
 
cell_cfg:
  dl_arfcn: 386000
  band: 2
  channel_bandwidth_MHz: 5
  common_scs: 15
  plmn: "00101"
  tac: 7
  pdcch:
    dedicated:
      ss2_type: common
      dci_format_0_1_and_1_1: false
    common:
      ss0_index: 0
      coreset0_index: 0 #12 #12 if 10 mhz
  prach:
    prach_config_index: 1
  pdsch:
    mcs_table: qam64
  pusch:
    mcs_table: qam64
  pucch:  #get rid of for 10mHZ
    f0_or_f1_nof_cell_res_sr: 2
    f2_or_f3_or_f4_nof_cell_res_csi: 2
 
log:
  filename: /tmp/gnb.log                         # save the log to a specified file
  phy_level: debug  
  all_level: debug                             # debug log level for PHY layer set to debug
  phy_rx_symbols_filename: /tmp/iq.bin           # save IQ samples to a specified file
 
pcap:
  mac_enable: enable
  mac_filename: /tmp/gnb_mac.pcap
  ngap_enable: enable
  ngap_filename: /tmp/gnb_ngap.pcap
```

[ue 1.log](https://github.com/user-attachments/files/19288979/ue.1.log)

[gnbLOGSS.zip](https://github.com/user-attachments/files/19289090/gnbLOGSS.zip)
