### ISSUE TITLE
The simple_rc_xapp.py is not working properly

### ISSUE THREAD

**Issue by Gmclaro** [srsran/srsRAN_Project#1139]
Hi community!
I have a CU-DU split setup in two separate machines and the DU is connected to B210 USRP and the CU and DU are both connected to a NearRT-RIC(OS-RIC) running in a separate machine. I have tried running the simple_rc_xapp.py to manipulate the PRBs of the UE(Google Pixel 6a) I have connected to the DU. When I run the xApp in the output it shows me these messages of RIC_CONTROL_FAILURE and the upload bitrate doesn't change at all.

simple_rc_xapp.py output

```bash
nap@ric-tests:~/oran-sc-ric/xApps/python$ sudo docker compose exec python_xapp_runner ./simple_rc_xapp.py --ue_id 1
WARN[0000] /home/nap/oran-sc-ric/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
1743089711104 20/RMR [INFO] ric message routing library on SI95 p=4560 mv=3 flg=00 id=a (f447e29 4.9.4 built: Dec 13 2023)
15:35:12 Send RIC Control Request to E2 node ID: gnbd_001_001_00019b_2 for UE ID: 1, PRB_min_ratio: 1, PRB_max_ratio: 5
Received RIC_CONTROL_ACK
15:35:17 Send RIC Control Request to E2 node ID: gnbd_001_001_00019b_2 for UE ID: 1, PRB_min_ratio: 1, PRB_max_ratio: 40
Received RIC_CONTROL_FAILURE
15:35:22 Send RIC Control Request to E2 node ID: gnbd_001_001_00019b_2 for UE ID: 1, PRB_min_ratio: 1, PRB_max_ratio: 100
Received RIC_CONTROL_FAILURE
15:35:27 Send RIC Control Request to E2 node ID: gnbd_001_001_00019b_2 for UE ID: 1, PRB_min_ratio: 1, PRB_max_ratio: 5
Received RIC_CONTROL_FAILURE
15:35:32 Send RIC Control Request to E2 node ID: gnbd_001_001_00019b_2 for UE ID: 1, PRB_min_ratio: 1, PRB_max_ratio: 40
Received RIC_CONTROL_FAILURE
15:35:37 Send RIC Control Request to E2 node ID: gnbd_001_001_00019b_2 for UE ID: 1, PRB_min_ratio: 1, PRB_max_ratio: 100
Received RIC_CONTROL_FAILURE
```

DU configuration

```yaml

gnb_id: 411 # Optional UINT (411). Sets the numerical ID associated with the gNB.
gnb_id_bit_length: 22 # Optional UNIT. Sets the bit length of the gnb_id above. Format: integer between [22 - 32]

gnb_du_id: 2

cells:
  - pci: 2
    dl_arfcn: 368640 # Optional TEXT. Set the ARFCN for the above PCI. Note, this must match the value used in the cell_cfg section.
f1ap:
  cu_cp_addr: 10.0.23.73
  bind_addr: 10.0.22.247

f1u:
  socket:
    - bind_addr: 10.0.22.247
      # ext_addr: 10.0.22.176
      udp:
        max_rx_msgs: 256 # maximum packets read from the socket in a single syscall.
        pool_threshold: 0.9 # Pool occupancy threshold, after which packets are dropped.

ru_sdr:
  srate: 30.72 # Required FLOAT (61.44). Sets the sampling rate of the RF-frontend in MHz.
  device_driver: uhd # Required TEXT (uhd). RF device driver name. Supported: [uhd, zmq].
  device_args: type=b200,num_recv_frames=64,num_send_frames=64 # Optional TEXT. An argument that gets passed to the selected RF driver.
  otw_format: sc12
  tx_gain: 70
  rx_gain: 40

cell_cfg:
  dl_arfcn: 368640
  sector_id: 1
  band: 3
  channel_bandwidth_MHz: 20   # Required UINT (20). Sets the channel Bandwidth in MHz, the number of PRBs will be derived from this. Supported: [5, 10, 15, 20, 25, 30, 40, 50, 60, 70, 80, 90, 100].
  common_scs: 15
  plmn: "00101"
  tac: 1
  pci: 2
  slicing:
    - 
      sst: 1 # Sets the Slice Service Type. Supported: [0 - 255].
      sd: 0  # Sets the Service Differentiator. Supported: [0-16777215].
      sched_cfg:                              # Scheduler configuration for the slice
        min_prb_policy_ratio: 0                 # Optional UINT (0). Sets the minimum percentage of PRBs to be allocated to the slice. Supported [0 - 100].
        max_prb_policy_ratio: 100               # Optional UINT (100). Sets the maximum percentage of PRBs to be allocated to the slice. Supported [1 - 100].
e2:
  enable_du_e2: true # Optional BOOLEAN (false). Enables the DU E2 agent. Supported: [false, true].
  addr: 10.0.23.52 # Optional TEXT (127.0.0.1). Sets the RIC IP address.
  port: 36421 # Optional UINT (36421). Sets the RIC Port. Supported: [20000 - 40000].
  bind_addr: 10.0.22.247 # Optional TEXT (127.0.0.1). Sets the local IP address to bind for RIC connection. Supported: IPv4 address.
  e2sm_kpm_enabled: true # Optional BOOLEAN (false). Enabled the E2SM KPM service module. Supported: [false, true].
  e2sm_rc_enabled: true # Optional BOOLEAN (false). Enabled the E2SM RC service module. Supported: [false, true].

```

CU configuration file

``ỳaml

gnb_id: 411 # Optional UINT (411). Sets the numerical ID associated with the gNB.
gnb_id_bit_length: 22 # Optional UNIT. Sets the bit length of the gnb_id above. Format: integer between [22 - 32]

cu_cp:
  f1ap:
    bind_addr: 10.0.23.73 # Configure the F1AP bind address, this will enable the CU-cp to connect to the DU
  amf:
    addr: 10.0.23.206 # The address or hostname of the AMF.
    bind_addr: 10.0.23.73 # A local IP that the gNB binds to for traffic from the AMF.
    supported_tracking_areas: # Configure the TA associated with the CU-CP
      - tac: 1
        plmn_list:
          - plmn: "00101"
            tai_slice_support_list:
              - sst: 1

  mobility:
    trigger_handover_from_measurements: true # Optional BOOLEAN (false). Sets whether or not to start HO if neighbor cells become stronger. Supported: [false, :true]
    cells: # Optional TEXT. Sets the list of cells known to the CU-CP, their configs (if not provided over F1) and their respective neighbor cells.
      - # Define Cell 1
        nr_cell_id: 0x19B0 # Required UINT. The ID of this serving cell.
        periodic_report_cfg_id: 1 # Optional UINT. The periodical report configuration to use for this serving cell.
        ncells: # Required TEXT. List of neighbor cells.
          - nr_cell_id: 0x19B1 # Required UINT. The ID of this neighbor cell.
            report_configs: [2] # Required TEXT. List of report configurations to use for measurements of this neighbor cell.

        gnb_id_bit_length: 22 # Optional UINT. The ID of this gNB. Supported: [22 - 32]
        pci: 1 # Optional UINT. The PCI of this serving cell. Supported: [0-1007]
        ssb_arfcn: 632628
        band: 78 # Optional UINT. The NR band of this serving cell cell. Must be present if not provided over F1.
        ssb_scs: 30 # Optional UINT. The SSB subcarrier spacing of this serving cell in KHz. Must be present if not provided over F1.
        ssb_period: 20 # Optional UINT. The SSB period of this serving cell in ms.  Must be present if not provided over F1.
        ssb_offset: 0 # Optional UINT. The SSB offset of this serving cell. Must be present if not provided over F1.
        ssb_duration: 5 # Optional UINT. The SSB duration of this serving cell in subframes. Must be present if not provided over F1.

      - # Define Cell 1
        nr_cell_id: 0x19B1
        periodic_report_cfg_id: 1
        ncells:
          - nr_cell_id: 0x19B0
            report_configs: [2]
        gnb_id_bit_length: 22 # Optional UINT. The ID of this gNB. Supported: [22 - 32]
        pci: 2 # Optional UINT. The PCI of this serving cell. Supported: [0-1007]
        ssb_arfcn: 368640
        band: 3 # Optional UINT. The NR band of this serving cell cell. Must be present if not provided over F1.
        ssb_scs: 15 # Optional UINT. The SSB subcarrier spacing of this serving cell in KHz. Must be present if not provided over F1.
        ssb_period: 20 # Optional UINT. The SSB period of this serving cell in ms.  Must be present if not provided over F1.
        ssb_offset: 0 # Optional UINT. The SSB offset of this serving cell. Must be present if not provided over F1.
        ssb_duration: 5 # Optional UINT. The SSB duration of this serving cell in subframes. Must be present if not provided over F1.

    report_configs: # Sets the report configuration for triggering handover
      - report_cfg_id: 1 # Report config ID 1
        report_type: periodical # Sets the report type as periodical
        report_interval_ms: 480 # Sets to report every 480ms
      - report_cfg_id: 2
        report_type: event_triggered
        event_triggered_report_type: a3
        meas_trigger_quantity: rsrp
        meas_trigger_quantity_offset_db: 6
        hysteresis_db: 0
        time_to_trigger_ms: 100
        report_interval_ms: 1024
e2:
  enable_cu_cp_e2: true # Optional BOOLEAN (false). Enables the CU-CP E2 agent. Supported: [false, true].
  enable_cu_up_e2: true # Optional BOOLEAN (false). Enables the CU-UP E2 agent. Supported: [false, true].
  addr: 10.0.23.52 # Optional TEXT (127.0.0.1). Sets the RIC IP address.
  port: 36421 # Optional UINT (36421). Sets the RIC Port. Supported: [20000 - 40000].
  bind_addr: 10.0.23.73 # Optional TEXT (127.0.0.1). Sets the local IP address to bind for RIC connection. Supported: IPv4 address.
  e2sm_kpm_enabled: true # Optional BOOLEAN (false). Enabled the E2SM KPM service module. Supported: [false, true].
  e2sm_rc_enabled: true # Optional BOOLEAN (false). Enabled the E2SM RC service module. Supported: [false, true].

# remote_control:
#   enabled: true                        # Optional BOOLEAN (false). Enables the remote control feature. Supported: [false, true].
#   bind_addr: 127.0.0.1                  # Optional TEXT (127.0.0.1). Sets the local IP address to bind for remote control. Supported: IPv4 address.
#   port: 30000                            # Optional UINT (8001). Sets the port where the remote control server listens for incoming connections. Supported: [0 - 65535].
cu_up:
  f1u:
    socket: # Define UDP/IP socket(s) for F1-U interface.
      - # Socket 1
        bind_addr: 10.0.23.73 # Required TEXT. Sets the address that the F1-U socket will bind to.
        udp:
          max_rx_msgs: 256 # maximum packets read from the socket in a single syscall.
          pool_threshold: 0.9 # Pool occupancy threshold, after which packets are dropped.

  ngu:
    socket:
      - bind_addr: 10.0.23.244

metrics:
  cu_cp_statistics_report_period: 1 # Optional UINT (1). Sets the CU-CP statistics report period in seconds. Set this value to 0 to disable this feature. Supported: [0 - inf].
  cu_up_statistics_report_period: 1 # Optional UINT (1). Sets the CU-UP statistics report period in seconds. Set this value to 0 to disable this feature. Supported: [0 - inf].
  pdcp_report_period: 20000 # Optional UINT (0). Sets the PDCP metrics report period.

```

I would like to know if its already  possible allocate prbs to a physicall UE or am i missing something?
