### ISSUE TITLE
F1 Setup failed

### ISSUE THREAD

**Issue by newt2105** [srsran/srsRAN_Project#1194]
Hi everyone,
I am trying to connect DU, CU together at srsRAN-Project commit `9d5dd742a70e82c0813c34f57982f9507f1b6d5d `
but I have an error:
```
$ sudo ./srsdu -c du.yml e2

--== srsRAN DU (commit 9d5dd742a7) ==--


The PRACH detector will not meet the performance requirements with the configuration {Format 0, ZCZ 0, SCS 1.25kHz, Rx ports 1}.
Lower PHY in executor blocking mode.
Available radio types: zmq.
Cell pci=1, bw=10 MHz, 1T1R, dl_arfcn=368500 (n3), dl_freq=1842.5 MHz, dl_ssb_arfcn=368410, ul_freq=1747.5 MHz

F1-C: Connection to CU-CP on 192.168.1.121:38472 completed
srsRAN ERROR: F1 Setup failed. Cause: CU-CP responded with "F1 Setup Failure" with F1AP cause "message-not-compatible-with-receiver-state"
``` 

here is my CU config:
```
# Example config for a locally deployed CU listening on the localhost interface for a DU connection
# put machine (wifi) IP here: 38.68.232.181 192.168.1.173
gnb_id: 411                                                     #Optional UINT (411). Sets the numerical ID associated with the gNB.
gnb_id_bit_length: 32
ran_node_name: gnb-du-1
cu_cp:
  amf:
    addr: 10.53.1.2 
    port: 38412
    bind_addr: 10.53.1.1
    supported_tracking_areas:
      - tac: 7
        plmn_list:
          - plmn: "00101"
            tai_slice_support_list:
              - sst: 1
                sd: 1
              - sst: 1
                sd: 2
              - sst: 1
                sd: 3 
  f1ap:
    bind_addr: 192.168.1.121 # zt IP

# cu_up:
#   nru:
#     bind_addr: 192.168.1.121 # zt IP
# Added E2 configuration
e2:
  # enable_cu_e2: false
  addr: 10.0.2.10                 # RIC IP address
  bind_addr: 10.0.2.1
  port: 36421                       # RIC port
  sctp_rto_initial: 120
  sctp_rto_min: 120
  sctp_rto_max: 500
  sctp_init_max_attempts: 3
  sctp_max_init_timeo: 500
  e2sm_kpm_enabled: true
  e2sm_rc_enabled: true
  
# Added metrics configuration
# metrics:
#   cu_cp_statistics_report_period: 1
#   cu_up_statistics_report_period: 1
#   pdcp_report_period: 1
#   #enable_json_metrics: true
#   #addr: 10.147.20.132
#   #port: 55555
log:
  filename: /tmp/srscu_mobile_ric.log
  all_level: info

```
And DU:
```
f1ap:
  cu_cp_addr: 192.168.1.121                    # The address of CU-CP
  bind_addr: 192.168.1.121             


ru_sdr:
  device_driver: zmq                # The RF driver name.
  device_args: tx_port=tcp://127.0.0.1:2100,rx_port=tcp://127.0.0.1:2101,base_srate=11.52e6 # Optionally pass arguments to the selected RF driver.
  srate: 11.52                      # RF sample rate might need to be adjusted according to selected bandwidth.
  tx_gain: 75                       # Transmit gain of the RF might need to adjusted to the given situation.
  rx_gain: 75 

cell_cfg:
  slicing:
    - sst: 1
      sd: 000001
      sched_cfg:                              # Scheduler configuration for the slice
        min_prb_policy_ratio: 50                # Optional UINT (0). Sets the minimum percentage of PRBs to be allocated to the slice. Supported [0 - 100].
        max_prb_policy_ratio: 50  
    - sst: 1
      sd: 000002
      sched_cfg:                              # Scheduler configuration for the slice
        min_prb_policy_ratio:  10                # Optional UINT (0). Sets the minimum percentage of PRBs to be allocated to the slice. Supported [0 - 100].
        max_prb_policy_ratio:  10
    - sst: 1
      sd: 000003
      sched_cfg:                              # Scheduler configuration for the slice
        min_prb_policy_ratio: 50                 # Optional UINT (0). Sets the minimum percentage of PRBs to be allocated to the slice. Supported [0 - 100].
        max_prb_policy_ratio: 50 
  dl_arfcn: 368500                  # ARFCN of the downlink carrier (center frequency).
  band: 3                           # The NR band.
  channel_bandwidth_MHz: 10         # Bandwith in MHz. Number of PRBs will be automatically derived.
  common_scs: 15                    # Subcarrier spacing in kHz used for data.
  plmn: "00101"                     # PLMN broadcasted by the gNB.
  tac: 7 
  pdcch:
    common:
      ss0_index: 0                  # Set search space zero index to match srsUE capabilities
      coreset0_index: 6             # Set search CORESET Zero index to match srsUE capabilities
    dedicated:
      ss2_type: ue_dedicated           # Search Space type, has to be set to common
      dci_format_0_1_and_1_1: true # Set correct DCI format (fallback)
  prach:
    prach_config_index: 1           # Sets PRACH config to match what is expected by srsUE
    total_nof_ra_preambles: 64      # Sets number of available PRACH preambles
    nof_ssb_per_ro: 1               # Sets the number of SSBs per RACH occasion.
    nof_cb_preambles_per_ssb: 64  

e2: 
  enable_du_e2: false                   # Optional BOOLEAN (false). Enables the DU E2 agent. Supported: [false, true].
  addr: 10.0.2.10                        # Optional TEXT (127.0.0.1). Sets the RIC IP address.
  port: 36421                           # Optional UINT (36421). Sets the RIC Port. Supported: [20000 - 40000].
  bind_addr: 10.0.2.1                 # Optional TEXT (127.0.0.1). Sets the local IP address to bind for RIC connection. Supported: IPv4 address.
  sctp_rto_initial: 120                 # Optional INT (120). Sets the initial retransmission timeout when creating the SCTP connection.
  sctp_rto_min: 120                     # Optional INT (120). Sets the minimum retransmission timeout for the SCTP connection.
  sctp_rto_max: 500                     # Optional INT (500). Sets the maximum retransmission timeout for the SCTP connection.
  sctp_init_max_attempts: 3          # Optional INT (3). Sets the maximum retransmission attempts for the initial SCTP connection.
  sctp_max_init_timeo: 500              # Optional INT (500). Sets the maximum retransmission timeout for the initial SCTP connection.
  e2sm_kpm_enabled: false               # Optional BOOLEAN (false). Enabled the E2SM KPM service module. Supported: [false, true].
  e2sm_rc_enabled: false 

log: 
# All gNB layers and components can be configured independently to output at various levels of detail. Logs can be configured to the following levels (from lowest to highest levels of detail):
# none, error, warning, info, debug
  filename: /tmp/du.log                             # Optional TEXT (/tmp/gnb.log). File path for logs. Logs can be redirected to stdout by setting the filename to "stdout".
  all_level: debug

```  
Have anyone meet this issue? 
Thanks!
