### ISSUE TITLE
DPDK srsRAN tests

### ISSUE THREAD

**Issue by abousselmi** [srsran/srsRAN_Project#1225]
Hi,

I'm trying to execute a test based on [this](https://github.com/srsran/srsRAN_Project/discussions/718), but for some reason the execution does not go beyond DPDK initialization. Am I missing something ?

`vfio-pci` is loaded (using and RT kernel), VFs are created and bound to DPDK using the helper script. Kernel flags are correctly set in grub and hugepages are also configured.

gNB config:

```
ru_ofh:
  gps_alpha: 0
  gps_beta: 0
  ru_bandwidth_MHz: 20
  t1a_max_cp_dl: 500
  t1a_min_cp_dl: 258
  t1a_max_cp_ul: 500
  t1a_min_cp_ul: 258
  t1a_max_up: 300
  t1a_min_up: 85
  ta4_max: 300
  ta4_min: 85
  is_prach_cp_enabled: true
  is_dl_broadcast_enabled: false
  ignore_ecpri_seq_id: false
  ignore_ecpri_payload_size: false
  warn_unreceived_ru_frames: true
  compr_method_ul: bfp
  compr_bitwidth_ul: 9
  compr_method_dl: bfp
  compr_bitwidth_dl: 9
  compr_method_prach: bfp
  compr_bitwidth_prach: 9
  enable_ul_static_compr_hdr: true
  enable_dl_static_compr_hdr: true
  iq_scaling: 0.35
  cells:
    - network_interface: 0000:17:00.0
      ru_mac_addr: 80:61:5f:0d:df:ab
      du_mac_addr: 64:b3:79:10:00:37
      vlan_tag_cp: 2
      vlan_tag_up: 2
      prach_port_id: [4,5]
      dl_port_id: [0,1]
      ul_port_id: [0,1]

cell_cfg:
  dl_arfcn: 637212
  band: 78
  channel_bandwidth_MHz: 20
  common_scs: 30
  plmn: "00101"
  tac: 7
  pci: 1
  nof_antennas_dl: 2
  nof_antennas_ul: 2
  prach:
    prach_config_index: 7
    prach_root_sequence_index: 1
    zero_correlation_zone: 0
    prach_frequency_start: 0
  tdd_ul_dl_cfg:
    dl_ul_tx_period: 10
    nof_dl_slots: 7
    nof_dl_symbols: 6
    nof_ul_slots: 2
    nof_ul_symbols: 4

hal:
  eal_args: "--lcores (0-1)@(2,4,6,8,10,12,14,16,18,20) -a 0000:3b:02.0"
```

UE config:

```
ru_emu:
  cells:
  - bandwidth: 100
    network_interface: 0000:3b:02.1
    ru_mac_addr: 80:61:5f:09:b6:c7
    du_mac_addr: 80:61:5f:09:b6:c6
    vlan_tag: 2
    ul_port_id: [0]
    compr_method_ul: "bfp"
    compr_bitwidth_ul: 9

log:
  filename: /tmp/ru.log
  level: warning

dpdk:
  eal_args: "--lcores (0-1)@(2,4,6,8,10,12,14,16,18,20) -a 0000:3b:02.1 --file-prefix ru"
```

gNB exec command and log:

```
./gnb -c /config/gnb.yaml cu_cp amf --no_core true test_mode test_ue --rnti 0x1 --ri 2

--== srsRAN gNB (commit ef4b0749a1) ==--


The PRACH detector will not meet the performance requirements with the configuration {Format 0, ZCZ 0, SCS 1.25kHz, Rx ports 1}.
EAL: Detected CPU lcores: 48
EAL: Detected NUMA nodes: 2
EAL: Detected shared linkage of DPDK
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: Selected IOVA mode 'VA'
EAL: VFIO support initialized
EAL: Using IOMMU type 1 (Type 1)
EAL: Probe PCI driver: net_iavf (8086:154c) device: 0000:3b:02.0 (socket 0)
TELEMETRY: No legacy callbacks, legacy socket not created

```

UE exec command and logs:

```
./ru_emulator -c /config/ru.yaml


EAL: Detected CPU lcores: 48
EAL: Detected NUMA nodes: 2
EAL: Detected shared linkage of DPDK
EAL: Multi-process socket /var/run/dpdk/ru/mp_socket
EAL: Selected IOVA mode 'VA'
EAL: VFIO support initialized
EAL: Using IOMMU type 1 (Type 1)
EAL: Probe PCI driver: net_iavf (8086:154c) device: 0000:3b:02.1 (socket 0)
TELEMETRY: No legacy callbacks, legacy socket not created

```

Log files are empty. 

Thanks for your help !
