### ISSUE TITLE
ssb_set using remote_control websocket causes disconnection

### ISSUE THREAD

**Issue by aibtw** [srsran/srsRAN_Project#1236]
I configured the DU as following:
```
# Example config for a DU with one 20MHz TDD cell using a USRP as RF frontend.
f1ap:
  cu_cp_addr: 127.0.10.1
  bind_addr: 127.0.10.2

ru_sdr:
  device_driver: uhd
  device_args: type=b200,num_recv_frames=64,num_send_frames=64
  srate: 23.04
  otw_format: sc12  
  tx_gain: 70
  rx_gain: 50

cell_cfg:
  dl_arfcn: 632628
  band: 78
  channel_bandwidth_MHz: 20
  common_scs: 30
  plmn: "99970"
  tac: 7
  pci: 1

  ssb:
    ssb_block_power_dbm: -16
remote_control:
  enabled: true                        # Optional BOOLEAN (false). Enables the remote control feature. Supported: [false, true].
  bind_addr: 127.0.0.1                  # Optional TEXT (127.0.0.1). Sets the local IP address to bind for remote control. Supported: IPv4 address.
  port: 8001                            # Optional UINT (8001). Sets the port where the remote control server listens for incoming connections. Supported: [0 - 65535].     

log:
  filename: /tmp/du.log
  all_level: debug

metrics: 
  autostart_stdout_metrics: true       # Optional BOOLEAN (false). Sets whether or note to autostart stdout metrics reporting. Supported [false, true].

``` 

I created a Python client to the websocket to set SSB power to -15 instead of -16: 
```
import asyncio
import websockets
import json

async def send_ssb_set():
    uri = "ws://127.0.0.1:8001"
    payload = {
        "cmd": "ssb_set",
        "cells": [
            {
                "plmn": "99970",
                "nci": 6733824,
                "ssb_block_power_dbm": -15 
            }
        ]
    }

    async with websockets.connect(uri) as websocket:
        await websocket.send(json.dumps(payload))
        response = await websocket.recv()
        print(f"Response from server: {response}")

asyncio.run(send_ssb_set())
```

When I run the system (Open5gs e12b1be31, srsRAN CU and DU d5fa4f0ecb or 122a1377e3 same behavior on both, USRP B210) then I start the python client, I get response from the server:
``` Response from server: {"cmd":"ssb_set"} ```
However, any UE that was connected to the network will disconnect **and no UE will ever connect again** until I restart the whole DU. 

Please find logs attached. 

[cu.log](https://github.com/user-attachments/files/20557361/cu.log)
[du.log](https://github.com/user-attachments/files/20557360/du.log)
link to pcaps
https://drive.google.com/drive/folders/1H2ZiM4gl1xbs5pBqiWORzfZxQzcaNGmf?usp=sharing

Not sure if this a bug or just a work in progress for a certain feature.
