### ISSUE TITLE
UE no detect a carrier with bandwidth 10mhz or 15mhz in tdd

### ISSUE THREAD

**Issue by EugeneBogush** [srsran/srsRAN_Project#128]
## Issue Description ##
I using Fibocom 150 for connecting to gnb.
and all work great in tdd mode with bandwidth 20 Mhz:
```
cell_cfg:
  dl_arfcn: 632610            
  band: 78                    
  channel_bandwidth_MHz: 20       
  common_scs: 30                             
  plmn: "46601"                                                   
  tac: 1                                                          
  pci: 13          
```                                               
When i change bandwidth to 10mhz or 15mhz my modem not detect a carrier at all.
```
cell_cfg:
  dl_arfcn: 632610            
  band: 78                    
  channel_bandwidth_MHz: 10       
  common_scs: 30                             
  plmn: "46601"                                                   
  tac: 1                                                          
  pci: 13          
```
