### ISSUE TITLE
Real-time failure in FAPI in Debug Mode

### ISSUE THREAD

**Issue by aibtw** [srsran/srsRAN_Project#242]
## Issue Description ##
I am working on the current main branch. I wanted to understand the behavior of some part of the code, which is why **I used debug build mode.** When building with debug mode and running the gnb (either directly or through gdb or vscode debugger, doesn't matter), I get "Real-time failure in FAPI" in the log file, and COTS UE can't connect. However, the same exact setup works fine if I switch to release build mode.

## Setup Details ##
* Intel NUC, 12th Gen Intel® Core™ i5-1240P × 16, 16GB RAM
* B210 USRP connected to USB3 port
* realme 9i 5G Phone as UE
* Core Network through open5gs

## Expected Behavior ##
COTS UE connecting to the cell, and tracing information available through gNB. Also, I am expecting ip routing and network masquerading to be working fine such that the UE can have access to the internet. 

## Actual Behaviour ##
* When running with debug mode, there is no tracing information available, and no connection from the UE side. Check the log files:
[gnb.log](https://github.com/srsran/srsRAN_Project/files/12846363/gnb.log)

* When running with release mode, connection is fine, I can see tracing information, and the UE connects successfully. 
So clearly my problem is in debug mode, but what is causing that?

## Steps to reproduce the problem ##
I followed the guides on srsRAN_Project docs and open5gs docs.
Please check the configuration files:
gnb config file:
```
# This configuration file example shows how to configure the srsRAN Project gNB to connect to a COTS UE. As with the 
# associated tutorial, this config has been tested with a OnePlus 8T. A B210 USRP is used as the RF-frontend.   
# This config creates a TDD cell with 20 MHz bandwidth in band 78. 
# To run the srsRAN Project gNB with this config, use the following command: 
#   sudo ./gnb -c gnb_b210_20MHz_oneplus_8t.yaml

amf:
  addr: 127.0.1.100                                             # The address or hostname of the AMF.
  bind_addr: 127.0.0.1                                          # A local IP that the gNB binds to for traffic from the AMF.

ru_sdr:
  device_driver: uhd                                            # The RF driver name.
  device_args: type=b200,num_recv_frames=64,num_send_frames=64  # Optionally pass arguments to the selected RF driver.
  clock: internal                                               # Specify the clock source used by the RF.
  sync:                                                         # Specify the sync source used by the RF.
  srate: 23.04                                                  # RF sample rate might need to be adjusted according to selected bandwidth.
  otw_format: sc12
  tx_gain: 80                                                   # Transmit gain of the RF might need to adjusted to the given situation.
  rx_gain: 40                                                   # Receive gain of the RF might need to adjusted to the given situation.

cell_cfg:
  dl_arfcn: 627340                                              # ARFCN of the downlink carrier (center frequency).
  band: 78                                                      # The NR band.
  channel_bandwidth_MHz: 20                                     # Bandwith in MHz. Number of PRBs will be automatically derived.
  common_scs: 30                                                # Subcarrier spacing in kHz used for data.
  plmn: "99970"                                                 # PLMN broadcasted by the gNB.
  tac: 7                                                        # Tracking area code (needs to match the core configuration).
  pci: 1                                                        # Physical cell ID.

log: 
# All gNB layers and components can be configured independently to output at various levels of detail. Logs can be configured to the following levels (from lowest to highest levels of detail):
# none, error, warning, info, debug
  filename:                             # Optional TEXT (/tmp/gnb.log). File path for logs
  all_level: debug                    # Optional TEXT (warning). Sets a common log level across PHY, MAC, RLC, PDCP, RRC, SDAP, NGAP and GTPU layers

pcap:
  mac_enable: false                                             # Set to true to enable MAC-layer PCAPs.
  mac_filename: /tmp/gnb_mac.pcap                               # Path where the MAC PCAP is stored.
  ngap_enable: false                                            # Set to true to enable NGAP PCAPs.
  ngap_filename: /tmp/gnb_ngap.pcap                             # Path where the NGAP PCAP is stored.
  
#   e2ap_enable: true                 # Set to true to enable E2AP PCAPs.
#   e2ap_filename: /tmp/gnb_e2ap.pcap # Path where the E2AP PCAP is stored.

# e2:
#   enable_du_e2: true                # Enable DU E2 agent (one for each DU instance)
#   e2sm_kpm_enabled: true            # Enable KPM service module
```

amf.yaml
```

logger:
    file: /var/log/open5gs/amf.log

sbi:
    server:
      no_tls: true
      cacert: /etc/open5gs/tls/ca.crt
      key: /etc/open5gs/tls/amf.key
      cert: /etc/open5gs/tls/amf.crt
    client:
      no_tls: true
      cacert: /etc/open5gs/tls/ca.crt
      key: /etc/open5gs/tls/amf.key
      cert: /etc/open5gs/tls/amf.crt

amf:
    sbi:
      - addr: 127.0.0.5
        port: 7777
    ngap:
      - addr: 127.0.1.100
    metrics:
      - addr: 127.0.0.5
        port: 9090
    guami:
      - plmn_id:
          mcc: 999
          mnc: 70
        amf_id:
          region: 2
          set: 1
    tai:
      - plmn_id:
          mcc: 999
          mnc: 70
        tac: 7
    plmn_support:
      - plmn_id:
          mcc: 999
          mnc: 70
        s_nssai:
          - sst: 1
    security:
        integrity_order : [ NIA2, NIA1, NIA0 ]
        ciphering_order : [ NEA0, NEA1, NEA2 ]
    network_name:
        full: mobisense
    amf_name: open5gs-amf0


scp:
    sbi:
      - addr: 127.0.1.10
        port: 7777

parameter:

max:

usrsctp:

time:
  t3512:
    value: 540     # 9 mintues * 60 = 540 seconds
```

upf.yaml:
```

#
logger:
    file: /var/log/open5gs/upf.log


upf:
    pfcp:
      - addr: 127.0.0.7
    gtpu:
      - addr: 127.0.1.100
    subnet:
      - addr: 10.45.0.1/16
      - addr: 2001:db8:cafe::1/48
    metrics:
      - addr: 127.0.0.7
        port: 9090

smf:


parameter:


max:


time:
```
