### ISSUE TITLE
no PDU Session establishment between GNB and UE

### ISSUE THREAD

**Issue by tilldroemmer** [srsran/srsRAN_Project#269]
## Issue Description ##
[Describe the issue in detail]
When running the GNB and UE, an RRC connection is established, but no PDU session is established, therefore no ip address is assigned to the UE. I get the same result with wireless and wired connection, I also tried using a GPSDO, both didn't have any impact on the result.

I tried to confirm that the core is running as intended by using UERANSIM (logs and configs below):
When running UERANSIM, GNB and UE start as intended and an PDU session is established for the UE. An ip address is assigned to the UE.

## Setup Details ##
[Specify details of the test setup. This would help us reproduce the problem reliably]
e.g. Network configuration, Operation System, Hardware, RF front-end, library and driver versions

- I ran the performance script.
- uhd_usrp_probe works on all used devices as it should

UE:
B200mini
Ubuntu 20.04
UHD 4.4
Intel(R) Core(TM) i7-7700T CPU @ 2.90GHz
Thread(s) per core:              1
Core(s) per socket:              4
Socket(s):                            1
NUMA node(s):                    1

GNB:
X310
Ubuntu 20.04
UHD 4.4
Intel(R) Core(TM) i7-7700T CPU @ 2.90GHz
Thread(s) per core:              1
Core(s) per socket:              4
Socket(s):                            1
NUMA node(s):                    1

Core:
Open5GS
Ubuntu 20.04
Intel(R) Core(TM) i7-7700T CPU @ 2.90GHz
Thread(s) per core:              1
Core(s) per socket:              4
Socket(s):                            1
NUMA node(s):                    1

## Expected Behavior ##
[What you expect to happen]
PDU session establishment and ip address asignment like in the tutorial [here](https://docs.srsran.com/projects/project/en/latest/tutorials/source/srsUE/source/index.html)
![tutorial](https://github.com/srsran/srsRAN_Project/assets/143410278/55014b3b-dbb3-470c-b31a-55d8a4c93a1c)

## Actual Behaviour ##
[What happens instead e.g. error message]
Core is starting and connecting to AMF, UE is starting and Connecting to the GNB, but no PDU session is established. In the Core no registration of the UE can be seen.
Logs, configs and traffic captured with wireshark below.
![ue](https://github.com/srsran/srsRAN_Project/assets/143410278/bd1fc325-3628-4983-b908-50b70d3f1165)

## Steps to reproduce the problem ##
[Tell us how to reproduce this issue e.g. RF setup, application config files]
As stated above, UE, GNB and Core run on seperate machines, the config files can be found below.
I am using the srsRAN_Project GNB and the srsRAN_4G UE.
[core.zip](https://github.com/srsran/srsRAN_Project/files/13113141/core.zip)
[gnb.zip](https://github.com/srsran/srsRAN_Project/files/13113142/gnb.zip)
[ue.zip](https://github.com/srsran/srsRAN_Project/files/13113143/ue.zip)
[UERANSIM.zip](https://github.com/srsran/srsRAN_Project/files/13113145/UERANSIM.zip)

## Additional Information ##
[Any additional information, configuration or data that might be necessary to reproduce the issue]

**Comment by brendan-mcauliffe** [comment]
Hi @tilldroemmer your gNB config is wrong. Have a look at the example config for the gNB [here](https://docs.srsran.com/projects/project/en/latest/tutorials/source/srsUE/source/index.html#). Your `cell_cfg` should be configured like so: 

```
  dl_arfcn: 368500                  # ARFCN of the downlink carrier (center frequency).
  band: 3                           # The NR band.
  channel_bandwidth_MHz: 10         # Bandwith in MHz. Number of PRBs will be automatically derived.
  common_scs: 15                    # Subcarrier spacing in kHz used for data.
  plmn: "00101"                     # PLMN broadcasted by the gNB.
  tac: 7                            # Tracking area code (needs to match the core configuration).
  pdcch:
    dedicated:
      ss2_type: common              # Search Space type, has to be set to common
      dci_format_0_1_and_1_1: false # Set correct DCI format (fallback)
  prach:
    prach_config_index: 1
```
Your gain values are also quite low for both the UE and gNB, you could try increasing them. Other than that your configuration looks to be OK. Check against the example configs, making sure to use above parameters for the gNB `cell_cfg`.
