### ISSUE TITLE
RAN550: No IQ data transmitted

### ISSUE THREAD

**Issue by doudoulail** [srsran/srsRAN_Project#302]
## Issue Description ##
[Describe the issue in detail]
I tried to ofh link ran550, but there was such an error in the log. Besides, I also found that no IQ data was transmitted through packet capture
This is my srsran configuration file
[gnb.txt](https://github.com/srsran/srsRAN_Project/files/13306858/gnb.txt)
this is my gnb.log
[gnb.log](https://github.com/srsran/srsRAN_Project/files/13306868/gnb.log)
![1699525163911](https://github.com/srsran/srsRAN_Project/assets/61570171/141040a8-82fb-404c-970f-1c995c042a08)
I configured it according to document, but I don't know what happened
gnb.log
```
2023-11-09T09:46:19.003201 [FAPI    ] [W] [  724.11] Real-time failure in FAPI: Received late DL_TTI.request from slot 724.10
2023-11-09T09:46:19.033444 [OFH     ] [W] Detected 3 lost messages
2023-11-09T09:46:19.033504 [OFH     ] [W] Detected 1 lost messages
2023-11-09T09:46:19.033562 [OFH     ] [W] Detected 1 lost messages
2023-11-09T09:46:19.033643 [OFH     ] [W] Detected 1 lost messages
2023-11-09T09:46:19.033731 [OFH     ] [W] Detected 1 lost messages
2023-11-09T09:46:19.033803 [OFH     ] [W] Detected 1 lost messages
2023-11-09T09:46:19.034023 [OFH     ] [W] Detected 2 lost messages
2023-11-09T09:46:19.034100 [OFH     ] [W] Detected 1 lost messages
2023-11-09T09:46:19.034239 [OFH     ] [W] Detected 1 lost messages
2023-11-09T09:46:19.034293 [OFH     ] [W] Detected 2 lost messages
2023-11-09T09:46:19.034376 [OFH     ] [W] Detected 1 lost messages
2023-11-09T09:46:19.034588 [OFH     ] [W] Detected 3 lost messages
2023-11-09T09:46:19.034834 [OFH     ] [W] Detected 1 lost messages
2023-11-09T09:46:19.034997 [OFH     ] [W] Detected 1 lost messages
2023-11-09T09:46:19.035011 [OFH     ] [W] Detected 1 lost messages
2023-11-09T09:46:19.035075 [OFH     ] [W] Detected 2 lost messages
2023-11-09T09:46:19.035088 [OFH     ] [W] Detected 2 lost messages
```
srsran configration
```
# This example configuration outlines how to configure the srsRAN Project CU/DU to use an O-RU and split 7.2. This is specifically for use
# with the Benetel R550 RU. This config will create a single TDD MIMO cell transmitting in band 78, with 20 MHz bandwidth and 30 kHz sub-carrier-spacing.
# The parameters used to configure the RU are found in the `ru_ofh` sub-section. This configuration makes used of the OFH Lib from SRS to enable split 7.2.

amf:
  addr: xxxx                                                # The address or hostname of the AMF.
  bind_addr: xxxx                                       # A local IP that the gNB binds to for traffic from the AMF.

ru_ofh:
  gps_alpha: 0                          # Optional FLOAT (0). Sets the GPS alpha. Supported: [0 - 1.2288e+07].
  gps_beta: 0                           # Optional INT (0). Sets the GPS beta. Supported: [-32768 - +32767].
  ru_bandwidth_MHz: 100                                           # RU instantaneous bandwidth.
  t1a_max_cp_dl: 500                                              # Maximum T1a on Control-Plane for Downlink in microseconds.
  t1a_min_cp_dl: 250                                              # Minimum T1a on Control-Plane for Downlink in microseconds.
  t1a_max_cp_ul: 465                                              # Maximum T1a on Control-Plane for Uplink in microseconds.
  t1a_min_cp_ul: 250                                              # Minimum T1a on Control-Plane for Uplink in microseconds.
  t1a_max_up: 250                                                 # Maximum T1a on User-Plane in microseconds.
  t1a_min_up: 80                                                  # Minimum T1a on User-Plane in microseconds.
  ta4_max: 300                          # Optional UINT (300). Sets the Ta4 maximum value for User-Plane. Supported: [0 - 1960].
  ta4_min: 85                           # Optional UINT (85). Sets the Ta4 maximum value for User-Plane. Supported: [0 - 1960].
  is_prach_cp_enabled: true                                      # Configures if Control-Plane messages should be used to receive PRACH messages.
  is_dl_broadcast_enabled: false                                   # Set to true for a workaround over a firmware bug in the RAN550 when operating in SISO mode.
  ignore_ecpri_payload_size: true          # Optional BOOLEAN (0). Sets whether or not to ignore eCPRI payload size field value. Supported [0. 1].
  compr_method_ul: bfp                                            # Uplink compression method.  
  compr_bitwidth_ul: 9                                            # Uplink IQ samples bitwidth after compression.
  compr_method_dl: bfp                                            # Downlink compression method.
  compr_bitwidth_dl: 9                                            # Downlink IQ samples bitwidth after compression.
  compr_method_prach: bfp                                         # PRACH compression method.
  compr_bitwidth_prach: 16                                         # PRACH IQ samples bitwidth after compression.
  enable_ul_static_compr_hdr: false                               # Configures if the compression header is present for uplink User-Plane messages (false) or not present (true).
  enable_dl_static_compr_hdr: false                                # Configures if the compression header is present for downlink User-Plane messages (false) or not present (true).
  
  iq_scaling: 0.8                                                # IQ samples scaling factor applied before compression, should be a positive value smaller than 1.
  cells:
    - network_interface: ens3f0                                 # Ethernet interface name used to communicate with the RU.
      ru_mac_addr: 00:11:22:33:44:55                              # RU MAC address.
      du_mac_addr: 50:7c:6f:53:ea:4c                              # DU MAC address.
      vlan_tag: 3                                                 # VLAN tag value.
      prach_port_id: [0,1,2,3]                                          # PRACH eAxC port value.
      dl_port_id: [0,1,2,3]   #[0,1]                                           # Downlink eAxC port values.
      ul_port_id: [0,1,2,3]                                             # Uplink eAxC port values.

cell_cfg:
  dl_arfcn: 504990                                                # ARFCN of the downlink carrier (center frequency).
  band: 41                                                        # The NR band.
  channel_bandwidth_MHz: 20                                       # Bandwith in MHz. Number of PRBs will be automatically derived.
  common_scs: 30                                                  # Subcarrier spacing in kHz used for data.
  plmn: "xxxx"                                                   # PLMN broadcasted by the gNB.
  tac: 1                                                          # Tracking area code (needs to match the core configuration).
  pci: 1                                                          # Physical cell ID.
  nof_antennas_dl: 4                                              # Number of transmission antennas.
  nof_antennas_ul: 1                                              # Number of reception antennas.    
  prach:
    prach_config_index: 159                                         # PRACH configuration index.
    prach_root_sequence_index: 1                                  # PRACH root sequence index.
    zero_correlation_zone: 0                                      # Zero correlation zone.
    prach_frequency_start: 12      # Offset in PRBs of lowest PRACH transmission occasion in frequency domain respective to PRB 0.
  tdd_ul_dl_cfg:
    nof_dl_slots: 7
    nof_dl_symbols: 6                         # Optional INT (0). Number of Downlink symbols at the beginning of the slot following full Downlink slots. Supported: [0-13]
    nof_ul_slots: 2
    nof_ul_symbols: 4                         # Optional INT (0). Number of Uplink symbols at the end of the slot preceding the first full Uplink slot. Supported: [0-13].
  pucch:
    #min_k1: 2
  pusch:
    #min_k2: 2

      #expert_cfg:
      #enable_tuned_affinity_profile: true
      #number_of_threads_per_cpu: 1
      #number_of_reserved_cores: 4

expert_phy:
  #max_proc_delay: 5
     #pusch_dec_max_iterations: 6           # Optional UINT (6). Sets the number of PUSCH LDPC decoder iterations. Format: Positive integer greater than 0.
     #pusich_dec_enable_early_stop: true     # Optional BOOL (true). Enables the PUSCH decoder early stopping mechanism.
     #pusch_sinr_calc_method: evm           # Optional TEXT (evm). Sets the PUSCH SINR calculation method. Supported: [channel_estimator, post_equalization, evm].
expert_execution:
  threads: 
    upper_phy: 
      #pdsch_processor_type: auto                    # Optional TEXT (auto). Sets the PDSCH processor type. Supported: [auto, generic, concurrent, lite].
        #nof_pdsch_threads: 1                          # Optional UINT (4). Sets the number of threads used to encode PDSCH.
        #nof_pusch_threads: 1                          # Optional UINT (1). Sets the number of threads used to encode PUSCH.
        #nof_ul_threads: 1                             # Optional UINT (1). Sets the number of upprt PHY threads to proccess uplink.
        #nof_dl_threads: 1                             # Optional UINT (1). Sets the number of upprt PHY threads to proccess downlink.  
    ofh: 
      #enable_dl_parallelization: 1                  # Optional BOOLEAN. Sets the Open Fronthaul downlink parallelization flag. Supported: [0, 1].

log:
  filename: /home/sun/gnb.log                                          # Path of the log file.
  all_level: warning                                              # Logging level applied to all layers.

pcap:
  mac_enable: true                                               # Set to true to enable MAC-layer PCAPs.
  mac_filename: /home/sun/gnb_mac.pcap                                 # Path where the MAC PCAP is stored.
  ngap_enable: false                                              # Set to true to enable NGAP PCAPs.
  ngap_filename: /tmp/gnb_ngap.pcap                               # Path where the NGAP PCAP is stored.
```

**Comment by ismagom** [comment]
Hi @doudoulail , can you edit your comment and format it accordingly? 

```
use this for code or config files
```

It's very difficult to read otherwise. Thanks

**Comment by doudoulail** [comment]
Okay, I'll upload it again

**Comment by doudoulail** [comment]
> Hi @doudoulail , can you edit your comment and format it accordingly?
> 
> ```
> use this for code or config files
> ```
> 
> It's very difficult to read otherwise. Thanks

Hi @ismagom ,I have changed, thank you, the log I intercepted, because it is the same warning after

**Comment by doudoulail** [comment]
> Hi @doudoulail , can you edit your comment and format it accordingly?
> 
> ```
> use this for code or config files
> ```
> 
> It's very difficult to read otherwise. Thanks

**Comment by ismagom** [comment]
Can you also provide the following information? 

- CPU model
- RAN550 firmware version
- srsRAN commit hash
- Network setup, do you have a switch between the RAN550 and the gNB? 
- PTP setup. What devices are you using for PTP. Can you share PTP logs from the gNB server and RAN550? 

thanks

**Comment by ismagom** [comment]
Also, I took the liberty to edit the subject, since this better describes the real issue

**Comment by doudoulail** [comment]
Okay, thanks

> I used xeon Platinum 6336y@ 3.10GHz dual socket with 24 real cores / 48 logical cores each, 64G RAM, a 10G fiber link to the RU,Use linuxptp and a synce network card for synchronization on the machine where srsran is located.

> RAN550 firmware version: sw V0.8.1

> srsRAN commit hash：srsRAN Project 23.10.1 

> Not have a switch between the RAN550 and the gNB

> the logs
ptp4l[1221.966]: rms    6 max   14 freq -25784 +/-   9 delay   172 +/-   1
ptp4l[1223.091]: rms    5 max   10 freq -25778 +/-   8 delay   170 +/-   1
ptp4l[1224.216]: rms    6 max   11 freq -25781 +/-   9 delay   169 +/-   1
ptp4l[1225.341]: rms    5 max   10 freq -25783 +/-   8 delay   170 +/-   1

**Comment by doudoulail** [comment]
I made sure the ptp was working and synchronized on the ran550 side

**Comment by ismagom** [comment]
And in addition to the above comment: 

- Have you verified if you see any signal coming out the RU? 
- Have you looked at the C/U-plane counters at RU logs?

**Comment by doudoulail** [comment]
> And in addition to the above comment:
> 
> * Have you verified if you see any signal coming out the RU?
> * Have you looked at the C/U-plane counters at RU logs?

> Yeah, I saw a U-plan emanating from the ru side and found a C/U-plane input from the oru counter

**Comment by doudoulail** [comment]
I made some configuration changes, and no cpu frequency scaling is applied during the application run，But it still shows up as 0.
```
is_dl_broadcast_enabled: true 
 iq_scaling: 1.7 #0.27                                                # IQ samples scaling factor applied before compression, should be a positive value smaller than 1.
  cells:
    - network_interface: ens3f0                                 # Ethernet interface name used to communicate with the RU.
      ru_mac_addr: 00:11:22:33:44:55                              # RU MAC address.
      du_mac_addr: 50:7c:6f:53:ea:4c                              # DU MAC address.
      vlan_tag: 3                                                 # VLAN tag value.
      prach_port_id: [0]                                          # PRACH eAxC port value.
      dl_port_id: [0,1]   #[0,1]                                           # Downlink eAxC port values.
      ul_port_id: [0]                                             # Uplink eAxC port values.

cell_cfg:
  dl_arfcn: 504990                                                # ARFCN of the downlink carrier (center frequency).
  band: 41                                                        # The NR band.
  channel_bandwidth_MHz: 100                                       # Bandwith in MHz. Number of PRBs will be automatically derived.
  common_scs: 30                                                  # Subcarrier spacing in kHz used for data.
  plmn: "xxxx"                                                   # PLMN broadcasted by the gNB.
  tac: 1                                                          # Tracking area code (needs to match the core configuration).
  pci: 1                                                          # Physical cell ID.
  nof_antennas_dl: 1                                              # Number of transmission antennas.
  nof_antennas_ul: 1                                              # Number of reception antennas.  
```
I found some other problems, and still no correlation IQ transfer
[gnb.log](https://github.com/srsran/srsRAN_Project/files/13314810/gnb.log)

**Comment by doudoulail** [comment]
Hi @ismagom ,Thanks,I have now discovered a new problem and I am not sure if it is because of my problem,Whether I set whether to compress or not, type1 always shows no compression and the compression bit width is 0.
![1699679905089](https://github.com/srsran/srsRAN_Project/assets/61570171/987df7c8-30f9-4bee-88f6-e6e2fc28e342)
[gnb.log](https://github.com/srsran/srsRAN_Project/files/13324533/gnb.log)

```
amf:
  addr: xxxx                                               # The address or hostname of the AMF.
  bind_addr: xxxx                                            # A local IP that the gNB binds to for traffic from the AMF.

ru_ofh:
  ru_bandwidth_MHz: 100                                           # RU instantaneous bandwidth.
  t1a_max_cp_dl: 400                                              # Maximum T1a on Control-Plane for Downlink in microseconds.
  t1a_min_cp_dl: 150                                              # Minimum T1a on Control-Plane for Downlink in microseconds.
  t1a_max_cp_ul: 465                                              # Maximum T1a on Control-Plane for Uplink in microseconds.
  t1a_min_cp_ul: 250                                              # Minimum T1a on Control-Plane for Uplink in microseconds.
  t1a_max_up: 250                                                 # Maximum T1a on User-Plane in microseconds.
  t1a_min_up: 80                                                  # Minimum T1a on User-Plane in microseconds.
  is_prach_cp_enabled: true                                      # Configures if Control-Plane messages should be used to receive PRACH messages.
  is_dl_broadcast_enabled: true 
  compr_method_ul: bfp                                            # Uplink compression method.
  compr_bitwidth_ul: 9                                            # Uplink IQ samples bitwidth after compression.
  compr_method_dl: bfp                                            # Downlink compression method.
  compr_bitwidth_dl: 9                                            # Downlink IQ samples bitwidth after compression.
  compr_method_prach: bfp                                         # PRACH compression method.
  compr_bitwidth_prach: 9                                         # PRACH IQ samples bitwidth after compression.
  enable_ul_static_compr_hdr: false                                # Configures if the compression header is present for uplink User-Plane messages (false) or not present (true).
  enable_dl_static_compr_hdr: false                                # Configures if the compression header is present for downlink User-Plane messages (false) or not present (true).
  iq_scaling: 1.5                                                # IQ samples scaling factor applied before compression, should be a positive value smaller than 10.
  cells:
    - network_interface: ens3f0                                 # Ethernet interface name used to communicate with the RU.
      ru_mac_addr: 00:11:22:33:44:55                              # RU MAC address.
      du_mac_addr: 50:7c:6f:53:ea:4c                              # DU MAC address.
      vlan_tag: 3                                                 # VLAN tag value.
      prach_port_id: [4]                                          # PRACH eAxC port value.
      dl_port_id: [0]                                          # Downlink eAxC port values.
      ul_port_id: [0]                                          # Uplink eAxC port values.

cell_cfg:
  dl_arfcn: 504990                                                # ARFCN of the downlink carrier (center frequency).
  band: 41                                                        # The NR band.
  channel_bandwidth_MHz: 100                                      # Bandwith in MHz. Number of PRBs will be automatically derived.
  common_scs: 30                                                  # Subcarrier spacing in kHz used for data.
  plmn: "xxxx"                                                   # PLMN broadcasted by the gNB.
  tac: 1                                                          # Tracking area code (needs to match the core configuration).
  pci: 1                                                          # Physical cell ID.
  nof_antennas_dl: 1                                              # Downlink number of antennas.
  nof_antennas_ul: 1                                              # Uplink number of anntennas.
  prach:
    prach_config_index: 159                                         # PRACH configuration index.
    prach_root_sequence_index: 1                                  # PRACH root sequence index.
    zero_correlation_zone: 0                                      # Zero correlation zone.
    prach_frequency_start: 0                                      # Offset in PRBs of lowest PRACH transmission occasion in frequency domain respective to PRB 0.

log:
  filename: /home/sun/gnb.log                                          # Path of the log file.
  all_level: info                                              # Logging level applied to all layers.

pcap:
  mac_enable: false                                               # Set to true to enable MAC-layer PCAPs.
  mac_filename: /tmp/gnb_mac.pcap                                 # Path where the MAC PCAP is stored.
  ngap_enable: false                                              # Set to true to enable NGAP PCAPs.
  ngap_filename: /tmp/gnb_ngap.pcap                               # Path where the NGAP PCAP is stored.
```
