### ISSUE TITLE
COTS UE can not connect

### ISSUE THREAD

**Issue by eulenleber** [srsran/srsRAN_Project#35]
## Issue Description ##
UE can not connect

I only used the internal b210 clock - may that the issue for the connection problem?

That would not explain the missing network name on the UE GUI side

How can I get more relevant debug data? The phone is an unrooted android with adb access

## Setup Details ##
```
amf:
  addr: 127.0.0.5                 # The address or hostname of the AMF.
  bind_addr: 127.0.0.1              # A local IP that the gNB binds to for traffic from the AMF.

rf_driver:
  device_driver: uhd                # The RF driver name.
  device_args: type=b200            # Optionally pass arguments to the selected RF driver.
  clock:                            # Specify the clock source used by the RF.
  sync:                             # Specify the sync source used by the RF.
  srate: 30.72                      # RF sample rate might need to be adjusted according to selected bandwidth.
  tx_gain: 50                       # Transmit gain of the RF might need to adjusted to the given situation.
  rx_gain: 60                       # Receive gain of the RF might need to adjusted to the given situation.

cell_cfg:
  dl_arfcn: 632628                  # ARFCN of the downlink carrier (center frequency).
  band: 78                          # The NR band.
  channel_bandwidth_MHz: 20         # Bandwith in MHz. Number of PRBs will be automatically derived.
  common_scs: 30                    # Subcarrier spacing in kHz used for data.
  plmn: "90170"                     # PLMN broadcasted by the gNB.
  tac: 1                            # Tracking area code (needs to match the core configuration).
  pci: 1                            # Physical cell ID.
      
log:
  filename: /tmp/gnb.log            # Path of the log file.
  all_level: debug                # Logging level applied to all layers.

pcap:
  mac_enable: true                 # Set to true to enable MAC-layer PCAPs.
  mac_filename: /tmp/gnb_mac.pcap   # Path where the MAC PCAP is stored.
  ngap_enable: true                # Set to true to enable NGAP PCAPs.
  ngap_filename: /tmp/gnb_ngap.pcap # Path where the NGAP PCAP is stored.
```
amf.yaml

```
logger:
    file: /var/log/open5gs/amf.log
sbi:
    server:
      no_tls: true
      cacert: /etc/open5gs/tls/ca.crt
      key: /etc/open5gs/tls/amf.key
      cert: /etc/open5gs/tls/amf.crt
    client:
      no_tls: true
      cacert: /etc/open5gs/tls/ca.crt
      key: /etc/open5gs/tls/amf.key
      cert: /etc/open5gs/tls/amf.crt
amf:
    sbi:
      - addr: 127.0.0.5
        port: 7777
    ngap:
      - addr: 127.0.0.5
    metrics:
      - addr: 127.0.0.5
        port: 9090
    guami:
      - plmn_id:
          mcc: 901
          mnc: 70
        amf_id:
          region: 2
          set: 1
    tai:
      - plmn_id:
          mcc: 901
          mnc: 70
        tac: 1
    plmn_support:
      - plmn_id:
          mcc: 901
          mnc: 70
        s_nssai:
          - sst: 1
    security:
        integrity_order : [ NIA2, NIA1, NIA0 ]
        ciphering_order : [ NEA0, NEA1, NEA2 ]
    network_name:
        full: Test
    amf_name: open5gs-amf0
scp:
    sbi:
      - addr: 127.0.1.10
        port: 7777
parameter:
max:
usrsctp:
time:
  t3512:
    value: 540     # 9 mintues * 60 = 540 seconds
```
## Expected Behavior ##
UE sees "Test" and connects to it

## Actual Behaviour ##
UE sees "90170 5G" and can not connect to it

## Steps to reproduce the problem ##
```
sudo /usr/bin/gnb -c gnb.conf
```
## Additional Information ##
```
Available radio types: uhd.

--== srsRAN gNB (commit 0523be699) ==--

[INFO] [UHD] linux; Clang version 14.0.0 ; Boost_107400; UHD_4.4.0.0-68-g02558b69
Making USRP object with args 'type=b200'
Cell pci=1, bw=20 MHz, dl_arfcn=632628 (n78), dl_freq=3489.42 MHz, dl_ssb_arfcn=632544, ul_freq=3489.42 MHz

==== gNodeB started ===
Type <t> to view trace
Late: 0; Underflow: 16; Overflow: 0;
Late: 1; Underflow: 4; Overflow: 0;
```

```
tail -f /tmp/gnb.log /var/log/open5gs/*log |  grep -v Low-PHY

2023-03-22T13:15:44.078121 [NGAP    ] [I] Sending NgSetupRequest
2023-03-22T13:15:44.078187 [NGAP    ] [D] Tx NGAP PDU: {
  "initiatingMessage": {
    "procedureCode": 21,
    "criticality": "reject",
    "value": {
      "NGSetupRequest": {
        "protocolIEs": {
          {
            "id": 27,
            "criticality": "reject",
            "value": {
              "globalGNB-ID": {
                "pLMNIdentity": "09f107",
                "gNB-ID": {
                  "gNB-ID": "0000000000000110011011"
                }
              }
            }
          },
          {
            "id": 82,
            "criticality": "ignore",
            "value": "srsgnb01"
          },
          {
            "id": 102,
            "criticality": "reject",
            "value": [
              {
                "tAC": "000001",
                "broadcastPLMNList": [
                  {
                    "pLMNIdentity": "09f107",
                    "tAISliceSupportList": [
                      {
                        "s-NSSAI": {
                          "sST": "01"
                        }
                      }
                    ]
                  }
                ]
              }
            ]
          },
          {
            "id": 21,
            "criticality": "ignore",
            "value": "v256"
          }
        }
      }
    }
  }
}
2023-03-22T13:15:44.078553 [NGAP    ] [D] Handling PDU of type "successfulOutcome.NGSetupResponse"
2023-03-22T13:15:44.078572 [NGAP    ] [D] Rx NGAP PDU: {
  "successfulOutcome": {
    "procedureCode": 21,
    "criticality": "reject",
    "value": {
      "NGSetupResponse": {
        "protocolIEs": {
          {
            "id": 1,
            "criticality": "reject",
            "value": "open5gs-amf0"
          },
          {
            "id": 96,
            "criticality": "reject",
            "value": [
              {
                "gUAMI": {
                  "pLMNIdentity": "09f107",
                  "aMFRegionID": "00000010",
                  "aMFSetID": "0000000001",
                    "s-NSSAI": {
                      "sST": "01"
                    }
                  }
                ]
              }
            ]
          }
        }
      }
    }
  }
}
2023-03-22T16:01:03.728919 [NGAP    ] [D] Received PDU with successful outcome
2023-03-22T16:01:05.649001 [SCHED   ] [I] [     0.0] Cell with cell_index=0 was configured.
2023-03-22T16:01:06.750368 [RF      ] [W] Radio realtime event: Type=start-of-burst Source=tx Timestamp=80011086
2023-03-22T16:02:49.089853 [RF      ] [W] Radio realtime event: Type=underflow Source=tx Timestamp=na
2023-03-22T16:02:49.089857 [RF      ] [W] Radio realtime event: Type=underflow Source=tx Timestamp=na
2023-03-22T16:02:49.089858 [RF      ] [W] Radio realtime event: Type=underflow Source=tx Timestamp=na
2023-03-22T16:02:49.089858 [RF      ] [W] Radio realtime event: Type=underflow Source=tx Timestamp=na
2023-03-22T16:02:49.089859 [RF      ] [W] Radio realtime event: Type=underflow Source=tx Timestamp=na
2023-03-22T16:02:49.089861 [RF      ] [W] Radio realtime event: Type=underflow Source=tx Timestamp=na
2023-03-22T16:02:49.089862 [RF      ] [W] Radio realtime event: Type=underflow Source=tx Timestamp=na
2023-03-22T16:02:49.089864 [RF      ] [W] Radio realtime event: Type=underflow Source=tx Timestamp=na
2023-03-22T16:02:49.089865 [RF      ] [W] Radio realtime event: Type=underflow Source=tx Timestamp=na
2023-03-22T16:02:49.089866 [RF      ] [W] Radio realtime event: Type=underflow Source=tx Timestamp=na
2023-03-22T16:02:49.089868 [RF      ] [W] Radio realtime event: Type=underflow Source=tx Timestamp=na
2023-03-22T16:02:49.089869 [RF      ] [W] Radio realtime event: Type=underflow Source=tx Timestamp=na
2023-03-22T16:02:49.089870 [RF      ] [W] Radio realtime event: Type=underflow Source=tx Timestamp=na
2023-03-22T16:02:49.089871 [RF      ] [W] Radio realtime event: Type=underflow Source=tx Timestamp=na
2023-03-22T16:02:49.089872 [RF      ] [W] Radio realtime event: Type=underflow Source=tx Timestamp=na
2023-03-22T16:02:49.089873 [RF      ] [W] Radio realtime event: Type=underflow Source=tx Timestamp=na
2023-03-22T16:02:49.089884 [RF      ] [W] Radio realtime event: Type=end-of-burst Source=tx Timestamp=3223895884
2023-03-22T16:02:49.090919 [RF      ] [W] Radio realtime event: Type=start-of-burst Source=tx Timestamp=3223927716
```

**Comment by ismagom** [comment]
Can you set log level to info and enable pcap and attach èalogs and pcaps please? 
Aq
When you say the UE does not connect to 90170 plmn, what do you mean? Do you see an error message? 

What's the plmn of the sim card? 

What's the phone model? 
Thanks

**Comment by eulenleber** [comment]
> Can you set log level to info and enable pcap and attach logs and pcaps please?

```yaml
amf:
  addr: 127.0.0.5                 # The address or hostname of the AMF.
  bind_addr: 127.0.0.1              # A local IP that the gNB binds to for traffic from the AMF.

rf_driver:
  device_driver: uhd                # The RF driver name.
  device_args: type=b200            # Optionally pass arguments to the selected RF driver.
  clock:                            # Specify the clock source used by the RF.
  sync:                             # Specify the sync source used by the RF.
  srate: 30.72                      # RF sample rate might need to be adjusted according to selected bandwidth.
  tx_gain: 50                       # Transmit gain of the RF might need to adjusted to the given situation.
  rx_gain: 60                       # Receive gain of the RF might need to adjusted to the given situation.

cell_cfg:
  dl_arfcn: 632628                  # ARFCN of the downlink carrier (center frequency).
  band: 78                          # The NR band.
  channel_bandwidth_MHz: 20         # Bandwith in MHz. Number of PRBs will be automatically derived.
  common_scs: 30                    # Subcarrier spacing in kHz used for data.
  plmn: "90170"                     # PLMN broadcasted by the gNB.
  tac: 1                            # Tracking area code (needs to match the core configuration).
  pci: 1                            # Physical cell ID.
      
log:
  filename: /tmp/gnb.log            # Path of the log file.
  all_level: info                # Logging level applied to all layers.

pcap:
  mac_enable: true                 # Set to true to enable MAC-layer PCAPs.
  mac_filename: /tmp/gnb_mac.pcap   # Path where the MAC PCAP is stored.
  ngap_enable: true                # Set to true to enable NGAP PCAPs.
  ngap_filename: /tmp/gnb_ngap.pcap # Path where the NGAP PCAP is stored.
```

gnb.log
```
2023-03-23T08:22:32.656128 [NGAP    ] [I] Sending NgSetupRequest
2023-03-23T08:22:34.416965 [Low-PHY ] [I] Initialized with time_alignment_calibration=0 (0.0000 us), ul_to_dl_subframe_offset=1, max_processing_delay_slots=4.
2023-03-23T08:22:34.554591 [SCHED   ] [I] [     0.0] Cell with cell_index=0 was configured.
2023-03-23T08:22:35.555215 [Low-PHY ] [I] Starting...
2023-03-23T08:22:35.656299 [RF      ] [W] Radio realtime event: Type=start-of-burst Source=tx Timestamp=80550512
2023-03-23T08:22:54.001973 [RF      ] [W] Radio realtime event: Type=underflow Source=tx Timestamp=na
2023-03-23T08:22:54.001976 [RF      ] [W] Radio realtime event: Type=end-of-burst Source=tx Timestamp=644113312
2023-03-23T08:22:54.002174 [RF      ] [W] Radio realtime event: Type=start-of-burst Source=tx Timestamp=644141840
2023-03-23T08:23:42.266586 [RF      ] [W] Radio realtime event: Type=underflow Source=tx Timestamp=na
2023-03-23T08:23:42.266588 [RF      ] [W] Radio realtime event: Type=end-of-burst Source=tx Timestamp=2126809711
2023-03-23T08:23:42.266993 [RF      ] [W] Radio realtime event: Type=start-of-burst Source=tx Timestamp=2126839335
2023-03-23T08:25:54.942324 [RF      ] [W] Radio realtime event: Type=underflow Source=tx Timestamp=na
2023-03-23T08:25:54.942329 [RF      ] [W] Radio realtime event: Type=end-of-burst Source=tx Timestamp=6202609852
2023-03-23T08:25:54.942668 [RF      ] [W] Radio realtime event: Type=start-of-burst Source=tx Timestamp=6202640572
2023-03-23T08:26:07.001742 [RF      ] [W] Radio realtime event: Type=underflow Source=tx Timestamp=na
2023-03-23T08:26:07.001755 [RF      ] [W] Radio realtime event: Type=end-of-burst Source=tx Timestamp=6573076595
2023-03-23T08:26:07.001814 [RF      ] [W] Radio realtime event: Type=underflow Source=tx Timestamp=na
2023-03-23T08:26:07.002033 [RF      ] [W] Radio realtime event: Type=start-of-burst Source=tx Timestamp=6573105123
2023-03-23T08:32:45.002289 [RF      ] [W] Radio realtime event: Type=underflow Source=tx Timestamp=na
2023-03-23T08:32:45.002298 [RF      ] [W] Radio realtime event: Type=end-of-burst Source=tx Timestamp=18799673882
2023-03-23T08:32:45.002768 [RF      ] [W] Radio realtime event: Type=start-of-burst Source=tx Timestamp=18799703506
2023-03-23T08:34:23.522552 [RF      ] [W] Radio realtime event: Type=underflow Source=tx Timestamp=na
2023-03-23T08:34:23.522642 [RF      ] [W] Radio realtime event: Type=underflow Source=tx Timestamp=na
2023-03-23T08:34:23.522694 [RF      ] [W] Radio realtime event: Type=end-of-burst Source=tx Timestamp=21826209375
2023-03-23T08:34:23.531773 [RF      ] [W] Radio realtime event: Type=start-of-burst Source=tx Timestamp=21826514383
2023-03-23T08:35:45.978377 [RF      ] [W] Radio realtime event: Type=underflow Source=tx Timestamp=na
2023-03-23T08:35:45.978378 [RF      ] [W] Radio realtime event: Type=end-of-burst Source=tx Timestamp=24359255502
2023-03-23T08:35:45.978714 [RF      ] [W] Radio realtime event: Type=start-of-burst Source=tx Timestamp=24359289526
2023-03-23T08:35:58.032573 [RF      ] [W] Radio realtime event: Type=underflow Source=tx Timestamp=na
2023-03-23T08:35:58.032589 [RF      ] [W] Radio realtime event: Type=end-of-burst Source=tx Timestamp=24729569741
2023-03-23T08:35:58.033006 [RF      ] [W] Radio realtime event: Type=start-of-burst Source=tx Timestamp=24729598269
2023-03-23T08:36:40.274961 [RF      ] [W] Radio realtime event: Type=underflow Source=tx Timestamp=na
2023-03-23T08:36:40.275053 [RF      ] [W] Radio realtime event: Type=end-of-burst Source=tx Timestamp=26027246172
2023-03-23T08:36:40.284134 [RF      ] [W] Radio realtime event: Type=start-of-burst Source=tx Timestamp=26027554484
2023-03-23T08:38:36.862900 [RF      ] [W] Radio realtime event: Type=underflow Source=tx Timestamp=na
2023-03-23T08:38:36.862902 [RF      ] [W] Radio realtime event: Type=underflow Source=tx Timestamp=na
2023-03-23T08:38:36.862907 [RF      ] [W] Radio realtime event: Type=end-of-burst Source=tx Timestamp=29608831737
2023-03-23T08:38:36.863179 [RF      ] [W] Radio realtime event: Type=start-of-burst Source=tx Timestamp=296088668%
```

gnb_ngap.pcap

```bash

base64 -d <<< 1MOyoQIABAAAAAAAAAAAAP//AACYAAAASAwcZG4DCgA3AAAANwAAAAAVADMAAAQAGwAIAAnxBwAABmwAUkAKA4BzcnNnbmIwMQBmAA0AAAAAAQAJ8QcAAAAIABVAAWBIDBxkjgQKADYAAAA2AAAAIBUAMgAABAABAA4FgG9wZW41Z3MtYW1mMABgAAgAAAnxBwIAQABWQAH/AFAACAAJ8QcAAAAI |xxd
00000000: d4c3 b2a1 0200 0400 0000 0000 0000 0000  ................
00000010: ffff 0000 9800 0000 480c 1c64 6e03 0a00  ........H..dn...
00000020: 3700 0000 3700 0000 0015 0033 0000 0400  7...7......3....
00000030: 1b00 0800 09f1 0700 0006 6c00 5240 0a03  ..........l.R@..
00000040: 8073 7273 676e 6230 3100 6600 0d00 0000  .srsgnb01.f.....
00000050: 0001 0009 f107 0000 0008 0015 4001 6048  ............@.`H
00000060: 0c1c 648e 040a 0036 0000 0036 0000 0020  ..d....6...6... 
00000070: 1500 3200 0004 0001 000e 0580 6f70 656e  ..2.........open
00000080: 3567 732d 616d 6630 0060 0008 0000 09f1  5gs-amf0.`......
00000090: 0702 0040 0056 4001 ff00 5000 0800 09f1  ...@.V@...P.....
000000a0: 0700 0000 08 
```

gnb_mac.pcap is empty though
 
> When you say the UE does not connect to 90170 plmn, what do you mean? Do you see an error message?

What I mean is that I see the network when I disable automatic network connection but when I tap on my network I get the message "Connection not possible" (roughly translated)
The Logcat does not seem to contain a relevant hint?


> What's the plmn of the sim card?
```
logcat | grep -i mcc                                                                                                                                                                                                                                                                                                
03-23 09:19:17.213  1516  1516 D NetworkController.MobileSignalController(1)(0): notifyListeners mCurrentState.isDefault = false level = 0 getCurrentIconId() = 132608 voiceNetType = 0/UNKNOWN mCurrentState.dataConnected = false dataDisabled = false showDataIcon = false qsTypeIcon = 0 mConfig.alwaysShowDataRatIcon = false volteIcon = (null) mCurrentState.airplaneMode = false isImsOverWfc = false mCurrentState.imsCap = -1 mCurrentState.roaming = false mCurrentState.enabled = true mCurrentState.connected = false activityIn = false activityOut = false mccmnc = 90170
03-23 09:25:57.419  1714  1714 D SimHotSwapHandler: handler=com.mediatek.settings.network.SimHotSwapHandler@453d874, cacheList=[{id=1 iccId=898821100[****] simSlotIndex=0 carrierId=-1 displayName=CARD 1 carrierName=Dienst nicht verfügbar nameSource=0 iconTint=-16746133 number= dataRoaming=1 iconBitmap=android.graphics.Bitmap@15eb19d mcc=901 mnc=70 countryIso=null isEmbedded=false nativeAccessRules=null cardString=898821100[****] cardId=0 isOpportunistic=false groupUUID=null isGroupDisabled=false profileClass=-1 ehplmns=null hplmns=null subscriptionType=0 groupOwner=null carrierConfigAccessRules=null areUiccApplicationsEnabled=true}]
03-23 09:25:57.458  1714  1714 D SimHotSwapHandler: handleHotSwap, handler=com.mediatek.settings.network.SimHotSwapHandler@453d874, currentSubIdList=[{id=1 iccId=898821100[****] simSlotIndex=0 carrierId=-1 displayName=CARD 1 carrierName=Dienst nicht verfügbar nameSource=0 iconTint=-16746133 number= dataRoaming=1 iconBitmap=android.graphics.Bitmap@9016db3 mcc=901 mnc=70 countryIso=null isEmbedded=false nativeAccessRules=null cardString=898821100[****] cardId=0 isOpportunistic=false groupUUID=null isGroupDisabled=false profileClass=-1 ehplmns=null hplmns=null subscriptionType=0 groupOwner=null carrierConfigAccessRules=null areUiccApplicationsEnabled=true}]
```

i.e.  `mccmnc = 90170`

> What's the phone model? Thanks

T Phone Pro (https://www.inside-digital.de/handys/telekom-t-phone-pro)
