### ISSUE TITLE
UL TCP Resulted in UE Drop (RLF) with OFH (Benetel Radio) permenantly

### ISSUE THREAD

**Issue by IbrahimBabiker87** [srsran/srsRAN_Project#449]
## Issue Description ##
Initiating Uplink TCP will always result in  RLF and UE drop. 

## Setup Details ##
Last Build of Srsran 23.10.1
Benetel Radio 1.0.4

## Expected Behavior ##
To work fine

## Actual Behaviour ##
when initiating UDP traffic in UL it works fine, However when using TCP the UE drops,
this is permanent behavior with several UE models.

```
ad@intel-vm-amf:~$ sudo iperf3 -c 10.45.0.20  -p 5210  -t 86400  -b 100M -R -u
Connecting to host 10.45.0.20, port 5210
Reverse mode, remote host 10.45.0.20 is sending
[  5] local 10.45.0.1 port 54063 connected to 10.45.0.20 port 5210
[ ID] Interval           Transfer     Bitrate         Jitter    Lost/Total Datagrams
[  5]   0.00-1.00   sec  6.79 MBytes  57.0 Mbits/sec  0.139 ms  0/5285 (0%)  
[  5]   1.00-2.00   sec  7.37 MBytes  61.8 Mbits/sec  0.201 ms  0/5734 (0%)  
[  5]   2.00-3.00   sec  7.02 MBytes  58.9 Mbits/sec  0.172 ms  0/5463 (0%)  
[  5]   3.00-4.00   sec  7.21 MBytes  60.5 Mbits/sec  0.972 ms  0/5611 (0%)  
[  5]   4.00-5.00   sec  6.94 MBytes  58.2 Mbits/sec  0.199 ms  0/5398 (0%)  
[  5]   5.00-6.00   sec  7.00 MBytes  58.7 Mbits/sec  0.147 ms  0/5446 (0%)  
[  5]   6.00-7.00   sec  7.27 MBytes  61.0 Mbits/sec  0.235 ms  0/5655 (0%)  
[  5]   7.00-8.00   sec  7.09 MBytes  59.5 Mbits/sec  0.458 ms  0/5519 (0%)  
[  5]   8.00-9.00   sec  7.01 MBytes  58.8 Mbits/sec  0.166 ms  0/5453 (0%)  
[  5]   9.00-10.00  sec  7.04 MBytes  59.0 Mbits/sec  0.202 ms  0/5474 (0%)  
^C[  5]  10.00-10.93  sec  6.11 MBytes  55.3 Mbits/sec  0.203 ms  0/4749 (0%)  
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Jitter    Lost/Total Datagrams
[  5]   0.00-10.93  sec  0.00 Bytes  0.00 bits/sec  0.000 ms  0/0 (0%)  sender
[  5]   0.00-10.93  sec  76.9 MBytes  59.0 Mbits/sec  0.203 ms  0/59787 (0%)  receiver
iperf3: interrupt - the client has terminated
ad@intel-vm-amf:~$ sudo iperf3 -c 10.45.0.20  -p 5210  -t 86400  -b 100M -R 
Connecting to host 10.45.0.20, port 5210
Reverse mode, remote host 10.45.0.20 is sending
[  5] local 10.45.0.1 port 35940 connected to 10.45.0.20 port 5210
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-1.00   sec  13.2 KBytes   108 Kbits/sec                  
[  5]   1.00-2.00   sec  0.00 Bytes  0.00 bits/sec                  
[  5]   2.00-3.00   sec  0.00 Bytes  0.00 bits/sec                  
[  5]   3.00-4.00   sec  0.00 Bytes  0.00 bits/sec                  
[  5]   4.00-5.00   sec  0.00 Bytes  0.00 bits/sec                  
[  5]   5.00-6.00   sec  0.00 Bytes  0.00 bits/sec                  
[  5]   6.00-7.00   sec  0.00 Bytes  0.00 bits/sec                  
^C[  5]   7.00-7.57   sec  0.00 Bytes  0.00 bits/sec                  
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-7.57   sec  0.00 Bytes  0.00 bits/sec                  sender
[  5]   0.00-7.57   sec  13.2 KBytes  14.2 Kbits/sec                  receiver
iperf3: interrupt - the client has terminated
```

## Steps to reproduce the problem ##
connect last build of Srsran 23.10.1 with benetel radio and initiate UL TCP.

## Additional Information ##

[gnb.zip](https://github.com/srsran/srsRAN_Project/files/14142976/gnb.zip)

**Comment by ismagom** [comment]
It seems the UE stops receiving/transmisting as soon as the iperf starts. 

can you capture a PCAP? 

Can you start iperf from the UE? (instead of iperf3 in reverse mode)

thanks

**Comment by IbrahimBabiker87** [comment]
@ismagom 
Here you go,
The behavior is the same when starting iperf from UE side,


[gnb_pcap.zip](https://github.com/srsran/srsRAN_Project/files/14162489/gnb_pcap.zip)

**Comment by FredNys** [comment]
@ismagom This problem is seen using all radios Benetel, N310, B210.

**Comment by alvasMan** [comment]
Hum... the very large SINR swing seems to happen around here:

```
2024-02-02T16:40:44.970602 [UL-PHY  ] [I] [  536.19] PUSCH: rnti=0x4601 h_id=0 prb=[4, 165) symb=[0, 14) mod=64QAM rv=0 tbs=14862 crc=OK iter=3.0 sinr=21.7dB t=425.7us uci_t=0.0us ret_t=199.8us
2024-02-02T16:40:44.980534 [UL-PHY  ] [I] [  537.18] PUSCH: rnti=0x4601 h_id=0 prb=[4, 165) symb=[0, 14) mod=64QAM rv=0 tbs=14862 crc=KO iter=10.0 ack=01 sinr=-29.2dB t=856.3us uci_t=122.1us ret_t=238.5us
```

I also see alot of these messages:
```
2024-02-02T16:40:44.969971 [OFH     ] [I] Dropped received Open Fronthaul User-Plane packet as decoded eAxC value '1' is not configured
2024-02-02T16:40:44.969979 [OFH     ] [I] Dropped received Open Fronthaul User-Plane packet as decoded eAxC value '1' is not configured
```

@IbrahimBabiker87 could you please share your full config? @AlaiaL Could you please advise @IbrahimBabiker87 with the dropped OFH packets?

**Comment by AzeezEbrahim** [comment]
hey @IbrahimBabiker87  @ismagom 
i am facing same issue with Quectel UE (RM502Q-AE).
see it here #454

**Comment by AlaiaL** [comment]
> Dropped received Open Fronthaul User-Plane packet as decoded eAxC value '1' is not configured

This usually happens when there are more `ul_port_id` in the OFH section than the number of rx antennas in the gNB configuration. If you want to get rid of these messages you could match these parameters in your configuration. For example for SISO:

```

ru_ofh:
  cells:
    - ul_port_id: [0]


cell_cfg:
  nof_antennas_dl: 1
  nof_antennas_ul: 1



```

**Comment by IbrahimBabiker87** [comment]
Matching the ports in UL and DL didnt solve the issue ( below results with 2X2)
for SISO need to reconfigure the Benetel RU, but usually we use 2x2 at least
its good to know that its working fine with Nokia Xr20 and Samsung S22


```
ad@intel-vm-amf:~$ sudo iperf3 -c 10.45.0.20  -p 5210  -t 86400 -b 0.1G -u -R
Connecting to host 10.45.0.20, port 5210
Reverse mode, remote host 10.45.0.20 is sending
[  5] local 10.45.0.1 port 40003 connected to 10.45.0.20 port 5210
[ ID] Interval           Transfer     Bitrate         Jitter    Lost/Total Datagrams
[  5]   0.00-1.00   sec  5.92 MBytes  49.6 Mbits/sec  0.054 ms  0/4602 (0%)  
[  5]   1.00-2.00   sec  5.91 MBytes  49.6 Mbits/sec  0.141 ms  0/4598 (0%)  
[  5]   2.00-3.00   sec  5.93 MBytes  49.8 Mbits/sec  0.115 ms  0/4616 (0%)  
[  5]   3.00-4.00   sec  6.01 MBytes  50.4 Mbits/sec  0.212 ms  0/4675 (0%)  
[  5]   4.00-5.00   sec  6.06 MBytes  50.8 Mbits/sec  0.253 ms  0/4715 (0%)  
[  5]   5.00-6.00   sec  5.84 MBytes  49.0 Mbits/sec  0.284 ms  0/4544 (0%)  
[  5]   6.00-7.00   sec  6.16 MBytes  51.7 Mbits/sec  0.390 ms  0/4794 (0%)  
[  5]   7.00-8.00   sec  5.93 MBytes  49.8 Mbits/sec  0.270 ms  0/4614 (0%)  
[  5]   8.00-9.00   sec  6.07 MBytes  50.9 Mbits/sec  0.231 ms  0/4720 (0%)  
[  5]   9.00-10.00  sec  5.92 MBytes  49.7 Mbits/sec  0.463 ms  0/4607 (0%)  
[  5]  10.00-11.00  sec  6.02 MBytes  50.5 Mbits/sec  0.255 ms  0/4680 (0%)  
[  5]  11.00-12.00  sec  5.98 MBytes  50.2 Mbits/sec  0.223 ms  0/4651 (0%)  
[  5]  12.00-13.00  sec  6.05 MBytes  50.7 Mbits/sec  0.213 ms  0/4705 (0%)  
[  5]  13.00-14.00  sec  6.14 MBytes  51.5 Mbits/sec  1.596 ms  0/4775 (0%)  
[  5]  14.00-15.00  sec  6.18 MBytes  51.9 Mbits/sec  0.198 ms  0/4811 (0%)  
[  5]  15.00-16.00  sec  5.75 MBytes  48.2 Mbits/sec  0.243 ms  0/4473 (0%)  
[  5]  16.00-17.00  sec  6.15 MBytes  51.6 Mbits/sec  1.113 ms  0/4781 (0%)  
[  5]  17.00-18.00  sec  6.10 MBytes  51.1 Mbits/sec  0.605 ms  0/4742 (0%)  
[  5]  18.00-19.00  sec  5.98 MBytes  50.2 Mbits/sec  0.290 ms  0/4654 (0%)  
[  5]  19.00-20.00  sec  6.14 MBytes  51.5 Mbits/sec  1.027 ms  0/4779 (0%)  
[  5]  20.00-21.00  sec  6.20 MBytes  52.0 Mbits/sec  0.052 ms  0/4820 (0%)  
[  5]  21.00-22.00  sec  6.28 MBytes  52.6 Mbits/sec  0.510 ms  0/4882 (0%)  
[  5]  22.00-23.00  sec  5.96 MBytes  50.0 Mbits/sec  0.216 ms  0/4633 (0%)  
[  5]  23.00-24.00  sec  6.25 MBytes  52.5 Mbits/sec  0.186 ms  0/4865 (0%)  
[  5]  24.00-25.00  sec  5.93 MBytes  49.7 Mbits/sec  0.352 ms  0/4613 (0%)  
[  5]  25.00-26.00  sec  6.16 MBytes  51.7 Mbits/sec  0.383 ms  0/4793 (0%)  
[  5]  26.00-27.00  sec  6.23 MBytes  52.3 Mbits/sec  0.135 ms  0/4847 (0%)  
[  5]  27.00-28.00  sec  6.21 MBytes  52.1 Mbits/sec  0.186 ms  0/4828 (0%)  
[  5]  28.00-29.00  sec  6.09 MBytes  51.1 Mbits/sec  0.184 ms  0/4740 (0%)  
^C[  5]  29.00-29.66  sec  4.04 MBytes  51.1 Mbits/sec  0.090 ms  0/3143 (0%)  
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Jitter    Lost/Total Datagrams
[  5]   0.00-29.66  sec  0.00 Bytes  0.00 bits/sec  0.000 ms  0/0 (0%)  sender
[  5]   0.00-29.66  sec   180 MBytes  50.8 Mbits/sec  0.090 ms  0/139700 (0%)  receiver
iperf3: interrupt - the client has terminated
ad@intel-vm-amf:~$ sudo iperf3 -c 10.45.0.20  -p 5210  -t 86400 -b 0.1G  -R
Connecting to host 10.45.0.20, port 5210
Reverse mode, remote host 10.45.0.20 is sending
[  5] local 10.45.0.1 port 57344 connected to 10.45.0.20 port 5210
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-1.00   sec  13.2 KBytes   108 Kbits/sec                  
[  5]   1.00-2.00   sec  0.00 Bytes  0.00 bits/sec                  
[  5]   2.00-3.00   sec  0.00 Bytes  0.00 bits/sec                  
[  5]   3.00-4.00   sec  0.00 Bytes  0.00 bits/sec                  
^C[  5]   4.00-4.93   sec  0.00 Bytes  0.00 bits/sec                  
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-4.93   sec  0.00 Bytes  0.00 bits/sec                  sender
[  5]   0.00-4.93   sec  13.2 KBytes  21.9 Kbits/sec                  receiver
iperf3: interrupt - the client has terminated
```

config:

```
ru_ofh:
  ru_bandwidth_MHz: 100                                           # RU instantaneous bandwidth.
  t1a_max_cp_dl: 470                                              # Maximum T1a on Control-Plane for Downlink in microseconds.
  t1a_min_cp_dl: 419                                              # Minimum T1a on Control-Plane for Downlink in microseconds.
  t1a_max_cp_ul: 336                                              # Maximum T1a on Control-Plane for Uplink in microseconds.
  t1a_min_cp_ul: 285                                              # Minimum T1a on Control-Plane for Uplink in microseconds.
  t1a_max_up: 345                                                 # Maximum T1a on User-Plane in microseconds.
  t1a_min_up: 294
  ta4_max: 200                                                    # Maximum Ta4 on User-Plane in microseconds.
  ta4_min: 0                                                      # Minimum Ta4 on User-Plane in microseconds.
  ignore_ecpri_seq_id: 0                # Optional BOOLEAN (0). Sets whether or not to ignore eCPRI sequence ID field value. Supported [0, 1].
  ignore_ecpri_payload_size: 0          # Optional BOOLEAN (0). Sets whether or not to ignore eCPRI payload size field value. Supported [0, 1].
  is_prach_cp_enabled: 0                                      # Configures if Control-Plane messages should be used to receive PRACH messages.
  compr_method_ul: bfp                                            # Uplink compression method.
  compr_bitwidth_ul: 9                                            # Uplink IQ samples bitwidth after compression.
  compr_method_dl: bfp                                            # Downlink compression method.
  compr_bitwidth_dl: 9                                           # Downlink IQ samples bitwidth after compression.
  compr_method_prach: bfp                                         # PRACH compression method.
  compr_bitwidth_prach: 9                                     # PRACH IQ samples bitwidth after compression.
  enable_ul_static_compr_hdr: 1                                # Configures if the compression header is present for uplink User-Plane messages (false) or not present (true).
  enable_dl_static_compr_hdr: 1                                # Configures if the compression header is present for downlink User-Plane messages (false) or not present (true).
  iq_scaling: 8                                      # IQ samples scaling factor applied before compression, should be a positive value smaller than 10.  
  cells:                                # Optional TEXT. Sets the hardware specific cell configuration on a per cell basis.
  - network_interface: 0000:01:00.0             # Optional TEXT (enp1s0f0). Sets the ethernet network interface name for the RU. Format: a string, e.g. [interface_name].
    ru_mac_addr: 70:b3:d5:e1:5d:3d       # Optional TEXT (70:b3:d5:e1:5b:06). Sets the RU MAC address. Format: a string, e.g. [AA:BB:CC:DD:11:22:33].
    du_mac_addr: 7c:c2:55:69:f5:88       # Optional TEXT (00:11:22:33:00:77). Sets the DU MAC address. Format: a string, e.g. [AA:BB:CC:DD:11:22:33].
    vlan_tag: 5                             # Optional UINT (1). Sets the V-LAN tag control information field. Supported: [1 - 4094].
    prach_port_id: [4,5]                   # Optional UINT (4). Sets the RU PRACH eAxC port ID. Supported: [0 - 65535].
    dl_port_id: [0,1]                   # Optional UINT (0, 1). Sets the RU downlink eAxC port ID. Format: vector containing all DL eXaC ports, e.g. [0, ...\ , N].
    ul_port_id: [0,1]                      # Optional UINT (0). Sets the RU uplink eAxC port ID. Supported: [0 - 65535].

hal:
  eal_args: "--lcores (0-1)@(0-31) -a 0000:01:00.0"


cell_cfg:
  dl_arfcn: 637212                                             # ARFCN of the downlink carrier (center frequency).
  band: 78                                                        # The NR band.
  channel_bandwidth_MHz: 100                                       # Bandwith in MHz. Number of PRBs will be automatically derived.
  common_scs: 30                                                  # Subcarrier spacing in kHz used for data.
  plmn: "00101"                                                   # PLMN broadcasted by the gNB.
  tac: 1                                                          # Tracking area code (needs to match the core configuration).
  pci: 1                                                          # Physical cell ID. 
  nof_antennas_dl: 2                                              # Downlink number of antennas.
  nof_antennas_ul: 2                                              # Uplink number of anntennas.



```
