### ISSUE TITLE
E2 interface doesn't decode CONTROL request message correctly

### ISSUE THREAD

**Issue by HaoxinSEU** [srsran/srsRAN_Project#468]
## Issue Description ##
Using the latest version of srsRAN and FlexRIC, I'm able to run the KPM xApp as described in the tutorial. However, when we tried to run the RC xApp `xapp_oran_ctrl` in FlexRIC, the gNB doesn't seem to decode the CONTROL request message correctly.

## Setup Details ##
As written in the tutorial, we are using the branch `br-flexric` of FlexRIC, and also the latest version of srsRAN. We don't change the code on gNB side.

We change the `slice_level_PRB_quota_param_id_e` in `xapp_oran_ctrl` to skip ID 4, so it's aligned with the gNB and O-RAN spec.

## Expected Behavior ##
We expect that the gNB can correctly decode the CONTROL request message from xApp / RIC.

## Actual Behaviour ##
After digging into the code, we found that the SETUP request and response are correct. 

But in `lib/e2/e2sm/e2sm_rc/e2sm_rc_control_action_du_executor.cpp`, when the gNB decodes the CONTROL request message from RIC in the function `e2sm_rc_control_action_2_6_du_executor::convert_to_du_config_request()` , it only finds RAN parameter ID 1, all other RAN parameter IDs are missing (including 11 and 12). Then, `ctrl_cfg` would be empty.

Therefore, in the function: `e2sm_rc_control_action_2_6_du_executor::execute_ric_control_action()`, it will return `return_ctrl_failure(req)`. And finally the gNB sends the CONTROL failure message to RIC by the function: `send_e2_ric_control_failure(e2_request, e2_response)` in the file `lib/e2/procedures/e2_ric_control_procedure.cpp`.

## Steps to reproduce the problem ##
The gNB config files is like this:
```
gnb_id: 147

slicing:
 - sst: 1
   sd: 0
   
amf:
  addr: 10.43.178.231
  bind_addr: 10.42.1.6

ru_sdr:
  device_driver: uhd
  device_args: 
  # clock:
  # sync:
  srate: 23.040
  otw_format: sc12
  tx_gain: 80
  rx_gain: 40

cell_cfg:
  dl_arfcn: 632628
  band: 78
  channel_bandwidth_MHz: 20
  common_scs: 30
  plmn: "00103"
  tac: 1
  pci: 1
  nof_antennas_ul: 1
  nof_antennas_dl: 1
  pdsch:
    mcs_table: qam256

log:
  filename: /tmp/gnb.log
  all_level: debug

pcap:
  e2ap_enable: true
  e2ap_filename: /tmp/gnb_e2ap.pcap
  
e2:
  enable_du_e2: true                # Enable DU E2 agent (one for each DU instance)
  e2sm_kpm_enabled: false            # Enable KPM service module
  e2sm_rc_enabled: true
  addr: 10.42.1.7                 # RIC IP address
  bind_addr: 10.42.1.6           # A local IP that the E2 agent binds to for traffic from the RIC. ONLY required if running the RIC on a separate machine. 
  port: 36421                       # RIC port

metrics: 
  rlc_json_enable: 1                # Enable RLC metrics reporting (need to deliver measurements to E2SM_KPM service model)
  rlc_report_period: 1000           # Set reporting period to 1s
```

FlexRIC config:
```
SM_DIR = "/usr/local/lib/flexric/"
Name = "NearRT_RIC"
NearRT_RIC_IP = "10.42.1.7"
E2_Port = 36421
E42_Port = 36422
```

## Additional Information ##
As described in the discussion, @RobinWie also met this problem.

The captured E2 pcap is here: 
[e2ap.zip](https://github.com/srsran/srsRAN_Project/files/14236728/e2ap.zip)
