### ISSUE TITLE
srsGNB FATAL ERROR: Failed to find valid csi-MeasConfig

### ISSUE THREAD

**Issue by IbrahimBabiker87** [srsran/srsRAN_Project#485]
## Issue Description ##
It seems there is a limitation in with CSI mapping when using Heavy UL TDD pattern, when you have less than two consecutive DL slots
SRSRAN fail to map the CSI.

TDDPattern
DSUUUUDSUU [Special Slot 6:4:4]

``` 
ad@bm-super4:~/srsRAN_Project/configs$ sudo gnb -c cell_config.yml 

The PRACH detector will not meet the performance requirements with the configuration {Format 0, ZCZ 0, SCS 1.25kHz, Rx ports 1}.
EAL: Detected CPU lcores: 32
EAL: Detected NUMA nodes: 1
EAL: Detected shared linkage of DPDK
EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
EAL: Selected IOVA mode 'VA'
EAL: 2048 hugepages of size 2097152 reserved, but no mounted hugetlbfs found for that size
EAL: VFIO support initialized
EAL: Using IOMMU type 1 (Type 1)
EAL: Probe PCI driver: net_i40e (8086:1572) device: 0000:01:00.0 (socket -1)
TELEMETRY: No legacy callbacks, legacy socket not created

--== srsRAN gNB (commit bcf941b34) ==--

Connecting to AMF on 10.0.135.40:38412
srsGNB FATAL ERROR: Failed to find valid csi-MeasConfig
Aborted


```
## Setup Details ##

tried to comment out the CSI settings and it didnt work
  ```
csi: 
     csi_rs_enabled: 1                       # Optional BOOLEAN (1). Enables CSI-RS resources and CSI reporting. Supported: [0, 1].
     csi_rs_period: 20                       # Optional UINT (20). Sets the CSI-RS period in milliseconds. Supported: [10, 20, 40, 80].
     meas_csi_rs_slot_offset: 2               # Optional UINT (2). Sets the slot offset of first CSI-RS resource used for measurement.
     tracking_csi_rs_slot_offset: 13             # Optional UINT (12). Sets the slot offset of the first CSI-RS slot used for tracking.
     zp_csi_rs_slot_offset:                  # Optional TEXT. Sets the slot offset of the ZP CSI-RS resources.     
     pwr_ctrl_offset: 0                      # Optional INT (0). Sets the power offset of PDSCH RE to NZP CSI-RS RE in dB. Supported: [-8 - 15].

```
```
tdd_ul_dl_cfg: 
    dl_ul_tx_period: 6                     # Optional INT (10). Sets the TDD pattern periodicity in slots. The combination of this value and the chosen numerology must lead to a TDD periodicity of 0.5, 0>
    nof_dl_slots: 1                         # Optional INT (6). Number of consecutive full Downlink slots. Supported: [0-80].
    nof_dl_symbols: 6                       # Optional INT (0). Number of Downlink symbols at the beginning of the slot following full Downlink slots. Supported: [0-13].
    nof_ul_slots: 4                         # Optional INT (3). Number of consecutive full Uplink slots. Supported: [0 - 80].
    nof_ul_symbols: 4                       # Optional INT (0). Number of Uplink symbols at the end of the slot preceding the first full Uplink slot. Supported: [0-13].
    pattern2: 
      dl_ul_tx_period: 2                       # Optional INT (10). Sets the TDD pattern periodicity in slots. The combination of this value and the chosen numerology must lead to a TDD periodicity of 0.>
      nof_dl_slots: 1                           # Optional INT (6). Number of consecutive full Downlink slots. Supported: [0-80].
      nof_dl_symbols: 6                         # Optional INT (0). Number of Downlink symbols at the beginning of the slot following full Downlink slots. Supported: [0-13]
      nof_ul_slots: 2                           # Optional INT (3). Number of consecutive full Uplink slots. Supported: [0 - 80].
      nof_ul_symbols: 4                         # Optional INT (0). Number of Uplink symbols at the end of the slot preceding the first full Uplink slot. Supported: [0-13].

```

```
ssb: 
     ssb_period: 10                          # Optional UINT (10). Sets the period of SSB scheduling in milliseconds. Supported: [5, 10, 20].
     ssb_block_power_dbm: -8                 # Optional INT (-16). Sets the SS PBCH block power in dBm. Supported: [-60 - +50].
     pss_to_sss_epre_db: 0                   # Optional UINT (0). Sets the Synchronization Signal Block Primary Synchronization Signal to Secondary Synchronization Signal Energy Per Resource Element rati>
  ul_common: 
     p_max: 23             
```                     # Optional TEXT. Sets maximum transmit power allowed in this serving cell. Supported: [-30 - +23].

## Expected Behavior ##
to Work fine

## Actual Behaviour ##
Error:
srsGNB FATAL ERROR: Failed to find valid csi-MeasConfig


## Steps to reproduce the problem ##
above settings and bellow TDD pattern:
DSUUUUDSUU [Special Slot 6:4:4]

**Comment by herlesupreeth** [comment]
That is because for CSI-RS we need 2 consecutive slots starting from slot index 2. The reason for starting from slot index 2 is because we avoid overlapping of CSI-RS and SIB1.

**Comment by frankist** [comment]
> That is because for CSI-RS we need 2 consecutive slots starting from slot index 2. The reason for starting from slot index 2 is because we avoid overlapping of CSI-RS and SIB1 which is scheduled at slot index 1.

Just to add to what @herlesupreeth said - you can make the CSI-RS start at slot indexes 0 or 1 if the CSI-RS is not in the same frame as the SSB/SIB1.

**Comment by IbrahimBabiker87** [comment]
@herlesupreeth @frankist 

I have tried with all combination as per bellow,

SSB >> 10ms
CSI >> 20ms

![Screenshot from 2024-02-22 14-50-56](https://github.com/srsran/srsRAN_Project/assets/137053120/cbd2f360-80c7-49ef-822b-58ac6d241885)

what are the are the symbol pair used for Tracking RS if its 4,8  {4, 8}, {5, 9} or {6, 10}we can make use of special slot next to the DL slot giving that special slot should have at least 8 symbols, I think we are limited by The Tracking signal
![Screenshot from 2024-02-22 14-53-22](https://github.com/srsran/srsRAN_Project/assets/137053120/b8e5217a-0afe-4e6b-a6f4-df3660a88b8b)

**Comment by frankist** [comment]
Hey @IbrahimBabiker87,

There is some confusion here. Some observations:
- The pattern you described `DSUUUUDSUU` has a duration of 10 slots. However, you set a TDD pattern of 8 slots (6 + 2):
```
tdd_ul_dl_cfg: 
    dl_ul_tx_period: 6                     # Optional INT (10). Sets the TDD pattern periodicity in slots. The combination of this value 
...
    pattern2: 
      dl_ul_tx_period: 2                       # Optional INT (10). Sets the TDD pattern periodicity in slots. The combination of this value and the chosen numerology must lead to a TDD periodicity of 0.>
```
From now on, I will assume that what you want is a TDD pattern with 10 slots of periodicity (6 + 4).
- `meas_csi_rs_slot_offset: 2` - This falls in the UL slot DS**U**UUUDSUU. This is not correct.
- `tracking_csi_rs_slot_offset: 13` - falls in slot 13 % 10 == 3, which is the UL slot DSUUUUDSUUDSU**U**UUDSUU. This is not correct.

Instead, I would suggest using the following values:
- `meas_csi_rs_slot_offset: 6` - slot offset 6 is DL slot and should not collide in time with SSB/SIB1
- `tracking_csi_rs_slot_offset: 10` - slots 10 and 11 are DL and special slots. Given that the tracking CSI-RS uses symbols 4 and 8, you have to ensure that your special slot has at least 9 symbols. So you have to ensure this as well:
```
tdd_ul_dl_cfg: 
    nof_dl_symbols: 9                       # Optional INT (0). Number of Downlink symbols at the beginning of the slot following full Downlink slots. Supported: [0-13].
```
