### ISSUE TITLE
UE does not connect - RAN550 split 7.2

### ISSUE THREAD

**Issue by abcd11abcd** [srsran/srsRAN_Project#516]
### Discussed in https://github.com/srsran/srsRAN_Project/discussions/398

<div type='discussions-op-text'>

<sup>Originally posted by **AzeezEbrahim** January 10, 2024</sup>
Hi, i trying to use split 7.2 setup, i am getting a locked from the RU and everything seems ok, **However, UEs does not connects.**

anyone can help?  am i missing something?

**Issue**
UE is not connecting to the network. But it is able search for the cell.

**Setup and connections:**

- Ubuntu 22.04
- 13th Gen Intel® Core™ i9-13900K × 32
- 64GB RAM
- Intel Ethernet Network Adapter E810-XXVDA4T (**without** internal GNSS module) --> Grandmaster
- Benetel RAN650
- External GNSS & ublox GPS antenna

**DU Config**

```
amf:
  addr: <ip of core pc>                                               # The address or hostname of the AMF.
  bind_addr: 127.0.0.1                                            # A local IP that the gNB binds to for traffic from the AMF.


ru_ofh:
  ru_bandwidth_MHz: 100                # RU instantaneous bandwidth.
  t1a_max_cp_dl: 392                                              # Maximum T1a on Control-Plane for Downlink in microseconds.
  t1a_min_cp_dl: 258                                              # Minimum T1a on Control-Plane for Downlink in microseconds.
  t1a_max_cp_ul: 300                                              # Maximum T1a on Control-Plane for Uplink in microseconds.
  t1a_min_cp_ul: 285                                              # Minimum T1a on Control-Plane for Uplink in microseconds.
  t1a_max_up: 300                                                 # Maximum T1a on User-Plane in microseconds.
  t1a_min_up: 155
  ta4_max: 300
  ta4_min: 85
  is_prach_cp_enabled: 0            # Configures if Control-Plane messages should be used to receive PRACH messages.
  is_dl_broadcast_enabled: 1            # Optional BOOLEAN (0). Sets downlink broadcast enabled flag. Supported: [0, 1]. 
  #ignore_ecpri_payload_size: 1     # Optional BOOLEAN (0). Sets whether or not to ignore eCPRI payload size field value. Supported [0. 1].
  compr_method_ul: bfp                 # Uplink compression method.
  compr_bitwidth_ul: 9                 # Uplink IQ samples bitwidth after compression.
  compr_method_dl: bfp                 # Downlink compression method.
  compr_bitwidth_dl: 9                 # Downlink IQ samples bitwidth after compression.
  compr_method_prach: bfp              # PRACH compression method.
  compr_bitwidth_prach: 9              # PRACH IQ samples bitwidth after compression.
  enable_ul_static_compr_hdr: 1     # Configures if the compression header is present for uplink User-Plane messages (false) or not present (true).
  enable_dl_static_compr_hdr: 1     # Configures if the compression header is present for downlink User-Plane messages (false) or not present (true).
  iq_scaling: 5.5                      # IQ samples scaling factor applied before compression, should be a positive value smaller than 10.
  cells:
    - network_interface: enp1s0f0np0      # Ethernet interface name used to communicate with the RU.
      ru_mac_addr: <xxxxxxx>   # RU MAC address.
      du_mac_addr: <xxxxxxx>   # DU MAC address.
      vlan_tag: 3                      # VLAN tag value.
      prach_port_id: [4]               # PRACH eAxC port value.
      dl_port_id: [0, 1]                 # Downlink eAxC port values.
      ul_port_id: [0]                 # Uplink eAxC port values.
      
cell_cfg:
  dl_arfcn: 637212                                                 # ARFCN of the downlink carrier (center frequency).
  band: 78                                                        # The NR band.
  channel_bandwidth_MHz: 100                                       # Bandwith in MHz. Number of PRBs will be automatically derived.
  common_scs: 30                                                  # Subcarrier spacing in kHz used for data.
  plmn: "00101"                                                   # PLMN broadcasted by the gNB.
  tac: 1                                                          # Tracking area code (needs to match the core configuration).
  pci: 1                                                          # Physical cell ID.
  nof_antennas_dl: 1                                             # Downlink number of antennas.
  nof_antennas_ul: 1                                              # Downlink number of antennas.
  prach:
    prach_config_index: 7                                          # PRACH configuration index.
    prach_root_sequence_index: 1                                  # PRACH root sequence index.
    zero_correlation_zone: 0                                      # Zero correlation zone.
    prach_frequency_start: 0

  tdd_ul_dl_cfg:
    dl_ul_tx_period: 10                     # Optional INT (10). Sets the TDD pattern periodicity in slots. The combination of this value and the chosen numerology must lead to a TDD periodicity of 0.5, 0.625, 1, 1.25, 2, 2.5, 3, 4, 5 or 10 milliseconds. Supported: [2 - 80].
    nof_dl_slots: 7                         # Optional INT (6). Number of consecutive full Downlink slots. Supported: [0-80].
    nof_dl_symbols: 6                       # Optional INT (0). Number of Downlink symbols at the beginning of the slot following full Downlink slots. Supported: [0-13].
    nof_ul_slots: 2                         # Optional INT (3). Number of consecutive full Uplink slots. Supported: [0 - 80].
    nof_ul_symbols: 2                       # Optional INT (0). Number of Uplink symbols at the end of the slot preceding the first full Uplink slot. Supported: [0-13].

expert_phy:
  max_proc_delay: 5

expert_execution:
  threads:
    upper_phy:
     # nof_pdsch_threads: 4
      # nof_pusch_threads: 2
     # nof_dl_threads: 2
     # nof_ul_threads: 2
    ofh:
      enable_dl_parallelization: 1

log:
  filename: /tmp/gnb.log                                          # Path of the log file.
  all_level: info                                              # Logging level applied to all layers.
```

**RU Config 4x2**
```
LOG_INFO "Set expected DU MAC Address for C-Plane Traffic (C0319/C031A)"
/usr/bin/registercontrol -w C031A -x 0x507c
/usr/bin/registercontrol -w C0319 -x 0x6f5285f0

LOG_INFO "Set expected DU MAC Address for U-Plane Traffic (C0315/C0316)"
/usr/bin/registercontrol -w C0316 -x 0x507c
/usr/bin/registercontrol -w C0315 -x 0x6f5285f0

LOG_INFO "Set required DU VLAN Tag Control Information for uplink U-Plane Traffic (C0318)"
/usr/bin/registercontrol -w C0318 -x 0x3

LOG_INFO "Set expected DU VLAN Tag Control Information for downlink U-Plane Traffic (C0330)"
/usr/bin/registercontrol -w C0330 -x 0x3

LOG_INFO "Set expected DU VLAN Tag Control Information for downlink C-Plane Traffic (C0331)"
/usr/bin/registercontrol -w C0331 -x 0x3

LOG_INFO "Aligning TDD switching relative to downlink and uplink data and with respect to PPS (C0366)"
/usr/bin/registercontrol -w C0366 -x 0x1225
LOG_INFO "Aligning FPGA uplink timing to arrival of uplink frame(C0303)"
/usr/bin/registercontrol -w c0303 -x 0x24


LOG_INFO "Set the Number of Tx's to 4 (C0300)"
/usr/bin/registercontrol -w C0300 -x 0x01010101

LOG_INFO "Disable  udCompHdr option for DL (C0352)"       
/usr/bin/registercontrol -w c0350 -x 0x0   

LOG_INFO "Disable  udCompHdr option for UL (C0352)"       
/usr/bin/registercontrol -w c0351 -x 0x0

LOG_INFO "Disable  udCompHdr option for PRACH (C0352)"
/usr/bin/registercontrol -w c0352 -x 0x0


LOG_INFO "Set PRACH compression disable for FlexRAN (C0353)"
/usr/bin/registercontrol -w C0353 -x 0x1

LOG_INFO "Set Downlink scaling 6 dB for FlexRAN (C0358)"
/usr/bin/registercontrol -w C0358 -x 0x6

LOG_INFO "PRACH LONG (C0328)"
/usr/bin/registercontrol -w c0328 -x 0x1

LOG_INFO "Set expected RU PRACH Configuration Index (C0322)"                                         
/usr/bin/registercontrol -w C0322 -x 0x7

```

**TDD pattern**
```
<xml>
    <tdd-config version="1.0">
            <description>DDDDDDDSUU</description>
                        <pattern index="1">
                                <slots>DDDD</slots>
                                <numerology>1</numerology>
                                <periodicity>2</periodicity>
                                <special-slot-symbols></special-slot-symbols>
                        </pattern>
                        <pattern index="2">
                                <slots>DDSUUU</slots>
                                <numerology>1</numerology>
                                <periodicity>3</periodicity>
                                <special-slot-symbols>DDDDDDGGGGUUUU</special-slot-symbols>
                        </pattern>
    </tdd-config>
</xml>
```

**RU status**

```

[INFO] Platform: RAN650_A_4x2_FlexRAN
[INFO] Frequency: 3558.18
[INFO] Radio bringup begin, 91.00 seconds since boot
[INFO] Initlialize TDD Pattern
[INFO] Waiting for Sync
[INFO] Sync completed
[INFO] Set expected DU MAC Address for C-Plane Traffic (C0319/C031A)
[INFO] Set expected DU MAC Address for U-Plane Traffic (C0315/C0316)
[INFO] Set required DU VLAN Tag Control Information for uplink U-Plane Traffic (C0318)
[INFO] Set expected DU VLAN Tag Control Information for downlink U-Plane Traffic (C0330)
[INFO] Set expected DU VLAN Tag Control Information for downlink C-Plane Traffic (C0331)
[INFO] Aligning TDD switching relative to downlink and uplink data and with respect to PPS (C0366)
[INFO] Aligning FPGA uplink timing to arrival of uplink frame(C0303)
[INFO] Set the Number of Tx's to 4 (C0300)
[INFO] Enable  udCompHdr option for DL (C0352)
[INFO] Enable  udCompHdr option for UL (C0352)
[INFO] Enable  udCompHdr option for PRACH (C0352)
[INFO] Set PRACH compression disable for FlexRAN (C0353)
[INFO] Set Downlink scaling 6 dB for FlexRAN (C0358)
[INFO] PRACH LONG (C0328)
[INFO] Configure eAxC ID via /etc/eaxc.xml settings, as M-Plane is disabled.
[INFO] Set expected RU PRACH Configuration Index (C0322)
[INFO] Start Radio Configuration
[INFO] Initialize RF SoC
[INFO]  Configure CFR for Antenna 1 (0.45)
[INFO] Configure CFR for Antenna 2 (0.45)
[INFO] Configure CFR for Antenna 3 (0.45)
[INFO] Configure CFR for Antenna 4 (0.45)
[INFO] Move platform to TDD mode
[INFO] Set CP60 as TDD control master
[INFO] DPD Tx1 configuration
[INFO] DPD Tx2 configuration
[INFO] DPD Tx3 configuration
[INFO] DPD Tx4 configuration
[INFO] Enable PA Protection on Transmitters
[INFO] End Radio Configuration - Start U-Plane Data
[INFO]  
[INFO] Set the attenuation for TX1/2/3/4
[INFO] Radio bringup complete
 13:03:48 up 5 min,  load average: 0.10, 0.40, 0.23

```

</div>

kpi.sh
SAMPLE_TIME          | RX_TOTAL             | RX_ON_TIME           | RX_EARLY             | RX_LATE              | RX_ON_TIME_C         | RX_EARLY_C           | RX_LATE_C            | TX_TOTAL             
 14:05:24.696231      | 39606                | 36791                | -0                   | 3                    | 2810                 | -0                   | -0                   | -0                   
 14:05:25.697682      | 39603                | 36797                | -0                   | -0                   | 2800                 | -0                   | -0                   | -0                   
 14:05:26.689592      | 39605                | 36792                | -0                   | 2                    | 2800                 | -0                   | -0                   | -0                   
 14:05:27.691531      | 39603                | 36799                | -0                   | 1                    | 2802                 | -0                   | -0                   | -0     

i'm also trying to use bentel 650 RU with srsRAN project. The TDD pattern i'm using is 7-2 on both DU and RU side. The TX_TOTAL field is showing as 0 in my case also. Means, no uplink messages are flowing. The configuration file is as same as the one you are using (du and ru mac addresses will change). Im using 100MHz bandwidth. Im using an external GNSS clock for RU synchronization.

The problem I'm facing here, the UE is unable to regsiter to the core network. Im using samsung s22 mobile. UE is able recognize the network but not registering.

How did you solve this problem? how to make the uplink messages to flow?

All the configurations and logs are same on my side. That's why I am not sharing them here
