### ISSUE TITLE
gNB refuses connection for UE

### ISSUE THREAD

**Issue by dominikheinz** [srsran/srsRAN_Project#706]
## Issue Description ##
I am trying to setup a simple SA 5G network with srsRAN and open5gs.
The UE tries to connect, shows up briefly in the logs with connection refused and then is removed.

## Setup Details ##
My setup uses the following components:
For the basestation I have a USRP B210, connected to a system running Ubuntu 22.04.
The UE consists of a [RM520NGLAA-M20-SGASA 5G Module](https://shop.tekmodul.de/RM520N-GL-p541645396) connected via USB to a [M.2 Carrier Board](https://shop.tekmodul.de/M-2-USB-modem-carrier-board-standard-edition-p541645344).
The UE uses a [sysmoISIM](https://shop.sysmocom.de/sysmoISIM-SJA5-SIM-USIM-ISIM-Card-10-pack-with-ADM-keys/sysmoISIM-SJA5-9FV-10p-adm).
The UE is connected to a separate Laptop, also running Ubuntu 22.04.

I start the gnb like so with my config (config is linked below):
```
sudo ./gnb -c gnb_b210_20MHz_oneplus_8t.yml
```
The gNB does start, and then, when powering the UE, after a short moment, it does show up in the output, but only briefly:

```
$ sudo ./gnb -c gnb_b210_20MHz_oneplus_8t.yml 

--== srsRAN gNB (commit a804c5b9c) ==--


The PRACH detector will not meet the performance requirements with the configuration {Format B4, ZCZ 0, SCS 30kHz, Rx ports 1}.
Lower PHY in quad executor mode.
N2: Connection to AMF on 127.0.0.5:38412 completed
Cell pci=1, bw=20 MHz, 1T1R, dl_arfcn=627340 (n78), dl_freq=3410.1 MHz, dl_ssb_arfcn=626976, ul_freq=3410.1 MHz

Available radio types: uhd.
[INFO] [UHD] linux; GNU C++ version 11.4.0; Boost_107400; UHD_4.7.0.0-0ubuntu1~jammy1
[INFO] [LOGGING] Fastpath logging disabled at runtime.
Making USRP object with args 'type=b200,num_recv_frames=64,num_send_frames=64'
[INFO] [B200] Detected Device: B210
[INFO] [B200] Loading FPGA image: /usr/share/uhd/images/usrp_b210_fpga.bin...
[INFO] [B200] Operating over USB 3.
[INFO] [B200] Detecting internal GPSDO.... 
[INFO] [GPS] No GPSDO found
[INFO] [B200] Initialize CODEC control...
[INFO] [B200] Initialize Radio control...
[INFO] [B200] Performing register loopback test... 
[INFO] [B200] Register loopback test passed
[INFO] [B200] Performing register loopback test... 
[INFO] [B200] Register loopback test passed
[INFO] [B200] Setting master clock rate selection to 'automatic'.
[INFO] [B200] Asking for clock rate 16.000000 MHz... 
[INFO] [B200] Actually got clock rate 16.000000 MHz.
[INFO] [MULTI_USRP] Setting master clock rate selection to 'manual'.
[INFO] [B200] Asking for clock rate 23.040000 MHz... 
[INFO] [B200] Actually got clock rate 23.040000 MHz.
==== gNB started ===
Type <h> to view help
t

          |--------------------DL---------------------|-------------------------UL------------------------------
 pci rnti | cqi  ri  mcs  brate   ok  nok  (%)  dl_bs | pusch  rsrp  mcs  brate   ok  nok  (%)    bsr     ta  phr
   1 4601 |  15 1.0   23   8.6k   11    0   0%      0 |  27.1 -25.6   26    43k   10    0   0%      0  -317n   12
   1 4601 |  15 1.0    0      0    0    0   0%      0 |  27.2 -26.2   28   8.7k    2    0   0%      0  -244n   11
   1 4601 |  15 1.0    0      0    0    0   0%      0 |   n/a   n/a    0      0    0    0   0%      0  -195n   11
```
It only shows these 3 lines of output, nothing more.
The SIM card used in the UE is correctly registered in open5gs with IMSI, Subscriber key and Operator key.

Looking into the logs `/var/logs/open5gs/amf.log` reveals that the conncetion is refused?

```
07/05 09:53:52.367: [amf] INFO: gNB-N2 accepted[127.0.0.1]:34318 in ng-path module (../src/amf/ngap-sctp.c:113)
07/05 09:53:52.367: [amf] INFO: gNB-N2 accepted[127.0.0.1] in master_sm module (../src/amf/amf-sm.c:757)
07/05 09:53:52.370: [amf] INFO: [Added] Number of gNBs is now 1 (../src/amf/context.c:1236)
07/05 09:53:52.370: [amf] INFO: gNB-N2[127.0.0.1] max_num_of_ostreams : 30 (../src/amf/amf-sm.c:796)
07/05 09:54:52.631: [amf] INFO: InitialUEMessage (../src/amf/ngap-handler.c:401)
07/05 09:54:52.631: [amf] INFO: [Added] Number of gNB-UEs is now 1 (../src/amf/context.c:2662)
07/05 09:54:52.631: [amf] INFO:     RAN_UE_NGAP_ID[0] AMF_UE_NGAP_ID[1] TAC[7] CellID[0x66c000] (../src/amf/ngap-handler.c:562)
07/05 09:54:52.631: [amf] INFO: Unknown UE by 5G-S_TMSI[AMF_ID:0x20040,M_TMSI:0xc0000683] (../src/amf/context.c:1862)
07/05 09:54:52.631: [amf] INFO: [Added] Number of AMF-UEs is now 1 (../src/amf/context.c:1621)
07/05 09:54:52.631: [gmm] INFO: Registration request (../src/amf/gmm-sm.c:1214)
07/05 09:54:52.631: [gmm] INFO: [Unknown ID]    5G-S_GUTI[AMF_ID:0x20040,M_TMSI:0xc0000683] (../src/amf/gmm-handler.c:185)
07/05 09:54:52.670: [gmm] INFO: Identity response (../src/amf/gmm-sm.c:1482)
07/05 09:54:52.670: [gmm] INFO: [suci-0-999-70-0-0-0-0000066491]    SUCI (../src/amf/gmm-handler.c:944)
07/05 09:54:52.674: [sbi] INFO: [AUSF] (SCP-discover) NF registered [597ce764-3aa3-41ef-98bd-53cd70be0554:1] (../lib/sbi/path.c:211)
07/05 09:54:52.752: [sbi] INFO: [UDM] (SCP-discover) NF registered [597cf45c-3aa3-41ef-a1d2-9540dfdf5b78:1] (../lib/sbi/path.c:211)
07/05 09:54:52.754: [sbi] WARNING: [UDM] (SCP-discover) NF has already been added [597cf45c-3aa3-41ef-a1d2-9540dfdf5b78:2] (../lib/sbi/path.c:216)
07/05 09:54:52.757: [amf] WARNING: NF EndPoint(addr) updated [127.0.0.12:7777] (../src/amf/npcf-handler.c:143)
07/05 09:54:52.970: [gmm] INFO: [imsi-<censored>] Registration complete (../src/amf/gmm-sm.c:2313)
07/05 09:54:52.970: [amf] INFO: [imsi-<censored>] Configuration update command (../src/amf/nas-path.c:591)
07/05 09:54:52.970: [gmm] INFO:     UTC [2024-07-05T07:54:52] Timezone[0]/DST[0] (../src/amf/gmm-build.c:558)
07/05 09:54:52.970: [gmm] INFO:     LOCAL [2024-07-05T09:54:52] Timezone[7200]/DST[1] (../src/amf/gmm-build.c:563)
07/05 09:54:55.779: [amf] INFO: UE Context Release [Action:2] (../src/amf/ngap-handler.c:1696)
07/05 09:54:55.779: [amf] INFO:     RAN_UE_NGAP_ID[0] AMF_UE_NGAP_ID[1] (../src/amf/ngap-handler.c:1697)
07/05 09:54:55.779: [amf] INFO:     SUCI[suci-0-999-70-0-0-0-0000066491] (../src/amf/ngap-handler.c:1701)
07/05 09:54:55.779: [amf] INFO: [Removed] Number of gNB-UEs is now 0 (../src/amf/context.c:2669)
07/05 09:55:08.763: [amf] INFO: gNB-N2[127.0.0.1] connection refused!!! (../src/amf/amf-sm.c:809)
07/05 09:55:08.763: [amf] INFO: [Removed] Number of gNBs is now 0 (../src/amf/context.c:1263)
```
I did censor the IMSI from the logs, but it is the correct one for the SIM card the UE uses.
Why does my UE fail to connect? I assume it is likely a misconfiguration, but I don't know what could be the cause.
All configs are linked below.

## Expected Behavior ##
I expect the UE to connect correctly to the gNB and also stay connected, so I can send receive data between the two.

## Actual Behaviour ##
The UE is refused from connecting to the gNB.

## Steps to reproduce the problem ##
1. Setup base station with srsRAN and open5gs using the hardware listed above
2. Start gNB with the config linked below
3. Connect UE to other system and observe the logs for the connection issue.

## Additional Information ##

**gnb_b210_20MHz_oneplus_8t.yml (The config I start gnb with):**

```
# This configuration file example shows how to configure the srsRAN Project gNB to connect to a COTS UE. As with the 
# associated tutorial, this config has been tested with a OnePlus 8T. A B210 USRP is used as the RF-frontend.   
# This config creates a TDD cell with 20 MHz bandwidth in band 78. 
# To run the srsRAN Project gNB with this config, use the following command: 
#   sudo ./gnb -c gnb_b210_20MHz_oneplus_8t.yaml

amf:
  addr: 127.0.0.5 #127.0.1.100                                             # The address or hostname of the AMF.
  bind_addr: 127.0.0.1                                          # A local IP that the gNB binds to for traffic from the AMF.

ru_sdr:
  device_driver: uhd                                            # The RF driver name.
  device_args: type=b200,num_recv_frames=64,num_send_frames=64  # Optionally pass arguments to the selected RF driver.
  sync: external                                                # Specify the sync source used by the RF. NOTE: Set to internal if NOT using an external 10 MHz reference clock. 
  srate: 23.04                                                  # RF sample rate might need to be adjusted according to selected bandwidth.
  otw_format: sc12
  tx_gain: 80                                                   # Transmit gain of the RF might need to adjusted to the given situation.
  rx_gain: 40                                                   # Receive gain of the RF might need to adjusted to the given situation.

cell_cfg:
  dl_arfcn: 627340                                              # ARFCN of the downlink carrier (center frequency).
  band: 78                                                      # The NR band.
  channel_bandwidth_MHz: 20                                     # Bandwith in MHz. Number of PRBs will be automatically derived.
  common_scs: 30                                                # Subcarrier spacing in kHz used for data.
  plmn: "99970" #"90170"                                                 # PLMN broadcasted by the gNB.
  tac: 7                                                        # Tracking area code (needs to match the core configuration).
  pci: 1                                                        # Physical cell ID.

pcap:
  mac_enable: false                                             # Set to true to enable MAC-layer PCAPs.
  mac_filename: /tmp/gnb_mac.pcap                               # Path where the MAC PCAP is stored.
  ngap_enable: false                                            # Set to true to enable NGAP PCAPs.
  ngap_filename: /tmp/gnb_ngap.pcap                             # Path where the NGAP PCAP is stored.
```

**/etc/open5gs/amf.yaml:**

```
logger:
  file:
    path: /var/log/open5gs/amf.log
    level: trace
global:
  max:
    ue: 1024  # The number of UE can be increased depending on memory size.
#    peer: 64

amf:
  sbi:
    server:
      - address: 127.0.0.5
        port: 7777
    client:
      scp:
        - uri: http://127.0.0.200:7777
  ngap:
    server:
      - address: 127.0.0.5
  metrics:
    server:
      - address: 127.0.0.5
        port: 9090
  guami:
    - plmn_id:
        mcc: 999
        mnc: 70
      amf_id:
        region: 2
        set: 1
  tai:
    - plmn_id:
        mcc: 999
        mnc: 70
      tac: 7 #1
  plmn_support:
    - plmn_id:
        mcc: 999
        mnc: 70
      s_nssai:
        - sst: 1
  security:
    integrity_order : [ NIA2, NIA1, NIA0 ]
    ciphering_order : [ NEA0, NEA1, NEA2 ]
  network_name:
    full: Open5GS
    short: Next
  amf_name: open5gs-amf0
  time:
    t3512:
      value: 540    # 9 minutes * 60 = 540 seconds
```

**/etc/open5gs/mme.yaml:**

```
logger:
  default:
    timestamp: false
  file:
    path: /var/log/open5gs/mme.log
    timestamp: true

global:
  max:
    ue: 1024  # The number of UE can be increased depending on memory size.
#    peer: 64

mme:
  freeDiameter: /etc/freeDiameter/mme.conf
  s1ap:
    server:
      - address: 127.0.0.2
  gtpc:
    server:
      - address: 127.0.0.2
    client:
      sgwc:
        - address: 127.0.0.3
      smf:
        - address: 127.0.0.4
  metrics:
    server:
      - address: 127.0.0.2
        port: 9090
  gummei:
    - plmn_id:
        mcc: 999
        mnc: 70
      mme_gid: 2
      mme_code: 1
  tai:
    - plmn_id:
        mcc: 999
        mnc: 70
      tac: 7 #1
  security:
    integrity_order : [ EIA2, EIA1, EIA0 ]
    ciphering_order : [ EEA0, EEA1, EEA2 ]
  network_name:
    full: Open5GS
    short: Next
  mme_name: open5gs-mme0
  time:
```

**/etc/open5gs/upf.yaml:**
```
logger:
  file:
    path: /var/log/open5gs/upf.log

global:
  max:
    ue: 1024  # The number of UE can be increased depending on memory size.
#    peer: 64

upf:
  pfcp:
    server:
      - address: 127.0.0.7
    client:
#      smf:     #  UPF PFCP Client try to associate SMF PFCP Server
#        - address: 127.0.0.4
  gtpu:
    server:
      - address: 127.0.0.7
  session:
    - subnet: 10.45.0.0/16
      gateway: 10.45.0.1
    - subnet: 2001:db8:cafe::/48
      gateway: 2001:db8:cafe::1
  metrics:
    server:
      - address: 127.0.0.7
        port: 9090
```

**/etc/open5gs/nrf/yaml:**
```
logger:
  file:
    path: /var/log/open5gs/nrf.log
#  level: info   # fatal|error|warn|info(default)|debug|trace

global:
  max:
    ue: 1024  # The number of UE can be increased depending on memory size.
#    peer: 64

nrf:
  serving:  # 5G roaming requires PLMN in NRF
    - plmn_id:
        mcc: 999
        mnc: 70
  sbi:
    server:
      - address: 127.0.0.10
        port: 7777
```
