### ISSUE TITLE
Config file parsing error with pcap enabled for N3 Interface

### ISSUE THREAD

**Issue by flenz00** [srsran/srsRAN_Project#733]
## Issue Description ##
I copied the pcap section from the configuration reference manual (https://docs.srsran.com/projects/project/en/latest/user_manuals/source/config_ref.html) but i get the following error "INI was not able to parse pcap.n3_filename"

## Setup Details ##
srsRAN version: srsRAN 5G gNB version 24.04.0 (1483bda30)

```
amf:
  addr: 192.168.12.130 #172.22.0.10 #127.0.0.5 #127.0.1.100                                               # The address or hostname of the AMF.
  bind_addr: 192.168.7.227 #127.0.0.5                                            # A local IP that the gNB binds to for>
#  tai: 

ru_sdr:
  device_driver: uhd                                              # The RF driver name.
#  device_args: type=b200,num_recv_frames=64,num_send_frames=64    # Optionally pass arguments to the selected RF driver.
  device_args: addr=192.168.40.2,type=x300,send_frame_size=8000,recv_frame_size=8000,master_clock_rate=184.32e6    # Optionally pass arguments to the selected RF driver.
    #device_args: type=x300,master_clock_rate=184.32e6,send_frame_size=8000,recv_frame_size=8000    # Optionally pass arguments to the selected RF driver.
  sync: external #internal #gpsdo                                          # Set sync to external. This set-up uses a LEO BODNAR GPDSO providing a 10 MHz ref.
  clock: external
  srate: 30.72 #61.44 #23.04 #30.72 # 5.76 11.52 23.04                                      # RF sample rate might need to be adjusted according to selected bandwidth.
  tx_gain: 3 #1 #2 #10 #55 #45? # 60 funziona                                       # Transmit gain of the RF might need to adjusted to the given situation.
  rx_gain: 8 #12 # 3 # 50 #20? # 50                                               # Receive gain of the RF might need to adjusted to the given situation. 
    #  otw_format: sc12

cell_cfg:
  dl_arfcn: 637212 #640000 #368500 #388000 #361500 # 388000                                                # ARFCN of the downlink carrier (center frequency).
  band: 78 #3 #2 # 66                                                     # The NR band.
  channel_bandwidth_MHz: 20 #100 #20 # 5 10 15 20                                       # Bandwith in MHz. Number of PRBs will be automatically derived.
  common_scs: 30                                                  # Subcarrier spacing in kHz used for data.
  plmn: 00101 # "20895"                                                   # PLMN broadcasted by the gNB.
  tac: 40960 #7
  pci: 1                                                       # Tracking area code (needs to match the core configuration). 
  pdsch:
    min_ue_mcs: 1 #9
    max_ue_mcs: 9 #10
  pusch:
    min_ue_mcs: 1 #9
    max_ue_mcs: 9 #10                           

  pdcch:
    common:
      ss0_index: 0 # 1 #0
      coreset0_index: 2 #12
    dedicated:
      ss2_type: common                                            # Set search space to common to match capabilities
      dci_format_0_1_and_1_1: false
    
  prach:
    prach_config_index: 1 #7 #1
      #prach_root_sequence_index: 1                                  # PRACH root sequence index.
      #zero_correlation_zone: 0                                      # Zero correlation zone.
      #prach_frequency_start: 0

log:
  filename: /tmp/gnb.log                                          # Path of the log file.
  #all_level: warning                                                 # Logging level applied to all layers.
  gtpu_level: debug

pcap: 
  ngap_filename: /tmp/gnb_ngap.pcap     # Optional TEXT (/tmp/gnb_ngap.pcap). Path for NGAP PCAPs. 
  ngap_enable: false                    # Optional BOOLEAN (false). Enable/disable NGAP packet capture. Supported: [false, true].
  n3_filename: /tmp/gnb_n3.pcap         # Optional TEXT (/tmp/gnb_n3.pcap). Path for N3 PCAPs. 
  n3_enable: false                      # Optional BOOLEAN (false). Enable/disable N3 packet capture. Supported: [false, true].
```
I tried also with pcap enabled for all layers and i get the same behavior for f1u_filename "INI was not able to parse pcap.f1u_filename".
