### ISSUE TITLE
Docker: gNB fails to connect to Open5GS core

### ISSUE THREAD

**Issue by dominikheinz** [srsran/srsRAN_Project#739]
## Issue Description ##
I am having trouble setting up a 5G SA network with Docker. 
It appears that the gNB and Open5GS containers can't communicate.
Starting the containers, after a couple of minutes, I get a timout:

```
gnb_1             | 
gnb_1             | --== srsRAN gNB (commit ) ==--
gnb_1             | 
gnb_1             | 
gnb_1             | The PRACH detector will not meet the performance requirements with the configuration {Format B4, ZCZ 0, SCS 30kHz, Rx ports 1}.
gnb_1             | Lower PHY in quad executor mode.
gnb_1             | N2: Failed to connect to AMF on 10.53.1.2:38412. error="Connection timed out" timeout=340922ms
gnb_1             | srsRAN ERROR: CU-CP failed to connect to AMF
srsran_gnb exited with code 1
```

## Setup Details ##
- Ubuntu 22.04
- USRPB210

## Expected Behavior ##
I'd expect that the gNB would start in the container and connect to the open5gs core container.

## Actual Behaviour ##
When starting the containers, they all start fine, but I don't see any output from the gnb container. 
The logs for the gnb container are empty. I'd expect that the gnb container would load my custom config and connect to core.

## Steps to reproduce the problem ##
1. Run `docker-compose -f docker-compose-custom.yml up` with the docker-compose file attached below.
2. Observe how the gnb container is running idle, but there is no output and seemingly no connection to 5gcore
## Additional Information ##

**docker-compose-custom.yml**:

```
services:
  5gc:
    container_name: open5gs_5gc
    build:
      context: open5gs
      target: open5gs
      args:
        OS_VERSION: "22.04"
        OPEN5GS_VERSION: "v2.7.0"
    env_file:
      - ${OPEN_5GS_ENV_FILE:-open5gs/open5gs.env}
    privileged: true
    ports:
      - "9999:9999/tcp"
      # To expose o5gc outside the container
      - "38412:38412/sctp"
      - "2152:2152/udp"
    command: 5gc -c open5gs-5gc.yml
    healthcheck:
      test: [ "CMD-SHELL", "nc -z 127.0.0.20 7777" ]
      interval: 3s
      timeout: 1s
      retries: 60
    networks:
      ran:
        ipv4_address: ${OPEN5GS_IP:-10.53.1.2}

  gnb:
    container_name: srsran_gnb
    image: srsran/gnb
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        OS_VERSION: "24.04"
    privileged: true
    cap_add:
      - SYS_NICE
      - CAP_SYS_PTRACE
    volumes:
      - /dev/bus/usb/:/dev/bus/usb/
      - /usr/share/uhd/images:/usr/share/uhd/images
      - gnb-storage:/tmp
      - ./gnb_custom.yml:/gnb_config.yml:ro
      # - ../configs/gnb_rf_b200_tdd_n78_20mhz.yml:/gnb_config.yml:ro
    networks:
      ran:
        ipv4_address: ${GNB_IP:-10.53.1.3}
      metrics:
        ipv4_address: 172.19.1.3
    depends_on:
      5gc:
        condition: service_healthy
    # command: gnb -c /gnb_config.yml amf --addr ${OPEN5GS_IP:-10.53.1.2} --bind_addr ${GNB_IP:-10.53.1.3}
    command: gnb -c /gnb_config.yml log --all_level debug amf --addr ${OPEN5GS_IP:-10.53.1.2} --bind_addr ${GNB_IP:-10.53.1.3}

  metrics-server:
    container_name: metrics_server
    image: srsran/metrics_server
    build:
      context: metrics_server
    environment:
      - PORT=${METRICS_SERVER_PORT}
      - BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET}
      - TESTBED=default
      - URL=http://${DOCKER_INFLUXDB_INIT_HOST}:${DOCKER_INFLUXDB_INIT_PORT}
      - ORG=${DOCKER_INFLUXDB_INIT_ORG}
      - TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
    ports:
      - 55555:${METRICS_SERVER_PORT}/udp
    networks:
      metrics:
        ipv4_address: 172.19.1.4

  influxdb:
    container_name: influxdb
    image: influxdb:${DOCKER_INFLUXDB_VERSION}
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    env_file:
      - .env
    restart: on-failure:10
    networks:
      metrics:
        ipv4_address: 172.19.1.5

  grafana:
    container_name: grafana
    image: srsran/grafana
    build:
      context: grafana
    volumes:
      - grafana-storage:/var/lib/grafana:rw
    env_file:
      - .env
    depends_on:
      - influxdb
      - metrics-server
    ports:
      - 3300:${GRAFANA_PORT}
    networks:
      metrics:
        ipv4_address: 172.19.1.6

volumes:
  gnb-storage:
  grafana-storage:
  influxdb-storage:
  gnb-config:

networks:
  ran:
    ipam:
      driver: default
      config:
        - subnet: 10.53.1.0/24
  metrics:
    ipam:
      driver: default
      config:
        - subnet: 172.19.1.0/24
```

**The gnb_custom.yml (My custom gnb config):**

```
# amf:
  # addr: 127.0.0.5                                               # The address or hostname of the AMF.
  # bind_addr: 127.0.0.1                                          # A local IP that the gNB binds to for traffic from the AMF.

amf:
  addr: 127.0.1.100                                               
  bind_addr: 127.0.0.1

ru_sdr:
  device_driver: uhd                                            # The RF driver name.
  device_args: type=b200,num_recv_frames=64,num_send_frames=64  # Optionally pass arguments to the selected RF driver.
  sync: internal                                                # Specify the sync source used by the RF. NOTE: Set to internal if NOT using an external 10 MHz reference clock. 
  srate: 23.04                                                  # RF sample rate might need to be adjusted according to selected bandwidth.
  otw_format: sc12
  tx_gain: 80                                                   # Transmit gain of the RF might need to adjusted to the given situation.
  rx_gain: 40                                                   # Receive gain of the RF might need to adjusted to the given situation.

cell_cfg:
  dl_arfcn: 627340                                              # ARFCN of the downlink carrier (center frequency).
  band: 78                                                      # The NR band.
  channel_bandwidth_MHz: 20                                     # Bandwith in MHz. Number of PRBs will be automatically derived.
  common_scs: 30                                                # Subcarrier spacing in kHz used for data.
  plmn: "99970"                                                 # PLMN broadcasted by the gNB.
  # plmn: "00101"
  tac: 7                                                        # Tracking area code (needs to match the core configuration).
  pci: 1                                                        # Physical cell ID.


log:
  filename: /tmp/gnb.log                                         
  all_level: warning

pcap:
  mac_enable: false                                        
  mac_filename: /tmp/gnb_mac.pcap                          
  ngap_enable: false                                       
  ngap_filename: /tmp/gnb_ngap.pcap  
```

I assume it is some sort of network misconfiguration?
