### ISSUE TITLE
gnb: "Error: exceeded maximum number of timed out transmissions"

### ISSUE THREAD

**Issue by tiger762** [srsran/srsRAN_Project#772]
## Issue Description ##
Hello. Trying to stand up a gnb but neither an IPhone 12 nor a OnePlus N200 can discover the 5G network. Using band 71 (617-652 down, 663-698 up)

## Setup Details ##
Ubuntu 22.04.4 LTS
srsRAN 5G gNB version 24.04.0
Ettus B200 (UHD_4.1.0.5-3)
Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
IPhone 12 and OnePlus N200
GPSDO providing 10MHz sinewave to port of B200

## Expected Behavior ##
That the gnb runs stably, maybe an overflow or underflow every once in a while, and the 5G handsets discover the network

## Actual Behaviour ##
Always this error:
Error: exceeded maximum number of timed out transmissions.
Less often, one of these:
Error: unhandled error in Rx metadata ERROR_CODE_BAD_PACKET
[ERROR] [STREAMER] The receive packet handler caught a value exception.
[ERROR] [STREAMER] recv packet demuxer unexpected sid 0xabfea009

## Steps to reproduce the problem ##
```
cat /root/gnb_b71_arfcn127900.yml

amf:
  addr: 192.168.16.254                                          # The address or hostname of the AMF.
  bind_addr: 192.168.16.1                                       # A local IP that the gNB binds to for traffic from the AMF.

ru_sdr:
  device_driver: uhd                                            # The RF driver name.
  device_args: type=b200,num_recv_frames=64,num_send_frames=64  # Optionally pass arguments to the selected RF driver.
  sync: external
  srate: 11.52                                                  # RF sample rate might need to be adjusted according to selected bandwidth.
  otw_format: sc12
  tx_gain: 70                                                   # Transmit gain of the RF might need to adjusted to the given situation.
  rx_gain: 70                                                   # Receive gain of the RF might need to adjusted to the given situation.

cell_cfg:
  dl_arfcn: 127980                                              # ARFCN of the downlink carrier (center frequency).
  band: 71                                                      # The NR band.
  channel_bandwidth_MHz: 5                                      # Bandwith in MHz. Number of PRBs will be automatically derived.
  common_scs: 15                                                # Subcarrier spacing in kHz used for data.
  plmn: "310690"                                                # PLMN broadcasted by the gNB.
  tac: 7                                                        # Tracking area code (needs to match the core configuration).
  pci: 1                                                        # Physical cell ID.
      
log:
  filename: /tmp/gnb.log                                        # Path of the log file.
  all_level: info                                               # Logging level applied to all layers.

pcap:
  mac_enable: true                                              # Set to true to enable MAC-layer PCAPs.
  mac_filename: /tmp/gnb_mac.pcap                               # Path where the MAC PCAP is stored.
  ngap_enable: true                                             # Set to true to enable NGAP PCAPs.
  ngap_filename: /tmp/gnb_ngap.pcap                             # Path where the NGAP PCAP is stored.
```

## Additional Information ##
Just because someone is bound to ask, have tried all these suggested remedies:

```
taskset -c 0-7 ./gnb -c /root/gnb_b71_arfcn127900.yml
echo "performance" | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
./srsran_performance
./benchmark_rate --args type=b200 --rx_rate 23.04e6 --tx_rate 23.04e6
./latency_test
./test_timed_commands
./tx_waveforms --freq=900e6 --rate=23.04e6
./pdsch_ue -f 751000000 -a clock=external ----> CFO is within 100 Hz of local Verizon LTE eNodeB, so GPSDO is working
```

Spectrum analyzer showing the 5MHz bandwidth:
![b71_gnb_arfcn127900](https://github.com/user-attachments/assets/5469db07-0a58-4af0-aabc-a9d975608be2)
