### ISSUE TITLE
srsRAN with Open5GS on Raspberrys shows different bitrate on gNB trace and Iperf3 results 

### ISSUE THREAD

**Issue by giuliafgomes36** [srsran/srsRAN_Project#948]
## Issue Description ##
Hello, everyone. I'm trying to build a network with srsRAN_Project (in a Raspberry Pi4) and Open5GS (in a Raspberry Pi5) with ZMQ and srsUE, the document I followed is indicated bellow. The Raspberrys are conected with an Ethernet cable, but the problem is that although my network is running, when I test UE and CORE communication with Iperf3 the gNB trace shows a bitrate of 74Mbps for UL while Iperf3 shows a bitrate of 4Mbps. I know that Iperf3 only measures the payload of the test but the difference is too big, so I came to see if someone could help me.

Document: https://docs.srsran.com/projects/project/en/latest/tutorials/source/srsUE/source/index.html#zeromq-based-setup

## Setup Details ##
srsRAN (Raspberry Pi 4) 
Open5GS (Raspberry Pi 5)
ZMQ
srsUE

## Expected Behavior ##
That gNB trace and Iperf3 results have simmilar values for bitrate.

## Actual Behaviour ##
gNB trace shows 74Mbps of bitrate while Iperf3 shows 4Mbps.

## Steps to reproduce the problem ##

gNB config
```
cu_cp:
  amf:
    addr: 10.0.0.1 #IP AMF (Pi5)
    port: 38412
    bind_addr: 10.0.0.2 #IP gNB (Pi4)
    supported_tracking_areas:
      - tac: 7
        plmn_list:
          - plmn: "00101"
            tai_slice_support_list:
              - sst: 1
  inactivity_timer: 7200

ru_sdr:
  device_driver: zmq
  device_args: tx_port=tcp://127.0.0.1:2000,rx_port=tcp://127.0.0.1:2001,base_srate=23.04e6
  srate: 23.04
  tx_gain: 75
  rx_gain: 75
[...]
```

srsUE config
```
[rf]
freq_offset = 0
tx_gain = 75
rx_gain = 75
srate = 23.04e6
nof_antennas = 1

device_name = zmq
device_args = tx_port=tcp://127.0.0.1:2001,rx_port=tcp://127.0.0.1:2000,base_srate=23.04e6

[rat.eutra]
dl_earfcn = 2850
nof_carriers = 0

[rat.nr]
bands = 3
nof_carriers = 1
max_nof_prb = 106
nof_prb = 106

[pcap]
enable = none
mac_filename = /tmp/ue_mac.pcap
mac_nr_filename = /tmp/ue_mac_nr.pcap
nas_filename = /tmp/ue_nas.pcap

[log]
all_level = info
phy_lib_level = none
all_hex_limit = 32
filename = /tmp/ue.log
file_max_size = -1

[usim]
mode = soft
algo = milenage
opc  = 63BFA50EE6523365FF14C1F45F88737D
k    = 00112233445566778899aabbccddeeff
imsi = 001010123456780
imei = 353490069873319

[rrc]
release = 15
ue_category = 4

[nas]
apn = srsapn
apn_protocol = ipv4

[gw]
netns = ue1
ip_devname = tun_srsue
ip_netmask = 255.255.255.0

[gui]
enable = false
```

Ip route config on Rasp Pi5

![ip_route_pi5](https://github.com/user-attachments/assets/ce0b4cb8-007c-4de0-8c18-7c8b950aaec9)

Iperf3 tests on Pi4
sudo ip netns exec ue1 iperf3 -c 10.45.0.1 -i 1 -t 60 
sudo ip netns exec ue1 iperf3 -c 10.45.0.1 -i 1 -t 60 -u -b 5M
sudo ip netns exec ue1 iperf3 -c 10.45.0.1 -i 1 -t 60 --sctp

## Additional Information ##
gNB trace 
![trace_gNB](https://github.com/user-attachments/assets/c395c779-6214-4f68-ae4a-a90c966f4926)

srsUE trace
![trace_srsUE](https://github.com/user-attachments/assets/73a0c3a6-9dd5-454e-bc0e-d7bf1fef5e8e)

iperf3 result
![iperf3_result](https://github.com/user-attachments/assets/cef64a31-763e-4be6-8564-2018f5d66f85)
