### ISSUE TITLE
gNB INI Log Parser

### ISSUE THREAD

**Issue by rcbarke** [srsran/srsRAN_Project#970]
Hello, the latest merge into the main branch (commit e5d5b44) appears to have problems with the INI file parser. Following both the config reference within the srsRAN Project Docs and example config files in this repo, we are receiving errors with the log, pcap, and metrics classes.

We're finding that none of these files are being created during deployment, and the INI Parser is not echoing the file names correctly to STDOUT. We're unable to start the gNB with the latest code.

We've rolled back to the last stable commit to restore gNB functionality.
```
log:
  filename: /tmp/gnb.log            # Path of the log file.
  all_level: info                   # Logging level applied to all layers.
  hex_max_size: 0

pcap:
  mac_enable: false                 # Set to true to enable MAC-layer PCAPs.
  mac_filename: /tmp/gnb_mac.pcap   # Path where the MAC PCAP is stored.
  ngap_enable: false                # Set to true to enable NGAP PCAPs.
  ngap_filename: /tmp/gnb_ngap.pcap # Path where the NGAP PCAP is stored.
  e2ap_enable: true                 # Set to true to enable E2AP PCAPs.
  e2ap_filename: /tmp/gnb_e2ap.pcap # Path where the E2AP PCAP is stored.

e2:
  enable_du_e2: true                # Enable DU E2 agent (one for each DU instance)
  e2sm_kpm_enabled: true            # Enable KPM service module
  e2sm_rc_enabled: true             # Enable KPM service module
  addr: 192.168.63.10                   # RIC IP address
  bind_addr: 192.168.63.1               # A local IP that the E2 agent binds to for traffic from the RIC. ONLY required if running the RIC on a separate machine. 
  port: 36421                       # RIC port

metrics: 
  rlc_json_enable: 1                # Enable RLC metrics reporting (need to deliver measurements to E2SM_KPM service model)
  rlc_report_period: 250            # Set reporting period to 1s
  enable_json_metrics: true         # Enable reporting metrics in JSON format
  addr: 172.19.1.4                  # Metrics-server IP
  port: 55555                       # Metrics-server Port
```

**Comment by pgawlowicz** [comment]
Now, we have the following parameters for e2ap pcap filenames:
```
pcap:
  e2ap_enable: true                 # Set to true to enable E2AP PCAPs.
  e2ap_du_filename: /tmp/gnb_du_e2ap.pcap # Path where the E2AP DU PCAP is stored.
  e2ap_cu_cp_filename:  /tmp/gnb_cu_cp_e2ap.pcap # Path where the E2AP CU-CP PCAP is stored.
  e2ap_cu_up_filename:  /tmp/gnb_cu_up_e2ap.pcap # Path where the E2AP CU-UP PCAP is stored.
```

@brendan-mcauliffe Could you update the docs?
