### ISSUE TITLE
Documentation update request for feature description about Transmission Modes / Number of Antennas supported

### ISSUE THREAD

**Issue by ohault** [srsran/srsRAN_Project#979]
As we can read on https://docs.srsran.com/projects/4g/en/latest/feature_list.html and https://docs.srsran.com/projects/4g/en/latest/usermanuals/source/srsue/source/1_ue_intro.html#features there are a clear description of Transmission Modes with number of antennas supported.

Could the same be specified also for this page ? https://docs.srsran.com/projects/project/en/latest/general/source/2_features_and_roadmap.html#current-features

Does srsRAN 5G RAN can be used with a single antenna?

**Comment by pgawlowicz** [comment]
By default, it operated with a single antenna (see [configuration reference](https://docs.srsran.com/projects/project/en/latest/user_manuals/source/config_ref.html))
```
cell_cfg:
  pci: 1                                # Required UINT (1). Sets the Physical Cell ID. Supported: [0-1007].
  sector_id: 0                          # Optional UINT (0). Sets the Sector ID (4-14 bits). This value is concatenated with the gNB Id to form the NR Cell Identity (NCI). If not specified, a unique value for the DU is automatically derived. Supported: [0 - 16383].
  dl_arfcn: 536020                      # Required UINT (536020). Sets the Downlink ARFCN.
  band: auto                            # Optional TEXT (auto). Sets the NR band being used for the cell. If not specified, will be set automatically based on ARFCN. Supported: all release 17 bands.
  common_scs: 15                        # Required UINT (15). Sets the subcarrier spacing in KHz to be used by the cell. Supported: [15, 30].
  channel_bandwidth_MHz: 20             # Required UINT (20). Sets the channel Bandwidth in MHz, the number of PRBs will be derived from this. Supported: [5, 10, 15, 20, 25, 30, 40, 50, 60, 70, 80, 90, 100].
  nof_antennas_dl: 1                    # Optional UINT (1). Sets the number of antennas for downlink transmission. Supported: [1, 2, 4].
  nof_antennas_ul: 1                    # Optional UINT (1). Sets the number of antennas for uplink transmission. Supported: [1, 2, 4].
  plmn: 00101                           # Required TEXT (00101). Sets the Public Land Mobile Network code. Format: 7-digit PLMN code containing MCC & MNC.
  tac: 7                                # Required UINT (7). Sets the Tracking Area Code.
```

If you want MIMO, you enable multiple antennas as in the example [mimo_usrp.yml](https://github.com/srsran/srsRAN_Project/blob/main/configs/mimo_usrp.yml)
