### ISSUE TITLE
X310 MIMO2x2 DL throughput does not reach expectation. Deploy Open5gs on another server also degrade DL throughput

### ISSUE THREAD

**Issue by Timez-zx** [srsran/srsRAN_Project#986]
## Issue Description ##
I use srsRAN with x310 USRP devices to test the MIMO 2x2 performance. I tried both 80 Mhz and 90 Mhz. However, the SISO DL throughput is around 200Mbps, the MIMO 2x2 performance is only 90Mbps. The MCS for both setup is almost the same (27 for DL, 24 for UL). I am not sure why?

For the SISO, when I deploy Open5gs and srsRAN on seperate machines, the DL throughput will degrade from 200 Mbps to 90 Mbps.

## Setup Details ##
UE: Amarisoft UE Box E
gNB: Ubuntu 22.04 with low-latency kernel and usrp-x310 (10G network to transfer data). Using UHD to communicate with Amarisoft UE (gNB and UE are connected by copper fiber)
Open5gs: Deploy on the same node with gNB or different node connected to gNB with 25 Gbps fiber.

## Expected Behavior ##
1. The DL throughput of MIMO 2x2 doubles the SISO
2. Deploy Open5gs on another server will not affect the DL performance.

## Actual Behaviour ##
1. For 90 Mhz and 80 Mhz, MiMO's 2x2 performance is worse than SISO 
2. When Deploying the Open5gs on another server, the DL throughput degrades a lot.

## Steps to reproduce the problem ##
I have attached the configuration file I used to this issues
[mimo_usrp.txt](https://github.com/user-attachments/files/18134051/mimo_usrp.txt)
[gnb_rf_x310_tdd_n78_90mhz.txt](https://github.com/user-attachments/files/18134052/gnb_rf_x310_tdd_n78_90mhz.txt)
[gnb_rf_x310_tdd_n78_80mhz.txt](https://github.com/user-attachments/files/18134053/gnb_rf_x310_tdd_n78_80mhz.txt)
[gnb_rf_x310_tdd_n78_40mhz.txt](https://github.com/user-attachments/files/18134054/gnb_rf_x310_tdd_n78_40mhz.txt)
[gnb_rf_x310_tdd_n78_20mhz.txt](https://github.com/user-attachments/files/18134055/gnb_rf_x310_tdd_n78_20mhz.txt)

**Comment by pgawlowicz** [comment]
Please check our new tutorial on [gNB performance turning](https://docs.srsran.com/projects/project/en/latest/tutorials/source/tuning/source/index.html).

**Comment by Timez-zx** [comment]
> Please check our new tutorial on [gNB performance turning](https://docs.srsran.com/projects/project/en/latest/tutorials/source/tuning/source/index.html).

Thanks for your advise. I have tried that. But it does not work. For the DL MIMO throughput, I have found the bottleneck is related to the performance of UPF.

For now, I found some new issues related to UL MCS. Even if I tune the usrp rx_gain to maximum, the MCS can still not reach the maximum. I use a fiber to connect both amarisoft and srsRAN, which should be idea channel quality. 

I use usrpx310 with 80Mhz now, the UL MCS ranges from 17 to 24. Do you know what happens on this new issue?

**Comment by pgawlowicz** [comment]
did you tune nof PHY threads? For example:
```
expert_execution:
  threads:
    upper_phy:
      pdsch_processor_type: concurrent
      nof_pusch_decoder_threads: 4
      nof_ul_threads: 2
      nof_dl_threads: 8
```

**Comment by Timez-zx** [comment]
I have never tried to increase the thread before, so I just tried the configuration you have mentioned:
<img width="818" alt="Screenshot 2024-12-16 at 15 05 07" src="https://github.com/user-attachments/assets/88d84747-8893-43a8-85b6-f9ad3645df72" />
This is the log I got from srsRAN. The UL part mcs and signal strength are still lower than expected. It seems to be not related to cpu processing part? Because even I use default parameter, I can still get similar power strength.

**Comment by pgawlowicz** [comment]
did you try tuning  `rx_gain`?

**Comment by Timez-zx** [comment]
Yes. I use the maximum rx_gain: 37.5 dB.  For the sender side, I use tx_gain: 90 dB. They are both maximum gain I can adjust to.

**Comment by Timez-zx** [comment]
I have change a little to adapt to my pc [srs_gnb.yml.txt](https://github.com/user-attachments/files/18157499/srs_gnb.yml.txt).

This is the result from the configuration you provided:
<img width="814" alt="Screenshot 2024-12-16 at 15 58 24" src="https://github.com/user-attachments/assets/3c9c70f2-f75d-4a4c-b64d-c68d3e4c86e3" />

**Comment by pgawlowicz** [comment]
could you share amariUE config?

**Comment by Timez-zx** [comment]
Yes. 
This is the main configuration:
[ue-nr-sa-rb273-srs-x310.txt](https://github.com/user-attachments/files/18157552/ue-nr-sa-rb273-srs-x310.txt)

This is for controlling the gain:
[1chan-rb273-srs-x310.txt](https://github.com/user-attachments/files/18157557/1chan-rb273-srs-x310.txt)

**Comment by pgawlowicz** [comment]
does it have any impact if you reduce tx gain in amariUE?

**Comment by Timez-zx** [comment]
Yes. The MCS will reduce a lot, from 24 to 17 if I reduce tx_gain from 90 to 80.

**Comment by Timez-zx** [comment]
RF cable. We try to avoid any attenuation at first, so only use RF cable. I also try to change some cables, but cannot solve this problem.

**Comment by pgawlowicz** [comment]
could you try to add an attenuator? like 10-20db?

**Comment by Timez-zx** [comment]
We do not have an attenuator to be installed. What's the attenuator for?

**Comment by pgawlowicz** [comment]
I would be afraid of killing the x310 if connecting it without attenuator.

The UE seems to have a lot of power headroom, you might try to push it to transmit with a bit higher power by tuning those parameters:
```
pusch:
    target_sinr: 10                         # Optional FLOAT (10). Sets the target SINR in dB. Supported: [-5 - 30].
    ref_path_loss: 70                       # Optional FLOAT (70). Sets the reference path-loss for target PUSCH SINR in dB. Supported: [50 - 120].
    pl_compensation_factor: 1               # Optional FLOAT (1). Sets the fractional path-loss compensation factor in PUSCH power control. Supported: [0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1].
```
