### ISSUE TITLE
Config YAML parser behaviour depends on the line ordering in the YAML file

### ISSUE THREAD

**Issue by bradunov** [srsran/srsRAN_Project#987]
## Issue Description ##
Config YAML parser behaviour depends on the line ordering in the YAML file.

## Setup Details ##

I am running srsRAN on Azure Linux 3.0 with Foxconn RU. I am using the latest commit (`e5d5b44b9`). The suspected bug is likely in the YAML parsing library. 

## Expected Behavior ##

I want to disable PRACH compression using `compr_method_prach: none` parameter in `ru_ofh` section. 
This works if `compr_method_prach` is before the `cells` key. If it is after, it gets ignored. 
YAML parameter values should not depend on the order. 

## Actual Behaviour ##

If I put `compr_method_prach: none` after `cells` key in `ru_ofh`, it gets ignored. 

## Steps to reproduce the problem ##

 I want to disable the PRACH compression. I used a sample configuration file and it worked. Here is the relevant snippet:
```yaml
ru_ofh:
  compr_method_prach: none
  compr_bitwidth_prach: 16
  compr_method_dl: bfp
  compr_bitwidth_dl: 9
  compr_method_ul: bfp
  compr_bitwidth_ul: 9
  enable_dl_static_compr_hdr: false
  enable_ul_static_compr_hdr: false
  ignore_ecpri_payload_size: true
  iq_scaling: 2.0
  is_dl_broadcast_enabled: false
  is_prach_cp_enabled: true
  ru_bandwidth_MHz: 100
  t1a_max_cp_dl: 470
  t1a_max_cp_ul: 429
  t1a_max_up: 196
  t1a_min_cp_dl: 258
  t1a_min_cp_ul: 285
  t1a_min_up: 50
  ta4_max: 75
  ta4_min: 0
  cells:
  - dl_port_id: [0, 1, 2, 3]
    du_mac_addr: 00:11:22:33:0a:a0
    network_interface: 0000:86:09.0
    prach_port_id: [4, 5, 6, 7]
    ru_mac_addr: 6c:ad:ad:00:0a:a0
    ul_port_id: [0, 1, 2, 3]
    vlan_tag_cp: 3
    vlan_tag_up: 3
```
The RAN starts with the following message:
```
Initializing the Open Fronthaul Interface for sector#0: ul_compr=[BFP,9], dl_compr=[BFP,9], prach_compr=[none,16], prach_cp_enabled=true, downlink_broadcast=false
```
PRACH compression is `none`, as expected. 

I needed to write a script that modifies the YAML file in python. The python script rearranged the order of the config as follows:
```yaml
ru_ofh:
  cells:
  - dl_port_id: [0, 1, 2, 3]
    du_mac_addr: 00:11:22:33:0a:a0
    network_interface: 0000:86:09.0
    prach_port_id: [4, 5, 6, 7]
    ru_mac_addr: 6c:ad:ad:00:0a:a0
    ul_port_id: [0, 1, 2, 3]
    vlan_tag_cp: 3
    vlan_tag_up: 3
  compr_method_prach: none
  compr_bitwidth_prach: 16
  compr_method_dl: bfp
  compr_bitwidth_dl: 9
  compr_method_ul: bfp
  compr_bitwidth_ul: 9
  enable_dl_static_compr_hdr: false
  enable_ul_static_compr_hdr: false
  ignore_ecpri_payload_size: true
  iq_scaling: 2.0
  is_dl_broadcast_enabled: false
  is_prach_cp_enabled: true
  ru_bandwidth_MHz: 100
  t1a_max_cp_dl: 470
  t1a_max_cp_ul: 429
  t1a_max_up: 196
  t1a_min_cp_dl: 258
  t1a_min_cp_ul: 285
  t1a_min_up: 50
  ta4_max: 75
  ta4_min: 0
```
Note that it is the same as above, except that `cells` section is before the rest. Now it seems that the PRACH config was ignored, as the starting message showed:
```
Initializing the Open Fronthaul Interface for sector#0: ul_compr=[BFP,9], dl_compr=[BFP,9], prach_compr=[BFP,9], prach_cp_enabled=true, downlink_broadcast=false
```
Notice that the PRAC compression is now BFP, although the config file says `compr_method_prach: none`.

I also noticed that I can make it work again if I make `compr_method_prach: none` as a part of the `cells` config, as shown here:
```yaml
ru_ofh:
  cells:
  - dl_port_id: [0, 1, 2, 3]
    du_mac_addr: 00:11:22:33:0a:a0
    network_interface: 0000:86:09.0
    prach_port_id: [4, 5, 6, 7]
    ru_mac_addr: 6c:ad:ad:00:0a:a0
    ul_port_id: [0, 1, 2, 3]
    vlan_tag_cp: 3
    vlan_tag_up: 3
    compr_method_prach: none
    compr_bitwidth_prach: 16
    compr_method_dl: bfp
    compr_bitwidth_dl: 9
    compr_method_ul: bfp
    compr_bitwidth_ul: 9
    enable_dl_static_compr_hdr: false
    enable_ul_static_compr_hdr: false
    ignore_ecpri_payload_size: true
    iq_scaling: 2.0
    is_dl_broadcast_enabled: false
    is_prach_cp_enabled: true
    ru_bandwidth_MHz: 100
    t1a_max_cp_dl: 470
    t1a_max_cp_ul: 429
    t1a_max_up: 196
    t1a_min_cp_dl: 258
    t1a_min_cp_ul: 285
    t1a_min_up: 50
    ta4_max: 75
    ta4_min: 0
```
I suspect that your code loads the default values, including `compr_method_prach` first, and then when you parse the `cells` section you delete all the default values and populate with the ones within the cell. The problem is that you seem to delete the default values even if they are not populated in the cells section. 

Also, at least according to [this documentation](https://docs.srsran.com/projects/project/en/latest/user_manuals/source/config_ref.html), `compr_method_prach` is not a part of the `cells` section, so the last configuration option should not be accepted.
